halo-dev/halo

README-en-US.md
README-tr.md
README.md

Added turkish translation.
Turkish flag icon doesn't exist in emoji set. Added from external library: [flag-icon-css](https://github.com/lipis/flag-icon-css)

Turkish translation

---

pom.xml
src/main/java/cc/ryanc/halo/utils/CommentUtil.java
src/main/java/cc/ryanc/halo/utils/HaloUtils.java
src/main/resources/templates/admin/admin_index.ftl
src/main/resources/templates/admin/module/_header.ftl
src/main/resources/templates/admin/module/_macro.ftl
src/main/resources/templates/common/macro/common_macro.ftl

Enhance utils

---

src/main/java/cc/ryanc/halo/repository/PostRepository.java
src/main/java/cc/ryanc/halo/service/PostService.java
src/main/java/cc/ryanc/halo/service/impl/PostServiceImpl.java
src/main/java/cc/ryanc/halo/web/controller/api/ApiArchivesController.java

:alien: 添加小程序返回所有文章Api

---

pom.xml
src/main/java/cc/ryanc/halo/utils/CommentUtil.java

优化组装评论的工具类

---

src/main/java/run/halo/app/listener/StartedListener.java

Fix the problem that the project cannot start after moving to a new server

Fix the problem that the project cannot start after moving to a new server

---

build.gradle
src/main/java/run/halo/app/handler/file/BaiDuYunFileHandler.java
src/main/java/run/halo/app/model/enums/AttachmentType.java
src/main/java/run/halo/app/model/properties/BaiDuYunProperties.java

新增百度云oss文件上传和删除功能，亲测可用
前端也提交了pr请查收

新增百度云oss文件上传下载功能

---

build.gradle
src/main/java/run/halo/app/handler/file/TencentYunFileHandler.java
src/main/java/run/halo/app/model/enums/AttachmentType.java
src/main/java/run/halo/app/model/properties/TencentYunProperties.java

并解决腾讯云jar包中的日志包与项目的日志包冲突问题
功能待测试

新增腾讯云oss功能；

---

src/main/java/run/halo/app/controller/admin/api/BackupController.java
src/main/java/run/halo/app/service/BackupService.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

批量导出hexo格式的markdown文档备份接口添加
关闭昨天错误的提交
改为提交到dev分支

Batch export markdown backup in hexo format

---

src/main/java/run/halo/app/config/HaloConfiguration.java
src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/resources/application.yaml

feat:(add customize resttempalte timeout.)

---

src/main/java/run/halo/app/service/impl/AdminServiceImpl.java

Its expiration time should be 1 day

Fix a bug when building tokens

---

build.gradle
src/main/java/run/halo/app/cache/LevelCacheStore.java
src/main/java/run/halo/app/config/HaloConfiguration.java
src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/resources/application-dev.yaml
src/test/java/run/halo/app/cache/CacheStoreTest.java

add leveldb cache store impl
add leveldb config by yaml dev
add cache impl test
leveldb config application-dev.yaml
```
halo:
//level: leveldb local store   memory: in memory store
cache: level
```

feat: add leveldb cache store impl

---

src/main/java/run/halo/app/utils/FileUtils.java

Fix issue: https://github.com/halo-dev/halo/issues/495

Fix vulnerability due to uncheck theme id

---

src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
src/main/java/run/halo/app/controller/content/ContentArchiveController.java
src/main/java/run/halo/app/controller/content/ContentContentController.java

Add custom RequestMappingHandlerMapping for enable static resources access

---

src/main/java/run/halo/app/config/HaloConfiguration.java
src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/java/run/halo/app/model/enums/Mode.java
src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
src/main/java/run/halo/app/security/filter/ApiAuthenticationFilter.java
src/main/java/run/halo/app/security/filter/ContentFilter.java
src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
src/main/resources/application-dev.yaml
src/main/resources/application-test.yaml

Refactor halo mode

---

src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java

Fix installation on the first startup

---

src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
src/main/java/run/halo/app/handler/file/BaiduBosFileHandler.java
src/main/java/run/halo/app/handler/file/FileHandler.java
src/main/java/run/halo/app/handler/file/FileHandlers.java
src/main/java/run/halo/app/handler/file/LocalFileHandler.java
src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java
src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java
src/main/resources/application.yaml

临时解决文件上传过程中，由于 undertow 启动时所创建的临时文件夹被删除导致无法创建临时文件的错误。
Resolved #521

Fix file upload exception

---

src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java

Stop supporting admin folder mapping in workspace.

---

src/main/java/run/halo/app/controller/content/ContentFeedController.java
src/main/resources/templates/common/web/atom.ftl
src/main/resources/templates/common/web/rss.ftl

支持分类订阅
/feed/categories/{slugName}.xml 
or
/atom/categories/{slugName}.xml

Support category feed.

---

src/main/java/run/halo/app/controller/admin/api/InstallController.java

几点修改：
1. 示例文章信息。
2. 修复示例文章和示例分类没有关联上的问题。
3. 新增了示例页面的生成。
4. 新增了 `默认分类` 和 `示例页面` 的菜单。
5. 示例评论信息。

Refactor installation data.

---

src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
src/main/java/run/halo/app/controller/content/ContentContentController.java
src/main/java/run/halo/app/controller/content/ContentIndexController.java
src/main/java/run/halo/app/controller/content/model/PostModel.java
src/main/java/run/halo/app/model/vo/ArchiveYearVO.java
src/main/java/run/halo/app/service/PostService.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

之前的归档页面有个很大的问题，绝大部分主题使用的是自定义标签，但是那样的话就无法进行分页。
当前效果：

Support paging of archive pages.

---

src/main/java/run/halo/app/controller/content/model/CategoryModel.java
src/main/java/run/halo/app/controller/content/model/PostModel.java
src/main/java/run/halo/app/controller/content/model/TagModel.java
src/main/java/run/halo/app/model/properties/PostProperties.java
src/main/java/run/halo/app/service/OptionService.java
src/main/java/run/halo/app/service/impl/OptionServiceImpl.java

Support set archives page size.

---

src/main/java/run/halo/app/controller/admin/api/AttachmentController.java
src/main/java/run/halo/app/controller/admin/api/CategoryController.java
src/main/java/run/halo/app/controller/admin/api/JournalCommentController.java
src/main/java/run/halo/app/controller/admin/api/LogController.java
src/main/java/run/halo/app/controller/admin/api/PhotoController.java
src/main/java/run/halo/app/controller/admin/api/PostCommentController.java
src/main/java/run/halo/app/controller/admin/api/SheetCommentController.java
src/main/java/run/halo/app/controller/admin/api/TagController.java
src/main/java/run/halo/app/controller/content/ContentContentController.java
src/main/java/run/halo/app/controller/content/model/CategoryModel.java
src/main/java/run/halo/app/controller/content/model/JournalModel.java
src/main/java/run/halo/app/controller/content/model/PhotoModel.java
src/main/java/run/halo/app/controller/content/model/PostModel.java
src/main/java/run/halo/app/controller/content/model/TagModel.java
src/main/java/run/halo/app/controller/core/CommonController.java

1. 修复带后缀文章 404 的问题。
2. 部分 admin api 的默认排序由 `updateTime` 改为 `createTime`。

Fix failure of suffixes in posts.

---

src/main/java/run/halo/app/config/HaloConfiguration.java
src/main/java/run/halo/app/filter/CorsFilter.java
src/main/java/run/halo/app/filter/LogFilter.java
src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
src/main/java/run/halo/app/security/filter/AdminAuthenticationFilter.java
src/main/java/run/halo/app/security/filter/ApiAuthenticationFilter.java
src/main/java/run/halo/app/security/filter/ContentFilter.java

Fix a fatal filter bug

---

src/main/java/run/halo/app/listener/StartedListener.java
src/main/resources/banner.txt

1. 去除 SpringBoot 信息。
2. 将启动完成后打印的博客地址和提示高亮，降低 issue 量。

Refactor banner info.

---

src/main/java/run/halo/app/exception/RepeatTypeException.java
src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
src/main/java/run/halo/app/handler/file/BaiduBosFileHandler.java
src/main/java/run/halo/app/handler/file/FileHandler.java
src/main/java/run/halo/app/handler/file/FileHandlers.java
src/main/java/run/halo/app/handler/file/LocalFileHandler.java
src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java
src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java

Optimize FileHandler's logic to  improve performance

optimize FileHandler's logic

---

src/main/java/run/halo/app/controller/content/ContentFeedController.java
src/main/resources/application-dev.yaml
src/main/resources/templates/common/web/atom.ftl
src/main/resources/templates/common/web/rss.ftl

resolved #629 。
临时解决方案，用正则替换掉不合规的字符，这样效率不高。初步怀疑是 flexmark 解析的问题，插入了不改插入的字符。
另外，修改了 application-dev.yaml 中的 `cache` 为 `memory`，此方式有坑，不能及时更新缓存。

Fix rss invaid char error.

---

src/main/java/run/halo/app/model/entity/Tag.java

Add Index on tags.name to Accelerate Query.
See #652

Add Index on tags.name

---

src/main/java/run/halo/app/model/entity/Photo.java

Add Index on photos.team to Accelerate Query.
See #656

Add Index on photos.team

---

src/main/java/run/halo/app/model/entity/Menu.java

Add Index on menus.parent_id to Accelerate Query.
See #654

Add Index on menus.parent_id

---

src/main/java/run/halo/app/model/entity/Link.java

Add Index on links.name to Accelerate Query.
See #650

Add Index on links.name

---

src/main/java/run/halo/app/model/entity/Category.java

Add index on categories.name and categories.parent_id to Accelerate Query.
See #642 and #644

Add index on categories.name and categories.parent_id

---

src/main/java/run/halo/app/model/entity/BaseComment.java

Add Index on comments.post_id to Accelerate Query.
See #648

Add Index on comments.post_id

---

src/main/java/run/halo/app/model/entity/Log.java

Add Index on logs.create_time to Accelerate Query.
See #667

Add Index on logs.create_time

---

src/main/java/run/halo/app/model/entity/PostCategory.java

Add Index on post_categories.post_id and post_categories.category_id to Accelerate Query.
See #669 and #670

Add Index on post_categories.post_id and post_categories.category_id

---

src/main/java/run/halo/app/model/entity/PostTag.java

Add Index on post_tags.post_id and post_tags.tag.id to Accelerate Query.
See #673 and #674

Add Index on post_tags.post_id and post_tags.tag.id

---

src/main/java/run/halo/app/model/entity/ThemeSetting.java

Add Index on theme_settings.theme_id and theme_settings.setting_key to Accelerate Query.
See #680

Add Index on theme_settings.setting_key and theme_settings.theme_id

---

src/main/java/run/halo/app/repository/PostRepository.java

Fix post query sql.

---

src/main/java/run/halo/app/model/entity/BasePost.java

Add Index on posts.(type,status) and posts.create_time to Accelerate Query.
See #683

Add Index on posts.(type,status) and posts.create_time

---

src/main/java/run/halo/app/model/entity/BaseComment.java

Add Index on comments.(type,status) and comments.parent_id to Accelerate Query.
See #685

Add Index on comments.(type,status) and comments.parent_id

---

src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/java/run/halo/app/controller/admin/api/BackupController.java
src/main/java/run/halo/app/controller/admin/api/DataProcessController.java
src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/model/dto/BackupDTO.java
src/main/java/run/halo/app/model/entity/PostCategory.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/service/BackupService.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

Refactor backup service.

---

src/main/java/run/halo/app/core/freemarker/tag/CategoryTagDirective.java
src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java

feat: #598

---

src/main/java/run/halo/app/listener/comment/CommentEventListener.java
src/main/resources/templates/common/mail_template/mail_notice.ftl
src/main/resources/templates/common/mail_template/mail_reply.ftl

现在支持主题开发者自定义邮件消息模板了。开发者可根据自己的主题样式定制消息模板。相关 API 会在开发文档中说明。

Support custom email templates.

---

src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/service/impl/AdminServiceImpl.java

Refactor get database version.

---

src/test/java/run/halo/app/controller/DisableOnConditionController.java

update /src/test/java/run/halo/app/controller/DisableOnConditionController.java  blockAccess()  "return BaseResponse.ok("测试静止访问");" to "return BaseResponse.ok("测试禁止访问");"

update some chinese descriptions

---

src/main/java/run/halo/app/model/entity/Attachment.java

添加attachments.media_type索引加快相关查询速度。
详见 #717

添加attachments.media_type索引加快相关查询速度

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

And upgrade gradle version to 6.3.

Refactor extra properties in build.gradle

---

src/main/java/run/halo/app/model/entity/Menu.java

添加menus.name索引加快相关查询速度 
详见 #721

添加menus.name索引加快相关查询速度

---

src/main/java/run/halo/app/model/entity/Photo.java

添加photos.create_time索引加快相关查询速度。
详见 #726

添加photos.create_time索引加快相关查询速度

---

src/main/java/run/halo/app/model/entity/Attachment.java

添加attachments.create_time索引加快相关查询速度。
详见 #724

添加attachments.create_time索引加快相关查询速度

---

build.gradle
src/main/java/run/halo/app/config/HaloConfiguration.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/resources/application.yaml

使用springboot gradle 插件可以 Exposing build information of Spring Boot 到 BuildProperties， 然后可以读取 version 甚至 git 等信息。
```
springBoot {
buildInfo()
}
```

fix #713, 开发环境也能获取版本信息了

---

src/main/java/run/halo/app/service/impl/CommentBlackListServiceImpl.java
src/main/java/run/halo/app/utils/DateTimeUtils.java
src/test/java/run/halo/app/utils/DateTimeUtilsTest.java

1.新增DateTimeUtils
2.使用DateTimeUtils优化部分代码

新增DateTimeUtils

---

src/main/java/run/halo/app/handler/theme/config/impl/YamlThemeConfigResolverImpl.java
src/main/java/run/halo/app/model/enums/InputType.java

主题设置选项支持 switch 输入类型。数据类型仅支持 bool。

Add switch type for theme settings.

---

src/main/java/run/halo/app/cache/InMemoryCacheStore.java
src/main/java/run/halo/app/cache/LevelCacheStore.java
src/main/java/run/halo/app/cache/lock/CacheLockInterceptor.java
src/main/java/run/halo/app/controller/admin/api/StaticPageController.java
src/main/java/run/halo/app/controller/content/ContentFeedController.java
src/main/java/run/halo/app/controller/content/MainController.java
src/main/java/run/halo/app/filter/CorsFilter.java
src/main/java/run/halo/app/handler/file/LocalFileHandler.java
src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
src/main/java/run/halo/app/handler/staticdeploy/NetlifyStaticDeployHandler.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/security/context/SecurityContextHolder.java
src/main/java/run/halo/app/security/util/SecurityUtils.java
src/main/java/run/halo/app/utils/HttpClientUtils.java
src/main/java/run/halo/app/utils/JsonUtils.java
src/test/java/run/halo/app/utils/GithubTest.java

https://google.github.io/styleguide/javaguide.html#s4.8.7-modifiers

style: final static -> static final

---

README.md

Add more download sources support

---

src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
src/main/java/run/halo/app/utils/ValidationUtils.java

https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java

fix: volatile in double-checked locking

---

src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

排序使用Comparator静态方法实现

---

build.gradle
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
src/main/java/run/halo/app/service/impl/StaticPageServiceImpl.java
src/main/java/run/halo/app/utils/DateTimeUtils.java

抽取 yyyy-MM-dd-HH-mm-ss- 格式的日期pattern到工具类中

抽取 yyyy-MM-dd-HH-mm-ss- 格式的日期pattern到工具类中

---

src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java

Use .equals instead of !=
#850

Replace != usage with equals to avoid bugs.

---

src/main/java/run/halo/app/Application.java

Remove redundant annotations

---

config/checkstyle/checkstyle.xml
src/main/java/run/halo/app/Application.java

> Fix #913 
- 删除多余得 module
- 新增 [SuppressionCommentFilter](https://checkstyle.sourceforge.io/config_filters.html#SuppressionCommentFilter) module

Perfect checkstyle.xml

---

src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/utils/VersionUtil.java
src/test/java/run/halo/app/utils/VersionUtilTest.java

- 修复初始化时无主题导致无法启动 Halo 的错误
- 修复开发环境下无法获取 Halo 版本导致无法导入主题的错误

Fix startup exception and theme imports in dev environment

---

.gitignore
src/main/java/run/halo/app/Application.java
src/main/java/run/halo/app/controller/admin/api/AdminController.java

Remove restart feature

---

src/main/java/run/halo/app/controller/content/api/CategoryController.java
src/main/java/run/halo/app/controller/content/api/TagController.java
src/main/java/run/halo/app/controller/content/model/CategoryModel.java
src/main/java/run/halo/app/model/dto/post/BasePostSimpleDTO.java

Add top priority sort at post list in category and tag

---

src/main/java/run/halo/app/controller/content/ContentFeedController.java
src/main/java/run/halo/app/core/ControllerExceptionHandler.java
src/main/java/run/halo/app/security/handler/DefaultAuthenticationFailureHandler.java
src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
src/main/java/run/halo/app/utils/GitUtils.java

Make some unnecessary error detail hide

---

config/checkstyle/checkstyle.xml
src/main/java/run/halo/app/utils/Version.java
src/main/java/run/halo/app/utils/VersionUtil.java
src/test/java/run/halo/app/utils/VersionTest.java
src/test/java/run/halo/app/utils/VersionUtilTest.java

Enable beta version comparable

---

src/main/java/run/halo/app/controller/admin/api/AdminController.java
src/main/java/run/halo/app/service/AdminService.java
src/main/java/run/halo/app/service/impl/AdminServiceImpl.java

feat: #1065

---

src/main/java/run/halo/app/controller/admin/api/ThemeController.java
src/main/java/run/halo/app/service/ThemeSettingService.java
src/main/java/run/halo/app/service/impl/ThemeSettingServiceImpl.java

fix: #1068

---

src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
src/main/java/run/halo/app/theme/ThemePropertyScanner.java
src/main/java/run/halo/app/utils/FileUtils.java
src/main/java/run/halo/app/utils/GithubUtils.java
src/test/java/run/halo/app/utils/FileUtilsTest.java

1. 修复主题 zip 文件上传失败问题。
1. 提供寻找根据条件查找根目录的功能。
1. 去除脆弱的 FileUtils#tryToSkipZipParentFolder 方法。

Fix theme zip file upload bug and provide finding root folder function

---

build.gradle
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
src/main/java/run/halo/app/utils/FileUtils.java
src/main/java/run/halo/app/utils/GithubUtils.java
src/test/java/run/halo/app/utils/FileUtilsTest.java

1. 修复解压后没有正确找到主题根目录问题。
1. 修复 github 链接中包含 .git 后缀的问题。

Fix handling root theme folder unexpectedly

---

Dockerfile

fix: #1028

---

src/main/java/run/halo/app/controller/core/CommonController.java

1.添加请求状态码（原先不管是404还是500,返回的状态码都是500）
2.修改过时方法

添加请求状态码&修改过时方法

---

src/main/java/run/halo/app/controller/admin/api/LinkController.java
src/main/java/run/halo/app/repository/LinkRepository.java
src/main/java/run/halo/app/service/LinkService.java
src/main/java/run/halo/app/service/impl/LinkServiceImpl.java

feat: 添加或修改友链时校验 name 和 url 是否重复 (#997)

---

src/main/java/run/halo/app/utils/HaloUtils.java

fix: #1098

---

src/main/java/run/halo/app/controller/admin/api/ThemeController.java
src/main/java/run/halo/app/repository/ThemeSettingRepository.java
src/main/java/run/halo/app/service/ThemeService.java
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java

feat: 删除主题时可选是否删除配置

---

src/main/java/run/halo/app/model/enums/converter/AbstractConverter.java
src/main/java/run/halo/app/model/enums/converter/AttachmentTypeConverter.java
src/main/java/run/halo/app/model/enums/converter/CommentStatusConverter.java
src/main/java/run/halo/app/model/enums/converter/DataTypeConverter.java
src/main/java/run/halo/app/model/enums/converter/LogTypeConverter.java
src/main/java/run/halo/app/model/enums/converter/PostStatusConverter.java
src/main/java/run/halo/app/model/enums/converter/PostTypeConverter.java

重构 AbstractConverter 构造函数，自动获取 ValueEnum 类型，移除所有子类构造函数。

Refactor AbstractConverter constructor

---

SECURITY.md

As stated in https://github.com/halo-dev/halo/issues/803 I've created a standard Security Policy ;)

Propose Security Policy

---

src/main/java/run/halo/app/controller/content/ContentContentController.java
src/main/java/run/halo/app/model/enums/SheetPermalinkType.java
src/main/java/run/halo/app/model/properties/PermalinkProperties.java
src/main/java/run/halo/app/service/OptionService.java
src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
src/main/java/run/halo/app/service/impl/SheetCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/SheetServiceImpl.java

feat: #1174

---

src/main/java/run/halo/app/controller/content/api/JournalController.java
src/main/java/run/halo/app/controller/content/api/PostController.java
src/main/java/run/halo/app/repository/JournalRepository.java
src/main/java/run/halo/app/service/JournalService.java
src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
src/main/java/run/halo/app/service/impl/JournalServiceImpl.java

feat: #1158

---

src/main/java/run/halo/app/model/params/JournalParam.java

feat: #1160.

---

src/main/java/run/halo/app/controller/admin/api/ThemeController.java

fix: #1180

---

src/main/java/run/halo/app/controller/content/api/CategoryController.java
src/main/java/run/halo/app/controller/content/api/TagController.java

feat: #766

---

.github/workflows/halo.yml
Dockerfile
build.gradle

Refactor Dockerfile with layered jar

---

src/main/java/run/halo/app/utils/FileUtils.java

Fix folder copy error: ProviderMismatchException

---

src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
src/main/java/run/halo/app/service/impl/OptionServiceImpl.java

fix: #1255.

---

src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
src/test/java/run/halo/app/repository/ThemeRepositoryImplTest.java

Improve performance for scanning local theme files.

Cache current theme in theme repository

---

src/main/java/run/halo/app/model/params/OptionParam.java

pref: #1050

---

src/main/java/run/halo/app/handler/file/LocalFileHandler.java

Make more tolerant of reading image

---

src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java

Fix error for updating activated theme

---

src/main/resources/templates/common/web/rss.ftl

feat: #1313

---

src/main/resources/banner.txt

style: set the color of log to default after banner

---

src/main/java/run/halo/app/repository/base/BaseCommentRepository.java
src/main/java/run/halo/app/service/base/BaseCommentService.java
src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/JournalServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/main/java/run/halo/app/service/impl/SheetServiceImpl.java

fix: #1311

---

src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/java/run/halo/app/listener/StartedListener.java

之前修改的初始化默认主题不妥，会导致在没有默认主题的情况下无法启动。

revert: #1297

---

src/main/java/run/halo/app/controller/content/ContentFeedController.java
src/main/resources/templates/common/web/atom.ftl
src/main/resources/templates/common/web/rss.ftl

1.Add the "lastBuildDate" in RSS.
2.Change the date format in RSS and Atom
3.Add the lastModified in the response header.

About RSS/Atom

---

src/main/java/run/halo/app/controller/content/api/CategoryController.java
src/main/java/run/halo/app/controller/content/model/CategoryModel.java

fix: intimate posts should not be searchable in the category list

---

src/main/java/run/halo/app/controller/admin/api/InstallController.java
src/test/java/run/halo/app/it/IndexPageRequestTest.java

fix: #1394

---

src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java

fix(security): freemarker SSTI vulnerability.

---

src/main/java/run/halo/app/repository/JournalCommentRepository.java
src/main/java/run/halo/app/repository/PostCommentRepository.java
src/main/java/run/halo/app/repository/SheetCommentRepository.java
src/main/java/run/halo/app/repository/base/BaseCommentRepository.java

fix: incorrect comment count statistics. #1411

---

CHANGELOG.md
src/main/java/run/halo/app/handler/file/LocalFileHandler.java

fix: deleting a non-picture file throws an exception.

---

src/main/java/run/halo/app/handler/file/MinioFileHandler.java
src/main/java/run/halo/app/model/properties/MinioProperties.java

fix: add region for operate minio attachment

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml

chore: add deployment method option for issue templates.

---

src/main/java/run/halo/app/controller/content/model/CategoryModel.java

1. 判断目录是否存在密码 存在密码则 查询status = 3,否则走默认 status = 0 
Fix #1470

Fix the problem of incorrect query posts when accessing the category with a password

---

.github/workflows/halo.yml

Simplify Java setup in GitHub workflow using [setup-java](https://github.com/actions/setup-java#caching-packages-dependencies) action v2.
Fix #1506 
/kind chore

Simplify Java setup in GitHub workflow

---

.github/workflows/halo.yml

Refactor docker release in GitHub workflow using [docker/metadata-action@v3](https://github.com/docker/metadata-action).
The final results are:
Fix #1507 
/kind enhancement

Refactor docker release in GitHub workflow

---

src/main/java/run/halo/app/controller/content/api/PhotoController.java

feat: add photo teams api in content api

---

src/main/java/run/halo/app/controller/admin/api/MenuController.java
src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
src/main/java/run/halo/app/service/impl/MenuServiceImpl.java

修复批量保存方法会刷新缺省字段为`null`的问题
see #1521

Fix the problem of updating categories and menus in batch

---

.github/workflows/halo.yml

Cherry pick of #1510 on release-1.4.
#1510: Refactor docker release in GitHub workflow
```release-note
```

Automated cherry pick of #1510: Refactor docker release in GitHub workflow

---

src/main/java/run/halo/app/controller/admin/api/MenuController.java
src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
src/main/java/run/halo/app/service/impl/MenuServiceImpl.java

Cherry pick of #1526 on release-1.4.
#1526: fix: batch update
```release-note
```

Automated cherry pick of #1526: fix: batch update

---

CONTRIBUTING.md
hack/cherry_pick_pull.sh

This script is from https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh.

Add cherry_pick_pull.sh for cherry-picking pull request

---

CONTRIBUTING.md

Cherry pick of #1524 on release-1.4.
#1524: Fix invalid URL in CONTRIBUTING.md
```release-note
```

Automated cherry pick of #1524: Fix invalid URL in CONTRIBUTING.md

---

src/main/java/run/halo/app/controller/admin/api/PhotoController.java

增加图库批量添加图片接口
需要修改 sdk 对 admin-api 增加相应接口方法
#1032

Add a batch creation api for photos

---

src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/model/support/HaloConst.java

Cherry pick of #1549 on release-1.4.
#1549: fix: 1547
```release-note
```

Automated cherry pick of #1549: fix: 1547

---

src/main/java/run/halo/app/handler/file/HuaweiObsFileHandler.java

fix: huawei obs upload file address is incorrect

---

build.gradle

Cherry pick of #1595 on release-1.4.
#1595: refactor: gradle config of log4j version
```release-note
```

Automated cherry pick of #1595: refactor: gradle config of log4j version

---

build.gradle
settings.gradle

- Bump dependencies to safety versions
- Refine build.gradle and setting.gradle
Fix #1580

Bump version of dependencies

---

build.gradle

Upgrade log4j dependencies to 2.17.1

---

README.md

docs: add demo site

---

build.gradle

See https://github.com/spring-projects/spring-boot/releases/tag/v2.5.9 for more.

Bump spring boot to 2.5.9

---

src/main/java/run/halo/app/controller/admin/api/PhotoController.java

feat: add api for delete photos in batch

---

src/main/java/run/halo/app/controller/admin/api/PhotoController.java
src/main/java/run/halo/app/model/params/PhotoParam.java

feat: add api for update photos in batch

---

build.gradle

See https://github.com/spring-projects/spring-boot/releases/tag/v2.5.10 for more.

Bump spring boot to 2.5.10

---

src/main/java/run/halo/app/core/ControllerExceptionHandler.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

针对 `IllegalArgumentException` 增加全局异常捕获
代码中的某些参数不合法会抛出`IllegalArgumentException`增加对它的全局异常捕获对用户提示更友好

Refactoring exception throw for backup import

---

src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
src/main/java/run/halo/app/utils/Version.java
src/main/java/run/halo/app/utils/VersionUtil.java
src/test/java/run/halo/app/utils/VersionTest.java
src/test/java/run/halo/app/utils/VersionUtilTest.java

Remove compare method and add a compatible method instead in Version class.
Fix #1704 

Fix the problem of theme version compatibility

---

src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java

As mentioned in the title.
Fixes #1741

Reverse theme required version compatibility check

---

README.md

doc: update download links

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml

Issues 模板添加 Checklist。
see https://github.com/ruibaby/halo/issues/new?assignees=&labels=bug&template=bug_report.zh.yml

chore: issue templates add checklist

---

src/main/java/run/halo/app/service/impl/PostServiceImpl.java

修复批量发布文章没有识别私密文章将其改为私密状态的问题
/kind bug

fix: batch publishing does not refresh private status

---

src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java

refactor: optimize post update listener code

---

src/main/resources/application-dev.yaml
src/main/resources/application.yaml

fix typo: eanbled to enabled

---

build.gradle
src/main/java/run/halo/app/identity/authentication/AccessToken.java
src/main/java/run/halo/app/identity/authentication/JwtTokenProvider.java
src/main/java/run/halo/app/identity/authentication/SecurityConstant.java
src/main/java/run/halo/app/infra/properties/JwtProperties.java
src/main/java/run/halo/app/infra/utils/HaloUtils.java
src/test/java/run/halo/app/JwtTokenProviderTest.java

新增 jwt token 生成器
待优化点(下个PR)：
- JwtTokenProvider 中使用到的配置允许动态修改
- AccessToken对象中的 token 属性应该使用 token 对象替换  jwt 方便针对不同的token
- 在上述优化点的基础上优化测试类
/kind feature
/area core

feat: add token provider

---

src/main/java/run/halo/app/service/impl/PostServiceImpl.java

fix #1842 
现在查询的时候会关联content表。

fix: searching posts without related contents

---

CONTRIBUTING.md

As I mentioned in the title, I refactored documentation in CONTRIBUTION.md file to be clearer.
Fix #1888

Refine contribution.md to be clearly

---

src/main/java/run/halo/app/controller/content/MainController.java

fix: Accessing the /install interface exposes the administrator interface address

---

CHANGELOG.md

fix: CHANGELOG.md typo

---

config/checkstyle/checkstyle.xml
src/main/java/run/halo/app/identity/authentication/ProviderSettings.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthentication.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationEntryPoint.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationFilter.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationToken.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenError.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenErrors.java
src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationToken.java
src/main/java/run/halo/app/identity/authorization/AuthorizingVisitor.java
src/main/java/run/halo/app/identity/authorization/RequestInfoFactory.java
src/main/java/run/halo/app/identity/authorization/RoleRef.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTest.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTokenTest.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorTest.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorsTest.java
src/test/java/run/halo/app/authentication/verifyer/JwtAuthenticationProviderTest.java
src/test/java/run/halo/app/authentication/verifyer/JwtGrantedAuthoritiesConverterTest.java

添加无用导入语句规则和javadoc style规则
https://checkstyle.sourceforge.io/config_javadoc.html#JavadocStyle
https://checkstyle.sourceforge.io/config_imports.html#UnusedImports
```release-note
NONE
```

chore: add checkstyle rule

---

src/main/java/run/halo/app/extension/AbstractExtension.java
src/main/java/run/halo/app/extension/DefaultExtensionClient.java
src/main/java/run/halo/app/extension/Extension.java
src/main/java/run/halo/app/extension/ExtensionClient.java
src/main/java/run/halo/app/extension/ExtensionConverter.java
src/main/java/run/halo/app/extension/ExtensionUtil.java
src/main/java/run/halo/app/extension/GVK.java
src/main/java/run/halo/app/extension/GroupKind.java
src/main/java/run/halo/app/extension/GroupVersion.java
src/main/java/run/halo/app/extension/GroupVersionKind.java
src/main/java/run/halo/app/extension/JSONExtensionConverter.java
src/main/java/run/halo/app/extension/Metadata.java
src/main/java/run/halo/app/extension/Scheme.java
src/main/java/run/halo/app/extension/Schemes.java
src/main/java/run/halo/app/extension/exception/ExtensionConvertException.java
src/main/java/run/halo/app/extension/exception/ExtensionException.java
src/main/java/run/halo/app/extension/exception/SchemeNotFoundException.java
src/main/java/run/halo/app/extension/store/ExtensionStore.java
src/main/java/run/halo/app/extension/store/ExtensionStoreClient.java
src/main/java/run/halo/app/extension/store/ExtensionStoreClientJPAImpl.java
src/main/java/run/halo/app/extension/store/ExtensionStoreRepository.java
src/test/java/run/halo/app/extension/AbstractExtensionTest.java
src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
src/test/java/run/halo/app/extension/ExtensionUtilTest.java
src/test/java/run/halo/app/extension/FakeExtension.java
src/test/java/run/halo/app/extension/GroupVersionTest.java
src/test/java/run/halo/app/extension/JSONExtensionConverterTest.java
src/test/java/run/halo/app/extension/SchemeTest.java
src/test/java/run/halo/app/extension/SchemesTest.java
src/test/java/run/halo/app/extension/store/ExtensionStoreClientJPAImplTest.java

/kind feature
/area core
This PR only adds some basic features for Extension mechanism.
See [Extension Model RFC](https://github.com/halo-dev/rfcs/blob/26768761e69d25e72d57f6c4d1a59f930b71b9d9/extension/README.md) for more.
Something we need to do in next PR:
- Validate Extension.
- Watch Extension change.
- Usage documentation.
Fixes #
```release-note
None
```

Add support for Extension mechanism

---

build.gradle
src/main/java/run/halo/app/extension/JSONExtensionConverter.java
src/main/java/run/halo/app/extension/Metadata.java
src/main/java/run/halo/app/extension/Scheme.java
src/main/java/run/halo/app/extension/Schemes.java
src/main/java/run/halo/app/extension/exception/SchemaViolationException.java
src/test/java/run/halo/app/extension/ExtensionUtilTest.java
src/test/java/run/halo/app/extension/JSONExtensionConverterTest.java
src/test/java/run/halo/app/extension/SchemeTest.java

/kind feature
/area core
/milestone 2.0
Add JSON schema generator and validator according to https://json-schema.org/implementations.html.
Before saving Extension data into database, we need to verify if the data violate the JSON schema or not.
BTY, I have enhanced the metadata fields schema configuration using the Swagger Schema annotation.
About Extension mechanism, please see [here](https://github.com/halo-dev/rfcs/blob/26768761e69d25e72d57f6c4d1a59f930b71b9d9/extension/README.md).
Fixes #
```release-note
None
```

Add JSON schema generator and validator

---

build.gradle

Upgrade to Spring Boot 3.0.0-M3. See <https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0-M3> for more.
Fixes #
```release-note
None
```

Upgrade to Spring Boot 3.0.0-M3

---

Dockerfile

/kind cleanup
/kind deprecation
在`Dockerfile`中使用 Eclipse Temurin 镜像替代 AdoptOpenJDK 镜像
AdoptOpenJDK 项目已迁移至 Eclipse Adoptium，JDK 更名为「Eclipse Temurin」。
https://blog.adoptium.net/2021/08/adoptium-celebrates-first-release/
N/A
Adoptium 已不再构建基于 Eclipse OpenJ9 的 JDK，因此标签中的`hotspot`已被移除。
https://adoptium.net/docs/faq/#_where_are_the_openj9_builds
```release-note
使用 Eclipse Temurin 镜像替代 AdoptOpenJDK 镜像
```

Replace AdoptOpenJDK docker image with Eclipse Temurin

---

src/main/java/run/halo/app/config/WebSecurityConfig.java
src/main/java/run/halo/app/infra/SchemeInitializer.java
src/main/java/run/halo/app/infra/utils/JsonUtils.java
src/main/java/run/halo/app/infra/utils/YamlUnstructuredLoader.java
src/main/resources/extensions/rolesTemplates.yaml
src/test/java/run/halo/app/infra/utils/JsonUtilsTest.java
src/test/java/run/halo/app/infra/utils/YamlUnstructuredLoaderTest.java

/kind feature
/area core
/milestone 2.0
新增 YamlUnstructuredLoader 用于将扫描到的 yaml 文件转为 Unstructured 结构
一个合法的 Unstructured 结构的yaml 必须包含以下 key
- apiVersion
- kind
- metadata.name
Fixes #
```release-note
None
```

feat: add yaml unstructured loader

---

build.gradle
src/main/java/run/halo/app/plugin/BasePlugin.java
src/main/java/run/halo/app/plugin/ExtensionContextRegistry.java
src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/PluginApplicationContext.java
src/main/java/run/halo/app/plugin/PluginApplicationEventBridgeDispatcher.java
src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
src/main/java/run/halo/app/plugin/PluginProperties.java
src/main/java/run/halo/app/plugin/PluginRequestMappingManager.java
src/main/java/run/halo/app/plugin/PluginStartingError.java
src/main/java/run/halo/app/plugin/PropertyPluginStatusProvider.java
src/main/java/run/halo/app/plugin/SharedEvent.java
src/main/java/run/halo/app/plugin/SpringComponentsFinder.java
src/main/java/run/halo/app/plugin/SpringExtensionFactory.java
src/main/java/run/halo/app/plugin/event/HaloPluginStartedEvent.java
src/main/java/run/halo/app/plugin/event/HaloPluginStateChangedEvent.java
src/main/java/run/halo/app/plugin/event/HaloPluginStoppedEvent.java
src/main/resources/application-dev.yaml

/kind feature
/area core
/milestone 2.0
提供插件功能基础能力实现包括：
- 插件生命周期管理：启用，停用，卸载
- 通过插件管理器获取扩展点实现类对象
- 插件可订阅 halo 标记了 `@SharedEvent` 注解的事件
- 插件可定义APIs
此 PR 暂无法提供单元测试
该 PR 属于 https://github.com/halo-dev/rfcs/pull/10 功能实现的一部分
TODO:
- 提供插件管理api，用于插件生命周期管理
- 提供插件自定义模型用于存储和获取插件资源清单
```release-note
None
```

feat: initial plugin implementation

---

src/main/java/run/halo/app/identity/authorization/PolicyRule.java
src/test/java/run/halo/app/identity/authorization/PolicyRuleTest.java

/area core
/milestone 2.0
重构 PolicyRule 的构造方法和builder 避免可以绕过判断出现数组为 null 值的情况
该类保证每个类型为数组的字段都永远不会为 null值
增加测试类
```release-note
None
```

refactor: policy rule constructor to avoid null values

---

src/main/java/run/halo/app/infra/SchemeInitializer.java
src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/Plugin.java
src/main/java/run/halo/app/plugin/PluginApplicationContext.java
src/main/java/run/halo/app/plugin/PluginApplicationEventBridgeDispatcher.java
src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
src/main/java/run/halo/app/plugin/PluginLifeCycleManagerController.java
src/main/java/run/halo/app/plugin/PluginService.java
src/main/java/run/halo/app/plugin/PluginServiceImpl.java
src/test/java/run/halo/app/plugin/PluginLifeCycleManagerControllerTest.java

/kind feature
/milestone 2.0
/area core
- 新增插件生命周期管理 controller，并初始化了一个模版角色给 personal access token用于测试
- 重构 PluginApplicationEventBridgeDispatcher 去除了对 PluginManager 的引用避免出现循环依赖问题
```release-note
None
```

feat: add plugin life cycle management

---

src/main/java/run/halo/app/plugin/Plugin.java
src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
src/main/java/run/halo/app/plugin/YamlPluginFinder.java
src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java

/kind feature
/area core
/milestone 2.0
插件可能需要声明多种 LICENSE 来让使用者知道它的使用范围，并且可能会填写 LICENSE 地址。
本 PR 允许插件作者以如下的方式声明 LICENSE：
1. 指定一个 LICENSE 名称
```yaml
apiVersion: v1alpha1
kind: Plugin
metadata:
name: plugin-name
spec:
license: MIT
```
2. 指定多个 LICENSE 名称
```yaml
apiVersion: v1alpha1
kind: Plugin
metadata:
name: plugin-name
spec:
license: ["MIT", "Apache-2.0"]
```
2. 指定 LICENSE 名称和 url
```yaml
apiVersion: v1alpha1
kind: Plugin
metadata:
name: plugin-name
spec:
license:
- name: MIT
url: https://choosealicense.com/licenses/mit
- name: Apache-2.0
url: https://choosealicense.com/licenses/apache-2.0
```
Fixes #
```release-note
None
```

feat: plugin supports multiple ways of specifying licenses

---

src/main/java/run/halo/app/controller/admin/api/BackupController.java

本地测试：
- 可以成功上传md，markdown，mdown后缀的文件。
- 上传其他格式比如jpg的文件报错：“不支持jpg格式的文件上传”
- 上传不带扩展名的文件报错：“不支持未知格式的文件上传”
/kind bug
修复 `/api/admin/backups/markdown/import`接口因配置了错误的MediaType导致markdown文章无法上传的问题。
Fixes #2176 
1. 尝试了在halo-admin，`uploadHandler: (file, options) => apiClient.backup.importMarkdown(file, options)`中拦截并修改Content-Type，无效。
2. 没有找到markdown文件的magic number，所以无法通过魔数去匹配文件格式。
3. 最后选择用文件扩展名匹配过滤。
```release-note
导入 Markdown 时只允许上传具有指定扩展名的文件
```

Filter files with markdown extension while importing markdown

---

src/main/java/run/halo/app/core/extension/Role.java
src/main/java/run/halo/app/plugin/PluginRequestMappingHandlerMapping.java
src/main/java/run/halo/app/security/authorization/Attributes.java
src/main/java/run/halo/app/security/authorization/AttributesRecord.java
src/main/java/run/halo/app/security/authorization/RbacRequestEvaluation.java
src/main/java/run/halo/app/security/authorization/RequestInfo.java
src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
src/test/java/run/halo/app/plugin/PluginRequestMappingHandlerMappingTest.java
src/test/java/run/halo/app/security/authorization/PolicyRuleTest.java
src/test/java/run/halo/app/security/authorization/RequestInfoResolverTest.java

/milestone 2.0
/area core
由于 [Plugin RFC](https://github.com/halo-dev/rfcs/pull/15) 设计更改，因此同步修改代码
1. 本次 PR 主要修改插件自定义 APIs 的生成规则
2. 撤销对之前插件 APIs 生成规则所改动的部分代码
Fixes #
```release-note
None
```

refactor: plugin custom api generate rules

---

src/main/java/run/halo/app/infra/utils/JsonParseException.java
src/main/java/run/halo/app/infra/utils/JsonUtils.java

/area core
/milestone 2.0
重构 json 工具类，当序列化/反序列化失败时抛出自定义J sonParseException
Fixes #
```release-note
None
```

refactor: JSON serialize exception

---

src/main/java/run/halo/app/config/WebServerSecurityConfig.java

/milestone 2.0
/area core
允许前端请求携带 Credentials，以及 X-XSRF-TOKEN、COOKIE 的请求头。
Fixes #
```release-note
None
```

refactor: allow additional headers for session CORS login

---

.github/pull_request_template.md

Change optimization into improvement in PR template.
Fixes #
```release-note
None
```

Change optimization into improvement in PR template

---

src/main/java/run/halo/app/extension/ConfigMap.java
src/test/java/run/halo/app/extension/ConfigMapTest.java

/kind feature
/area core
/milestone 2.0
新增 ConfigMap 自定义模型 https://github.com/halo-dev/rfcs/pull/17
ConfigMap 使用 `data` 字段接收键-值对作为其取值, 它是可选的设计用来保存 UTF-8 字符串。
Fixes #
```release-note
None
```

feat: add configmap extension

---

src/main/java/run/halo/app/core/extension/Role.java
src/main/java/run/halo/app/core/extension/RoleBinding.java
src/main/java/run/halo/app/core/extension/User.java
src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
src/main/java/run/halo/app/extension/ExtensionOperator.java
src/test/java/run/halo/app/core/extension/RoleBindingTest.java
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java
src/test/java/run/halo/app/extension/ExtensionOperatorTest.java

/kind feature
/area core
/milestone 2.0
Add an endpoint to grant permissions to user.
Fixes #
Test steps:
1. Start Halo
2. Check the initial password in the console log
3. Request <http://localhost:8090/webjars/swagger-ui/index.html> from browser and you will be redirected to login page
4. Input the username(admin) and the password you got just now
5. Grant permission as you wish
```release-note
None
```

Add an endpoint to grant permissions to user

---

.github/workflows/halo.yaml

/kind bug
Add checkout-from parameter for composite action. Please see <https://github.com/halo-sigs/actions/blob/a801af5be50a13a581bf8ded351eadbc8d8f2182/README.md>.
If we don't set the parameter for the action, it will checkout from `default branch` to build docker image. You can see <https://github.com/halo-dev/halo/runs/7316162265?check_suite_focus=true#step:2:478>.
Fixes #
```release-note
None
```

Add checkout-from parameter for composite action

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/Role.java
src/main/java/run/halo/app/core/extension/User.java
src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/RoleReconciler.java
src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
src/main/java/run/halo/app/core/extension/service/RoleService.java
src/main/java/run/halo/app/core/extension/service/UserService.java
src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
src/main/java/run/halo/app/infra/utils/JsonUtils.java
src/main/java/run/halo/app/security/authorization/DefaultRuleResolver.java
src/test/java/run/halo/app/core/extension/TestRole.java
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java
src/test/java/run/halo/app/core/extension/reconciler/RoleReconcilerTest.java
src/test/java/run/halo/app/core/extension/service/DefaultRoleServiceTest.java
src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java

/kind feature
/area core
/milestone 2.0
新增 `/apis/api.halo.run/v1alpha1/users/{name}/permissions` endpoint 用于根据用户名查询所具有的角色和 ui 权限
1. 当 Role 变更时在 Role reconciler 中查询该 Role 的依赖 Role 聚合其 metadata.annotations 中的 `rbac.authorization.halo.run/ui-permissions` 到当前 Role 的 metadata.annotations 中 key 为`rbac.authorization.halo.run/ui-permissions-aggregated`避免覆盖修改当前 Role 的 `rbac.authorization.halo.run/ui-permissions`
2. 根据用户名查询 ui 权限时，先根据用户名获取 RoleBinding 再获取 Role 然后合并 metadata.annotation 中的两个 key：`rbac.authorization.halo.run/ui-permissions` 和 `rbac.authorization.halo.run/ui-permissions-aggregated` 得到权限作为 API 返回值
Fixes #
```release-note
None
```

feat: add an API to fetch user permissions

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/plugin/SettingFetcher.java
src/test/java/run/halo/app/plugin/SettingFetcherTest.java

/area core
/milestone 2.0
由于 Setting 自定义模型关联表单值的存储结构改变，对应修改 SettingFetcher 的取值方式
https://github.com/halo-dev/rfcs/pull/18
Fixes #
```release-note
None
```

refactor: the value structure of ConfigMap for Setting custom extension

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/security/SuperAdminInitializer.java

/area core
/milestone 2.0
- 超级管理员具有所有 ui-permissions
- 根据用户名获取权限的接口标记非空文档注解
Fixes #
```release-note
None
```

refactor: super administrator role has all UI permissions

---

src/main/java/run/halo/app/core/extension/Plugin.java
src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
src/main/java/run/halo/app/plugin/BasePlugin.java
src/main/java/run/halo/app/plugin/BasePluginFactory.java
src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java

/kind feature
/milestone 2.0
/area core
插件 plugin.yaml 中不用在写 pluginClass 属性，插件的生命周期类通过标注 `@Component` 注解在启动时通过 PluginApplicationContext 依赖注入并创建实例，这得益于每个插件都有一个单独的 PluginApplicationContext 插件启动时可以将PluginWrapper 放到 Context 以支撑 pluginClass 实例的创建
```yaml
apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
name: PluginTemplate
spec:
pluginClass: run.halo.template.TemplatePlugin
```
现在只需要如下方式即可无需配置 pluginClass
```java
@Component
public class TemplatePlugin extends BasePlugin {}
```
Fixes #
```release-note
None
```

feat: plugin class is registered as a bean at startup

---

src/main/java/run/halo/app/core/extension/Plugin.java
src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
src/main/java/run/halo/app/plugin/resources/JsBundleRuleProvider.java
src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java

/area core
/milestone 2.0
重构 JsBundle 获取方式，增加对 js entry 的文件校验如果不存在，则启用插件时不生成反向代理 APIs
Fixes #
```release-note
None
```

refactor: scanning of the jsBundleRule for plugins

---

src/main/java/run/halo/app/controller/content/MainController.java

访问后台管理时使用重定向，在有反向代理且配置不完善的情况下，会导致重定向的域名发生错误。
https://spring.io/guides/gs/serving-web-content/
Fixes #2254
```release-note
修改后台管理页面为直接渲染而不是重定向，以更好的兼容反向代理
```

perf: access to admin page changed to template rendering

---

.github/workflows/halo.yaml

/kind flake
/milestone 2.0
- Change image name to `halo-dev`.
- Add checkout step due to <https://github.com/halo-sigs/actions/pull/7>.
```release-note
None
```

Change image name to halo-dev

---

src/main/java/run/halo/app/core/extension/Plugin.java
src/main/java/run/halo/app/core/extension/reconciler/RoleReconciler.java
src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/PluginApplicationContext.java
src/main/java/run/halo/app/plugin/PluginBeforeStopSyncListener.java
src/main/java/run/halo/app/plugin/PluginStartedListener.java
src/main/java/run/halo/app/plugin/YamlPluginFinder.java
src/main/java/run/halo/app/plugin/event/HaloPluginBeforeStopEvent.java
src/test/java/run/halo/app/core/extension/reconciler/RoleReconcilerTest.java
src/test/java/run/halo/app/plugin/PluginStartedListenerTest.java
src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java

/kind feature
/milestone 2.0
/area core
1. 重构插件初始自定义模型资源加载，修复无法加载问题
2. 增加插件停用前的初始自定义资源清理工作，如果插件被停止则插件启动时从 extensions 目录加载并创建的自定义模型资源将被删除，如果是角色则会相应删除 RoleBinding。
当插件被停止时并没有去检查 Role 中的 dependencies annotation 是否关联到被删除的 Role，对整个功能不会有任何影响
Fixes #
```release-note
None
```

feat: add plugin initial resource cleanup when plugin stop

---

build.gradle

/kind flake
/area core
/milestone 2.0
Upgrade Spring Boot to 3.0.0-M4. Please see <https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0-M4>.
```release-note
None
```

Upgrade Spring Boot to 3.0.0-M4

---

src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/infra/properties/HaloProperties.java
src/main/java/run/halo/app/plugin/PluginProperties.java
src/main/resources/application-dev.yaml
src/main/resources/application.yaml

/kind feature
/area core
/milestone 2.0
Provide an endpoint to install plugin using Jar file.
Currently, you could login and open the swagger ui to test against this feature.
```release-note
None
```

Provide an endpoint to install plugin using Jar file

---

src/main/java/run/halo/app/config/SwaggerConfig.java
src/main/java/run/halo/app/config/WebServerSecurityConfig.java
src/main/resources/application-dev.yaml

/kind feature
/area core
/milestone 2.0
1. Add grouped OpenAPI
3. Enable basic authentication on API endpoints.
```bash
curl -s -u admin:iY4PcvZLN4Dm0woV --basic 'http://localhost:8090/api/v1alpha1/users'
```
```release-note
None
```

Refine Swagger API with group

---

src/main/java/run/halo/app/config/SwaggerConfig.java

/area core
/milestone 2.0
Add all-api group for swagger. Related to https://github.com/halo-dev/halo/pull/2273.
```release-note
None
```

Add all-api group for swagger

---

src/main/java/run/halo/app/controller/content/model/PostModel.java

/kind bug
/area core
修复文章内容查询问题导致 meta_description 内容生成为空
Fixes #2281 
```release-note
修复文章内容查询问题导致的文章详情页 meta_description 为空 
```

fix: issue of post details page without meta_description variables

---

build.gradle
src/main/java/run/halo/app/config/SwaggerConfig.java
src/main/java/run/halo/app/extension/JSONExtensionConverter.java
src/main/java/run/halo/app/extension/Scheme.java
src/main/java/run/halo/app/extension/Unstructured.java
src/main/java/run/halo/app/extension/exception/SchemaViolationException.java
src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
src/test/java/run/halo/app/extension/SchemeTest.java

/area core
/milestone 2.0
This PR introduces [openapi4j](https://github.com/openapi4j/openapi4j) to replace JSON schema. See #2294 for more.
Fix #2294
```release-note
None
```

Replace JSON schema with OpenAPI 3.0

---

src/main/java/run/halo/app/theme/ThemeConfiguration.java
src/main/java/run/halo/app/theme/dialect/DefaultJava8TimeExpressionFactory.java
src/main/java/run/halo/app/theme/dialect/ThemeJava8TimeDialect.java
src/test/java/run/halo/app/theme/dialect/ThemeJava8TimeDialectIntegrationTest.java
src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
src/test/resources/themes/default/templates/timezone.html

/kind feature
/area core
/milestone 2.0
主题可以通过 temporals 表达式方言来格式化日期，格式化时会根据时区显示，例如：`${#temporals.format(instants, 'yyyy-MM-dd HH:mm:ss')}`
访问主题时通过携带 cookie 如 cookie:time_zone=Africa/Accra 来切换时区
支持的时区列表参考：https://jenkov.com/tutorials/java-date-time/java-util-timezone.html
表达式更多用法参考：https://github.com/thymeleaf/thymeleaf-extras-java8time
Fixes #2293
```release-note
None
```

feat: Theme temporals supports time zone

---

src/main/java/run/halo/app/core/extension/Theme.java
src/test/java/run/halo/app/core/extension/ThemeTest.java

/area core
/milestone 2.0
主题支持配置 settingName 和 configMapName
Fixes #2298
```release-note
None
```

refactor: support configuration settings and configmap name

---

OWNERS

chore: update reviewers for OWNERS file

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
src/main/java/run/halo/app/infra/exception/NotFoundException.java
src/main/java/run/halo/app/infra/exception/ThemeInstallationException.java
src/main/java/run/halo/app/infra/exception/ThemeUninstallException.java
src/main/java/run/halo/app/theme/TemplateEngineManager.java
src/main/java/run/halo/app/theme/ThemePathPolicy.java
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java

/kind feature
/milestone 2.0
/area core
新增主题卸载 endpoint
Fixes #2306
```release-note
None
```

feat: add theme uninstall endpoint

---

src/main/java/run/halo/app/plugin/DefaultDevelopmentPluginRepository.java
src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java
src/main/java/run/halo/app/plugin/PluginProperties.java
src/main/java/run/halo/app/plugin/PluginRequestMappingHandlerMapping.java
src/main/java/run/halo/app/plugin/SettingFetcher.java
src/test/java/run/halo/app/plugin/SettingFetcherTest.java

/kind feature
/milestone 2.0
/area core
目前插件开发模式允许配置项目目录，但必须配置到项目目录的上一级，并不友好
此 PR 提供了 fixedPluginPath 选项允许在开发模式时配置它为插件项目目录
在开发 gradle 插件时更易于通过配置此选项来加载插件
Fixes #
```release-note
None
```

feat: support fixed plugin path for development mode

---

src/main/java/run/halo/app/extension/ListResult.java
src/main/java/run/halo/app/extension/router/ExtensionRouterFunctionFactory.java
src/test/java/run/halo/app/extension/ListResultTest.java

/area core
/milestone 2.0
/release-note-none
Extract generateListResultClass into ListResult to make it easy to use in other places.

Extract generateListResultClass into ListResult

---

src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
src/main/java/run/halo/app/listener/comment/CommentEventListener.java
src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java

/kind bug
reply comments的评论审核通过时创建回复事件
添加了回复邮件发送的条件：当评论由管理员发布后回复邮件
Fixes #2246
null
```release-note
修复未审核评论回复会发送邮件提醒的问题
```

refactor: comments are converted to publish before sending reply email

---

src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java

/area core
/milestone 2.0
文章更新时 reconcile 文章内容是否有草稿正在编辑，有则更新status.inProgress=true否则为false
a part of #2322
```release-note
None
```

feat: update post in progress status when post changed

---

src/main/resources/extensions/system-setting.yaml

/kind feature
/milestone 2.0
/area core
新增系统设置默认资源 yaml
Fixes #2329
```release-note
None
```

feat: improve the site setting config

---

src/main/java/run/halo/app/infra/SystemSetting.java
src/main/java/run/halo/app/theme/TemplateEngineManager.java
src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
src/main/java/run/halo/app/theme/dialect/PostTemplateHeadProcessor.java
src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
src/main/java/run/halo/app/theme/dialect/TemplateGlobalHeadProcessor.java
src/main/java/run/halo/app/theme/dialect/TemplateHeadProcessor.java
src/main/java/run/halo/app/theme/router/PermalinkPatternProvider.java
src/main/resources/extensions/system-configurable-configmap.yaml
src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java

/kind feature
/milestone 2.0
/area core
主题模板渲染时支持代码片段自动注入
如何测试：
1. 文章页 head 注入
对于文章当spec.htmlMetas字段存在数据时访问文章页面 post.html 会自动在该页面的 head 中插入 meta tag
例如
htmlMetas = [{"name":"keywords", "content": "Halo,Blog"}, {"property":"org:name", "content": "fake-name"}]
则在 post.html返回结果的 `<head></head>`中能看到
```
<meta name="keywords" content="Halo,Blog" />
<meta property="org:name" content="fake-name" />
```
2. 内容页注入
当在后台设置->代码注入的`内容页 head`中填写了内容则访问 post.html 和 page.html 时会自动注入到 head 标签中（需要主题的是 page.html 为自定义页面，该功能在另一个 PR 中还未合并，因此内容页注入目前只适用 post.html）
3. 全局 head
当在后台设置->代码注入的`全局 head` 中填写的内容，访问任意模板页面时都会自动注入到 head 标签中
4. 页脚
页脚自定注入不适合，一般由主题开发者选择位置注入，因此提供了一个`<halo:footer></halo:footer>`标签，当在模板页面使用了此标签则 后台设置->代码注入的`页脚`处填写的内容在渲染后会替换此标签
Fixes #2376
```release-note
None
```

feat: support code snippet injection for theme template

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/content/ListedSinglePage.java
src/main/java/run/halo/app/content/PostQuery.java
src/main/java/run/halo/app/content/SinglePageQuery.java
src/main/java/run/halo/app/content/SinglePageRequest.java
src/main/java/run/halo/app/content/SinglePageService.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
src/main/java/run/halo/app/core/extension/SinglePage.java
src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
src/main/java/run/halo/app/infra/SchemeInitializer.java
src/main/java/run/halo/app/theme/DefaultTemplateEnum.java
src/main/java/run/halo/app/theme/finders/SinglePageFinder.java
src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
src/main/java/run/halo/app/theme/finders/vo/BasePostVo.java
src/main/java/run/halo/app/theme/finders/vo/SinglePageVo.java
src/main/java/run/halo/app/theme/router/PermalinkPatternProvider.java
src/main/java/run/halo/app/theme/router/TemplateRouteManager.java
src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
src/test/java/run/halo/app/content/impl/PostServiceImplTest.java
src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
src/test/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategyTest.java

/kind feature
/milestone 2.0
/area core
新增自定义页面模块
Fixes #2379
```release-note
None
```

feat: add single page extension module

---

src/main/java/run/halo/app/content/permalinks/ExtensionLocator.java
src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
src/main/java/run/halo/app/theme/router/PermalinkIndexer.java
src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
src/test/java/run/halo/app/core/extension/reconciler/TagReconcilerTest.java

/kind bug
/area core
/milestone 2.0
修复文章 分类 标签的 slug 改变时，没有重新生成 permalink 的问题
Fixes #
```release-note
None
```

fix: permalink update when slug changed

---

.github/workflows/halo.yaml

/kind feature
Support pushing to Docker Hub.
Please wait for https://github.com/halo-sigs/actions/pull/8 to be merged.
/hold
```release-note
None
```

Support pushing to Docker Hub

---

src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
src/main/java/run/halo/app/infra/utils/DataBufferUtils.java
src/main/java/run/halo/app/infra/utils/FileUtils.java
src/main/java/run/halo/app/infra/utils/HaloUtils.java

/kind bug
/area core
/milestone 2.0
We will encounter a stackoverflow error when installing theme with large size. Please see the following screenshot:
How to test?
1. Create a big theme installation package
2. Install it and see the result
```release-note
None
```

Fix stackoverflow error when installing big theme

---

src/main/java/run/halo/app/config/WebFluxConfig.java
src/main/java/run/halo/app/core/extension/endpoint/CustomEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/CustomEndpointsBuilder.java

/area core
/milestone 2.0.0
Refactor CustomEndpoint for customizing GroupVersion.
```release-note
None
```

Refactor CustomEndpoint for customizing GroupVersion

---

src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java

/area core
/milestone 2.0
文章自动摘要只从正在使用的已发布版本的内容中取得
Fixes #2452
```release-note
None
```

fix: post excerptare generated using only published content that is in use

---

src/main/java/run/halo/app/theme/router/PermalinkIndexer.java

/area core
/milestone 2.0
注册 permalink 到 Permalinker 时校验 permalink 是否已经存在，如果存在则记录错误日志且不向 PermalinkIndexer 添加记录
TODO：
A part of #2454
```release-note
None
```

feat: add error log when permalink exists

---

src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java

/kind bug
/area core
/milestone 2.0
Fix empty listing of single page while using PostgreSQL.
```release-note
None
```

Fix empty listing of single page

---

src/main/java/run/halo/app/content/PostSorter.java

/milestone 2.0
/area core
修改文章列表的默认排序规则，之前是按照创建时间（createTime）升序，现在改为降序。即最新创建的文章在前面。
测试方式：
连续创建多篇文章，检查前后台的文章排序是否是最新的在最前面。
```release-note
None
```

perf: change the default sort order of articles

---

src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
src/test/java/run/halo/app/core/extension/endpoint/ThemeEndpointTest.java

/area core
/milestone 2.0
主题 reload endpoint 增加对 theme.yaml 的 reload 操作
Fixes #
```release-note
None
```

refactor: reload theme.yaml when theme reload

---

src/main/java/run/halo/app/core/extension/Theme.java
src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java

/area core
/milestone 2.0
主题支持展示绝对路径位置
Fixes #2461
```release-note
None
```

feat: add location for theme

---

src/main/java/run/halo/app/content/SinglePageQuery.java
src/main/java/run/halo/app/content/SinglePageSorter.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
src/main/java/run/halo/app/core/extension/SinglePage.java

/kind feature
/milestone 2.0
/area core
自定义页面增加排序和筛选：
筛选：
关键词
状态
可见性
作者
排序：
发布时间
创建时间
Fixes #2469
```release-note
None
```

feat: add more query params and sorter for single page

---

src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java

/area core
/milestone 2.0
创建评论时 hidden 字段默认为 false
Fixes #
```release-note
None
```

refactor: comment hidden default is false

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/core/extension/service/UserService.java
src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java

/kind bug
/area core
/milestone 2.0
Fix the problem of granting role not taking effect.
Fixes https://github.com/halo-dev/halo/issues/2490
Steps to test:
1. Create an user
2. Grant a role for the user
3. Check the user list
```release-note
None
```

Fix the problem of granting role not taking effect

---

src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java

/area core
/milestone 2.0
发布和更新文章及自定义页面时如果遇到乐观锁错误自动重试
Fixes #
```release-note
None
```

feat: add retry operation for post and single page when publish and update

---

README.md

/milestone 2.0
更新 README。
See https://github.com/halo-dev/halo/issues/2410 for more
/hold
```release-note
None
```

docs: update readme for Halo 2.0

---

src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java

/area core
/milestone 2.0
修复文章和自定义页面的总评论数量统计取值错误
Fixes #
```release-note
None
```

fix: total comment count for page and singlepage

---

.github/workflows/halo.yaml

/area core
/milestone 2.0
Change condition of docker push for releasing.
```release-note
None
```

Change condition of docker push for releasing

---

.github/pull_request_template.md

See https://github.com/halo-dev/halo/pull/2078 for more.
```release-note
None
```

Add Pull Request template for default branch

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/reconciler/ReverseProxyReconciler.java
src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
src/main/java/run/halo/app/plugin/PluginConst.java
src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
src/test/java/run/halo/app/plugin/PluginCompositeRouterFunctionTest.java
src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java

/area core
/milestone 2.0
重构插件反向代理注册方式
Fixes #2520
How to test:
1. clone 项目 https://github.com/halo-sigs/plugin-comment-widget 后 build 一个 jar
2. 将该 jar 作为一个插件安装到系统并启用它
3. 访问插件提供的反向代理资源
```
curl --location --request GET 'http://localhost:8090/assets/PluginCommentWidget/static/comment-widget.iife.js'
```
期望得到结果
4. 停用插件，重复 Step 3，期望得到 404
5. 重复数次 Step 3-4 均与期望相同即可 
```release-note
None
```

refactor: the way of router function register for reverse proxy

---

README.md

/milestone 2.0
更新 README，提供 Halo 2.0 的演示环境信息。
```release-note
None
```

docs: provides Halo 2.0 online demo environment

---

src/main/java/run/halo/app/theme/finders/impl/MenuFinderImpl.java
src/main/java/run/halo/app/theme/finders/vo/MenuItemVo.java
src/main/java/run/halo/app/theme/finders/vo/MenuVo.java
src/main/java/run/halo/app/theme/finders/vo/VisualizableTreeNode.java
src/test/java/run/halo/app/theme/finders/impl/MenuFinderImplTest.java

/area core
/milestone 2.0
优化主题端菜单项查询
Fixes #2564
使用 menuFinder.getDefault() 方法测试多级菜单项的排序及新增
```release-note
修复主题端菜单查询数据错误问题
```

refactor: get default menu

---

src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java

/kind bug
/area core
/milestone 2.0
修复主题列表数据类型转换问题
Fixes #
访问如下 API 不报错即可
```
curl http://localhost:8090/apis/api.console.halo.run/v1alpha1/themes?uninstalled=false
```
```release-note
None
```

refactor: theme list data conversion

---

src/main/java/run/halo/app/core/extension/endpoint/StatsEndpoint.java

/area core
/milestone 2.0
修改仪表盘统计返回类型的名称避类名相同时 swagger api 的 schema 被覆盖
Fixes #
```release-note
None
```

refactor: rename stats to dashboard stats

---

src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java

/kind bug
保存空白内容的草稿时，将 `null` 转换为无内容的字符串，防止读取相关实体的数据时发生空指针异常
Fixes #2614
```release-note
None
```

fix: fail to save existing post with blank content

---

src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java

/kind bug
/milestone 2.0
修复文章、自定义页面、评论聚合查询接口排序不固定的问题。
Fixes https://github.com/halo-dev/halo/issues/2622
测试方式：检查 Console 端的文章、自定义页面、评论、回复的排序是否正常，需要多次刷新检查。
```release-note
修复文章、自定义页面、评论聚合查询接口排序不固定的问题。
```

fix: issue of abnormal sorting in the aggregation query interface

---

src/main/resources/application-dev.yaml

/milestone 2.0
在 dev 的配置文件中禁用 Thymeleaf 的模板缓存。
```release-note
在 dev 的配置文件中禁用 Thymeleaf 的模板缓存。
```

chore: disable thymeleaf cache in dev profile

---

build.gradle

/area core
/milestone 2.0
Please refer to <https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.0-RC1>.
```release-note
None
```

Bump SpringDoc to 2.0.0-RC1

---

README.md

Bump image tag in docker command.
```release-note
None
```

Update README.md due to 2.0.0-alpha.3 released

---

src/main/resources/extensions/system-setting.yaml

/milestone 2.0
/area core
更新系统设置的表单定义，为 Logo / Favicon 使用新的选择附件输入框，为代码注入部分设置使用新的代码编辑器输入框。
Ref https://github.com/halo-dev/halo/issues/2558
/hold
请等待以下 PR 合并：
- https://github.com/halo-dev/console/pull/674
- https://github.com/halo-dev/console/pull/672
- https://github.com/halo-dev/console/pull/675
测试方式：
1. Console 需要使用最新的 main 分支。
2. 测试系统设置中的 Logo / Favicon 和代码注入部分的设置项是否正常使用。
```release-note
更新系统设置的表单定义，提供更便捷的代码和附件选择输入框。
```

perf: use the new formkit custom input for system setting forms schema

---

src/main/java/run/halo/app/metrics/CounterMeterHandler.java
src/main/java/run/halo/app/metrics/VisitLogWriter.java
src/test/java/run/halo/app/metrics/VisitLogWriterTest.java

/kind bug
/area core
/milestone 2.0
修复 Halo 异常停止时日志服务线程无法中断的问题
使用 mysql 启动 halo 但不启动 mysql，此时 halo 会无法链接 mysql
期望现象：Halo 服务终止，异常现象：Halo 抛异常但 Netty 服务器不会停止
```release-note
修复 Halo 异常停止时日志服务线程无法中断的问题
```

fix: cannot stop thread when system is interrupted

---

src/main/java/run/halo/app/metrics/VisitLogWriter.java

/kind bug
/area core
/milestone 2.0
修复日志 while 循环导致 cpu 占用高的问题
```release-note
None
```

fix: while cycles cause high cpu usage

---

.github/workflows/halo.yaml

Pass console-ref param into build-and-push action. You can see <https://github.com/halo-sigs/actions/commit/0414dd915a2a23e5c8c3ef987ad8311ce8a97266> for more.
```release-note
None
```

Build console with release tag when releasing

---

src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
src/main/java/run/halo/app/infra/SystemSetting.java
src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
src/main/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/CategoriesRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/CategoryRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/IndexRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/ModelConst.java
src/main/java/run/halo/app/theme/router/strategy/TagRouteStrategy.java
src/main/resources/extensions/system-setting.yaml
src/test/java/run/halo/app/theme/router/strategy/RouterStrategyTestSuite.java

/area core
/milestone 2.0
允许通过配置修改文章分页大小
1. 多创建一些文章并关联分类和标签
2. 通过后台设置修改在不同位置的文章分页大小查看是否生效，包括首页文章列表、根据标签查询文章、根据分类查询文章、文章归档
```release-note
支持通过配置修改文章分页大小
```

refactor: add page size configuration for post

---

src/main/java/run/halo/app/extension/ListResult.java
src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
src/test/java/run/halo/app/extension/ListResultTest.java

/area core
/milestone 2.0
分页结果返回总页数
Fixes #2666
```release-note
分页结果返回总页数
```

feat: total pages returned from paging results

---

build.gradle

/area core
/milestone 2.0
Bump Spring Boot to 3.0.0-RC2. 
See https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0-RC2 for more.
```release-note
升级 Spring Boot 至 3.0.0-RC2
```

Bump Spring Boot to 3.0.0-RC2

---

README.md

1. 更新 2.0.0 的版本号。
2. 更新文档的版本号描述。
3. 更新标语。
```release-note
None
```

docs: update readme for Halo 2.0.0-beta.1 and new slogan

---

src/main/java/run/halo/app/search/IndicesServiceImpl.java
src/main/java/run/halo/app/search/post/PostEventListener.java
src/main/java/run/halo/app/theme/finders/PostFinder.java
src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java

/kind bug
/area core
/milestone 2.0
修复上一个 PR 没有拉取最新代码合并后导致无法构建的问题
```release-note
None
```

fix: failed to build due to wrong type

---

src/main/resources/application-dev.yaml
src/main/resources/application.yaml
src/main/resources/extensions/attachment-local-policy.yaml

/area core
/milestone 2.0.0
See https://github.com/halo-dev/halo/issues/2727 for more.
Fixes https://github.com/halo-dev/halo/issues/2727
```release-note
None
```

Change working directory to .halo2

---

src/main/java/run/halo/app/theme/finders/impl/ContributorFinderImpl.java
src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
src/main/java/run/halo/app/theme/finders/impl/TagFinderImpl.java

/area core
/milestone 2.0.0-rc.1
修复主题端文章列表排序不固定问题
Fixes #2734
```release-note
修复主题端文章列表排序不固定问题
```

fix: inconsistent order of post for theme-side

---

src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java

/kind feature
/area core
/milestone 2.0.0-rc.1
Provide `ungrouped` query param to filter ungrouped attachments. Please note that we will ignore `group` query param when `ungropued` is `true`.
```bash
curl -X 'GET' \
'http://localhost:8090/apis/api.console.halo.run/v1alpha1/attachments?ungrouped=true' \
-H 'accept: */*'
```
Fixes https://github.com/halo-dev/halo/issues/2451
```release-note
None
```

Provide ungrouped query param to filter ungrouped attachments

---

README.md

为 Halo 2.0.0-rc.1 更新 README。
```release-note
None
```

docs: update readme for Halo 2.0.0-rc.1 and new slogan

---

build.gradle

/area core
/milestone 2.0.0-rc.2
See https://github.com/halo-dev/halo/issues/2767 for more.
Fixes https://github.com/halo-dev/halo/issues/2767
```release-note
升级依赖 SpringDoc OpenAPI 至 2.0.0
```

Upgrade to SpringDoc OpenAPI 2.0.0

---

build.gradle

/area core
See https://github.com/halo-dev/halo/issues/2766 for more.
Fixes https://github.com/halo-dev/halo/issues/2766
```release-note
升级依赖 Spring Boot 至 3.0.0
```

Upgrade to Spring Boot 3.0.0

---

build.gradle

/area core
see also https://github.com/pf4j/pf4j/compare/release-3.7.0...release-3.8.0
Fixes #2771
```release-note
升级依赖 PF4J 至 3.8.0
```

chore: upgrade to PF4J 3.8.0

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml
.github/ISSUE_TEMPLATE/feature_request.en.yml
.github/ISSUE_TEMPLATE/feature_request.zh.yml

为 Halo 2.0 更新 issue 模板。
效果可以查看：
- https://github.com/ruibaby/halo/issues/new?assignees=&labels=bug&template=bug_report.zh.yml
- https://github.com/ruibaby/halo/issues/new?assignees=&labels=&template=feature_request.zh.yml
```release-note
None
```

chore: update issue templates for Halo 2.0

---

src/main/java/run/halo/app/core/extension/reconciler/RoleReconciler.java

/area core
/milestone 2.0.x
This PR only do one improvement for reconciling Role. I always fetch the latest data and compare the difference between the latest and current, and then decide whether to update based on the result.
Fixes https://github.com/halo-dev/halo/issues/2784
Steps to test:
1. Restart Halo multiple times and see the log
```release-note
None
```

Fix an optimistic lock error always appearing when restarting Halo

---

README.md

为 Halo 2.0 正式版本更新 README。
/hold
等待创建 2.0 的 release。
```release-note
None
```

docs: update readme for Halo 2.0.0

---

gradle.properties

/area core
Bump Halo version in gradle.properties for next release.
```release-note
None
```

Bump Halo version in gradle.properties

---

gradle.properties

/area core
Bump halo version to 2.1.0-SNAPSHOT for next release.
```release-note
None
```

Bump halo version to 2.1.0-SNAPSHOT for next release

---

README.md

Update Halo version to 2.0.1 in README.
```release-note
None
```

Update Halo version to 2.0.1

---

src/main/java/run/halo/app/metrics/VisitLogWriter.java

/kind bug
/area core
Shutdown AsyncLogWriter on VM exit.
Fixes https://github.com/halo-dev/halo/issues/2901
```release-note
None
```

Fix the problem of getting stuck on VM exit

---

README.md

see https://github.com/badges/shields/issues/8671
```release-note
None
```

docs: update github workflow badge

---

OWNERS

将 @minliacom 添加到 Reviewer 列表。
他的贡献列表：
- https://github.com/halo-dev/halo/pulls?q=is%3Apr+author%3Aminliacom+
- https://github.com/halo-dev/halo/issues?q=+is%3Aissue+author%3Aminliacom+
- https://github.com/halo-sigs/awesome-halo/pulls?q=+is%3Apr+author%3Aminliacom+
欢迎 @minliacom 加入。
```release-note
None
```

chore: add @minliacom to reviewer list

---

gradle.properties

/kind cleanup
/area core
Bump version to 2.0.2-SNAPSHOT for next release.
```release-note
None
```

Bump version to 2.0.2-SNAPSHOT for next release

---

gradle.properties

/kind cleanup
/area core
Bump version to 2.0.3-SNAPSHOT.
```release-note
None
```

Bump version to 2.0.3-SNAPSHOT for next release

---

src/main/resources/application.yaml

/area core
Provide a default configuration for logging system. Default log filename is `${halo.work-dir}/logs/halo.log`.
References:
- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.logging.file-output
- https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.logging.file-rotation
Fixes https://github.com/halo-dev/halo/issues/2968
Start Halo and check the log file `${halo.work-dir}/logs/halo.log`.
```release-note
持久化并归档历史日志
```

Persist and archive historical logs

---

build.gradle

/area core
Upgrade to spring boot 3.0.1
Fixes #3030 
```release-note
NONE
```

Upgrade to spring boot 3.0.1

---

src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java

/area core
主题卸载时等待删除关联资源后再清除 Finalizer
see #2967 for more detail.
https://github.com/halo-dev/halo/issues/2967#issuecomment-1354384978
- 在主题中多添加一个 AnnotationSetting 资源 yaml，测试主题删除是否正常。
- 对包 `org.springframework.retry` 开启 debug 日志后能在删除主题时看到类似如下日志：
```
16:33:02.822 [Test worker] DEBUG org.springframework.retry.support.RetryTemplate - Retry: count=0
16:33:03.128 [Test worker] DEBUG org.springframework.retry.support.RetryTemplate - Checking for rethrow: count=1
```
Fixes #2967
```release-note
主题卸载时等待删除关联资源后再清除 Finalizer
```

refactor: remove finalizer when resources deleted completely

---

src/main/java/run/halo/app/config/WebFluxConfig.java
src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
src/main/java/run/halo/app/theme/ThemeConfiguration.java

/area core
Add cache control and last modified headers for responses of static resources.
Fixes https://github.com/halo-dev/halo/issues/2966
We can check the response header of statis resources to know if the cache control is working correctly.
```release-note
完善静态资源的缓存策略
```

Cache static resources, including plugin, theme, console, attachment

---

gradle.properties

/kind cleanup
/area core
Bump version to 2.2.0-SNAPSHOT for next iteration.
```release-note
None
```

Bump version to 2.2.0-SNAPSHOT for next iteration

---

gradle.properties

/kind cleanup
/area core
Update version to 2.0.4-SNAPSHOT for next iteration.
```release-note
None
```

Update version to 2.0.4-SNAPSHOT for next iteration

---

gradle.properties

/kind cleanup
/area core
Bump version to 2.1.1-SNAPSHOT for next iteration.
```release-note
None
```

Bump version to 2.1.1-SNAPSHOT for next iteration

---

README.md

- Use arguments instead of environments.
- Change Docker image halo:2.0 into halo:2.1
```release-note
None
```

Refine docker-run command in README.md

---

src/main/java/run/halo/app/config/WebFluxConfig.java
src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
src/main/java/run/halo/app/theme/ThemeConfiguration.java
src/main/resources/application-dev.yaml
src/main/resources/application.yaml

/area core
This PR adapt web properties to control cache of static resources.
Users who want to disable cache can configure like this:
```yaml
spring:
web:
resources:
cache:
cachecontrol:
no-cache: true
use-last-modified: false
```
By default, we have disabled cache in development environment.
Fixes https://github.com/halo-dev/halo/issues/3127
```release-note
None
```

Adapt spring.web.resources.cache configuration

---

src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java

/area core
Provide administrators with the ability to adjust the order of articles by modifying the publish time.
Fixes https://github.com/halo-dev/halo/issues/3143
修改前：
修改后：
```release-note
主题侧文章以发布时间排序
```

improve the sorting rules for themes side posts using publishTime

---

src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java

/area core
Display archives in reverse chronological order.
Fixes https://github.com/halo-dev/halo/issues/3157
改进前：
改进后：
```release-note
归档以年份降序排序
```

improve the sorting rules of archives by using reverse year order

---

build.gradle

/area core
Upgrade Spring Boot to 3.0.2. 
See https://github.com/spring-projects/spring-boot/releases/tag/v3.0.2 for more.
```release-note
升级依赖 Spring Boot 至 3.0.2
```

Upgrade Spring Boot to 3.0.2

---

build.gradle

/area core
See https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-scanning-index for more.
This might help a little, bu we have to.
```release-note
None
```

Add spring-context-indexer to speed up startup

---

build.gradle

/area core
See <https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.2> and <https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.1> for more.
```release-note
升级依赖 SpringDoc 至 2.0.2
```

Upgrade SpringDoc to 2.0.2

---

build.gradle

/kind imporvement
/area core
See https://github.com/pf4j/pf4j/blob/2d3cf24fed4c0ca8addbbbc70ebcb1fe4c3f877f/CHANGELOG.md#390---2023-01-30 for more.
Please confirm that the plugin module is working fine.
```release-note
升级依赖 PF4J 至 3.9.0
```

Upgrade pf4j to 3.9.0

---

build.gradle

/area core
See https://lucene.apache.org/core/9_5_0/MIGRATE.html for more.
Please confirm that the search widget is working fine.
```release-note
升级依赖 Lucene 至 9.5.0
```

Upgrade Lucene to 9.5.0

---

README.md
gradle.properties

/kind cleanup
/area core
Bump Halo version to 2.3.0-SNAPSHOT and update README.md
```release-note
None
```

Bump Halo version to 2.3.0-SNAPSHOT for main branch

---

README.md
gradle.properties

/kind cleanup
/area core
Bump Halo to 2.2.1-SNAPSHOT and update README.md.
```release-note
None
```

Bump Halo to 2.2.1-SNAPSHOT for release-2.2 branch

---

src/main/java/run/halo/app/content/impl/PostServiceImpl.java

/kind bug
replaced flatMap with flatMapSequential to ensure that the list of tags and categories shown in console post order is not random
Fixes #3139
/cherrypick release-2.0
/cherrypick release-2.1
```release-note
修复控制台文章列表中，标签和分类顺序随机的问题
```

Fix random list problem of tags and categories

---

src/main/java/run/halo/app/theme/TemplateEngineManager.java

/area core
修改 TemplateEngineManager 中 LRU cache 的缓存 key
see #3242 for more details.
Fixes #3242
1. 安装几个主题测试预览功能是否正常
2. 特别关注激活主题的预览，激活主题的预览和激活主题直接访问使用的不同的 TemplateEngine
```release-note
None
```

refactor: lru cache key for template engine manager

---

OWNERS

将 @LIlGG 添加到 Reviewer 列表。
```release-note
None
```

chore: add @LIlGG to reviewers list

---

src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java

/kind bug
/area core
Fixed incorrect number of comments after comment deletion.
Fixes https://github.com/halo-dev/halo/issues/3287
为一篇文章添加多个评论，期望评论数量正确。
删除评论，期望评论数量正常减少。
删除全部评论，期望评论数量归零。
```release-note
修复删除评论后Console端文章和单页评论数量不正确
```

fix: incorrect number of comments

---

src/main/resources/application.yaml

/kind feature
Fixes #3188 
测试方式：
1. 使用 prod 模式启动项目，使用超级管理员登陆
2. 访问 /actuator/logfile 查看是否有日志显示。
```release-note
NONE
```

feat: open actuator logfile endpoint for prod

---

src/main/java/run/halo/app/actuator/DatabaseInfoContributor.java

/kind feature
Fixes #3263
测试方法：
1. 使用超级管理员登录
2. 查看接口 /actuator/info 查看是否存在 database 字段。
```release-note
NONE
```

feat: add database endpoint for actuator

---

build.gradle

/kind cleanup
/area core
Upgrade to Spring Boot 3.0.3. See https://github.com/spring-projects/spring-boot/releases/tag/v3.0.3 for more.
```release-note
Upgrade to Spring Boot 3.0.3.
```

Upgrade to Spring Boot 3.0.3

---

.github/workflows/halo.yaml
README.md
build.gradle

/kind cleanup
/area core
1. Report test result using Jacoco plugin
2. Support uploading coverage reports to Codecov
You can see the result from <https://github.com/JohnNiang/halo/pull/7#issuecomment-1442866254>.
Refs:
- https://docs.gradle.org/current/userguide/jacoco_plugin.html
- https://github.com/codecov/example-java-gradle
```release-note
None
```

Report test result using Jacoco plugin

---

src/main/resources/extensions/user.yaml

/area core
为系统默认用户添加系统保护 finalizer，避免被删除
```shell
curl -u username:password --basic 'http://localhost:8090/api/v1alpha1/users/ghost'
curl -u username:password --basic 'http://localhost:8090/api/v1alpha1/users/anonymousUser'
```
将看到 
```json
"finalizers": [
"...",
"system-protection"
]
```
Fixes #
```release-note
None
```

chore: add finalizer for ghost and anonymous users

---

README.md

修复 Docker 快速运行的 `halo.security.initializer.superadminusername` 参数。
```release-note
None
```

docs: fix command of docker run

---

src/main/java/run/halo/app/theme/router/factories/ArchiveRouteFactory.java
src/main/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactory.java
src/main/java/run/halo/app/theme/router/factories/CategoryPostRouteFactory.java
src/main/java/run/halo/app/theme/router/factories/IndexRouteFactory.java
src/main/java/run/halo/app/theme/router/factories/RouteFactory.java
src/main/java/run/halo/app/theme/router/factories/TagPostRouteFactory.java
src/test/java/run/halo/app/theme/router/factories/RouteFactoryTest.java

/kind bug
/area core
修复文章列表分页配置取值错误的问题
此问题为 #3300 PR 引入，由于改动较大遗漏了这点没测试到。
how to test it？
修改文章设置中的大小，查看主题端分页是否符合预期：
包括首页，归档页，标签文章页，分类文章页。
Fixes #3411
```release-note
None
```

fix: post page size configuration not work

---

.github/workflows/halo.yaml

/kind cleanup
/area core
For a stable workflow.
```release-note
None
```

Update halo-next-docker-build actio to release-2.0

---

.github/workflows/halo.yaml

/kind cleanup
/area core
For a stable workflow.
```release-note
None
```

Update halo-next-docker-build action to release-2.1

---

gradle.properties

/kind cleanup
/area core
Update Halo version to 2.2.2-SNAPSHOT for next development.
```release-note
None
```

Update Halo version to 2.2.2-SNAPSHOT

---

gradle.properties

/kind cleanup
/area core
Update Halo version to 2.4.0-SNAPSHOT for next development.
```release-note
None
```

Update Halo version to 2.4.0-SNAPSHOT

---

gradle.properties

/kind cleanup
/area core
Update Halo version to 2.3.1-SNAPSHOT for next development.
```release-note
None
```

Update halo version to 2.3.1-SNAPSHOT

---

.github/workflows/halo.yaml

/kind cleanup
I have to manually make those changes due to <https://github.com/halo-dev/halo/pull/3368#issuecomment-1449292283>.
See https://github.com/halo-dev/halo/pull/3368 for more.
Fixes https://github.com/halo-dev/halo/issues/3200
```release-note
None
```

Bump up checkout and setup-java actions

---

.github/workflows/halo.yaml

/kind cleanup
I have to manually make those changes due to <https://github.com/halo-dev/halo/pull/3368#issuecomment-1449292283>.
See https://github.com/halo-dev/halo/pull/3368 for more.
Fixes https://github.com/halo-dev/halo/issues/3200
```release-note
None
```

Bump up checkout and setup-java actions for release-2.1 branch

---

.github/workflows/halo.yaml

/kind cleanup
/area core
For stable CI/CD in branch release-2.3.
```release-note
None
```

Adapt GitHub Workflow for branch release-2.3

---

console/src/modules/contents/comments/components/CommentListItem.vue
console/src/modules/system/plugins/layouts/PluginLayout.vue

/area console
移除 Console 未使用的变量和导入，解决 ESLint 的警告。
```release-note
None
```

chore: remove unused vars and imports to fix eslint warning

---

src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java

/area core
去掉开发模式初始化器中加载插件的逻辑，以解决开发模式下启动插件时会遇到的问题
1. 重启插件/Halo启动时 PluginApplicationContext#hash has been closed already.
2. 卸载插件时 NullPointerException at pluginWrapper.getPlugin().stop() becuase 'pluginWrapper' is null
3. Halo 启动时 `Most likely this exception is thrown because the called constructor (xxx) cannot handle 'null' parameters. Original message was:  ...`
4. 以及启动插件后插件的 bean 没有被创建等
```shell
2023-03-20T13:28:02.811+08:00 ERROR 59170 --- [nReconciler-t-1] r.h.a.e.controller.DefaultController     : Reconciler in run.halo.app.core.extension.reconciler.PluginReconciler-worker-1 aborted with an error, re-enqueuing...
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 10
at …
```

refactor: plugin development initializer

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat

/kind cleanup
/area core
Upgrade to Gradle 8.0.2 by using command `./gradlew wrapper --gradle-version 8.0.2 --distribution-type bin`.
Recently, we have a plan to restructure our project via Gradle 8, so I upgrade to Gradle 8.0.2 now.
```release-note
None
```

Upgrade to Gradle 8.0.2

---

console/src/modules/interface/themes/components/ThemeListModal.vue
console/src/modules/interface/themes/components/preview/ThemePreviewModal.vue

使用 [TanStack Query](https://github.com/TanStack/query) 重构主题相关数据请求的相关逻辑。
Ref https://github.com/halo-dev/halo/issues/3360
测试方式：
1. 测试主题管理列表的数据是否加载正常。
2. 测试预览主题弹框中设置数据是否加载正常。
```release-note
None
```

refactor: use tanstack query to refactor theme-related fetching

---

console/package.json
console/packages/components/src/components/modal/Modal.vue
console/packages/components/src/index.ts
console/pnpm-lock.yaml
console/src/App.vue
console/src/components/editor/DefaultEditor.vue
console/src/layouts/BasicLayout.vue
console/src/main.ts
console/src/modules/contents/posts/widgets/RecentPublishedWidget.vue
console/src/modules/dashboard/widgets/QuickLinkWidget.vue
console/src/modules/interface/themes/components/preview/ThemePreviewModal.vue
console/src/setup/setupStyles.ts

/area console
优化页面滚动条的样式，引入 [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars) 实现类似于 macOS 下的仅滚动时显示滚动条的特性，并保证在各个浏览器的表现一致。
测试方式：使用不同的浏览器测试滚动条是否可以自动隐藏以及样式是否一致即可。
```release-note
优化 Console 端页面滚动条的样式。
```

perf: improve the style of the scrollbar

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
See https://github.com/halo-dev/halo/issues/3599 for more.
Fixes https://github.com/halo-dev/halo/issues/3599
```release-note
升级至 Spring Boot 3.0.5
```

Upgrade to Spring Boot 3.0.5

---

console/src/modules/contents/posts/components/PostSettingModal.vue

/kind bug
/area console
修复从文章列表打开设置之后保存会调用两次发布接口的问题。
Fixes https://github.com/halo-dev/halo/issues/3615
测试从文章列表打开设置后保存是否会调用多次发布接口即可。
```release-note
修复 Console 端发布文章可能调用多次接口的问题。
```

fix: post publishing api is requested twice

---

application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java

/kind feature
/area core
See https://github.com/halo-dev/halo/issues/3605#issuecomment-1486509473 for more.
Fixes https://github.com/halo-dev/halo/issues/3605
```release-note
提供配置以控制能否被 iframe 引用
```

Make frame options header configurable

---

console/src/modules/interface/themes/ThemeSetting.vue
console/src/modules/interface/themes/layouts/ThemeLayout.vue
console/src/modules/system/plugins/PluginSetting.vue
console/src/modules/system/plugins/layouts/PluginLayout.vue
console/src/modules/system/users/UserList.vue

使用 [TanStack Query](https://github.com/TanStack/query) 重构主题和插件设置表单的逻辑，移除无意义的重复请求。
Ref https://github.com/halo-dev/halo/issues/3360
测试方式：
1. 安装若干带有设置表单的主题和插件。
2. 测试主题和插件的设置表单是否加载正常，以及保存设置后再重复加载的时候是否正常。
```release-note
None
```

refactor: use tanstack query to refactor setting-form-related fetching of theme and plugin

---

console/src/layouts/BasicLayout.vue

/area console
/milestone 2.4.0
优化左侧菜单栏边框阴影的样式。
Fixes https://github.com/halo-dev/halo/issues/3629
```release-note
优化左侧菜单栏边框阴影的样式。
```

perf: improve shadow style of side menu

---

application/src/main/resources/extensions/role-template-post.yaml
application/src/main/resources/extensions/role-template-singlepage.yaml
application/src/main/resources/extensions/role-template-snapshot.yaml
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml

/kind cleanup
/area core
/area console
See https://github.com/halo-dev/halo/issues/3529 for more.
Fixes https://github.com/halo-dev/halo/issues/3529
```release-note
None
```

Fix typo: snaphosts -> snapshots

---

console/src/locales/index.ts
console/src/main.ts
console/src/modules/system/users/Login.vue

/kind feature
/area console
在登录页面添加语言设置的支持。
在登录页面测试语言切换是否生效即可。
```release-note
None
```

feat: add setting locale supports in login page

---

application/build.gradle

/kind cleanup
Upgrade to plugin-comment-widget 1.5.0.
```release-note
None
```

Upgrade to plugin-comment-widget 1.5.0

---

README.md
gradle.properties

/kind cleanup
/area core
- Bump up version to 2.5.0-SNAPSHOT for next development
- Update README.md
```release-note
None
```

Bump up version to 2.5.0-SNAPSHOT

---

console/src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
console/src/modules/interface/themes/ThemeSetting.vue
console/src/modules/interface/themes/components/preview/ThemePreviewModal.vue
console/src/modules/system/auth-providers/AuthProviderDetail.vue
console/src/modules/system/plugins/PluginSetting.vue
console/src/modules/system/settings/SystemSetting.vue

Cherry pick of #3668 on release-2.4.
#3668: fix: radio value type is incorrect in the form defined by
```release-note
```

Automated cherry pick of #3668: fix: radio value type is incorrect in the form defined by

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json
gradle.properties

/kind cleanup
Prepare to release 2.4.1.
```release-note
None
```

Bump up version to 2.4.1

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json
gradle.properties

修改版本号，准备发布 2.4.2。
```release-note
None
```

chore: bump up version to 2.4.2

---

console/src/modules/interface/themes/components/preview/ThemePreviewModal.vue

/kind bug
修复预览主题页面的设置表单可能因为接口请求速度导致无法正常渲染表单的问题。
Fixes https://github.com/halo-dev/halo/issues/3705
测试方式：
1. 在主题管理页面点击预览按钮，检查设置表单是否可以正常渲染即可。
```release-note
修复 Console 端预览主题页面的设置表单可能出现无法渲染的问题。
```

fix: the setting form of the preview theme page may not be rendered

---

application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
application/src/main/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactory.java
application/src/test/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactoryTest.java

/kind bug
/area core
修复作者页无法访问的问题
Fixes #3718
```release-note
修复作者页无法访问的问题
```

fix: user page not found

---

console/src/modules/interface/menus/Menus.vue
console/src/modules/interface/menus/components/MenuList.vue

使用 [TanStack Query](https://github.com/TanStack/query) 重构菜单和菜单项的逻辑，修复菜单项和菜单关联可能发现混乱的问题。
Ref https://github.com/halo-dev/halo/issues/3360
Fixed https://github.com/halo-dev/halo/issues/3467
测试方式：
1. 创建若干菜单和菜单项，检查功能是否正常。
```release-note
修复 Console 端菜单项和菜单关联可能发现混乱的问题。
```

refactor: use tanstack query to refactor menu related data fetching

---

console/src/modules/system/users/Binding.vue
console/src/modules/system/users/Login.vue

/area console
此修改对登录、注册界面原有风格无影响。解决了1920*1080分辨率下，注册界面，“已有账号 立即登录”与“简体中文”文字重叠问题
Fixes #3695
```release-note
解决1920*1080分辨率下，注册界面，“已有账号 立即登录”与“简体中文”文字重叠问题
```

fix: signup form overlaps with locale form.

---

console/src/modules/dashboard/Dashboard.vue

/kind bug
/area console
修复 Console 端仪表盘添加组件时，切换标签页面报错的问题。
Fixes #3764 
```release-note
修复 Console 端仪表盘添加组件时的报错问题。
```

fix: error occurred when switching tab in dashboard component.

---

SECURITY.md

更新 SECURITY.md 文档中支持的版本。
```release-note
None
```

docs: update SECURITY.md for Halo 2.x

---

application/src/main/java/run/halo/app/infra/exception/handlers/ProblemDetailErrorAttributes.java
application/src/main/java/run/halo/app/theme/ThemeConfiguration.java
application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
application/src/test/java/run/halo/app/infra/exception/handlers/I18nExceptionTest.java

/area core
优化异常信息
- 5xx 服务器内部错误不显示异常详情到页面，如主题模板表达式错误
- 访问 `GET /apis/api.halo.run/v1alpha1/comments` 提示 400 且不会打印异常堆栈
- 访问不存在的主题静态资源提示 404 且不会打印异常堆栈，如 `GET /themes/guqing-higan/assets/dist/style1.css`
Fixes #3483
```release-note
None
```

refactor: optimize the exception information

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json
gradle.properties

修改版本号，准备发布 2.4.3。
```release-note
None
```

chore: bump up version to 2.4.3

---

console/packages/components/src/components.ts
console/packages/components/src/components/description/Description.vue
console/packages/components/src/components/description/DescriptionItem.vue
console/packages/components/src/components/description/index.ts
console/src/modules/contents/attachments/components/AttachmentDetailModal.vue
console/src/modules/interface/themes/ThemeDetail.vue
console/src/modules/system/actuator/Actuator.vue
console/src/modules/system/auth-providers/AuthProviderDetail.vue
console/src/modules/system/plugins/PluginDetail.vue
console/src/modules/system/roles/RoleDetail.vue
console/src/modules/system/users/UserDetail.vue

/kind feature
/area console
/milestone 2.5.0
为 Console 端添加 Description 组件。
Fixes #3790 
测试方式：
1. 检查主题管理、插件详情、认证方式详情页面的样式是否异常即可。
```release-note
为 Console 端添加 Description 组件。
```

feat: add description component

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
Upgrade to Spring Boot 3.0.6.
Fixes https://github.com/halo-dev/halo/issues/3829
```release-note
升级 Spring Boot 至 3.0.6
```

Upgrade to Spring Boot 3.0.6

---

console/src/router/index.ts

/area console
修改 Vue Router 的 scrollBehavior 配置，添加是否是不同路由的跳转，如果是才会在跳转之后滚动到页面顶部。可以解决在 https://github.com/halo-dev/halo/issues/3833 中提到的打开附件详情之后，列表滚动到顶部的问题。这是因为在打开附件详情的时候会修改路由的参数。
Fixes #3833 
测试方式：
1. 上传若干附件，滚动到列表底部。
2. 然后打开某个附件详情，观察列表是否自动滚动到了顶部，如果没有，则修改有效。
```release-note
None
```

perf: improve router scrollBehavior configuration

---

console/src/modules/system/users/Binding.vue
console/src/modules/system/users/Login.vue

/kind bug
/area console
/milestone 2.5.0
修复登录表单与顶部间距异常的问题，并解决在 https://github.com/halo-dev/halo/pull/3756 中提到的在低分辨率屏幕下，语言选择和表单元素重叠的问题。
Fixes https://github.com/halo-dev/halo/issues/3806
测试方式：
1. 检查登录页面的表单是否和以前的版本一致即可。
2. 可以尝试调整浏览器的缩放大小，检查是否有样式问题。
```release-note
None
```

fix: distance between the login form and the top of the page

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java

/kind bug
/area core
修复插件安装后无法启动会导致卸载后插件 JAR 文件残留的问题
1. 安装一个无法启动的插件，比如在插件声明周期方法中抛一个异常
2. 启动插件，然后卸载插件看插件 JAR 是否被正确删除
3. 如果是插件开发模式则不会删除文件
Fixes #3840
```release-note
修复插件安装后无法启动会导致卸载后插件 JAR 文件残留的问题
```

fix: different jar file with the same name appears in the plugins directory after a failed installation

---

application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java

/kind bug
/area core
修复文章上下篇数据查询 NPE 问题
```release-note
None
```

fix: NPE when navigation post not exists

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

修改版本号，准备发布 2.5.0。
```release-note
None
```

chore: bump up version to 2.5.0

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json

修改版本号，准备发布 2.5.1。
```release-note
None
```

chore: bump up version to 2.5.1

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json

修改版本号，准备发布 2.5.2。
```release-note
None
```

chore: bump up version to 2.5.2

---

README.md
gradle.properties

/kind chore
/area core
Upgrade version to 2.6.0-SNAPSHOT for next development iteration.
```release-note
None
```

Upgrade version to 2.6.0-SNAPSHOT

---

api/build.gradle
application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
Upgrade to Spring Boot 3.1.0-RC2.
See https://github.com/spring-projects/spring-boot/releases/tag/v3.1.0-RC2 and https://github.com/spring-projects/spring-boot/releases/tag/v3.1.0-RC1 for more.
Fixes https://github.com/halo-dev/halo/issues/3816
```release-note
升级 Spring Boot 至 3.1.0-RC2
```

Upgrade to Spring Boot 3.1.0-RC2

---

api/src/main/java/run/halo/app/extension/router/QueryParamBuildUtil.java

/kind bug
/area core
Sort properties before building.
Fixes https://github.com/halo-dev/halo/issues/3944
Try to generate api client several times.
```release-note
None
```

Fix the problem of inconsistent OpenAPI generation

---

console/src/modules/system/plugins/PluginDetail.vue

/kind bug
修复插件详情页面协议名字重复出现的问题
Fixes https://github.com/halo-dev/halo/issues/3971
```release-note
NONE
```

fix: fix plugin detail page protocol name duplication issue

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
Upgrade to Spring Boot 3.1.0, please refer to <https://github.com/spring-projects/spring-boot/releases/tag/v3.1.0>.
```release-note
升级 Spring Boot 至 3.1.0
```

Upgrade to Spring Boot 3.1.0

---

console/src/modules/system/users/Login.vue
console/src/router/guards/auth-check.ts
console/src/router/routes.config.ts
console/src/views/system/Redirect.vue

/area console
优化 Console 端登录之后重定向的体验，解决在重定向时会重新显示登录页面的问题。
Fixes #4010 
测试方式与 https://github.com/halo-dev/halo/pull/3989 相同。
```release-note
None
```

perf: improve the experience of redirection after login

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

/area core
修改版本号，准备发布 2.6.0。
```release-note
None
```

chore: release 2.6.0

---

README.md
gradle.properties

/kind cleanup
/area core
Bump Halo to 2.7.0-SNAPSHOT for next development iteration.
```release-note
None
```

Bump Halo to 2.7.0-SNAPSHOT

---

.github/workflows/halo.yaml
README.md
gradle.properties

/kind cleanup
/area core
Bump Halo to 2.6.1 for next development iteration.
```release-note
None
```

Bump Halo to 2.6.1

---

application/src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java

/kind bug
Fix AttachmentReconciler repeated execution.
Fixes #3746
The reconile method in run.halo.app.core.extension.reconciler.attachment.AttachmentReconciler will be executed repeatedly, uploading an attachment will be executed twice, because updating the finalizers property will be in onUpdate of run.halo.app.extension.controller.ExtensionWatcher Will request duplicate addition, I provide a fix for you to review
```release-note
修复 AttachmentReconciler 重复执行
```

Fix AttachmentReconciler repeated execution

---

console/src/components/login/LoginForm.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/utils/api-client.ts

/area console
简化请求异常提示的逻辑。
```release-note
None
```

refactor: simplify request exception handling

---

application/build.gradle
gradle.properties
platform/application/build.gradle

/kind cleanup
/area core
Upgrade Spring Boot to 3.1.1. See https://github.com/spring-projects/spring-boot/releases/tag/v3.1.1 for more.
```release-note
升级 Spring Boot 至 3.1.1
```

Upgrade Spring Boot to 3.1.1

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

修改版本号，准备发布 2.7.0。
```release-note
None
```

chore: release 2.7.0

---

README.md
gradle.properties

/kind cleanup
/area core
- Update README
- Bump version to 2.8.0-SNAPSHOT
```release-note
None
```

Prepare for next release 2.8.0

---

.github/workflows/halo.yaml
README.md
gradle.properties

/kind cleanup
/area core
- Change version to `2.7.1-SNAPSHOT`
- Update README
- Change GitHub workflow
```release-note
None
```

Prepare for next release 2.7.1

---

console/src/modules/contents/attachments/AttachmentList.vue

/area console
重构附件数据管理的筛选条件逻辑以及 UI。
Ref https://github.com/halo-dev/halo/pull/4182
Ref https://github.com/halo-dev/halo/issues/4181
需要测试：
1. 测试附件的筛选条件包括关键词筛选功能是否正常。
```release-note
重构 Console 端附件数据列表的筛选项 UI 和逻辑。
```

refactor: logic of attachment data filtering

---

.github/FUNDING.yml
README.md

添加[爱发电](https://afdian.net/a/halo-dev)的赞助入口，以及在 README 上添加 Sponsors 图像，此图像会在 https://github.com/halo-sigs/sponsor-images 仓库中自动更新。
```release-note
None
```

chore: add sponsorship entry and sponsor image

---

console/src/modules/interface/themes/ThemeSetting.vue
console/src/modules/interface/themes/layouts/ThemeLayout.vue

/area console
/kind bug
修复主题设置选项卡切换的延迟问题。
Fixes #4239 
需要测试：
1. 进入主题设置，尝试对设置选项卡进行切换，观察选项卡和实际的设置表单是否一致。
```release-note
None
```

fix: delay issue in the theme settings tab switch

---

console/src/modules/contents/attachments/composables/use-attachment.ts
console/src/modules/contents/comments/CommentList.vue
console/src/modules/contents/comments/components/CommentListItem.vue
console/src/modules/contents/pages/DeletedSinglePageList.vue
console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/posts/DeletedPostList.vue
console/src/modules/contents/posts/PostList.vue
console/src/modules/contents/posts/categories/composables/use-post-category.ts
console/src/modules/contents/posts/tags/composables/use-post-tag.ts
console/src/modules/interface/menus/Menus.vue
console/src/modules/interface/menus/components/MenuList.vue
console/src/modules/interface/themes/components/ThemeListModal.vue
console/src/modules/system/plugins/PluginList.vue
console/src/modules/system/roles/composables/use-role.ts
console/src/modules/system/users/UserList.vue

/area console
优化 Console 端对异步数据轮询的间隔时间
Fixes https://github.com/halo-dev/halo/issues/4214
```release-note
优化 Console 端对异步数据轮询的间隔时间
```

perf: improve polling interval for api requests

---

console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/pages/components/SinglePageListItem.vue

/area console
重构 Console 端页面管理列表的代码结构，封装列表项为单个组件。
需要测试页面管理的功能是否正常。
```release-note
None
```

refactor: code structure of the single page data list

---

console/src/modules/contents/posts/PostList.vue
console/src/modules/contents/posts/components/PostListItem.vue

/area console
重构 Console 端文章管理列表的代码结构，封装列表项为单个组件。
需要测试文章管理的功能是否正常。
```release-note
None
```

refactor: code structure of the post data list

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
Upgrade Spring Boot 3.1.2. See https://github.com/spring-projects/spring-boot/releases/tag/v3.1.2 for more.
```release-note
升级 Spring Boot 至 3.1.2。
```

Upgrade Spring Boot 3.1.2

---

application/src/main/java/run/halo/app/config/WebFluxConfig.java

/kind feature
/area core
Support resolving static resources at halo work directory `${halo.work-dir}/static/`.
Please note that we only support adding static resources at hand by logging in the server.
Fixes https://github.com/halo-dev/halo/issues/4087
1. Create a file `index.html` at `${halo.work-dir}/static`
2. Edit the file with any content
3. Browse with `http://localhost:8090/index.html`
```release-note
支持静态资源映射
```

Support resolving static resources at halo work directory

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

修改版本号，发布 2.8.0-rc.1
```release-note
None
```

chore: release 2.8.0-rc.1

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/system/users/components/UserAvatarCropper.vue

对头像处理组件的 toolbar 进行国际化处理。
Fixes #4296 
```release-note
None
```

pref: internationalize the avatar processing toolbar

---

console/src/modules/contents/comments/CommentList.vue
console/src/modules/contents/comments/components/CommentListItem.vue
console/src/modules/contents/comments/components/ReplyListItem.vue

/area console
/kind bug
修复评论有新回复时，无法展开回复列表的问题。
Fixes https://github.com/halo-dev/halo/issues/4252
需要测试：
1. 选中任意一个评论，尝试进行回复。
2. 点击回复按钮打开回复列表，观察是否能够正常打开。
```release-note
修复 Console 的评论有新回复时，无法展开回复列表的问题。
```

fix: unable to expand the replies list of the comment

---

console/packages/components/src/components/pagination/Pagination.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/contents/attachments/AttachmentList.vue
console/src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
console/src/modules/contents/comments/CommentList.vue
console/src/modules/contents/pages/DeletedSinglePageList.vue
console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/posts/DeletedPostList.vue
console/src/modules/contents/posts/PostList.vue
console/src/modules/system/plugins/PluginList.vue
console/src/modules/system/users/UserList.vue

/area console
重构 Console 的分页组件，以支持显示数据总条数。
Fixes #4268 
需要测试：
- 测试各个页面的分页功能是否正常
```release-note
重构 Console 的分页组件，以支持显示数据总条数。
```

refactor: refactor pagination component to support display total items

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

/kind cleanup
Bump version of console to 2.8.0-rc.2.
```release-note
None
```

Prepare for releasing 2.8.0-rc.2

---

console/src/locales/zh-CN.yaml

/area console
优化刷新搜索引擎索引的文案。
```release-note
优化刷新搜索引擎索引的文案。
```

chore: update zh-cn translation for refresh search engine operation

---

console/src/locales/zh-TW.yaml

/area console
优化刷新搜索引擎索引的文案。
```release-note
优化刷新搜索引擎索引的文案。
```

chore: update zh-tw translation for refresh search engine operation

---

README.md
console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json
gradle.properties

/kind cleanup
/area core
Bump up Halo to `2.9.0-SNAPSHOT` for developing Halo 2.9.0.
```release-note
None
```

Prepare for developing Halo 2.9.0

---

.github/workflows/halo.yaml
README.md
console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json
gradle.properties

/kind cleanup
/area core
Bump up Halo to `2.8.1` for developing Halo 2.8.1.
```release-note
None
```

Prepare for developing Halo 2.8.1

---

README.md

在 Readme 中增加应用市场链接。
```release-note
NONE
```

docs: add appstore link in readme

---

console/src/components/form/AnnotationsForm.vue

/kind bug
/area console
为 AnnotationsForm 的 formkit 表单 id 增加 uuid 前缀，防止由于一个页面具有多个 AnnotationsForm 时编号互相冲突。
Fixes #4368 
检查使用 AnnotationsForm 的界面，例如文章、页面设置的元数据处没有出现问题即可。
```release-note
None
```

fix: add random uuid to resolve the issue of id conflicts

---

README.md

Add ProductHunt badge in README.md.
```release-note
NONE
```

docs: add ProductHunt badge in README.md

---

api/src/main/java/run/halo/app/infra/utils/GenericClassUtils.java
application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades Spring Boot to 3.1.3. See https://github.com/spring-projects/spring-boot/releases/tag/v3.1.3 for more.
```release-note
升级依赖 Spring Boot 至 3.1.3
```

Upgrade Spring Boot to 3.1.3

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades Lucene to 9.7.0. See: 
- https://lucene.apache.org/core/corenews.html#apache-lucenetm-970-available
- https://lucene.apache.org/core/9_7_0/changes/Changes.html
for more. for more.
```release-note
升级依赖 Lucene 至 9.7.0
```

Upgrade Lucene to 9.7.0

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java

/kind bug
/area core
修复 Windows 系统上的插件路径问题
1. 在 windows 系统上使用插件生成模式初始化 halo 插件可以正常运行，测试上传插件 jar 升级可以正常运行
2. 测试 windows 系统上使用插件开发模式可以正确运行插件
Fixes #4466 
```release-note
修复 Windows 系统上的插件路径问题
```

fix: unable to use plugin development mode on Windows systems

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java

/area core
修复新增加的配置项默认值没有填充的问题
测试插件和主题新增加的配置项（带默认值）在升级后是否具有默认值
Fixes #4377
```release-note
修复新增加的配置项默认值没有填充的问题
```

fix: newly added setting item are not taking effect

---

console/src/modules/system/plugins/PluginList.vue

/area console
移除插件管理列表的分页功能，默认列表出所有安装的插件。
Fixes #4469 
```release-note
移除 Console 端插件管理列表的分页功能，默认列表出所有安装的插件。
```

refactor: remove the pagination feature of plugin management

---

console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

/area console
/kind cleanup
更新 Console 中 package.json 文件的 repository 设置。
```release-note
None
```

chore: update repository config for console packages

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/system/backup/tabs/Restore.vue

/area console
/kind feature
系统恢复支持通过远程文件链接恢复
测试远程恢复的功能是否正常即可。
```release-note
系统恢复功能支持通过远程文件链接恢复。
```

feat: add supports for system restore by remote url

---

console/src/modules/system/plugins/composables/use-plugin.ts

/area console
/kind bug
修复可能因为 version 锁的原因导致无法正常切换插件状态，现在改为在调用切换状态接口前，获取一次最新的插件信息，并提供了 retry 的配置，即失败之后重试 3 次。
测试能否正常切换插件状态即可。
```release-note
None
```

fix: failed to change plugin status

---

application/src/main/resources/schema-mariadb.sql

/kind feature
spring.sql.init.platform 增加 mariadb 参数支持
适配 1Panel 安装 halo 时 选择 mariadb
```release-note
None
```

feat: add schema-mariadb.sql file

---

console/docs/extension-points/entity-listitem-field.md
console/packages/shared/src/types/plugin.ts
console/src/modules/contents/comments/components/CommentListItem.vue
console/src/modules/contents/posts/PostList.vue
console/src/modules/contents/posts/components/PostListItem.vue
console/src/modules/contents/posts/components/entity-fields/ContributorsField.vue
console/src/modules/contents/posts/components/entity-fields/PublishStatusField.vue
console/src/modules/contents/posts/components/entity-fields/TitleField.vue
console/src/modules/contents/posts/components/entity-fields/VisibleField.vue
console/src/modules/interface/themes/components/ThemeListItem.vue
console/src/modules/system/backup/components/BackupListItem.vue
console/src/modules/system/plugins/components/PluginListItem.vue

/area console
/kind feature
文章数据列表的显示字段支持通过插件扩展。
需要测试文章管理功能是否正常。
```release-note
Console 端文章数据列表的显示字段支持通过插件扩展。
```

feat: make field items of post data list extendable

---

README.md
console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json
gradle.properties

/kind cleanup
/area core
Bump Halo to 2.10.0-SNAPSHOT.
```release-note
None
```

Prepare for developing Halo 2.10.0

---

README.md
console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json
gradle.properties

/kind cleanup
/area core
- Bump Halo version to 2.9.1-SNAPSHOT
- Bump Console 2.9.1
- Update README.md
```release-note
None
```

[release-2.9] Prepare for developing 2.9.1

---

console/packages/components/src/components/dialog/Dialog.vue
console/packages/components/src/components/toast/Toast.vue

/kind cleanup
/area console
修复 `@halo-dev/components` 包编译时有 error 级异常的问题。
Fixes https://github.com/halo-dev/halo/issues/4544
观察此 PR 的 ci 中是否有异常输出即可。
```release-note
None
```

fix: ts error in components package

---

application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java

/area core
修复 bundle resource 的缓存 key 生成可能会重复的问题
Fixes #4586
```release-note
修复 bundle resource 的缓存 key 生成可能会重复的问题
```

fix: bundle resources cache version may duplicate

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml
.github/ISSUE_TEMPLATE/feature_request.en.yml
.github/ISSUE_TEMPLATE/feature_request.zh.yml

None
更新 issue 模板。
```release-note
None 
```

chore: update issue templates

---

application/build.gradle

/area core
升级所有预设插件的版本。
执行 `./gradlew downloadPluginPresets` 检查是否能够正常下载。
```release-note
升级所有预设插件的版本。
```

chore: update preset plugins

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
/milestone 2.10.0
Upgrade to Spring Boot [3.1.4](https://github.com/spring-projects/spring-boot/releases/tag/v3.1.4).
```release-note
升级依赖 Spring Boot 至 3.1.4
```

Upgrade to Spring Boot 3.1.4

---

platform/application/build.gradle

/kind cleanup
/area core
/milestone 2.10.0
Upgrade to [PF4J 3.10.0](https://github.com/pf4j/pf4j/releases/tag/release-3.10.0).
```release-note
升级依赖 PF4J 至 3.10.0
```

Upgrade to PF4J 3.10.0

---

application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
application/src/main/java/run/halo/app/notification/EmailNotifier.java
application/src/main/java/run/halo/app/notification/endpoint/SubscriptionRouter.java
application/src/test/java/run/halo/app/notification/endpoint/SubscriptionRouterTest.java

/kind bug
/area core
修复邮件通知中取消订阅链接不正确的问题
```release-note
修复邮件通知中取消订阅链接不正确的问题
```

fix: incorrect unsubscribe link for email notification

---

application/src/main/java/run/halo/app/notification/EmailNotifier.java
application/src/main/resources/extensions/notification-templates.yaml

/area core
统一通知模板中的称呼，将"您"改为你
```release-note
None
```

chore: modify the name in the notification template

---

docs/authentication/README.md

Correct `metadata.annotations.security.halo.run/access-token` into `security.halo.run/access-token`.
```release-note
None
```

Fix typo of authentication document

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
Upgrade to Spring Boot 3.1.5. See https://github.com/spring-projects/spring-boot/releases/tag/v3.1.5 for more.
```release-note
升级依赖 Spring Boot 至 3.1.5
```

Upgrade to Spring Boot 3.1.5

---

.gitignore
application/src/main/java/run/halo/app/config/WebFluxConfig.java
application/src/main/java/run/halo/app/console/ProxyFilter.java
application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
application/src/main/java/run/halo/app/infra/properties/ProxyProperties.java
application/src/main/java/run/halo/app/infra/properties/UcProperties.java
application/src/main/resources/application-dev.yaml

/kind feature
/area core
/area console
This PR add a route to support user-center.
```release-note
None
```

Support user-center route

---

console/src/components/editor/DefaultEditor.vue

```release-note
解决页面切换而导致的编辑器卡死问题
```

[release-2.10] fix: resolve editor freezing issues

---

gradle.properties

/kind cleanup
Update version to 2.10.2-SNAPSHOT.
```release-note
None
```

[release-2.10] Update version to 2.10.2-SNAPSHOT

---

api/build.gradle
application/build.gradle
application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
application/src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
application/src/main/java/run/halo/app/migration/MigrationEndpoint.java
platform/application/build.gradle

/kind bug
/area core
This PR upgrades to SpringDoc 2.2.1-SNAPSHOT to resolve the problem of Swagger API doc display errors.
```release-note
升级 SpringDoc 至 2.2.1-SNAPSHOT 以解决部分 API 文档无法正常使用的问题
```

Upgrade to SpringDoc 2.2.1-SNAPSHOT

---

.github/workflows/halo.yaml
api/build.gradle
build.gradle

/kind feature
/area core
This PR integrates with SonarCloud to analyze source code.
Fixes #4679 
```release-note
None
```

Integrate with SonarCloud

---

api/src/main/java/run/halo/app/core/extension/content/Post.java
application/src/main/java/run/halo/app/search/IndicesServiceImpl.java

/kind bug
在加入索引前判断文章的可见性。只将PUBLIC文章加入索引，修复手动刷新搜索索引会将私有文章加入索引的问题
Fix #4879 
null
```release-note
修复手动刷新搜索索引会将私有文章加入索引的问题
```

Prevent private posts from being indexed when rebuilding index.

---

.github/workflows/halo.yaml
CONTRIBUTING.md
e2e/Dockerfile
e2e/README.md
e2e/compose.yaml
e2e/start.sh
e2e/testsuite.yaml

It would keep the important APIs always works well.
Fixes #
I just added parts of the APIs. But the most imporant part is making the e2e testing flow works well. Please let me kown if you believe there some other core APIs need e2e testing as well. I can do it in this PR or create a new one for that. No matter what. thanks for your time to review it.
```release-note
None
```

test: add e2e testing for the backend

---

console/console-src/modules/system/users/Login.vue

/area console
注册之后默认重定向到个人中心。
```release-note
None
```

refactor: redirect to user center by default after registration

---

.github/workflows/halo.yaml
.gitignore

/kind bug
https://github.com/halo-dev/halo/pull/4892 caused a bug. See https://github.com/halo-dev/halo/actions/runs/6968131488/job/18961558573
I have tested it in another PR https://github.com/LinuxSuRen/halo/pull/2. But the main branch building is failed due to some reasons. See also https://github.com/LinuxSuRen/halo/actions/runs/6968762257/job/18963304428
Fixes #
```release-note
None
```

fix: the image tag might be wrong when it is not a pr

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml

/kind cleanup
更新 issue 模板，支持粘贴系统概览中提供的信息。
```release-note
None
```

chore: update issue template

---

.github/workflows/halo.yaml
e2e/Makefile
e2e/compose-mysql.yaml
e2e/compose-postgres.yaml
e2e/compose.yaml

/kind test
See also https://docs.halo.run/getting-started/install/docker-compose
Fixes #
```release-note
None
```

test: run e2e testing on all supported databases

---

README.md
console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json
console/packages/ui-plugin-bundler-kit/package.json
gradle.properties

/kind cleanup
/area core
Bump versions to 2.12.0-SNAPSHOT for next development.
```release-note
None
```

Bump versions to 2.12.0-SNAPSHOT for next development

---

application/src/main/java/run/halo/app/theme/finders/CategoryFinder.java
application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java

/kind feature
add getParentByName method to CategoryFinder interface
Fixes #
${categoryFinder.getParentByName(anyChild.metadata.name)}
```release-note
NONE
```

Support getting parent category by child name in theme

---

console/packages/editor/src/extensions/index.ts
console/packages/editor/src/index.ts

/area editor
导出一些必要的默认编辑器扩展及工具类，例如 `Paragraph`
Fixes #5103 
```release-note
导出必要的默认编辑器扩展及工具类
```

pref: export necessary extensions externally

---

console/uc-src/modules/contents/posts/PostEditor.vue

/area console
/kind bug
修复在个人中心的文章编辑器中创建新文章时无法上传图片的问题
Fixes https://github.com/halo-dev/halo/issues/5035
测试在 UC 新建文章，在未保存时是否能上传图片。
```release-note
修复个人中心创建新文章时无法上传图片的问题
```

fix: cannot upload image when creating a new post in UC editor

---

console/console-src/layouts/BasicLayout.vue
console/console-src/modules/contents/pages/module.ts
console/console-src/modules/contents/posts/module.ts
console/env.d.ts
console/src/components/base-app/BaseApp.vue
console/uc-src/layouts/BasicLayout.vue
console/uc-src/modules/contents/posts/module.ts

/area console
在 Console 和 UC 的页面底部添加 Powered by 信息。
```release-note
在 Console 和 UC 的页面底部添加 Powered by 信息。
```

feat: add powered by information in page footer

---

console/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue
console/uc-src/modules/profile/tabs/PersonalAccessTokens.vue

/area console
重构 PAT 创建弹窗的显示逻辑，简化代码。基于 https://github.com/halo-dev/halo/pull/5078
需要测试 PAT 创建功能是否正常。
```release-note
None
```

refactor: logic of pat creation modal

---

console/uc-src/modules/profile/components/EmailVerifyModal.vue

/area console
重构邮箱验证弹窗的显示逻辑，简化代码。基于 https://github.com/halo-dev/halo/pull/5078
需要测试邮箱验证的功能是否正常。
```release-note
None
```

refactor: logic of email verify modal

---

console/console-src/modules/index.ts
console/console-src/modules/system/auth-providers/module.ts
console/console-src/modules/system/roles/module.ts
console/console-src/modules/system/users/module.ts
console/console-src/setup/setupModules.ts

/area console
简化 Console 中导入模块的方式，支持自动扫描模块，不再需要手动导入。
测试 Console 的各个页面是否能够正常访问即可。
```release-note
None
```

refactor: simplify the logic of importing module

---

console/uc-src/modules/contents/posts/components/PostCreationModal.vue
console/uc-src/modules/contents/posts/components/PostSettingEditModal.vue

/area console
重构个人中心的文章设置弹窗的显示逻辑，简化代码。基于 https://github.com/halo-dev/halo/pull/5078
需要测试个人中心的文章创建和设置功能是否正常。
```release-note
None
```

refactor: logic of post setting modal

---

.github/workflows/halo.yaml

/kind regression
In PR <https://github.com/halo-dev/halo/pull/5170>, I missed the codecov upload action. This PR adds it back.
```release-note
None
```

Add codecov action into workflow

---

application/src/main/resources/extensions/role-template-post.yaml
application/src/main/resources/extensions/role-template-uc-content.yaml
console/console-src/modules/system/roles/RoleDetail.vue
console/console-src/modules/system/roles/RoleList.vue
console/src/composables/use-role.ts
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/utils/role.ts

/area console
/area core
优化角色模板依赖的相关功能：
1. 修复勾选某个角色模板之后，其下依赖模板没有选中的问题。
2. 修复编辑角色时，模板其下依赖模板没有选中的问题。
3. 修复角色管理列表中，权限数量显示有误的问题。
4. 移除 **允许管理所有文章** 的角色模板，此角色模板与文章管理重复。
5. 优化 i18n。
Fixes https://github.com/halo-dev/halo/issues/5222
需要测试上诉问题是否还存在。
```release-note
优化角色模板依赖的相关功能，优化文章相关角色的翻译。
```

refactor: improve role dependency-related functions and i18n

---

console/console-src/modules/system/tools/Tools.vue
console/console-src/modules/system/tools/module.ts
console/packages/components/src/icons/icons.ts
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml

/area console
/kind feature
为 Console 提供工具页面和菜单项，方便插件集成。
Fixes https://github.com/halo-dev/halo/issues/5249
可以使用以下插件进行测试：
1. [plugin-umami-1.0.0-SNAPSHOT.jar.zip](https://github.com/halo-dev/halo/files/14049119/plugin-umami-1.0.0-SNAPSHOT.jar.zip)
2. [plugin-metrics-graph-1.0.0-beta.1.jar.zip](https://github.com/halo-dev/halo/files/14049127/plugin-metrics-graph-1.0.0-beta.1.jar.zip)
3. [NotifyMe-1.1.0.jar.zip](https://github.com/halo-dev/halo/files/14049131/NotifyMe-1.1.0.jar.zip)
```release-note
为 Console 提供工具页面和菜单项，方便插件集成。
```

feat: add tools page for console

---

platform/application/build.gradle

/area core
This PR upgrades Lucene to 9.9.1. See https://lucene.apache.org/core/corenews.html#apache-lucenetm-991-available for more.
```release-note
升级依赖 Lucene 至 9.9.1
```

Upgrade Lucene to 9.9.1

---

console/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue

/area console
/kind bug
修复创建 PAT 之后，点击复制按钮无法复制 token 的问题。
Fixes #5273 
测试步骤：
1. 构建生产环境的 UC。
2. 创建 PAT，点击复制按钮，观察是否能够正常复制。
```release-note
修复创建 PAT 之后，点击复制按钮无法复制 token 的问题。
```

fix: pat can not be copied

---

README.md
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/editor/package.json
console/packages/shared/package.json
console/packages/ui-plugin-bundler-kit/package.json
gradle.properties

/kind cleanup
/area core
This PR bumps version to 2.13.0-SNAPSHOT and corrects links of Halo in README.md.
```release-note
None
```

Prepare for 2.13.0 development

---

api/src/main/java/run/halo/app/extension/PageRequestImpl.java
api/src/test/java/run/halo/app/extension/PageRequestImplTest.java

/kind bug
/area core
This PR makes Halo compatible with negative page number and size parameters to resolve <https://github.com/halo-dev/halo/issues/5298>.
Fixes https://github.com/halo-dev/halo/issues/5298
Try to install [Hao theme](https://github.com/liuzhihang/halo-theme-hao/releases/tag/v1.4.7) and [Chirpy theme](https://github.com/AirboZH/halo-theme-chirpy/releases/tag/v1.3.3) and check the frontend pages.
```release-note
修复因限制分页参数导致部分主题页面无法正常渲染的问题。
```

Compatible with negative page number and size

---

ui/src/locales/zh-TW.yaml

Correct some simplified Chinese characters that were not replaced in the yaml file of traditional Chinese.
Fixes #3672
I have read the CONTRIBUTING file, but I'm not familiar with PR operations. If there's anything I can do to improve it, please let me know.
> By the way, the [contribution guidelines](https://github.com/halo-dev/halo/blob/master/CONTRIBUTING.md) provided in the PR template and README still use `master` as the main branch, which may cause some confusion for new contributors.
```release-note
NONE
```

Improve traditional Chinese translation

---

.github/pull_request_template.md
CONTRIBUTING.md
README.md

Prevent code contributors from being misled by outdated documentation(1.x).
Fixes #5358
```release-note
NONE
```

docs: update the branch name from `master` to `main` in contribution.md

---

.github/actions/setup-env/action.yaml

/kind cleanup
/area core
See https://github.com/halo-dev/halo/pull/5340#issuecomment-1950965406 for more.
```release-note
None
```

Bump pnpm/action-setup version to 3.0.0

---

ui/src/components/user-avatar/UserAvatar.vue

/area ui
/kind bug
修复 Console 中用户头像无法正确获取的问题。
Fixes #5368 
测试方式：
1. 创建若干用户，并为部分用户设置不同的头像。
2. 分别进入不同用户的个人资料页面，观察头像是否符合预期。
```release-note
修复 Console 中用户头像无法正确获取的问题。
```

fix: fail to fetch correct user avatar

---

ui/package.json
ui/packages/api-client/package.json
ui/pnpm-lock.yaml
ui/src/components/editor/utils/upload.ts

/area ui
升级 Axios 依赖版本至 1.6.x
```release-note
升级 Axios 依赖版本至 1.6.x
```

chore: bump axios version to 1.6.x

---

application/build.gradle
platform/application/build.gradle

/kind cleanup
/area core
Upgrade Spring Boot to [3.2.3](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.3).
```release-note
升级依赖 Spring Boot 至 3.2.3
```

Upgrade Spring Boot to 3.2.3

---

application/build.gradle

/area core
/milestone 2.13.0
更新预设插件的版本。
```release-note
None
```

chore: bump preset plugins version

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades Pf4j to [3.11.0](https://github.com/pf4j/pf4j/releases/tag/release-3.11.0) regularlly.
```release-note
升级依赖 PF4J 至 3.11.0
```

Upgrade PF4J to 3.11.0

---

api/build.gradle
application/build.gradle
build.gradle
platform/application/build.gradle
ui/build.gradle

/kind cleanup
/area core
This PR collects all Gradle plugin versions into root build.gradle for easy management.
```release-note
None
```

Collect Gradle plugin versions into root build.gradle

---

application/src/main/java/run/halo/app/content/ListedPost.java
application/src/main/java/run/halo/app/content/ListedSinglePage.java
application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java

/kind cleanup
/area core
优化并重新整理文章和自定义页面 Service 的部分代码
```release-note
None
```

chore: optimize and reorganize code for post and page service

---

ui/packages/editor/src/extensions/code-block/lowlight.ts

添加代码块 dart 语言的高亮
/kind feature
/area editor
> 为默认编辑器的代码块导入 dart 语言高亮
Fixes #5530 
```release-note
为需要代码块dart语言高亮的用户提供支持
```

feat: add Dart syntax highlighting for the code blocks in the editor

---

build.gradle

/kind cleanup
/area core
This PR mainly upgrades Spring Boot to [3.2.4](https://github.com/spring-projects/spring-boot/releases/tag/v3.2.4), and also upgrades other Gradle plugins.
```release-note
升级依赖 Spring Boot 至 3.2.4
```

Upgrade Spring Boot to 3.2.4

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades SpringDoc to [2.4.0](https://github.com/springdoc/springdoc-openapi/releases/tag/v2.4.0).
```release-note
升级依赖 SpringDoc 至 2.4.0
```

Upgrade SpringDoc to 2.4.0

---

ui/uc-src/modules/contents/posts/PostEditor.vue
ui/uc-src/modules/contents/posts/components/PostCreationModal.vue
ui/uc-src/modules/contents/posts/components/PostSettingEditModal.vue
ui/uc-src/modules/contents/posts/composables/use-post-update-mutate.ts

/area ui
为 UC 端保存文章的操作添加重试机制，防止出现因为锁导致的保存失败问题。
Fixes https://github.com/halo-dev/halo/issues/5474
需要多次尝试编辑文章，以及设置表单的保存功能。
```release-note
为 UC 端保存文章的操作添加重试机制，防止出现因为锁导致的保存失败问题。
```

feat: add retry mechanism for saving posts on the UC end

---

application/src/main/java/run/halo/app/endpoint/uc/content/UcPostEndpoint.java

/kind bug
/area core
修复在个人中心下，用户无法修改发布时间的问题。
需要测试两种情况：
1. 用户首次发布文章时，修改发布时间是否有效。
2. 用户后续编辑文章发布时间时是否生效。
Fixes #5473 
```release-note
修复个人中心中用户无法修改文章发布时间的问题
```

fix: unable to modify the publish time of post in the uc

---

README.md

同时使用 `-it` 和 `-d`，`-d` 会覆盖 `-it`，容器将会在后台运行，而 `-it` 参数请求的交互式会话和伪终端不会生效。
```release-note
None
```

docs: delete unnecessary options.

---

ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/area ui
简化部分确认框的标题。
Fixes https://github.com/halo-dev/halo/issues/5592
```release-note
简化部分确认框的标题。
```

refactor: simplify the dialogs title

---

application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
application/src/test/java/run/halo/app/notification/DefaultNotificationCenterTest.java

/area core
优化通知订阅数据查询
```release-note
优化通知订阅数据查询以解决由于数据过多导致查询慢进而阻塞调用方的问题
```

refactor: optimize the query for subscriptions

---

application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java

/area core
优化文章上一篇下一篇的查询方式避免瞬时内存占用过高
```release-note
优化文章上一篇下一篇的查询方式避免瞬时内存占用过高
```

refactor: optimize data acquisition from previous to next posts in a post

---

application/src/main/java/run/halo/app/actuator/GlobalInfoEndpoint.java
ui/console-src/views/system/Login.vue
ui/src/components/base-app/BaseApp.vue
ui/src/types/actuator.ts

/kind feature
/area ui
/area core
将 Console 与 UC 页面的标签页标题改为网站实际标题
查看 Console 页面与 UC 页面的标题页标题是否变为网站实际标题
Fixes #5679 
```release-note
将 Console 与 UC 的标签页标题改为网站实际标题
```

feat: change the tab title to the site title of the website

---

ui/console-src/modules/system/users/components/UserCreationModal.vue

/area ui
Fixes #5677 
```release-note
将新建用户的表单中的角色设置设为必填
```

feat: set selectedRole as required when creating a new user

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades SpringDoc to [2.5.0](https://github.com/springdoc/springdoc-openapi/releases/tag/v2.5.0).
```release-note
升级 SpringDoc 至 2.5.0
```

Upgrade SpringDoc to 2.5.0

---

ui/console-src/layouts/BasicLayout.vue
ui/src/components/base-app/BaseApp.vue
ui/uc-src/layouts/BasicLayout.vue

/kind bug
/area ui
布局高度引发页面背景色未完全填充滚动区域的问题；
另外，为了不影响全局 `footer` 置于页面底部，对 `BasicLayout.vue` 容器也添加了最小高度 `100vh`
Fixes #5678
当 Console 出现滚动条时，如：https://demo.halo.run/console/attachments?page=1&group= 
注意观察对布局设置最小高度 `100vh` 后与设置之前的背景色变化；
注意是否会对其它布局高度造成影响
```release-note
布局高度引发页面背景色未完全填充滚动区域的问题
```

fix: layout height triggers page background color not fully filling scroll area

---

e2e/Dockerfile

As I mentioned in the title. The [API Testing](https://github.com/LinuxSuRen/api-testing) has some performance improve.
Fixes #
```release-note
None
```

chore: upgrade the api-testing (e2e) to v0.0.16

---

api/src/main/java/run/halo/app/core/extension/content/Comment.java
api/src/main/java/run/halo/app/core/extension/content/Reply.java
application/src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
application/src/main/java/run/halo/app/infra/SchemeInitializer.java

/kind feature
/area core
优化评论数据的调协过程以降低 Halo 启动时评论的调协耗时同时提高性能和资源利用率
Fixes #5707
```release-note
优化评论数据的调协过程以降低 Halo 启动时评论的调协耗时同时提高性能和资源利用率
```

refactor: optimize comment reconciliation for better performance and efficiency

---

application/src/main/java/run/halo/app/infra/SchemeInitializer.java
ui/console-src/modules/contents/posts/PostList.vue
ui/src/locales/en.yaml
ui/src/locales/es.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/kind feature
/area core
/area ui
在文章列表增加按照更新时间进行排序的字段。
测试文章列表下，按照最近更新与较早更新是否符合逻辑。
Fixes #4513 
```release-note
在文章列表增加按照更新时间进行排序的选项。
```

feat: add the order of the posts according to last modify time

---

Dockerfile

/kind deprecation
Fixes #5790 
```release-note
None
```

chore: rm deprecated attr MAINTAINER

---

ui/console-src/views/system/Login.vue
ui/index.html
ui/src/components/base-app/BaseApp.vue
ui/src/composables/use-title.ts

/area ui
重构 Console 和 UC 的浏览器标题切换。
1. 将代码逻辑封装为统一的 Hook。
2. 移除 index.html 默认的标题，防止加载中的时候显示不正确。
Fixes https://github.com/halo-dev/halo/issues/5752
测试各个页面的标题显示正常即可。
```release-note
重构 Console 和 UC 的浏览器标题切换。
```

refactor: implementation of browser tab title

---

api/src/main/java/run/halo/app/core/endpoint/WebSocketEndpoint.java
application/src/main/java/run/halo/app/config/WebFluxConfig.java
application/src/main/java/run/halo/app/console/WebSocketUtils.java
application/src/main/java/run/halo/app/core/endpoint/WebSocketEndpointManager.java
application/src/main/java/run/halo/app/core/endpoint/WebSocketHandlerMapping.java
application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
application/src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
application/src/test/java/run/halo/app/core/endpoint/WebSocketHandlerMappingTest.java
application/src/test/java/run/halo/app/security/authorization/RequestInfoResolverTest.java
docs/plugin/websocket.md

/kind feature
/area core
/area plugin
This PR allows plugin developers defining WebSocket endpoints in plugins.
Fixes #5285 
```release-note
支持在插件中实现 WebSocket
```

Add WebSocket support in plugins

---

.github/workflows/halo.yaml

Hey! 🙂
I want to contribute the following changes to your workflow:
- Stop running workflows when there is a newer commit in PR
- Use 'if' for upload-artifact action
- Avoid deploying jobs on forks
Fixes #
These changes are part of a research Study at TU Delft looking at GitHub Action Smells. [Find out more](https://ceddy4395.github.io/research/gha-smells.html)
```release-note
None
```

Fix potential github action smells

---

application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java

/area core
修复重试更新文章的错误写法
```release-note
None
```

fix: update post with retry

---

README.md
gradle.properties
ui/packages/api-client/package.json
ui/packages/components/package.json
ui/packages/editor/package.json
ui/packages/shared/package.json
ui/packages/ui-plugin-bundler-kit/package.json

/kind cleanup
/area core
This is a regular action after releasing a minor version.
```release-note
None
```

Prepare for developing 2.16.0

---

application/src/main/java/run/halo/app/extension/JSONExtensionConverter.java

/kind bug
/area core
修复 Secret 的 data 字段无法在 YAML 使用的问题
```release-note
None
```

fix: secret data cannot be used in YAML

---

platform/application/build.gradle

/kind cleanup
/area core
/area plugin
See https://github.com/pf4j/pf4j/releases/tag/release-3.11.1 and https://github.com/halo-dev/halo/pull/5770 for more.
```release-note
升级 PF4J 至 3.11.1
```

Upgrade PF4J to 3.11.1

---

ui/console-src/modules/interface/menus/Menus.vue
ui/console-src/modules/interface/menus/components/MenuEditingModal.vue
ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue
ui/console-src/modules/interface/menus/components/MenuItemListItem.vue
ui/console-src/modules/interface/menus/components/MenuList.vue

/area ui
优化菜单管理相关的 UI 代码。
1. 使用 vue-draggable-plus 库代替 vuedraggable 库实现拖拽排序。vue-draggable-plus 是在 https://github.com/halo-dev/halo/pull/5914 中引入，替换的原因是 vuedraggable 库已经不再积极维护。
2. 改进菜单和菜单项编辑表单的逻辑，清理无用代码。
需要测试：
1. 测试菜单项拖拽排序功能是否表现正常。
2. 测试新增菜单、菜单项和修改菜单、菜单项功能是否表现正常。
```release-note
None
```

refactor: improve code base of menu-related

---

ui/console-src/modules/contents/posts/categories/CategoryList.vue
ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
ui/console-src/modules/contents/posts/categories/components/CategoryListItem.vue
ui/console-src/modules/contents/posts/categories/composables/use-post-category.ts
ui/package.json
ui/pnpm-lock.yaml
ui/src/vite/config-builder.ts

/area ui
优化文章分类管理相关的 UI 代码。
1. 使用 vue-draggable-plus 库代替 vuedraggable 库实现拖拽排序。vue-draggable-plus 是在 https://github.com/halo-dev/halo/pull/5914 中引入，替换的原因是 vuedraggable 库已经不再积极维护。
2. 改进分类编辑表单的逻辑，清理无用代码。
需要测试：
1. 测试文章分类拖拽排序功能是否表现正常。
2. 测试新增/编辑文章分类功能是否表现正常。
```release-note
None
```

refactor: improve code base of post category-related

---

ui/console-src/modules/contents/posts/tags/TagList.vue
ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue

/area ui
优化文章标签的表单组件代码。
```release-note
None
```

refactor: improve code base of post tag-related

---

ui/console-src/modules/system/users/UserDetail.vue
ui/console-src/modules/system/users/UserList.vue
ui/console-src/modules/system/users/components/UserCreationModal.vue
ui/console-src/modules/system/users/components/UserEditingModal.vue
ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
ui/src/components/login/LoginModal.vue
ui/uc-src/modules/profile/Profile.vue
ui/uc-src/modules/profile/components/PasswordChangeModal.vue
ui/uc-src/modules/profile/components/ProfileEditingModal.vue

/area ui
优化和用户管理相关的所有对话框显示逻辑，减少不必要的渲染开销和请求。
改动范围如下：
1. 用户密码修改
2. 用户资料修改
3. 用户创建
4. 重新登录
```release-note
优化和用户管理相关的所有对话框显示逻辑，减少不必要的渲染开销和请求。
```

refactor: improve code base of user-related

---

ui/console-src/layouts/BasicLayout.vue
ui/src/components/global-search/GlobalSearchModal.vue

/area ui
优化 Console 的全局搜索对话框显示逻辑，改为未开启时不渲染组件。
```release-note
None
```

refactor: improve visible condition of global search component

---

build.gradle

/kind cleanup
/area core
This PR upgrades dependency Spring Boot to [3.3.0](https://github.com/spring-projects/spring-boot/releases/tag/v3.3.0).
```release-note
升级 Spring Boot 至 3.3.0
```

Upgrade SpringBoot to 3.3.0

---

ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
ui/console-src/modules/interface/menus/components/MenuEditingModal.vue
ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue

/area ui
/kind bug
修复部分表单数据更新时，引用的初始值对象被跟着更新的问题。
```release-note
None
```

fix: update initial values when form data changes

---

ui/console-src/modules/contents/comments/components/CommentListItem.vue

/area ui
为更新评论的最后读取时间添加重试机制。Ref https://github.com/halo-dev/halo/pull/5903#issuecomment-2106855779
```release-note
None 
```

feat: add retry feature for update last read time of comment

---

application/src/main/resources/config/i18n/messages.properties
application/src/main/resources/config/i18n/messages_zh.properties

/area core
优化主题安装时的中文提示
```release-note
None
```

refactor: refine i18n prompts for themes

---

application/src/main/java/run/halo/app/infra/SchemeInitializer.java
application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java

/area core
/kind milestone 2.16.x
使用索引机制来查询扩展点定义
```release-note
None
```

refactor: use index mechanism to query extension point definitions

---

ui/.env.development
ui/.env.production
ui/console-src/composables/use-global-info.ts
ui/console-src/layouts/BasicLayout.vue
ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
ui/console-src/modules/system/overview/Overview.vue
ui/console-src/setup/setupModules.ts
ui/src/components/login/LoginForm.vue
ui/src/components/login/MfaForm.vue
ui/src/components/upload/UppyUpload.vue
ui/src/stores/global-info.ts
ui/src/utils/api-client.ts
ui/uc-src/layouts/BasicLayout.vue
ui/uc-src/modules/profile/tabs/Detail.vue
ui/uc-src/setup/setupModules.ts
ui/vite.config.ts

/area ui
/kind cleanup
移除 UI 项目中不必要的环境变量配置。
1. VITE_API_URL：当前 Console 不会考虑独立部署，并且在开发环境是后端 Proxy 的 Console 请求，所以此变量没有任何意义。
2. VITE_BASE_URL：无意义，当前不考虑修改。
```release-note
None
```

chore: remove unnecessary env

---

README.md
gradle.properties
ui/packages/api-client/package.json
ui/packages/components/package.json
ui/packages/editor/package.json
ui/packages/shared/package.json
ui/packages/ui-plugin-bundler-kit/package.json

/kind cleanup
/area core
This is a regular update after a release.
```release-note
None
```

Prepare for developing 2.17.0

---

ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
ui/packages/editor/src/extensions/code-block/code-block.ts
ui/packages/editor/src/index.ts
ui/packages/editor/src/locales/en.yaml
ui/packages/editor/src/locales/zh-CN.yaml
ui/packages/editor/src/styles/base.scss
ui/packages/editor/src/styles/index.scss
ui/packages/editor/src/styles/node-select.scss

/area editor
优化编辑器代码块样式。
before:
after:
测试复制功能是否正常。
```release-note
优化默认编辑器代码块样式
```

pref: improve code block styling in editor

---

README.md

docs: add image linked to video in README.md

---

build.gradle

/area core
This PR upgrades Spring Boot to [3.3.1](https://github.com/spring-projects/spring-boot/releases/tag/v3.3.1) and Dependency Management Plugin to [1.1.5](https://github.com/spring-gradle-plugins/dependency-management-plugin/releases/tag/v1.1.5).
```release-note
None
```

Upgrade SpringBoot to 3.3.1

---

ui/console-src/modules/contents/pages/SinglePageEditor.vue
ui/console-src/modules/contents/posts/PostEditor.vue
ui/src/components/dropdown-selector/EditorProviderSelector.vue
ui/src/composables/use-editor-extension-points.ts
ui/uc-src/modules/contents/posts/PostEditor.vue

/area ui
/kind bug
修复新建文章时，没有自动选择之前所选编辑器的问题。
Fixes https://github.com/halo-dev/halo/issues/6091
```release-note
修复新建文章时，没有自动选择之前所选编辑器的问题。
```

fix: not remembering the selected editor

---

ui/console-src/modules/contents/comments/CommentList.vue
ui/console-src/modules/contents/comments/components/CommentListItem.vue
ui/console-src/modules/contents/comments/components/ReplyListItem.vue

/area ui
使用新的 patch 接口重构评论相关的逻辑。
需要测试：
1. 审核评论和回复功能。
2. 批量审核评论和回复功能。
```release-note
None
```

Refactor comment data update using the patch api

---

ui/packages/api-client/entry/api-client.ts

/area ui
/kind bug
修复 api client 默认请求根地址不正确的问题。
```release-note
None
```

fix: incorrect root path in API client requests

---

platform/application/build.gradle

/kind bug
/area core
升级 pf4j 至 3.12.0 版本以解决插件依赖解析不正确的问题
Fixes #5616
```release-note
升级 pf4j 至 3.12.0 版本以解决插件依赖解析不正确的问题
```

chore: upgrade pf4j version to 3.12.0

---

ui/.vscode/extensions.json
ui/.vscode/settings.json

/area ui
添加针对 VSCode 的配置，防止因为编辑器的差异带来的 diff。
```release-note
None
```

chore: add vscode settings.json

---

ui/src/setup/setupStyles.ts

/area ui
/kind bug
修复 https://github.com/halo-dev/halo/pull/6152 中因为改动了 css 文件的导入顺序带来的样式问题。
```release-note
None
```

fix: resolve style issues caused by changing the order of CSS imports

---

ui/packages/api-client/README.md

/area ui
更新 `@halo-dev/api-client` 包的 readme。
```release-note
None
```

docs: update readme for api client package

---

ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue

/area ui
/kind bug
修复插件扩展点设置页面标题的颜色问题。
```release-note
None
```

fix: text style in extension point definition page

---

application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java

/area core
优化触发 Extension Watch 方法（onAdd/onUpdate/onDelete）时的参数始终为真实类型避免使用时进行类型转换
```release-note
None
```

refactor: optimize the extension watch parameters to always be of real type

---

platform/application/build.gradle

/kind cleanup
/area core
See https://github.com/apache/lucene/releases/tag/releases%2Flucene%2F9.11.1 for more.
```release-note
升级 Lucene 至 9.11.1
```

Upgrade Lucene to 9.11.1

---

application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java

/kind bug
/area core
/area theme
修复获取隐藏分类的面包屑路径不正确的问题
Fixes #6197
```release-note
修复获取隐藏分类的面包屑路径不正确的问题
```

fix: breadcrumbs for hidden category can not be displayed

---

application/src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java

/kind bug
/area core
修复文章关联或取消关联隐藏分类后显示不正确的问题
Fixes #6194
Fixes #6195
```release-note
修复文章关联或取消关联隐藏分类后显示不正确的问题
```

fix: incorrect post display when linking or unlinking hidden categories

---

ui/console-src/modules/contents/posts/PostEditor.vue
ui/uc-src/modules/contents/posts/PostEditor.vue

/area ui
/kind feature
支持在文章编辑页面创建文章时，也应用别名生成规则
Fixes https://github.com/halo-dev/halo/issues/5118
Fixes https://github.com/halo-dev/halo/issues/6155
```release-note
支持在文章编辑页面创建文章时，也应用别名生成规则
```

feat: add slug generation rules to post saving feature in the post editing page

---

ui/src/components/login/MfaForm.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml
ui/uc-src/modules/profile/Profile.vue
ui/uc-src/modules/profile/tabs/TwoFactor.vue
ui/uc-src/modules/profile/tabs/components/PasswordValidationForm.vue
ui/uc-src/modules/profile/tabs/components/TotpConfigureModal.vue
ui/uc-src/modules/profile/tabs/components/TotpDeletionModal.vue
ui/uc-src/modules/profile/tabs/components/TwoFactorDisableModal.vue
ui/uc-src/modules/profile/tabs/components/TwoFactorEnableModal.vue

/area ui
/kind feature
补充 2FA 相关的 i18n 定义。
```release-note
None
```

feat: refine 2fa-related i18n

---

application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java

/area core
由于2.17.0 修改了 listAll 的实现导致出现了不兼容 Sort 参数为 null 的情况，考虑到给开发者适应的时间因此先兼容并给出警告日志
see also #6219
Fixes #6219
```release-note
None
```

chore: compatibility support for null for sort parameter of listAll

---

ui/console-src/modules/system/plugins/PluginList.vue
ui/console-src/modules/system/plugins/module.ts

/area ui
优化插件扩展管理页面的 UI 权限，限制只有超级管理员才能访问。
```release-note
None
```

refactor: refine permissions of extension settings page

---

application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java

/kind bug
/area plugin
修复当插件入口文件的缓存目录被系统清理后会导致一直无法加载的问题
原问题复现步骤：
1. 登录后刷新页面，此时缓存目录被创建
2. 删除缓存目录后就会提示文件不存在然后导致插件入口文件一致无法加载直到重启 Halo
Fixes #6226
```release-note
修复当插件入口文件的缓存目录被系统清理后会导致一直无法加载的问题
```

fix: handle plugin entry file loading when cache temp directory is cleared

---

e2e/Dockerfile

Fixes #
```release-note
None
```

chore: upgrade api-testing to v0.0.17

---

README.md
gradle.properties
ui/packages/api-client/package.json
ui/packages/components/package.json
ui/packages/editor/package.json
ui/packages/shared/package.json
ui/packages/ui-plugin-bundler-kit/package.json

/kind cleanup
/area core
This PR bumps Halo version into 2.18.0 for next development iteration.
```release-note
None
```

Prepare for developing 2.18.0

---

application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java

/kind bug
/area core
设备管理去除 IP 地址检查以避免频繁登录
```release-note
设备管理去除 IP 地址检查以避免频繁登录
```

refactor: remove IP address judgment for device management

---

.devcontainer/devcontainer.json
.github/dependabot.yml

/area core
This PR adds  devcontainer support for a better development experience.
```release-note
None
```

Add devcontainer support

---

application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
application/src/main/java/run/halo/app/search/post/PostHaloDocumentsProvider.java
application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
application/src/test/java/run/halo/app/search/post/PostHaloDocumentsProviderTest.java

/kind bug
/area core
This PR fixes the problem of not being able to rebuild search index due to null description and updateTimestamp.
Fixes #6317 
```release-note
修复无法正常刷新搜索引擎的问题
```

Fix the problem of not being able to rebuild search index

---

ui/uc-src/modules/contents/posts/PostEditor.vue

/area ui
为个人中心发布文章的操作添加重试机制，方式后端因为乐观锁出现异常错误。
Fixes #6349 
```release-note
为个人中心发布文章的操作添加重试机制，方式后端因为乐观锁出现异常错误。
```

feat: add retry mechanism for publishing posts in user center

---

application/src/main/resources/extensions/system-setting.yaml

/kind cleanup
/area core
移除在 https://github.com/halo-dev/halo/pull/6403 中误推送的代码。
```release-note
None
```

fix: remove unused code in system-setting.yaml

---

application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java

/kind cleanup
/area core
This PR refines debug logs of listing all extensions.
```release-note
None
```

Refine debug logs of querying extensions

---

application/src/main/java/run/halo/app/plugin/DefaultReactiveSettingFetcher.java

/kind bug
/area core
修复保存系统配置时出现的 NPE 问题
此问题由于 PR #6346 导致
Fixes #6416
```release-note
None
```

fix: NPE when saving system configuration

---

application/src/main/java/run/halo/app/infra/SchemeInitializer.java

/area core
/kind cleanup
删除对文章错误的索引声明
```release-note
None
```

chore: remove incorrect index declaration

---

.github/FUNDING.yml
README.md

/kind cleanup
更新爱发电的地址。
```release-note
None
```

chore: update afdian url

---

ui/src/utils/image.ts

/kind feature
/area ui
支持在附件库中预览 `image/avif` 的图片。
Fixes #6320 
```release-note
支持在附件库中预览 avif 类型的图片
```

feat: support for previewing avif images in attachments

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml

None
Updated the issue template and added a reminder to disable all plugins to troubleshoot the problem.
```release-note
None
```

chore: update github issue templates

---

ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
ui/console-src/modules/contents/pages/SinglePageList.vue
ui/console-src/modules/contents/pages/components/SinglePageListItem.vue

/area ui
使用 patch 接口重构页面的删除、可见性修改等逻辑。
None
测试页面删除、可见性修改功能是否符合预期。
```release-note
使用 patch 接口重构页面的删除、可见性修改等逻辑。
```

refactor: improve part of the page operation logic using the patch api

---

ui/package.json
ui/pnpm-lock.yaml
ui/src/formkit/inputs/code/CodeInput.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/area ui
/kind feature
Code 输入框支持全屏编辑。
Fixes #6308 
需要在任意 Code 输入框中测试全屏功能是否正常。
```release-note
Code 输入框支持全屏编辑。
```

feat: add full-screen support to code input

---

ui/console-src/modules/contents/posts/DeletedPostList.vue
ui/console-src/modules/contents/posts/components/PostListItem.vue
ui/console-src/modules/contents/posts/components/entity-fields/VisibleField.vue

/area ui
使用 patch 接口重构文章的恢复、可见性修改等逻辑。
None
测试文章删除、恢复、可见性修改功能是否符合预期。
```release-note
使用 patch 接口重构文章的恢复、可见性修改等逻辑。
```

refactor: improve part of the post operation logic using the patch api

---

ui/console-src/modules/interface/menus/Menus.vue
ui/console-src/modules/interface/menus/components/MenuItemEditingModal.vue

/area ui
使用 patch 接口重构菜单项拖动排序等功能。
None
需要测试菜单项的拖动排序功能是否符合预期。
```release-note
使用 patch 接口重构菜单项拖动排序功能。
```

refactor: use patch api to refactor menu drag-and-drop sorting feature

---

application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
application/src/main/java/run/halo/app/core/extension/service/UserService.java
application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java

/area core
优化用户创建
```release-note
None
```

refactor: optimize user creation

---

api-docs/openapi/v3_0/aggregated.json
application/src/main/java/run/halo/app/infra/SchemeInitializer.java
application/src/main/java/run/halo/app/notification/UserNotificationQuery.java
ui/packages/api-client/src/api/notification-v1alpha1-uc-api.ts

/kind cleanup
/area core
清理没有用到的索引
```release-note
None
```

chore: cleanup unused index for notification

---

application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java

/kind bug
/area core
修复文章的上一篇下一篇链接包含了隐藏分类下的文章
```release-note
修复文章的上一篇下一篇链接包含了隐藏分类下的文章
```

fix: previous and next post links included hidden posts

---

ui/console-src/modules/system/overview/Overview.vue
ui/console-src/router/routes.config.ts
ui/console-src/views/system/Setup.vue
ui/src/components/alerts/H2WarningAlert.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/area ui
在初始化页面添加使用 H2 数据库的警告。
需要测试在首次安装的时候使用 H2 数据库时，初始化页面是否有警告界面。
```release-note
在初始化页面添加使用 H2 数据库的警告。
```

feat: add H2 database usage warning to setup page

---

application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
application/src/main/java/run/halo/app/extension/index/DefaultExtensionIterator.java
application/src/main/java/run/halo/app/extension/index/ExtensionIterator.java
application/src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClient.java
application/src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClientImpl.java

/area core
构建完索引后增加数据量一致性校验的步骤
```release-note
None
```

refactor: add post-index build validation to ensure data count matches index

---

ui/src/formkit/inputs/select/SelectMain.vue

/kind bug
/area ui
解决 formkit select 远程请求时的参数错误问题。
```release-note
None
```

fix: resolve incorrect parameters in fomkit select remote request

---

api/src/main/java/run/halo/app/extension/ExtensionUtil.java
api/src/main/java/run/halo/app/extension/router/SortableRequest.java
application/src/main/java/run/halo/app/content/PostQuery.java
application/src/main/java/run/halo/app/content/SinglePageQuery.java
application/src/main/java/run/halo/app/content/comment/CommentQuery.java
application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
application/src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
application/src/main/java/run/halo/app/core/extension/endpoint/TagEndpoint.java
application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
application/src/main/java/run/halo/app/infra/SchemeInitializer.java
application/src/main/java/run/halo/app/theme/endpoint/SinglePageQueryEndpoint.java
application/src/main/java/run/halo/app/theme/finders/SinglePageConversionService.java
application/src/main/java/run/halo/app/theme/finders/SinglePageFinder.java
application/src/main/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImpl.java
application/src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
application/src/test/java/run/halo/app/theme/endpoint/SinglePageQueryEndpointTest.java

/kind cleanup
/area core
This PR refactors some requests with sort parameter by reusing SortableRequest, and refactors some queries with indexer.
```release-note
None
```

Cleanup code with SortableRequest

---

application/src/main/java/run/halo/app/content/comment/AbstractCommentService.java
application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java

/area core
优化评论和回复的逻辑并减少重复代码
```release-note
None
```

refactor: optimize comment and reply logic to reduce duplicate code

---

.github/workflows/packages-preview-release.yaml

/area ui
集成 pkg.pr.new，实现自动发布 PR 的 npm packages 包。
```release-note
None
```

chore: set up preview release with pkg.pr.new

---

ui/packages/api-client/entry/api-client.ts
ui/packages/api-client/package.json
ui/pnpm-lock.yaml

/area ui
优化默认的 axios 实例的参数：
1. baseURL 改为空字符串。
2. 默认优化数组参数。
```release-note
None
```

refactor: improve axios instance parameters

---

application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java

/area core
将缩略图生成的模式改为自动，速度优先会导致图片失真率较高，部分图片在 w1600 的尺寸下看起来会比较模糊。
```release-note
None
```

refactor: change scalingMethod parameter to automatic for thumbnail generation

---

application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
application/src/main/java/run/halo/app/infra/DefaultSystemVersionSupplier.java
application/src/main/java/run/halo/app/infra/utils/VersionUtils.java
application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
application/src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
application/src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java
application/src/test/java/run/halo/app/infra/DefaultSystemVersionSupplierTest.java

/area core
替换 Version 过时方法的引用为新 API
```release-note
None
```

chore: replace deprecated Version methods with updated API

---

ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/area ui
简化页面回收站的页面标题。
```release-note
简化页面回收站的页面标题。
```

refactor: simplify page title of deleted page

---

application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
application/src/main/java/run/halo/app/security/ExceptionSecurityConfigurer.java
application/src/main/java/run/halo/app/security/RedirectAccessDeniedHandler.java
application/src/main/java/run/halo/app/security/authorization/NotAuthenticatedAuthorizationManager.java

/area core
This PR make authenticated users redirect to user center if they are trying to access login and signup pages.
1. Log in Halo
2. Try to request <http://localhost:8090/login> or <http://localhost:8090/signup>.
```release-note
None
```

Redirect to user center if authenticated users access login and signup pages

---

ui/src/components/editor/DefaultEditor.vue

/area ui
/kind cleanup
修复 DefaultEditor 组件中的格式问题。
```release-note
None
```

fix: correct formatting issues in DefaultEditor component

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades to Lucene 9.12.0. See https://lucene.apache.org/core/9_12_0/changes/Changes.html for more.
```release-note
升级依赖 Lucene 至 9.12.0
```

Upgrade to Lucene 9.12.0

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades to jsoup 1.18.1. See https://github.com/jhy/jsoup/releases/tag/jsoup-1.18.1 for more.
```release-note
升级依赖 jsoup 至 1.18.1
```

Upgrade to jsoup 1.18.1

---

application/src/main/resources/static/styles/main.css
application/src/main/resources/templates/gateway_modules/common_fragments.html
application/src/main/resources/templates/gateway_modules/login_fragments.html
application/src/main/resources/templates/signup.html

/area core
微调登录相关页面的样式。
```release-note
None
```

refactor: enhance login page styling for improved UX

---

ui/console-src/layouts/BasicLayout.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml
ui/uc-src/layouts/BasicLayout.vue

/area ui
/kind bug
修复 Console 中退出登录功能失效的问题。
Fixes #6756 
```release-note
None
```

fix: resolve issue with logout functionality in Console not working

---

ui/console-src/router/guards/permission.ts

/area ui
支持检查是否有权限访问 /console。
Fixes #6773 
```release-note
None
```

feat: add support to check access permissions for /console

---

OWNERS

None
Add @LIlGG as a approver
```release-note
None 
```

chore: add LIlGG as a approver

---

application/src/main/resources/templates/gateway_modules/form_fragments.html

/area core
/kind bug
修复注册页面的 JS 错误。
```release-note
None 
```

fix: JavaScript error on signup page

---

application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java

/kind cleanup
/area core
This PR changes the redirect URI to `/uc` instead of `/console` after authenticating successfully.
```release-note
None
```

Redirect to user center after authenticating successfully

---

application/src/main/java/run/halo/app/core/endpoint/console/UserEndpoint.java
application/src/main/java/run/halo/app/core/user/service/SignUpData.java
application/src/main/java/run/halo/app/core/user/service/UserServiceImpl.java
application/src/main/java/run/halo/app/infra/ValidationUtils.java
application/src/main/java/run/halo/app/infra/exception/UnsatisfiedAttributeValueException.java
application/src/main/resources/config/i18n/messages.properties
application/src/main/resources/config/i18n/messages_zh.properties
application/src/test/java/run/halo/app/core/endpoint/console/EmailVerificationCodeTest.java
application/src/test/java/run/halo/app/core/user/service/UserServiceImplTest.java
application/src/test/java/run/halo/app/infra/ValidationUtilsTest.java
ui/console-src/modules/system/users/components/UserCreationModal.vue
ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
ui/src/constants/regex.ts
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml
ui/uc-src/modules/profile/components/PasswordChangeModal.vue

/area core
统一用户名和密码的校验
密码只能包含字母数字和特定的几个特殊字符,此规则参考密码生成器的规则
Fixes #6793
```release-note
None
```

refactor: unified validation for username and password format

---

ui/console-src/modules/system/auth-providers/components/AuthProviderListItem.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/area ui
完善内置的认证提供商的 i18n。
```release-note
None
```

feat: improve built-in auth providers' i18n

---

application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
application/src/main/java/run/halo/app/security/preauth/PreAuthTwoFactorEndpoint.java
application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.html
application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_en.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_es.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_zh_TW.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_send.html
application/src/main/resources/templates/gateway_fragments/password_reset_email_send.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_send_en.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_send_es.properties
application/src/main/resources/templates/gateway_fragments/password_reset_email_send_zh_TW.properties

/area core
This PR adds globalInfo into template models and refactors password reset to adapt data binding.
Fixes https://github.com/halo-dev/halo/issues/6821
```release-note
None
```

Add globalInfo into templates model

---

application/src/main/resources/templates/gateway_fragments/common.html
application/src/main/resources/templates/gateway_fragments/login.html
application/src/main/resources/templates/login_local.html

/area core
提升登录页面的可访问性。
```release-note
None
```

refactor: improve accessibility for login page

---

application/src/main/resources/templates/gateway_fragments/signup.html

/area core
注册表单发送邮箱验证码时，支持显示来自后端的异常。
```release-note
None
```

feat: support toast a message for backend exceptions when sending emails

---

application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
application/src/main/resources/templates/setup.html
application/src/main/resources/templates/setup.properties
application/src/main/resources/templates/setup_en.properties
application/src/main/resources/templates/setup_es.properties
application/src/main/resources/templates/setup_zh_TW.properties

/area core
在初始化页面添加 H2 数据的使用警告。
Fixes https://github.com/halo-dev/halo/issues/6845
```release-note
None
```

feat: add H2 database usage warning for setup page

---

application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
application/src/test/java/run/halo/app/security/HaloServerRequestCacheTest.java

/kind bug
/area core
This PR ignores URI fragment while removing redirect URI. Before that, users may be redirected to previous redirect URI that contains fragment.
```release-note
修复二次登录后重定向跳转至旧地址的问题
```

Fix the problem of redirecting to previous URI with fragment after authenticated

---

README.md

更新快速开始的版本号。
```release-note
None
```

docs: update readme for 2.20

---

application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java

/area core
This PR exposes ReactiveUserDetailsService to authentication plugins.
```release-note
支持在插件中使用 ReactiveUserDetailsService
```

Expose ReactiveUserDetailsService to authentication plugins

---

.github/actions/docker-buildx-push/action.yaml

/area core
/kind cleanup
Fix wrong user property for Fit2Cloud Docker Registry
```release-note
None
```

chore: update action.yaml

---

.github/actions/docker-buildx-push/action.yaml

/kind cleanup
/area core
This PR fixes failure action <https://github.com/halo-dev/halo/actions/runs/11457902981/job/31879681434>.
```release-note
None
```

Configure registry while login to Fit2Cloud Docker Registry

---

gradle.properties

/kind cleanup
/area core
This PR updates Halo version to 2.20.8-SNAPSHOT.
```release-note
None
```

Update version to 2.20.8-SNAPSHOT

---

build.gradle

/area core
This PR upgrades to Spring Boot [3.4.0-RC1](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0-RC1).
```release-note
升级 Spring Boot 至 3.4.0-RC1
```

Upgrade to Spring Boot 3.4.0-RC1

---

ui/console-src/modules/system/users/UserDetail.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

What type of PR is this?
/area ui
What this PR does / why we need it:
期望支持在用户详情页面支持变更用户角色及删除用户 。
Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/issues/6944
Special notes for your reviewer:
Does this PR introduce a user-facing change?
```release-note
支持在用户详情页面支持变更用户角色及删除用户 。
```

feat: add grant permission and user deletion features to user detail page

---

api-docs/openapi/v3_0/aggregated.json
api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
api-docs/openapi/v3_0/apis_public.api_v1alpha1.json
api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
gradle.properties

/kind cleanup
This PR bumps version to 2.20.9-SNAPSHOT.
```release-note
None
```

Bump version to 2.20.9-SNAPSHOT

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml
.github/ISSUE_TEMPLATE/feature_request.en.yml
.github/ISSUE_TEMPLATE/feature_request.zh.yml

/kind cleanup
This PR use task list for issue and pr checks.
See https://github.com/orgs/halo-dev/discussions/7001 for more.
Fixes https://github.com/orgs/halo-dev/discussions/7001
```release-note
None
```

Use task list for issue and pr checks

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades to [PF4J 3.13.0](https://github.com/pf4j/pf4j/releases/tag/release-3.13.0).
```release-note
升级依赖 PF4J 至 3.13.0
```

Upgrade to PF4J 3.13.0

---

platform/application/build.gradle

/kind cleanup
/area core
This PR upgrades to SpringDoc to [2.8.3](https://github.com/springdoc/springdoc-openapi/releases/tag/v2.8.3).
```release-note
升级依赖 SpringDoc 至 2.8.3
```

Upgrade to SpringDoc to 2.8.3

---

ui/package.json
ui/pnpm-lock.yaml

/area ui
/kind cleanup
Bump axios version to 1.7.9
```release-note
None
```

chore: bump axios version to 1.7.9

---

build.gradle

/kind cleanup
/area core
This PR upgrades to Spring Boot [3.4.1](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.1).
```release-note
升级依赖 Spring Boot 至 3.4.1
```

Upgrade to Spring Boot 3.4.1

---

README.md

Fixes #
```release-note
None
```

docs: add a suggestion for using 1Panel in README.md

---

build.gradle

/kind cleanup
/area core
This PR upgrades to Spring Boot [3.4.3](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.3).
```release-note
升级依赖 Spring Boot 至 3.4.3
```

Upgrade to Spring Boot 3.4.3

---

api/src/main/java/run/halo/app/core/extension/Theme.java
api/src/main/java/run/halo/app/theme/router/PageUrlUtils.java
application/src/main/java/run/halo/app/content/SinglePageQuery.java
application/src/main/java/run/halo/app/content/comment/CommentEmailOwner.java
application/src/main/java/run/halo/app/core/reconciler/ReverseProxyReconciler.java
application/src/main/java/run/halo/app/security/authorization/RequestInfo.java
application/src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java

/kind cleanup
Replaces deprecated functions (`String defaultString(final String str, final String nullDefault)`) with its recommended alternatives
See https://github.com/apache/commons-lang/blob/29ccc7665f3bc5d84155a3092ab2209a053324e6/src/main/java/org/apache/commons/lang3/StringUtils.java#L1635 for more.
```release-note
None
```

Update deprecated default string function

---

.github/ISSUE_TEMPLATE/config.yml

None
Update issue templates config for commercial products
None
None
```release-note
None
```

chore: update issue templates config

---

application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
application/src/main/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactory.java
application/src/test/java/run/halo/app/theme/router/factories/AuthorPostsRouteFactoryTest.java

/area core
仅对包含文章权限的用户生成作者页面
Fixes #7202
```release-note
仅对包含文章权限的用户生成作者页面
```

refactor: restrict author page access to users with post permission

---

application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
application/src/main/java/run/halo/app/infra/console/ProxyFilter.java

/kind bug
/area core
This PR fixes the pending problem of requesting console and ui pages in dev mode.
Fixes https://github.com/halo-dev/halo/issues/7191
Steps to reproduce:
- Start ui projects with dev mode by executing command `make -C ui dev`.
- Run Halo instance in dev mode by executing command `./gradlew bootRun --args="--spring.profiles.active=dev"`.
- Try to request <http://localhost:8090/uc> and <http://localhost:8090/console>.
- Try to refresh page by hand and see the result
```release-note
修复开发模式下无法正常进入管理和个人中心页面的问题
```

Fix the pending problem of requesting console and uc pages in dev mode

---

application/src/main/resources/templates/gateway_fragments/layout.html

/area core
Add favicon to login page
Fixes #7287 
```release-note
为登录相关的页面添加 Favicon
```

feat: add favicon to login page

---

build.gradle

/area core
This PR upgrades to Spring Boot [3.4.4](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.4).
Fixes https://github.com/halo-dev/halo/issues/7170
```release-note
升级依赖 Spring Boot 至 3.4.4
```

Upgrade to Spring Boot 3.4.4

---

ui/uc-src/modules/contents/posts/PostEditor.vue
ui/uc-src/modules/contents/posts/components/PostCreationModal.vue

/area ui
/kind bug
See #6994
Fixes #6994
统一了发布文章时的行为，均先确保服务端创建草稿后保存内容。
```release-note
修复文章重复生成的问题
```

fix: resolve issue of duplicate post creation

---

application/src/main/java/run/halo/app/Application.java

/area core
This PR removes application startup steps buffer to reduce memory usage.
```release-note
None
```

Remove unused application startup steps buffer

---

application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java

/area core
This PR use secure-strong SecureRandom to generate unpredictable metadata name. Meanwhile, the length of generate name suffix is increased to `8` and lower-case is to prevent data conflicts caused by database case sensitivity as possible.
Another improvement is using bounded-elastic thread to run the method `secureString()#nextAlphanumeric` because the method contains blocking operation, which might cause system block.
```release-note
None
```

Prevent data conflicts caused by database case sensitivity as possible

---

ui/console-src/modules/system/users/components/UserCreationModal.vue

/kind feature
/area ui
Add support for multiple roles during user creation
Fixes #7325 
```release-note
新建用户时支持设置多个角色
```

feat: add support for multiple roles during user creation

---

application/src/main/java/run/halo/app/Application.java

Reverts halo-dev/halo#7364
Fixes https://github.com/halo-dev/halo/issues/7385
```release-note
None
```

Revert "Remove unused application startup steps buffer"

---

application/src/main/java/run/halo/app/infra/SchemeInitializer.java
ui/console-src/modules/contents/posts/tags/TagList.vue
ui/src/locales/_missing_translations_es.yaml
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml

/kind feature
标签支持根据文章量排序
```release-note
标签支持根据文章量排序
```

feat：support sorting tags by post count

---

application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java

/area core
This PR adds support for redirection on logout. We can request <http://localhost:8090/logout?redirect_uri=/archives> with GET method, then click the logout to see the redirection.
Fixes https://github.com/halo-dev/halo/issues/7401
```release-note
登出页面支持自定义重定向
```

Add support for redirection on logout

---

api/src/main/java/run/halo/app/theme/finders/Finder.java

过期的Spring @Component API
Fixes #7431
```release-note
None
```

Fix the deprecation warning of support for convention-base @Component names

---

application/src/main/java/run/halo/app/core/reconciler/PluginReconciler.java
ui/console-src/modules/system/plugins/components/PluginConditionsModal.vue
ui/console-src/modules/system/plugins/components/tabs/Detail.vue

/area core
/area plugin
This PR prints stack trace into plugin conditions to make plugin developers inspect conveniently.
```release-note
None
```

Show stack trace while failing to start plugin

---

application/build.gradle

/area core
Defining `into` property in `processResources` task is not working, so I create a new copy task to process UI dist.
```release-note
None
```

Refactor processResources with creating a new copy task

---

application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java

/area core
This PR removes `/uploads/**` from static resources to make it protected by Halo security.
```release-note
None
```

Make uploads resources protected

---

application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
application/src/main/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServices.java

/kind cleanup
/area core
This PR corrects location of LogoutHandler instead of in LogoutSuccessHandler. LogoutHanadler should be invoked before LogoutSuccessHandler.
```release-note
None
```

Refactor logout handler

---

ui/console-src/modules/contents/attachments/AttachmentList.vue
ui/console-src/modules/contents/attachments/components/AttachmentListItem.vue
ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
ui/console-src/modules/contents/attachments/composables/use-attachment.ts
ui/uc-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue

/area ui
/kind bug
Fix correct attachment selection state after new upload.
Fixes https://github.com/halo-dev/halo/issues/7472
```release-note
修复当有已选择附件时，上传新附件导致所选附件状态异常的问题。
```

fix: correct attachment selection state after new upload

---

ui/src/components/global-search/GlobalSearchModal.vue

/area ui
/kind bug
Exclude reserved users from global search results
Fixes https://github.com/halo-dev/halo/issues/7286
```release-note
修复 Console 的全局搜索能搜索出系统保留用户的问题。
```

fix: exclude reserved users from global search results

---

ui/console-src/modules/system/settings/tabs/Setting.vue

/area ui
Migrate system settings to new configmap API
Fixes #7515 
Need to test whether the system setting is working properly
```release-note
None
```

refactor: migrate system settings to new configmap API

---

ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
ui/console-src/modules/contents/posts/DeletedPostList.vue
ui/console-src/modules/contents/posts/components/PostListItem.vue
ui/console-src/modules/contents/posts/components/entity-fields/PublishTimeField.vue
ui/console-src/modules/dashboard/widgets/presets/posts/RecentPublishedWidget.vue
ui/console-src/modules/dashboard/widgets/presets/posts/components/PostListItem.vue
ui/src/locales/en.yaml
ui/src/locales/zh-CN.yaml
ui/src/locales/zh-TW.yaml
ui/uc-src/modules/contents/posts/components/PostListItem.vue

/area ui
```release-note
将 Console 端文章列表的发布时间改为语义化时间
```

refactor: convert post publish dates to human-readable format

---

ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue

/area ui
Update extension points settings using new configMap API
```release-note
None
```

refactor: update extension points settings using new configMap API

---

ui/uc-src/modules/contents/posts/components/PostListItem.vue

/area ui
Add cover image display for the post list in the uc.
```release-note
None
```

feat: add cover for post list in uc

---

ui/console-src/modules/contents/posts/DeletedPostList.vue
ui/console-src/modules/contents/posts/components/entity-fields/TitleField.vue
ui/uc-src/modules/contents/posts/components/PostListItem.vue

/area ui
Remove unused width prop for post title field
```release-note
None
```

refactor: remove unused width prop for post title field

---

ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
ui/src/layouts/MobileMenu.vue

/area ui
/kind cleanup
None
```release-note
None
```

chore: fix incorrect imports

---

ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
ui/console-src/modules/contents/posts/DeletedPostList.vue

/area ui
Add cover field for deleted post list in console.
```release-note
None
```

feat: add cover for deleted post list in console

---

README.md

docs: Add GitCode badge

---

gradle/libs.versions.toml

/area core
This PR upgrades to Spring Boot [3.5.4](https://github.com/spring-projects/spring-boot/releases/tag/v3.5.4).
```release-note
升级依赖 Spring Boot 至 3.5.4
```

Upgrade to Spring Boot 3.5.4

---

application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
application/src/main/java/run/halo/app/notification/DefaultNotificationSender.java
application/src/main/java/run/halo/app/notification/NotificationTrigger.java
application/src/test/java/run/halo/app/notification/DefaultNotificationSenderTest.java

/area core
This PR sets timeout on notification trigger to make sure the procedure won't getting stuck forever.
```release-note
修复运行过程中通知器可能失效的问题
```

Fix the problem that notification might not work anymore

---

application/src/main/resources/extensions/notification-templates.yaml
ui/console-src/modules/dashboard/widgets/presets/users/NotificationWidget.vue
ui/uc-src/modules/notifications/Notifications.vue
ui/uc-src/modules/notifications/components/NotificationContent.vue
ui/uc-src/modules/notifications/components/NotificationListItem.vue

/area core
/area ui
/kind feature
Optimize comment notification template to support rich text rendering
```release-note
None
```

Optimize comment notification template to support rich text rendering

---

ui/console-src/modules/system/roles/components/RoleEditingModal.vue

/area ui
/kind bug
See #7676 
Fixes #7676 
```release-note
修复角色修改表单中，所选权限可能出现不完整的问题。
```

Fix role dependency handling in role editing form

---

ui/console-src/layouts/BasicLayout.vue
ui/console-src/modules/system/tools/Tools.vue
ui/env.d.ts
ui/src/components/menu/MenuLoading.vue
ui/src/composables/use-route-menu-generator.ts
ui/uc-src/layouts/BasicLayout.vue

/area ui
/kind feature
Support async permission checks in route menu generator
example:
```ts
{
path: "",
name: "Foo",
component: Foo,
meta: {
title: "Foo",
searchable: true,
permissions: async () => {
const { data } = await checkPermission();
return data;
},
menu: {
name: "Foo",
group: "content",
icon: markRaw(MingcuteBook2Line),
priority: 4,
mobile: false,
},
},
}
```
Fixes #
```release-note
开发者相关：路由的权限检查支持函数
```

Support async permission checks in route menu generator

---

gradle/libs.versions.toml

/area core
This PR upgrads Lucene to version [10.3.0](https://github.com/apache/lucene/releases/tag/releases%2Flucene%2F10.3.0).
```release-note
升级 Lucene 至 10.3.0
```

Upgrade Lucene to version 10.3.0

---

.github/workflows/halo.yaml
application/build.gradle

/kind bug
/area core
This PR fixes the incorrect namespace of F2C Docker Registry.
```release-note
None
```

Update Docker image name and tags for Fit2Cloud registry

---

application/build.gradle
ui/build.gradle

/kind bug
/area core
This PR fixes the missing build for ui while executing bootJar task, which causes console and uc resources missed after packcaging Docker image using Buildpacks.
```release-note
None
```

Refactor build tasks to improve UI distribution and cleanup processes

---

gradle/libs.versions.toml

/area core
This PR upgrades Spring Boot to [3.5.6](https://github.com/spring-projects/spring-boot/releases/tag/v3.5.6).
```release-note
升级 Spring Boot 至 3.5.6
```

Upgrade Spring Boot version to 3.5.6

---

application/src/main/resources/extensions/system-setting.yaml
ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
ui/console-src/modules/contents/posts/components/PostSettingModal.vue
ui/console-src/modules/system/users/components/UserCreationModal.vue
ui/console-src/modules/system/users/components/UserEditingModal.vue
ui/package.json
ui/pnpm-lock.yaml
ui/src/formkit/formkit.config.ts
ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
ui/uc-src/modules/profile/components/ProfileEditingModal.vue

/area ui
Add auto-height prop to  formkit textarea to support automatic resizing based on content length.
```release-note
Console 端的部分多行文本输入框支持自动高度。
```

Enable auto-height for textarea fields in forms
