halo-dev/halo

- console/src/components/signup/SignupForm.vue
- console/src/locales/en.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
/area console
/kind feature
Add email field for signup
```release-note
用户注册新增电子邮箱字段。
```
> feat: add email field for signup

- console/console-src/modules/contents/attachments/AttachmentList.vue
- console/console-src/modules/contents/attachments/components/AttachmentListItem.vue
- console/console-src/modules/contents/comments/CommentList.vue
- console/console-src/modules/contents/pages/DeletedSinglePageList.vue
- console/console-src/modules/contents/pages/SinglePageList.vue
- console/console-src/modules/contents/pages/components/SinglePageListItem.vue
- console/console-src/modules/contents/posts/DeletedPostList.vue
- console/console-src/modules/contents/posts/PostList.vue
- console/console-src/modules/contents/posts/components/PostListItem.vue
- console/console-src/modules/system/plugins/PluginList.vue
- console/console-src/modules/system/plugins/components/PluginListItem.vue
- console/console-src/modules/system/roles/RoleDetail.vue
- console/console-src/modules/system/roles/components/RoleEditingModal.vue
- console/console-src/modules/system/users/UserList.vue
- console/package.json
- console/pnpm-lock.yaml
- console/src/components/global-search/GlobalSearchModal.vue
- console/src/formkit/theme.ts
- console/src/styles/tailwind.css
- console/tailwind.config.js
- console/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue
/area console
Use [@tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms) plugin to standardize the style of form elements, and resolve some style issues.
before:
after:
Fixes #4734 
```release-note
优化 Console 端表单元素样式
```
> feat: add tailwindcss/forms plugin to standardize the style of form elements

- application/build.gradle
- platform/application/build.gradle
/kind cleanup
/area core
Upgrades to Spring Boot 3.2.0. See https://github.com/spring-projects/spring-boot/releases/tag/v3.2.0 for more.
Supersedes <https://github.com/halo-dev/halo/pull/4850>.
```release-note
[Action Required] 升级 Spring Boot 依赖至 3.2.0
```
> Upgrade to Spring Boot 3.2.0

- .github/workflows/halo.yaml
- Dockerfile
/area core
使用 ibm-semeru-runtimes:open-17-jre 作为基础镜像构建 Halo 镜像，以获得更优的内存消耗。
Fixes #2584 
```
./gradlew build
docker build -t halohub/halo:openj9 .
```
```release-note
使用 ibm-semeru-runtimes:open-17-jre 作为基础镜像构建 Halo 镜像，以获得更优的内存消耗。
```
> chore: use ibm-semeru-runtimes to replace eclipse-temurin as the base image

- Dockerfile
/kind bug
/area core
Reset base Docker image of builder to eclipse-temurin to fix the problem of OOM while building multi-platform Docker image. See https://github.com/halo-dev/halo/actions/runs/6976331252/job/18984676251 for more.
```release-note
None
```
> Reset base Docker image of builder to eclipse-temurin

- console/console-src/layouts/BasicLayout.vue
- console/console-src/modules/interface/themes/ThemeDetail.vue
- console/console-src/modules/interface/themes/ThemeSetting.vue
- console/console-src/modules/interface/themes/layouts/ThemeLayout.vue
- console/console-src/modules/system/plugins/PluginDetail.vue
- console/console-src/modules/system/plugins/tabs/Detail.vue
- console/console-src/modules/system/plugins/tabs/Setting.vue
- console/packages/components/src/components/card/Card.vue
- console/uc-src/layouts/BasicLayout.vue
/area console
/kind bug
修复在 Card 组件中使用下拉组件无法完整显示的问题。
before:
after:
Fixes #4921 
```release-note
修复在 Card 组件中使用下拉组件无法完整显示的问题。
```
> fix: overflow issue of card component

- console/src/components/editor/DefaultEditor.vue
- console/src/utils/__tests__/anchor.spec.ts
- console/src/utils/anchor.ts
/area console
在默认编辑器中，自动为 heading 类型元素生成有意义的 id，而不是原来的 `heading-x`。
Fixes https://github.com/halo-dev/halo/issues/4838
需要测试在默认编辑器中编写若干 heading 类型的元素，发布之后查看元素的 id。
```release-note
为默认编辑器中 heading 类型元素生成有意义的 id。
```
> feat: generate id for heading in the default editor

- console/console-src/modules/system/actuator/Actuator.vue
- console/src/locales/en.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
/area console
支持在概览页面显示已启动插件和已激活的主题，同时支持复制。
example:
```
- 外部访问地址: 
- 启动时间: 2023-11-23 11:57
- 版本: 2.11.0-SNAPSHOT
- 构建时间: 2023-11-23 11:57
- Git Commit: cd02332
- Java: OpenJDK Runtime Environment / 17.0.9+0
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Mac OS X / 14.1.1
- 已激活主题: [Walker](https://halo.run/store/apps/app-GHgAR)
- 已启动插件:
- [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
- [Docsme](https://github.com/f2ccloud/plugin-docsme)
```
Fixes #4690 
测试概览页面的信息显示是否正确，以及复制之后的数据是否正确。
```release-note
支持在概览页面显示已启动插件和已激活的主题。
```
> feat: add support for displaying enabled plugins on actuator page

- application/src/main/java/run/halo/app/notification/DefaultNotificationService.java
- application/src/main/java/run/halo/app/notification/UserNotificationService.java
- application/src/main/java/run/halo/app/notification/endpoint/UserNotificationEndpoint.java
- application/src/main/resources/extensions/role-template-authenticated.yaml
- console/packages/api-client/src/api/api-notification-halo-run-v1alpha1-notification-api.ts
- console/uc-src/modules/notifications/Notifications.vue
- console/uc-src/modules/notifications/components/NotificationListItem.vue
- e2e/testsuite.yaml
/kind feature
/area core
/area console
新增用户站内消息删除功能
Fixes #4706
```release-note
新增用户站内消息删除功能
```
> feat: add delete function for user notification

- console/packages/ui-plugin-bundler-kit/.eslintignore
- console/packages/ui-plugin-bundler-kit/.eslintrc.js
- console/packages/ui-plugin-bundler-kit/.prettierrc.cjs
- console/packages/ui-plugin-bundler-kit/build.config.ts
- console/packages/ui-plugin-bundler-kit/package.json
- console/packages/ui-plugin-bundler-kit/src/index.ts
- console/packages/ui-plugin-bundler-kit/tsconfig.json
- console/pnpm-lock.yaml
/area console
/kind feature
添加 `@halo-dev/ui-plugin-bundler-kit` 包，用于向插件提供统一的 Vite 构建配置。
最终用法：
```bash
pnpm install @halo-dev/ui-plugin-bundler-kit -D
```
vite.config.ts
```ts
import { HaloUIPluginBundlerKit } from "@halo-dev/ui-plugin-bundler-kit";
export default defineConfig({
plugins: [
Vue(),
Icons({ compiler: "vue3" }),
HaloUIPluginBundlerKit(),
],
resolve: {
alias: {
"@": fileURLToPath(new URL("./src", import.meta.url)),
},
},
});
```
Fixes #4912 
测试方式：
1. 在任意支持 UI 扩展的插件中添加此包：`pnpm install path/to/halo/console/packages/ui-plugin-bundler-kit`
2. 构建插件，检查 UI 相关的构建产物以及功能是否正常。
```release-note
添加 `@halo-dev/ui-plugin-bundler-kit` 包，用于向插件提供统一的构建配置。
```
> feat: add ui-plugin-bundler-kit package

- console/console-src/modules/system/roles/components/RoleEditingModal.vue
- console/console-src/router/guards/auth-check.ts
- console/src/constants/annotations.ts
/area console
/kind feature
支持为自定义的角色配置登录之后默认跳转位置。
1. 创建一个新的角色，设置跳转位置。
2. 为一个用户赋予这个角色。
3. 测试登录之后是否正常跳转到设置的位置。
```release-note
支持为自定义的角色配置登录之后默认跳转位置。
```
> feat: support for configuring the redirection location after login for roles

- console/package.json
- console/pnpm-lock.yaml
- console/src/vite/library-external.ts
/area console
/area editor
升级编辑器依赖，并将其全局注册，此 PR 合并之后，插件如果需要扩展编辑器，则不必引入其中依赖，可以完全排除。
- https://github.com/halo-sigs/richtext-editor/pull/71 Fixes https://github.com/halo-dev/halo/issues/4868
```release-note
升级默认编辑器版本。
```
> chore: bump editor version and let it load globally

- console/console-src/modules/system/actuator/module.ts
- console/src/locales/en.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
/area console
完善系统概览页面的 UI 权限控制。
```release-note
完善系统概览页面的 UI 权限控制。
```
> feat: refine ui permissions of actuator page

- api/src/main/java/run/halo/app/extension/JsonExtension.java
- application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
- application/src/test/java/run/halo/app/extension/FakeExtension.java
- application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
/kind bug
/area core
This PR resolves the problem of incorrect old data passed to watcher during updates. As shown in the following line, the old value should be `old` instead of `extension` from outside.
https://github.com/halo-dev/halo/blob/7a84f553005b2d8047ccdb0acf473693384a7b51/application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java#L172
```release-note
None
```
> Fix the problem of incorrect old data passed to watcher during updates

- console/console-src/layouts/BasicLayout.vue
- console/console-src/modules/system/roles/components/RoleEditingModal.vue
- console/console-src/modules/system/users/UserDetail.vue
- console/console-src/modules/system/users/widgets/NotificationWidget.vue
- console/packages/editor/src/locales/zh-CN.yaml
- console/src/components/user-avatar/UserAvatar.vue
- console/src/components/user-avatar/UserAvatarCropper.vue
- console/src/locales/en.yaml
- console/src/locales/es.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
- console/uc-src/layouts/BasicLayout.vue
- console/uc-src/modules/contents/posts/PostEditor.vue
- console/uc-src/modules/contents/posts/PostList.vue
- console/uc-src/modules/contents/posts/components/PostListItem.vue
- console/uc-src/modules/contents/posts/components/PostSettingEditModal.vue
- console/uc-src/modules/contents/posts/module.ts
- console/uc-src/modules/notifications/Notifications.vue
- console/uc-src/modules/notifications/components/NotificationListItem.vue
- console/uc-src/modules/notifications/module.ts
- console/uc-src/modules/profile/Profile.vue
- console/uc-src/modules/profile/components/EmailVerifyModal.vue
- console/uc-src/modules/profile/components/PasswordChangeModal.vue
- console/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue
- console/uc-src/modules/profile/components/PersonalAccessTokenListItem.vue
- console/uc-src/modules/profile/components/ProfileEditingModal.vue
- console/uc-src/modules/profile/module.ts
- console/uc-src/modules/profile/tabs/Detail.vue
- console/uc-src/modules/profile/tabs/NotificationPreferences.vue
- console/uc-src/modules/profile/tabs/PersonalAccessTokens.vue
/area console
完善个人中心相关页面的 i18n。
测试各个语言的个人中心相关页面。
```release-note
完善个人中心相关页面的 i18n。
```
> feat: refine i18n for uc

- console/src/formkit/inputs/repeater/AddButton.vue
/kind bug
/area console
为 repeater 中的 addButton 点击事件增加校验 disabled 属性。
在 safari 浏览器下测试具有 max repeater 的组件，当其 addButton 按钮变灰之后继续点击。查看是否不再添加新的项。 
Fixes #4948 
```release-note
修复 safari 浏览器下，repeater 的 max 属性无效的问题
```
> fix: add disabled validation to the addButton click event for the repeater

- console/uc-src/modules/contents/posts/components/PostListItem.vue
/area console
/kind bug
修复在个人中心的文章列表中点击标签控制台报错的问题。
```release-note
None
```
> fix: issue of clicking on the post tag in uc to report an error

- application/src/main/resources/extensions/role-template-uc-content.yaml
- console/src/locales/en.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
/kind cleanup
/area core
This PR adds role templates for posts in user center for recreating more flexible roles. Related to <https://github.com/halo-dev/halo/pull/4866>.
```release-note
None
```
> Add role templates for posts in user center

- .github/workflows/halo.yaml
- console/package.json
- console/packages/api-client/package.json
- console/packages/components/package.json
- console/packages/editor/package.json
- console/packages/shared/package.json
- console/packages/ui-plugin-bundler-kit/package.json
- gradle.properties
/kind cleanup
/area core
Bump versions for next development.
Meanwhile, I also created a branch `release-2.11` for actions at [here](https://github.com/halo-sigs/actions/tree/release-2.11).
```release-note
None
```
> [release-2.11] Bump versions for next development

- console/src/components/editor/DefaultEditor.vue
/kind bug
/area console
修复在默认编辑器中无法使用拼音输入法输入标题的问题，此问题由 https://github.com/halo-dev/halo/pull/4909 引发。
Fixes #4970 
在编辑器中，使用拼音输入法输入标题（heading），观察是否可以正常输入。
```release-note
修复在默认编辑器中无法使用拼音输入法输入标题的问题。
```
> fix: can not input title using Chinese IME in editor

- console/packages/editor/src/extensions/image/ImageView.vue
/kind bug
/area editor
修复#4985 中调整图片大小时的高度变化bug
Fixes #4985 
似乎是因为横纵比aspectRatio在调整大小的doDrag函数中被动态的更新数值，导致依赖aspectRatio来计算的高度也会出现问题。直接把aspectRatio移动到函数外，只在挂载后更新一次值即可解决。
```release-note
这会修复当前console的editor中图片比例拉伸的bug
```
> fix: editor's image cannot be resized proportionally

- console/.gitignore
/area console
storybook-static 文件夹为 Storybook 的构建目录，此 PR 将此文件夹添加到 .gitignore
```release-note
None
```
> chore: add storybook-static folder to .gitignore

- console/uc-src/modules/profile/tabs/Detail.vue
/kind bug
Fix the issue of always displaying Unbind in the login method on the user profile page.
Fixes #5048
@JohnNiang 's help.
```release-note
修复个人中心用户登录方式仅显示解绑问题 
```
> Fix the issue of always displaying `Unbind` in the login method on the user profile page

- console/src/components/dropdown-selector/EditorProviderSelector.vue
- console/src/locales/en.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
/area console
当编辑器切换组件中有不可用编辑器时，添加提示。
Fixes #5059 
测试方式：
1. 安装若干不同类型的编辑器，并创建文章。
2. 修改文章时尝试选择不同类型的编辑器，观察是否有提示。
```release-note
当编辑器切换组件中有不可用编辑器时，添加提示。
```
> feat: add disallow tooltip for editor provider selector component

- console/console-src/modules/system/users/UserList.vue
/area console
/kind feature
在用户数据管理列表页面路由中记录查询条件，包括分页信息、筛选信息等。可以保证在刷新页面或者切换路由返回时保留之前的查询状态。
Fixes #5060 
需要测试：
1. 用户管理列表的所有筛选项是否可以正常工作。
```release-note
Console 端的用户管理列表支持在地址栏记录筛选条件。
```
> feat: record the user query conditions in the route query parameters

- console/packages/editor/src/extensions/heading/index.ts
- console/packages/editor/src/utils/anchor.ts
- console/src/components/editor/DefaultEditor.vue
/kind bug
/area editor
重写了对默认编辑器标题的 id 生成逻辑。目前将会在对标题进行任意的修改之后，对所有的标题进行 id 计算，用以解决当标题名称具有重复时，生成了相同的 id.
需要注意的是，由于需要对任意标题进行修改之后才会进行生效，因此已经存在重名标题 id 的问题时，需要修改任意的标题使其生效。
在文章内新增多个相同内容的标题，查看是否可以正常跳转。
Fixes #5068 
```release-note
解决默认编辑器中具有重名标题时，锚点只会跳转至首个的问题。
```
> fix: fix anchor positioning for identical table of contents names

- console/packages/editor/src/styles/base.scss
/kind bug
修改 code 内`br` 标签的 `display`，用于适配 firefox 浏览器
测试在 firefox 浏览器下，使用代码块回车等是否会出现样式问题。
Fixes #5064 
```release-note
解决在 Firefox 浏览器下的代码块编辑问题。
```
> fix: address styling issues with empty lines in code blocks

- console/packages/ui-plugin-bundler-kit/src/index.ts
/area console
将默认编辑器依赖添加到插件构建库的 external 中，基于 https://github.com/halo-dev/halo/pull/4924
```release-note
None
```
> chore: make editor lib external for plugin

- .github/actions/docker-buildx-push/action.yaml
- .github/actions/setup-env/action.yaml
- .github/workflows/halo.yaml
- application/build.gradle
/area core
This PR refactors workflow by not using compiste actions from <https://github.com/halo-sigs/actions> and adds a support of publishing Halo artifact into GitHub release.
I have tested the new workflow in my repo, please see 
- Release Detail: https://github.com/JohnNiang/halo/releases/tag/v2.12.0-alpha.3
- Push Event: https://github.com/JohnNiang/halo/actions/runs/7470856348
- PullRequest Event: https://github.com/JohnNiang/halo/actions/runs/7470570889?pr=13
- Release Event: https://github.com/JohnNiang/halo/actions/runs/7470874779
After this PR, the repository <https://github.com/halo-sigs/actions> can be archived.
Fixes https://github.com/halo-dev/halo/issues/2996
```release-note
支持发布构建产物 halo-x.y.z.jar
```
> Refactor workflow by not using composite actions from halo-sigs/actions

- console/packages/editor/src/extensions/table/table-row.ts
/kind bug
为表格 tr 增加 style 字段，解决由于合并单元格后 tr 高度为 0 的问题
将三列三行的表格，每列进行不一样的组合合并单元格后，查看其是否会出现变成两行的问题。
Fixes #5143 
```release-note
解决默认编辑器表格合并单元格后行丢失的问题
```
> fix: resolve the issue of reduced row count after merging cells

- console/src/locales/es.yaml
/area console
/kind bug
取消对 es.yaml 的注释，这应该是在 https://github.com/halo-dev/halo/pull/4957 中临时注释之后，合并前没有取消注释。
```release-note
None
```
> fix: revert es i18n file

- console/packages/editor/src/extensions/list-keymap/index.ts
- console/packages/editor/src/extensions/table/index.ts
- console/packages/editor/src/extensions/table/util.ts
/kind feature
为表格增加删除快捷键，删除逻辑为
1. 光标处于表格下一行，按下退格键（Backspace），将会选中表格
2. 选中表格后再次按下退格键（Backspace），将会删除表格
由于修改了无序列表等快捷键的部分逻辑，因此需要同步测试无序列表、有序列表、任务列表这三个功能是否正确。
1. 测试表格按照上述逻辑是否可删除
2. 测试 无序列表、有序列表、任务列表删除功能是否正确。
Fixes #5141 
```release-note
为默认富文本编辑器表格组件增加退格键删除方式
```
> feat: add shortcut for table deletion

- application/src/main/resources/application-dev.yaml
/area  core
When we are developing a plugin in development environment, APIs in plugin are frequently changed. But they are not reflected in Swagger UI instantly unless we restart Halo entirely.
This PR disables Swagger cache in that case.
```release-note
None
```
> Disable Swagger cache in development environment

- console/console-src/modules/contents/attachments/composables/use-attachment.ts
- console/console-src/modules/contents/pages/SinglePageEditor.vue
- console/console-src/modules/contents/posts/PostEditor.vue
- console/package.json
- console/packages/components/src/icons/icons.ts
- console/packages/editor/src/index.ts
- console/packages/editor/src/tiptap/index.ts
- console/pnpm-lock.yaml
- console/src/components/editor/DefaultEditor.vue
- console/src/components/editor/composables/use-attachment.ts
- console/src/components/editor/extensions/image/ImageView.vue
- console/src/components/editor/extensions/image/index.ts
- console/src/components/editor/extensions/index.ts
- console/src/components/editor/extensions/upload/index.ts
- console/src/components/editor/utils/attachment.ts
- console/src/components/editor/utils/upload.ts
- console/src/locales/en.yaml
- console/src/locales/zh-CN.yaml
- console/src/locales/zh-TW.yaml
- console/src/utils/api-client.ts
- console/uc-src/modules/contents/posts/PostEditor.vue
- console/uc-src/modules/contents/posts/types/index.ts
/kind feature
重构编辑器图片块上传逻辑，增加选择文件上传、上传进度条、取消、重试等机制。
直接拖动、复制或选择文件上传，查看是否显示上传进度条，取消、重试功能是否正常
Fixes #5122 
```release-note
重构编辑器图片块上传逻辑，增加选择文件上传、上传进度条、取消、重试等机制。
```
> feat: refactor editor image block upload logic

- application/src/main/resources/extensions/role-template-uc-content.yaml
/area core
修改文章编辑角色的显示名称为**文章管理员**，这样会更加直观。
Fixes #5221 
```release-note
修改文章编辑角色的显示名称为**文章管理员**。
```
> refactor: update chinese display name of post editor role

- application/build.gradle
- application/src/main/java/run/halo/app/content/comment/ReplyService.java
- application/src/main/java/run/halo/app/infra/exception/handlers/ProblemDetailErrorAttributes.java
- application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
- gradle.properties
- platform/application/build.gradle
/area core
See https://github.com/spring-projects/spring-boot/releases/tag/v3.2.2 for more.
```release-note
升级依赖 Spring Boot 至 3.2.2
```
> Upgrade Spring Boot to 3.2.2

- application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
/area core
This PR reverts changes in PR <https://github.com/halo-dev/halo/pull/4023>, mainly thanks to PR <https://github.com/halo-dev/halo/pull/5148>.
We don't need to refresh the plugin wrapper on every startup, because we entirely disable the plugin in plugin manager when disabling plugin at console.
Fixes https://github.com/halo-dev/halo/issues/4016
```release-note
None
```
> Revert: refresh the plugin wrapper when starting the plugin

- console/packages/editor/src/extensions/table/index.ts
/kind bug
当表格后存在选中的内容时，按下退格键或删除键不再执行选中表格的操作，而是继续向下执行。
在表格后紧跟着文本，从文本开头选中文本，然后按下退格键，查看文本是否能够被删除。
Fixes #5193 
```release-note
解决默认富文本编辑器中表格后的文本选中后无法删除的问题
```
> fix: text selected after resolving the table cannot be deleted

- api/src/main/java/run/halo/app/extension/Scheme.java
- application/src/test/java/run/halo/app/extension/SchemeTest.java
/kind bug
/area core
修复同一个自定义模型构建出的 Scheme 不相等导致无法正确从 SchemeManager 中移除的问题
Fixes #5243
```release-note
修复同一个自定义模型构建出的 Scheme 不相等导致无法正确从 SchemeManager 中移除的问题
```
> fix: resolve unequal schemes built from same Extension blocking unregister

- console/packages/components/src/components/menu/MenuItem.vue
- console/packages/components/src/components/menu/__tests__/Menu.spec.tsx
- console/packages/components/src/components/menu/__tests__/__snapshots__/Menu.spec.tsx.snap
/area console
优化 Console 左侧菜单的展开逻辑，改为可以通过点击展开图标来展开子菜单。
```release-note
优化 Console 左侧菜单的展开逻辑，支持通过点击图标来展开子菜单。
```
> refactor: improve effect of menu expand

- console/packages/editor/src/components/Editor.vue
/kind bug
/area console
/area editor
将默认编辑器的父级容器移除。用于解决冒泡菜单被遮挡的问题。
由于修改后默认编辑器自身可滚动，因此可以使默认编辑器容器内的绝对定位元素获取到当前滚动的位置。
输入超过一屏宽度的内容，按 `MOD + A` 全选，查看冒泡菜单是否被顶部菜单遮挡。
Fixes #4869
```release-note
解决冒泡菜单会被顶部工具栏遮挡的问题
```
> fix: resolve the issue of the bubble menu being obscured

- api/src/main/java/run/halo/app/core/extension/content/Post.java
- application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/test/java/run/halo/app/content/TestPost.java
- application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
/kind feature
/area core
我们为文章自定义模型的数据调协过程引入了重要的优化。
在以前，当数据量大（例如，50,000篇文章）的情况下，每次系统重启都会触发耗时且资源密集的所有数据的协调过程，即使大部分数据并不需要调协。这导致了不必要的数据库查询和高资源消耗。
为了解决这个问题，我们在文章自定义模型的 status 中添加了一个新的 `Long observedVersion` 属性。
每次协调后，此属性将更新为 `metadata.version`，还调整了 `syncAllOnStart` 条件，只有当 `status.observedVersion < metadata.version` 时才会调协数据。
这个改变确保了只有在启动时需要的数据会被协调，从而减少了资源使用和不必要的协调过程。
因此，Halo 的数据承载能力得到了显著提高。
**how to test it?**
使用此 PR 测试：启动时文章只有首次会执行 reconcile，再次重启时则不会再执行，如果直接修改数据去除掉 `status.observedVersion` 来模拟迁移或漏 reconcile 的过程则启动时该数据会被再次执行 reconcile
Fixes #5147
```release-note
优化文章数据的调协过程以降低 Halo 启动时文章的调协耗时同时提高性能和资源利用率
```
> feat: optimized post reconciliation process for enhanced performance and resource utilization

- application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
/kind bug
/area core
This PR treats logo as a path when building logo HTTP URL instead of a path segment. The concrete rules of logo is described [here](https://github.com/halo-dev/halo/issues/5253#issuecomment-1911729063).
See https://github.com/halo-dev/halo/issues/5253 for more.
Fixes https://github.com/halo-dev/halo/issues/5253
```release-note
None
```
> Fix the problem of resolving logo starting with slash

- platform/application/build.gradle
/area core
This PR upgrades Resilience4J to 2.2.0. See https://github.com/resilience4j/resilience4j/blob/v2.2.0/RELEASENOTES.adoc for more.
```release-note
升级依赖 Resilience4j 至 2.2.0
```
> Upgrade Resilience4j to 2.2.0

- application/src/main/java/run/halo/app/plugin/PluginControllerManager.java
/kind bug
/area core
/area plugin
/milestone 2.12.0
This PR adjusts the order of starting reconcilers in plugin, or it will be stuck in starting synchronizer and no reconcilers will be executed.
The problem may be introduced by <https://github.com/halo-dev/halo/pull/5251>.
```release-note
None
```
> Fix the problem of starting reconcilers in plugin before registering scheme

- console/src/composables/use-session-keep-alive.ts
/area console
/kind bug
修复当浏览器标签页不活跃时，文章编辑页面的 health 接口没有定时请求的问题。
Fixes #5265 
测试方式：
1. 可以在本地先将 refetchInterval 改为 1000 以方便测试。
2. 进入文章编辑页面。
3. 切换至其他标签页。
4. 返回之后查看浏览器开发者工具的 Network ，观察 health 接口是否有请求。
```release-note
修复当浏览器标签页不活跃时，文章编辑页面的 health 接口没有定时请求的问题。
```
> fix: unable to request session keep-alive API when browser tabs are inactive

- console/console-src/modules/system/users/UserDetail.vue
- console/src/components/user-avatar/UserAvatar.vue
- console/uc-src/modules/profile/Profile.vue
/area console
/kind bug
修复当头像因为后端服务无法正常变更时，前端因为一直处于 refetch 状态导致无法重新上传的问题。
Fixes https://github.com/halo-dev/halo/issues/4852
1. 使用 https://github.com/AirboZH/plugin-uposs 存储服务创建一个存储策略。
2. 用户设置中的头像存储位置改为此存储策略。
3. 上传头像，观测是否一直处于重新获取的状态。
```release-note
优化头像上传，防止因为后端服务异常导致无法重新上传。
```
> fix: it cannot be re-uploaded when the user's avatar cannot be obtained

- application/src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/DuplicateMetaTagProcessor.java
- application/src/test/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessorIntegrationTest.java
- application/src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java
/kind bug
/area core
/milestone 2.12.0
This PR refactors building html meta by using `modelFactory#createStandaloneElementTag`.
See https://github.com/halo-dev/halo/issues/4755 for more.
Fixes https://github.com/halo-dev/halo/issues/4755
Validate via <https://github.com/halo-dev/halo/issues/4755#issuecomment-1776391345>.
```release-note
修复摘要中包含特殊字符导致无法解析页面的问题
```
> Fix the problem of showing 500 error while containing special chars in excerpt

- application/src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
/area core
优化启动时用户头像获取不到的错误提示
原因是在启动时用户被执行 reconcile 时使用的 plugin-s3 插件还没有启动所以无法获取到 permalink 需要重试
使用 plugin-s3 插件作为用户头像的存储策略然后上传头像测试此 PR 在启动时的异常提示是否输出为：
```
2024-01-29T11:53:13.674+08:00  WARN 31937 --- [rReconciler-t-1] r.h.a.c.e.reconciler.UserReconciler      : Failed to get avatar permalink for user [guqing] with attachment [460be0c4-b09f-4b25-ad93-e45f30331ec7], re-enqueuing...
```
Fixes #5268
```release-note
优化启动时用户头像获取不到的错误提示
```
> refactor: error prompt for inability to obtain avatar permalink when starting

- console/src/composables/use-role.ts
/area console
/kind bug
修复创建角色时，勾选某个角色模板导致已选角色模板被清空的问题。
Fixes #5275 
```release-note
None
```
> fix: current selected role templates will be clear after select a other role

- console/console-src/composables/use-dashboard-stats.ts
- console/console-src/modules/contents/comments/widgets/CommentStatsWidget.vue
- console/console-src/modules/contents/pages/widgets/SinglePageStatsWidget.vue
- console/console-src/modules/contents/posts/widgets/PostStatsWidget.vue
- console/console-src/modules/dashboard/Dashboard.vue
- console/console-src/modules/dashboard/widgets/ViewsStatsWidget.vue
- console/console-src/modules/system/users/widgets/UserStatsWidget.vue
/area console
重构 Console 仪表盘中小部件的数据获取方式。
```release-note
None
```
> refactor: data fetching of dashboard widgets

- console/packages/editor/package.json
/area console
修改 `@halo-dev/richtext-editor` 的版本号，为发布 Halo 2.12 做准备。
```release-note
None
```
> chore: change editor version to 2.12.0

- application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
/area core
修复文章列表的 contributors 顺序不固定的问题
```release-note
None
```
> fix: the order of contributors for posts is not fixed

- .github/workflows/halo.yaml
/kind cleanup
/area core
This PR removes analyzing code step in test job because we have enabled Automatic Analysis in SonarCloud. There is no need to run CI analysis manually.
This PR also resolves [failing CI](https://github.com/halo-dev/halo/actions/runs/7708283716/job/21007037279):
```bash
User cache: /home/runner/.sonar/cache
Loading required plugins
Load plugins index
Load plugins index (done) | time=655ms
Load/download plugins
Load/download plugins (done) | time=815ms
Found an active CI vendor: 'Github Actions'
Load project settings for component key: 'halo-dev_halo'
Load project settings for component key: 'halo-dev_halo' (done) | time=650ms
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':sonar'.
> Task :sonar FAILED
> You are running CI …
```
> Remove analyzing code step in test job

- application/src/main/resources/extensions/role-template-authenticated.yaml
/kind bug
/area core
/milestone 2.12.0
This PR fixes the problem of unable to enable/disable 2FA for non-admin users. See https://github.com/halo-dev/halo/issues/5287 for more.
The problem is caused by <https://github.com/halo-dev/halo/pull/4737>.
Fixes https://github.com/halo-dev/halo/issues/5287
```release-note
None
```
> Fix the problem of unable to enable/disable 2FA for non-admin users

- console/packages/editor/src/dev/App.vue
- console/src/components/editor/DefaultEditor.vue
/kind bug
/area editor
/area console
在默认富文本编辑器解析文本时，使其保留空白符。
see https://prosemirror.net/docs/ref/#model.ParseOptions.preserveWhitespace
1. 输入一串文字，在其开始、结束、内容中分别键入空白字符。
2. 保存内容
3. 刷新页面，查看空白字符是否保留。
Fixes #5260 
```release-note
解决默认富文本编辑器内容刷新后空白字符丢失的问题
```
> fix: preserve white spaces when parsing the default editor

- application/src/main/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpoint.java
- application/src/main/resources/extensions/notification.yaml
- console/packages/api-client/src/models/post-status.ts
- console/packages/api-client/src/models/reason-type-info.ts
- console/packages/api-client/src/models/single-page-status.ts
- console/uc-src/modules/profile/tabs/NotificationPreferences.vue
/kind feature
/area core
/area console
为通知类型设置添加 UI 权限判断。
Fixes https://github.com/halo-dev/halo/issues/4728
```release-note
为通知类型设置添加 UI 权限判断。
```
> feat: add supports for ui permissions of notification reason type

- .github/actions/docker-buildx-push/action.yaml
/area core
This PR supports building Docker image with major version tag, e.g.: `halohub/halo:2`.
Fixes https://github.com/halo-dev/halo/issues/4976
```release-note
None
```
> Support building Docker image with major version tag

- application/src/main/java/run/halo/app/config/HaloConfiguration.java
- application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
- application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
/kind bugfix
/area core
修复事务未提交便触发控制器执行可能导致数据状态不正确的问题
**how to test it?**
1. 测试如 #5315 的问题是否还存在
2. 测试添加重名自定义模型对象会抛出异常且数据被回滚
Fixes #5315
```release-note
修复事务未提交便触发控制器执行可能导致数据状态不正确的问题
```
> fix: failure in data query due to reconciler triggered by uncommitted transaction

- application/src/main/java/run/halo/app/extension/gc/GcSynchronizer.java
- application/src/main/java/run/halo/app/extension/index/IndexedQueryEngineImpl.java
/kind bug
/area core
修复启动时 GcSynchronizer 没有精准过滤出所需数据导致内存占用会出现较高峰值的问题
Fixes #5324
```release-note
修复启动时 GcSynchronizer 没有精准过滤出所需数据导致内存占用会出现较高峰值的问题
```
> fix: possible incorrect result set obtained by Gc synchronizer when sartup

- application/src/main/java/run/halo/app/search/IndicesInitializer.java
/kind cleanup
/area core
移除启动时不必要的搜索引擎索引构建步骤
```release-note
移除启动时不必要的搜索引擎索引构建步骤
```
> chore: remove unnecessary indices build process for lucene on startup

- .github/actions/docker-buildx-push/action.yaml
- .github/actions/setup-env/action.yaml
- .github/workflows/halo.yaml
/kind cleanup
/area core
Recently, I noticed that there are a few warnings from GitHub actions, please see the annotations below:
```log
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, pnpm/action-setup@v2, actions/cache@v3, codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
According to [the instruction](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), I bump actions' verisons which have adapted to node 20.
However, only `pnpm/action-setup` hasn't adapted to node 20 yet, see https://github.com/pnpm/action-setup/issues/99 for more. …
> Bump actions' versions for muting warning from GitHub workflow

- Dockerfile
/area core
Last month, Eclipse has released [OpenJ9 0.42](https://projects.eclipse.org/projects/technology.openj9/releases/0.42.0) supported Java 21. It's time for Halo to run JRE 21.
Closes https://github.com/halo-dev/halo/issues/4929
```release-note
升级 Halo 运行环境至 JRE 21
```
> Upgrade Halo runtime environment to JRE 21

- .dockerignore
- ui/package.json
- ui/packages/api-client/package.json
- ui/packages/components/package.json
- ui/packages/editor/package.json
- ui/packages/shared/package.json
- ui/packages/ui-plugin-bundler-kit/package.json
/area ui
/kind cleanup
Rename console to ui in some files,
Ref https://github.com/halo-dev/halo/pull/5314
```release-note
None
```
> chore: rename console to ui in some files

- application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
- application/src/main/resources/extensions/extension-definitions.yaml
/kind cleanup
/area core
UsernamePasswordAuthenticator is a normal webfilter instead of authentication webfilter in security filter chain. There does not guarentee expected results due to different in execution order. So this PR changes UsernamePasswordAuthenticator to AuthenticationWebFilter for managing the filter by security filter chain.
By the way, these changes will not affect any plugins.
```release-note
None
```
> Move username-password authentication into security filter chain

- ui/uc-src/modules/contents/posts/PostEditor.vue
/kind bug
/area ui
在个人中心的文章功能中，点击设置时并不会重新获取最新的 Post 数据，进而导致点击保存时的 `version` 并非最新版本而报错。
此 PR 将在个人中心的文章页面点击设置时，额外增加一次获取最新的 Post 数据的请求，用于解决此问题。
1. 进入个人中心
2. 点击文章菜单
3. 点击右上角创建按钮
4. 在编辑器中随便输入内容
5. 点击保存
6. 修改文章的设置后点击保存。
7. 关闭设置框，再次打开设置框，然后点击保存。
8. 查看是否会出现无法保存的问题。
Fixes #5344 
```release-note
解决个人中心文章设置时报错的问题
```
> fix: fix the error when saving settings for posts in the uc

- application/src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
/area core
为插件静态代理资源增加缓存控制以减少不必要的请求
Fixes #5357
```release-note
为插件静态代理资源增加缓存控制以减少不必要的请求
```
> refactor: add cache control for reverse proxy resources

- application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSettings.java
- application/src/test/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSettingsTest.java
/kind bug
/area core
This PR ignored `email verified` status while 2FA was enabled.
Fixes https://github.com/halo-dev/halo/issues/5398
```release-note
修复开启两步验证但未配置 TOTP 可能无法登录的问题
```
> Fix the problem of being unable to login when 2FA was enabled but TOTP was not configured

- application/src/main/java/run/halo/app/plugin/PluginStartedListener.java
/kind bug
/area plugin
/area core
Fix the problem of updating plugin extensions incorrectly.
Fixes https://github.com/halo-dev/halo/issues/5394
```release-note
None
```
> Fix the problem of updating plugin extensions incorrectly

- api/src/main/java/run/halo/app/core/extension/User.java
- application/src/main/java/run/halo/app/core/extension/endpoint/StatsEndpoint.java
- application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
- application/src/main/java/run/halo/app/infra/DefaultInitializationStateGetter.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
- application/src/test/java/run/halo/app/infra/InitializationStateGetterTest.java
- ui/console-src/modules/system/users/UserList.vue
/area core
使用索引机制优化用户查询以提高性能
```release-note
使用索引机制优化用户查询以提高性能
```
> refactor: optimize user query using index

- api/src/main/java/run/halo/app/extension/index/query/LogicalQuery.java
- api/src/main/java/run/halo/app/extension/index/query/QueryFactory.java
- api/src/main/java/run/halo/app/extension/index/query/SimpleQuery.java
- api/src/test/java/run/halo/app/extension/index/query/QueryFactoryTest.java
- application/src/main/java/run/halo/app/extension/index/IndexedQueryEngineImpl.java
/area core
构建查询视图时只选择被使用到的索引字段
验证文章和附件列表的查询条件和排序条件不会报错即可
```release-note
优化查询视图构建只选择被使用到的索引字段构建查询视图
```
> refactor: only select the required index fields when build query index view

- application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
- application/src/main/java/run/halo/app/infra/exception/PluginDependencyException.java
- application/src/main/java/run/halo/app/plugin/YamlPluginDescriptorFinder.java
- application/src/main/resources/config/i18n/messages.properties
- application/src/main/resources/config/i18n/messages_zh.properties
/area core
This PR checks dependencies while installing and upgrading plugins.
Steps to test:
1. Prepare a plugin with dependencies.
```diff
apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
name: a-plugin
...
+  pluginDependencies:
+    app-store-integration: 1.*
```
2. Build the plugin.
3. Try to uninstall `app-store` plugin.
4. Install `a-plugin`.
5. See the result
Fixes #5345 
```release-note
插件安装和更新时检查依赖是否合法
```
> Check dependencies while installing and upgrading plugins

- api/src/test/java/run/halo/app/core/extension/notification/SubscriptionTest.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
- application/src/main/java/run/halo/app/notification/DefaultNotificationService.java
- application/src/main/java/run/halo/app/notification/ReasonNotificationTemplateSelectorImpl.java
- application/src/main/java/run/halo/app/notification/UserNotificationQuery.java
- application/src/main/java/run/halo/app/notification/endpoint/UserNotificationEndpoint.java
- application/src/test/java/run/halo/app/notification/DefaultNotificationCenterTest.java
- application/src/test/java/run/halo/app/notification/ReasonNotificationTemplateSelectorImplTest.java
- ui/console-src/modules/system/users/widgets/NotificationWidget.vue
- ui/packages/api-client/src/.openapi-generator/FILES
- ui/packages/api-client/src/api/api-halo-run-v1alpha1-user-api.ts
- ui/packages/api-client/src/api/api-notification-halo-run-v1alpha1-notification-api.ts
- ui/packages/api-client/src/base.ts
- ui/packages/api-client/src/configuration.ts
- ui/packages/api-client/src/models/sign-up-request.ts
- ui/uc-src/modules/notifications/Notifications.vue
/area core
使用索引机制优化通知和订阅查询以提高性能
how to test it
测试通知列表不报错即可
```release-note
使用索引机制优化通知和订阅查询以提高性能
```
> refactor: optimize notification and subscription query using index

- ui/src/components/editor/extensions/image/ImageView.vue
- ui/src/components/editor/extensions/video/VideoView.vue
/area editor
/area ui
/kind bug
在当前富文本编辑器中，当做出使图片、视频等组件需要重绘的事件时，会导致已经上传的文件重复上传。
本 PR 在上传完成后，将图片、视频组件 `file` 设置为空，用于解决此问题。
1. 使用复制、粘贴的方式在富文本编辑器中添加图片、视频
2. 将上传的图片、视频所处位置进行变更（需要向当前位置往后移动）。
3. 查看已上传的图片、视频是否会重复上传。
Fixes #5436 
```release-note
解决富文本编辑器中已上传的图片及视频会重复上传的问题
```
> fix: rich text editor reuploads images or videos repeatedly during redraws

- ui/src/components/editor/extensions/image/index.ts
- ui/src/components/editor/extensions/video/index.ts
/kind bug
/area editor
/area ui
使用默认编辑器时，当图片、视频中具有 `file` 属性时，进入编辑界面时会报错。此 PR 将不再从渲染后的 HTML 中获取 file 属性，并且在渲染 HTML 时，抛弃掉 file 属性用于解决这个问题。
测试图片上传、视频上传功能不受影响即可。
Fixes #5430 
```release-note
修复进入文章页面会偶现错误提示的问题
```
> fix: error editing post when img component has file attribute

- README.md
- gradle.properties
- ui/packages/api-client/package.json
- ui/packages/components/package.json
- ui/packages/editor/package.json
- ui/packages/shared/package.json
- ui/packages/ui-plugin-bundler-kit/package.json
/kind cleanup
/area core
Bump version to 2.14 to prepare for developing 2.14. This always happens after new version is released.
```release-note
None
```
> Prepare for developing 2.14

- SECURITY.md
/kind cleanup
Not long ago, we announced the cessation of maintenance for 1.x at <https://www.halo.run/archives/halo-1.x-eol>. So we also need to to synchronize changes to security policies.
```release-note
None
```
> Mark the security policy for version 1.x as unsupported

- ui/packages/editor/src/extensions/table/index.ts
/area editor
/area ui
/kind feature
为默认富文本编辑器中的表格，增加全选快捷键。具体操作逻辑如下：
1. 当光标处于表格中单元格内时，按 `Mod + a` 全选快捷键后，若未选中当前单元格，则选中单元格。
2. 若其中包含有其他影响全选快捷键的组件，则以组件自身为准，例如代码块中的全选。
3. 若已经选中单元格，则再次按全选快捷键，选中整个表格。
4. 若已经选中表格，则再按全选快捷键不会触发其他全选事件。
按照操作逻辑测试全选快捷键逻辑是否无误。是否与其他快捷键产生冲突。
Fixes #5438 
```release-note
为富文本编辑器中的表格组件增加全选快捷键
```
> feat: add select all shortcut function to the table

- api/src/main/java/run/halo/app/extension/index/query/And.java
- api/src/test/java/run/halo/app/extension/index/query/AndTest.java
/kind bug
/area core
修复了索引查询使用含有 OR 条件嵌套 AND 条件时若匹配数据集间无交集导致的查询结果不正确的问题
如伪查询：`or(query, and(otherQuery1, otherQuery2))`
问题描述：当 `query` 匹配的结果与 `and(otherQuery1, otherQuery2)` 匹配的结果无交集时 and 会将自身不匹配的数据剔除导致 `query` 无法匹配到而出现缺少数据的问题
```release-note
None
```
> fix: query mismatch with non-intersecting OR and nested AND condition

- application/src/main/java/run/halo/app/notification/EmailNotifier.java
/kind bug
/area core
更新邮件模板中查看通知的链接
Fixes https://github.com/halo-dev/halo/issues/5458
```release-note
None
```
> chore: update the link to view notifications in the email template

- ui/packages/editor/src/extensions/link/index.ts
/area editor
/area ui
将默认富文本编辑器中的链接中的 rel 属性由默认的 `noopener noreferrer nofollow` 属性改为 null，优化 SEO 。
查看使用默认富文本编辑器创建的链接，其 rel 属性是否不再是 `noopener noreferrer nofollow`
Fixes #5328 
```release-note
移除默认富文本编辑器中链接的 nofollow 等属性，优化 SEO。
```
> pref: remove nofollow from the default editor link

- ui/console-src/modules/contents/attachments/composables/use-attachment-group.ts
- ui/src/formkit/inputs/attachment-group-select.ts
/area ui
/kind bug
/milestone 2.14.0
为附件分组设置默认排序规则（按照创建时间升序），和 2.13.0 版本之间保持一致。
Fixes https://github.com/halo-dev/halo/issues/5429
测试方式：
1. 创建若干附件分组。
2. 观察排序是否符合预期。
```release-note
修复附件管理中的分组排序不固定的问题。
```
> fix: default sort policy of attachment groups

- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
/kind feature
/milestone 2.14.0
附件管理的排序功能支持按照文件名排序。
Fixes https://github.com/halo-dev/halo/issues/5028
测试方式：
1. 上传若干附件。
2. 测试根据文件名降序/升序功能是否符合预期。
```release-note
附件管理的排序功能支持按照文件名排序。
```
> feat: attachments supports sorting by display name

- api/build.gradle
- application/build.gradle
/kind chore
/area core
I get the following errors when I develop Halo in JDK 21:
```bash
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':application:bootRun'.
> Could not resolve all dependencies for configuration ':application:runtimeClasspath'.
> Failed to calculate the value of task ':application:compileJava' property 'javaCompiler'.
> No matching toolchains found for requested specification: {languageVersion=17, vendor=any, implementation=vendor-specific} for MAC_OS on aarch64.
> No locally installed toolchains match and toolchain download repositories have not been configured.
```
This PR removes the Java toolchain configuration and adds source and target compatibility to Java 17, allowing developers to develop Halo in Java …
> Set source and target compatibility to Java 17

- application/src/main/java/run/halo/app/content/comment/ReplyQuery.java
- application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
- application/src/main/java/run/halo/app/core/extension/endpoint/ReplyEndpoint.java
- application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java
- application/src/main/java/run/halo/app/theme/finders/CommentPublicQueryService.java
- application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
- application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImplTest.java
- application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
- ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-comment-api.ts
- ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-reply-api.ts
- ui/packages/api-client/src/models/plugin-status.ts
- ui/packages/api-client/src/models/tag-status.ts
/area core
使用索引机制优化回复功能的查询以提高查询速度
```release-note
使用索引机制优化回复功能的查询以提高查询速度
```
> refactor: optimize reply queries using index mechanisms

- ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
- ui/console-src/modules/contents/posts/components/PostSettingModal.vue
/kind bug
/area ui
解决文章、页面中无法手动填写发布日期的问题
测试文章设置与页面设置中的发布日期是否能够使用键盘填写。
需要同步测试其他设置项是否正常。
Fixes #5389 
```release-note
解决文章设置及页面设置中无法手动填写发布日期的问题
```
> fix: unable to manually fill in the publish time

- ui/packages/editor/src/extensions/link/index.ts
/kind bug
/area editor
/area ui
在默认的富文本编辑器中，使用了 [tiptap link](https://github.com/ueberdosis/tiptap/blob/b3ef574f3dd92852bc4dac24a82eb360db96c9c3/packages/extension-link/src/link.ts#L127C3-L135C5) ，而其中的 renderHTML 会对 href 进行处理，但当链接为纯数字的时候，`HTMLAttributes.href` 将不会有 `startsWith` 方法。
此 PR 将在解析 renderHTML 时，将 `HTMLAttributes.href` 转为 string，进而解决这个问题。
测试使用默认富文本编辑器时，编写一个链接，并将其设置为纯数字。
刷新页面，查看是否具有报错。
Fixes #5478 
```release-note
解决在默认富文本编辑器中当链接为纯数字时报错的问题
```
> fix: error occurs when the link is purely numerical

- api/src/main/java/run/halo/app/extension/index/query/QueryFactory.java
/area core
撤销 https://github.com/halo-dev/halo/pull/5453/files#diff-0577b8395b1acb8e87aff2150dfe0bd15b6768c433d73d9cf43ced91d8debc4cR123 中对 And query 返回值类型的更改 这会导致插件中用到这个方法的地方出现类型不兼容问题
see also https://github.com/halo-sigs/plugin-moments/issues/89
```release-note
None
```
> revert: changes to the return value type of And query

- ui/console-src/layouts/BasicLayout.vue
- ui/console-src/modules/system/overview/Overview.vue
- ui/console-src/modules/system/overview/module.ts
- ui/src/locales/en.yaml
- ui/src/locales/es.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
将原来的 Actuator 页面改为 Overview。
Fixes #5508 
```release-note
None
```
> chore: redefine the actuator page as the overview page

- application/src/main/resources/extensions/role-template-notification.yaml
- application/src/main/resources/extensions/role-template-setting.yaml
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind bug
/area core
修复分配通知器权限时一片空白的问题
- 隐藏了原先权限中展示的通知器配置权限选项
- 系统设置的权限中依赖了通知器配置权限,但需要有系统设置管理权限才会展示通知配置的 Tab
Fixes #5492
```release-note
修复仅拥有通知器配置权限时无法修改配置的问题
```
> fix: missing notifier descriptors permissions in notification role template

- application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
- application/src/main/java/run/halo/app/theme/finders/CommentPublicQueryService.java
- application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
- application/src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
- application/src/main/java/run/halo/app/theme/finders/vo/CommentWithReplyVo.java
/kind feature
/area core
主题端评论列表支持同时获得评论数据
Resolves #5435
```release-note
主题端评论列表支持同时获得评论数据
```
> feat: add support for fetching replies alongside comment list

- application/src/main/resources/extensions/system-setting.yaml
/area core
/milestone 2.14.0
improve the help tips for system setting options
Fixes #5513 
```release-note
完善系统设置选项的帮助提示。
```
> feat: improve the help tips for system setting options

- application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
/kind bug
/area core
修复主题测评论列表顺序不一致的问题
此问题由 #5505 导致,开启了同时返回回复后,评论列表的顺序出现问题
```release-note
None
```
> fix: sequence inconsistency in the comment list on the theme side

- ui/src/components/editor/components/InlineBlockBox.vue
- ui/src/components/editor/extensions/audio/AudioView.vue
- ui/src/components/editor/extensions/image/ImageView.vue
- ui/src/components/editor/extensions/video/VideoView.vue
/kind bug
/area ui
/area editor
解决默认编辑器中，行内块元素 `image`、`video` 及 `audio` 由于行内块导致其下方有额外一行的问题。
查看默认编辑器中上述组件是否还会出现在下方有额外空行的问题。
Fixes #5145 
```release-note
解决默认编辑器行内块元素下具有额外空行的问题
```
> fix: an extra line is added to the inline block

- ui/src/formkit/inputs/category-select/CategorySelect.vue
- ui/src/formkit/inputs/tag-select/TagSelect.vue
/area ui
在 `TagSelect` 与 `CategorySelect` 组件中，当搜索的同时允许进行创建新的分类或标签。
测试在搜索标签或者分类时，能否创建新的标签或者分类
Fixes #4660
```release-note
在搜索标签或分类的同时允许进行创建新的分类或标签
```
> pref: create while searching for tags or categories

- ui/packages/editor/src/components/Editor.vue
/kind bug
/area editor
在默认富文本编辑器下，当滚动时有概率会使页面小于正常大小。在文章最底部使用 AI 插件更加容易复现。
测试文章滚动时是否会小于正常大小，推荐在文章最底部使用 AI 插件来复现和测试。
Fixes #3853 
```release-note
修复文章编辑页面出现多个滚动条导致的页面高度样式问题。
```
> fix: duplicate scroller issue in post edit page

- ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
- ui/package.json
- ui/pnpm-lock.yaml
- ui/src/components/upload/UppyUpload.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
/kind feature
为上传附件的组件添加基本的图片编辑功能。
Fixes #5583 
```release-note
为上传附件的组件添加基本的图片编辑功能。
```
> feat: add image editor feature for attachment upload component

- ui/src/vite/config-builder.ts
/area ui
对 UI 的部分依赖进行分包处理。改动之后，如果下次构建 Halo，而这些依赖没有进行变更，那么 vendor 的 hash 后缀就不会变更，用户在升级之后这些依赖也可以有效命中缓存。
```release-note
对 UI 的部分依赖进行分包处理。
```
> chore: create shared common chunks during the ui build

- ui/console-src/modules/contents/posts/PostList.vue
/kind bug
/area ui
修复当选中首个文章设置时，点击上一个还可以继续修改 `page` 的问题。
测试选中首个文章设置之后，点击上一个是否不再修改 `page` 值
Fixes #5475 
```release-note
修复在文章列表设置中可以无限点击上一个的问题
```
> fix: selecting the previous post leads to a negative page

- ui/console-src/modules/system/plugins/PluginList.vue
- ui/console-src/modules/system/plugins/components/PluginInstallationModal.vue
- ui/console-src/modules/system/plugins/components/PluginListItem.vue
/area ui
优化插件安装弹框组件的渲染时机，改为在未打开时不进行渲染，可以避免一些不必要的请求，尤其是在安装了应用市场插件之后。
Fixes #5573 
测试插件安装和升级功能是否正常即可。
```release-note
优化插件安装弹框组件的渲染时机，避免不必要的请求。
```
> refactor: rendering conditions for plugin installation components

- ui/src/components/editor/DefaultEditor.vue
- ui/src/components/editor/components/EditorLinkObtain.vue
- ui/src/components/editor/extensions/image/index.ts
- ui/src/components/editor/utils/upload.ts
/kind bug
/area ui
在个人中心，使用默认富文本编辑器上传附件库时，由于在 UC 中不存在附件库列表，因此会出现错误。
本 PR 通过对默认富文本编辑器上传组件进行调整，调整如下：
1. 当不具有 uc 和 system 的附件权限时，用户仅能通过链接插入图片、音频等，且不允许拖拽和粘贴上传。
2. 当用户具有 uc 但没有 system 的附件权限时，用户可以通过拖拽和粘贴的方式上传，但不允许通过附件库上传。
3. 当用户具有 system 附件权限时，允许通过所有方式（上传、附件库、链接、拖拽和粘贴）进行上传。
测试默认富文本编辑器中，用户在不同附件库权限下上传图片是否能够按照逻辑正常处理。
Fixes #5581
```release-note
修复在个人中心中使用默认富文本编辑器的附件库而导致的报错问题
```
> fix: error occurs when opening attachment library in the uc

- ui/packages/editor/docs/extension.md
- ui/packages/editor/src/extensions/draggable/index.ts
- ui/packages/editor/src/types/index.ts
/kind bug
/area editor
解决在默认编辑器中，插件扩展 getDraggable 方法可能无效的问题。向 handleDrop 中添加属性 `selection`，方便插件对当前拖拽元素进行处理。
部分插件拖拽之后可能无效果，此时需要插件自行实现 `handleDrop` 方法来处理拖拽后的情况。
测试 getDraggable 方法是否正常。插件中使用此方法是否显示拖拽图标。
Fixes #5208 
```release-note
解决默认编辑器 getDraggable 在部分插件中失效的问题。
```
> fix: resolving the issue of the draggable extension not working in the editor

- ui/console-src/modules/contents/pages/SinglePageEditor.vue
- ui/console-src/modules/contents/posts/PostEditor.vue
- ui/uc-src/modules/contents/posts/PostEditor.vue
/area ui
编辑文章匹配编辑器类型时，忽略大小写。
Fixes https://github.com/halo-dev/halo/issues/5597
```release-note
None
```
> refactor: ignore case when matching editor raw types

- ui/console-src/router/guards/auth-check.ts
/kind bug
/area ui
修复当角色勾选禁止访问 Console 后，redirect_uri 参数无效的问题
测试角色禁止访问 console 时，当链接中携带 redirect_uri 参数，能否正常跳转
Fixes #5417 
```release-note
修复当角色禁止访问 Console 后，redirect_uri 参数无效的问题
```
> fix: wrong router navigation when redirect to /uc

- application/src/main/java/run/halo/app/content/AbstractContentService.java
- application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
- application/src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
- application/src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
- application/src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
/area core
减少文章更新因版本号冲突而失败的次数
Fixes #5579
```release-note
None
```
> refactor: reduce the number of failures due to conflict post update

- application/src/main/resources/extensions/attachment-local-policy.yaml
/area core
/milestone 2.14.0
在 Halo 完成动态数据的 i18n 之前，使用中文描述存储策略名称。
Ref https://github.com/halo-dev/plugin-s3/pull/128
```release-note
将默认存储策略模板的显示名称改为中文
```
> chore: update display name of default attachment policy

- ui/src/components/form/AnnotationsForm.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
默认隐藏自定义元数据表单，通常这不会让用户自行修改，默认显示反而会给使用者造成心智负担。
Fixes https://github.com/halo-dev/halo/issues/5439
```release-note
默认隐藏文章设置等界面的自定义元数据表单。
```
> refactor: hide the custom annotations form by defaults

- api/src/main/java/run/halo/app/core/extension/content/Comment.java
- application/src/main/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImpl.java
- application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceIntegrationTest.java
/kind feature
/area core
see https://github.com/halo-dev/plugin-comment-widget/issues/97
Fixes #5641 
```release-note
评论数据返回邮箱地址 hash 值以便生成默认头像
```
> feat: add gravatar url into annotation of spec of comment for anonymous

- OWNERS
更新 Prow 的 OWNERS 中关于 reviewers 的配置
```release-note
None
```
> chore: update reviewers for OWNERS file

- ui/console-src/modules/contents/posts/tags/TagList.vue
- ui/console-src/modules/contents/posts/tags/components/TagListItem.vue
- ui/console-src/modules/contents/posts/tags/composables/use-post-tag.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
使用分页列表的形式重新展示文章标签页，移除原有的 grid 形式。
查看文章标签页面的分页列表功能显示是否正常。
完成增、删、改之后是否能够正常回显。
Fixes #5415 
```release-note
使用分页列表的形式重构文章标签页 UI
```
> refactor: post tag management page

- ui/packages/editor/src/extensions/paragraph/index.ts
- ui/packages/editor/src/extensions/search-and-replace/index.ts
- ui/packages/editor/src/locales/en.yaml
- ui/packages/editor/src/locales/zh-CN.yaml
/kind feature
/area editor
此 PR 为默认富文本编辑器中的 P 标签设置了 `line-height` 属性，因此可以支持为某一行设置行高。
测试行高功能是否正常。测试在不同组件下功能是否正常。
Fixes #5660 
```release-note
为默认富文本编辑器增加行高设置
```
> feat: add line-height setting feature for the default editor

- application/src/main/resources/extensions/system-setting.yaml
/area core
Fixes #5688 
```release-note
当未开启允许注册选项时，隐藏注册相关的其他选项。
```
> feat: hide registration-related options when allowRegistration is disabled

- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/console-src/modules/contents/attachments/components/AttachmentDetailModal.vue
/kind bug
/area ui
修复由于 modal 延迟 200ms 所导致的数据可能为空的问题。
See #5078 
反复点击并关闭附件库详情弹窗，查看是否会有空数据的问题
Fixes #5689 
```release-note
修复附件详情弹窗可能无法显示数据的问题
```
> fix: the details of the attachment may be empty

- ui/packages/editor/src/dev/App.vue
- ui/packages/editor/src/extensions/clear-format/index.ts
- ui/packages/editor/src/extensions/index.ts
- ui/packages/editor/src/locales/en.yaml
- ui/packages/editor/src/locales/zh-CN.yaml
- ui/src/components/editor/DefaultEditor.vue
/kind feature
/area editor
为默认富文本编辑器添加清除格式的功能。快捷键为 `Mod + \`。
输入文本，使用加粗、链接、斜体等 mark 相关功能，之后使用清除格式，查看格式是否被清除。
Fixes #5684 
```release-note
为默认富文本编辑器添加清除格式的功能。
```
> feat: add the clear format function to the default rich text editor

- ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
- ui/console-src/modules/contents/posts/components/PostSettingModal.vue
- ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
/area ui
限定文章或页面中的发布日期中的年份为四位数，方便用户输入四位年份之后自定跳转至月份。
测试在 `chrome` 上输入四位年份之后，是否会自动跳转至月份。
Fixes #5630 
```release-note
限定文章或页面中的发布日期中的年份为四位数
```
> pref: limit the datetime year of the post or page to four digits

- ui/packages/editor/package.json
- ui/packages/editor/src/extensions/link/LinkBubbleButton.vue
- ui/packages/editor/src/extensions/link/index.ts
- ui/pnpm-lock.yaml
- ui/src/components/editor/DefaultEditor.vue
/area editor
/area ui
优化默认富文本编辑器中自动创建链接的逻辑。
- 移除了粘贴文本时，如果文本为链接则会自动转为链接的问题。
- 移除输入链接文本之后回车，会自动转化为链接的问题。
- 新增当选中的文本内容为链接时，点击链接按钮，将会自动转化选中的文本为链接。
在富文本编辑器中，测试如下场景：
1. 在浏览器地址栏复制一个链接，粘贴后不会再转为链接，而是一个普通文本。
2. 输入一段链接文本，按回车后是否不会再被转为链接。
3. 选中一段可以被解析为链接的地址，选中此地址，点击链接按钮，此地址是否会被默认转为链接。
Fixes #5653 
```release-note
优化默认富文本编辑器中文本自动转为链接的相关逻辑
```
> pref: optimize the rich text editor link paste logic

- ui/packages/editor/src/components/EditorHeader.vue
- ui/packages/editor/src/components/toolbar/ToolbarItem.vue
/area editor
优化默认富文本编辑器中，顶部工具栏子菜单的弹出方式，将原有的鼠标移入弹出改为点击左键弹出。并且为了显示效果，将会在具有子菜单的工具栏后方显示额外的下拉图标。
查看顶部工具栏子菜单弹出方式是否已改变。（插入组件未进行更改，仍旧保持原有鼠标移入弹出方式）
Fixes #5668 
```release-note
优化默认富文本编辑器中顶部工具栏的子菜单弹出方式
```
> pref: optimize the pop-up mode of toolbar submenu

- ui/packages/editor/src/extensions/code-block/code-block.ts
/kind bug
/area editor
在编写多行文本后，粘贴代码块时，会出现粘贴的内容插入错误，其与代码块分割开。
[例如 #5736 中的示例所示](https://github.com/halo-dev/halo/assets/44745967/4b1ef8dc-60bf-47fd-b64d-23b0d6537d9e)
在本 PR 中，在创建 CodeBlock 时，将 Text 转为 `TextNode` 后，一同传入作为 `CodeBlock` 的 content。
另外为了保证插入代码块之后，光标处于代码块中，将会从插入位置的 from 开始往文档顶部搜索。
测试示例中的场景下，代码块插入是否正常。
测试在代码块前后放入其他代码块或者其他块，插入代码块后光标是否在代码块中。
Fixes #5736 
```release-note
修复默认编辑器中粘贴代码块会出现错行的问题
```
> fix: code block content insertion location error

- ui/packages/editor/src/extensions/text-align/index.ts
- ui/packages/editor/src/extensions/text/index.ts
- ui/packages/editor/src/locales/en.yaml
- ui/packages/editor/src/locales/zh-CN.yaml
/area editor
本 PR 对富文本编辑器中工具栏和冒泡菜单进行精简。
- 对默认富文本冒泡菜单及顶部工具栏相同类型的功能进行了折叠。
- 删除在 text 的冒泡菜单中，不属于当前选中文本的功能，例如转换为代码块等，这些实际上是段落的功能，并非是文本的功能。而 textAlign 目前也仅仅用在标题和行上，因此也移除。
查看默认富文本编辑器工具栏中，折叠的功能是否正常。选中文本，查看文本中是否不包含段落相关的功能。
Fixes #5669 
```release-note
对默认富文本编辑器中的工具栏进行折叠及精简优化。
```
> pref: optimize the toolbar space and fold the same type of function

- application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
- application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
- application/src/main/java/run/halo/app/notification/DefaultNotificationCenter.java
/kind bug
/area core
修复分页遍历数据的查询参数
此问题由 #5504 和 #5656 重构导致，如果数据超过分页限制会导致无法结束的致命问题
```release-note
None
```
> fix: paginated data queries by expand

- platform/application/build.gradle
/kind cleanup
/area core
/area plugin
[pf4j 3.11.0](https://github.com/pf4j/pf4j/releases/tag/release-3.11.0) has some critical bugs, such as https://github.com/pf4j/pf4j/issues/576  and https://github.com/pf4j/pf4j/issues/574, which might lead to unpredictable behaviour in Halo.
See https://github.com/halo-dev/halo/issues/5615#issuecomment-2061543808 for more.
```release-note
降级 PF4J 至 3.10.0
```
> Downgrade pf4j to 3.10.0

- ui/console-src/modules/system/users/UserDetail.vue
- ui/console-src/modules/system/users/tabs/Detail.vue
- ui/packages/shared/src/index.ts
- ui/packages/shared/src/states/user-tab.ts
- ui/packages/shared/src/types/plugin.ts
- ui/uc-src/modules/profile/Profile.vue
- ui/uc-src/modules/profile/tabs/Detail.vue
- ui/uc-src/modules/profile/tabs/NotificationPreferences.vue
/area ui
/kind feature
为 Console 的用户详情页面的选项卡和个人中心的个人资料页面选项卡添加扩展点，支持通过插件扩展选项卡。
todo:
Fixes https://github.com/halo-dev/halo/issues/5745
可以使用 [plugin-starter-1.3.2-SNAPSHOT.jar.zip](https://github.com/halo-dev/halo/files/15059291/plugin-starter-1.3.2-SNAPSHOT.jar.zip) 进行测试。
```release-note
为 Console 的用户详情页面的选项卡和个人中心的个人资料页面选项卡添加扩展点
```
> feat: add extension points for user detail tab

- application/src/main/java/run/halo/app/core/extension/reconciler/CommentReconciler.java
- application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
/kind bug
/area core
修复由于没有更新 observed version 导致评论和回复的 reconciler 执行次数控制没有生效的问题
```release-note
None
```
> fix: comment and reply observed version for status

- ui/src/utils/api-client.ts
/area ui
优化 Console 的请求异常提示，如果异常不满足原有的判断逻辑，最终将提示 status + statusText，不再显示未知错误，方便使用者根据异常提示进行排查。
Fixes https://github.com/halo-dev/halo/issues/5739
我的测试方式：
使用 Caddy 模拟请求异常：
```
:9000
encode gzip
@blocked {
path /apis/content.halo.run/v1alpha1/posts/**
}
respond @blocked 413
reverse_proxy 127.0.0.1:8090
```
```release-note
优化 Console 的请求异常提示，方便异常排查。
```
> feat: toast the http request error

- ui/console-src/modules/system/users/tabs/Detail.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
- ui/uc-src/modules/profile/tabs/Detail.vue
/area ui
在个人中心的个人资料页面添加邮箱已验证的标识，方便用户知晓。
```release-note
在个人中心的个人资料页面添加邮箱已验证的标识。
```
> feat: add verified badge for email field in profile detail page

- application/src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
- application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
- application/src/test/java/run/halo/app/content/comment/CommentServiceImplIntegrationTest.java
- application/src/test/java/run/halo/app/content/comment/ReplyServiceImplIntegrationTest.java
/area core
优化评论和回复删除，只有删除第一页后才会再次查询避免数据堆积
```release-note
None
```
> refactor: optimize comment and reply deletion

- ui/packages/editor/src/extensions/table/index.ts
- ui/packages/editor/src/extensions/table/util.ts
/kind feature
/area editor
为默认编辑器表格增加 `Tab` 与 `Shift-Tab` 切换至上一个单元格或下一个单元格。具体功能如下：
1. 使用 Tab 快捷键从左向右切换至下一个单元格，当光标在最后一个单元格时，使用 Tab 键新建一行并跳转至新一行的第一个单元格。
2. 使用 Shift + Tab 快捷键从右向左来切换至上一个单元格。
测试在默认编辑器中 `Tab` 快捷键切换单元格是否生效。
测试在合并单元格等各种表格操作下，切换单元格是否生效。
Fixes #5771 
```release-note
为默认编辑器表格增加 Tab 快捷键切换单元格的功能
```
> feat: add tab shortcut function to the default editor table

- ui/src/components/editor/extensions/upload/index.ts
/kind bug
/area ui
/area editor
在进行图片上传的前置处理中，将剪切板属性中的 `text/plain` 类型与 `text/html` 类型进行过滤，用于解决将 Excel 表格粘贴至默认编辑器时，会导致其变为了图片而不是表格。
从 Excel 中复制一个表格，在默认编辑器中使用粘贴，查看其是否成功粘贴为表格而不是图片。
Fixes #5761 
```release-note
解决 Excel 表格粘贴至默认编辑器后会变为图片的问题。
```
> fix: excel tables copied into editor become images

- application/src/main/resources/extensions/role-template-tag.yaml
/kind bug
/area ui
补充 #5593 中缺少的 `api.console.halo.run` 权限。用于解决具有文章列表权限的用户，访问标签列表时提示无权限的问题
创建一个具有文章列表查看权限的用户，是否能够访问到标签列表。
Fixes #5814
```release-note
None
```
> fix: the post admin does not have tag list permissions

- application/src/main/resources/extensions/role-template-post.yaml
- application/src/main/resources/extensions/role-template-singlepage.yaml
/kind bug
/area core
修复拥有文章管理权限的用户无法正常使用版本历史的问题
Fixes #5815 
```release-note
修复拥有文章管理权限的用户无法正常使用版本历史的问题
```
> fix: permissions for post content versions

- ui/console-src/modules/contents/pages/SinglePageSnapshots.vue
- ui/console-src/modules/contents/pages/components/SnapshotListItem.vue
- ui/console-src/modules/contents/posts/PostSnapshots.vue
- ui/console-src/modules/contents/posts/components/SnapshotListItem.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
/kind feature
支持清理所有无用的文章历史快照，仅保留已发布、基础版本、正在编辑的版本。
Fixes https://github.com/halo-dev/halo/issues/5817
需要在历史版本页面测试清理功能是否符合预期。
```release-note
None
```
> feat: add cleanup feature for post snapshots

- Dockerfile
When traefik is used, the host cannot be accessed to 8090 by default after being configured. Therefore, you need to configure loadbalance. The process is complicated, so specify the expose port
当使用 traefik 时， 配置完 host 后无法直接的访问到对应的服务， 需要额外的配置service， loadbalance.port 才能， 所以建议增加一个 expose port， 指定下默认的服务端口
```release-note
None
```
> chore: specify expose port in dockerfile

- ui/console-src/modules/system/plugins/components/PluginListItem.vue
- ui/console-src/modules/system/plugins/composables/use-plugin.ts
/area ui
/kind bug
/milestone 2.15.0
修复插件异常启动时，指示器显示不正确的问题。
Fixes https://github.com/halo-dev/halo/pull/5520
```release-note
None
```
> fix: show plugin error message

- ui/build.gradle
/kind cleanup
/area core
There are too many unrelated results from node_modules folders when we try to search in files using IDEA IDE. This PR adapts the IDEA IDE using Gradle plugin `idea` to reduce search results.
Before:
After:
```release-note
None
```
> Support excluding node_modules for idea IDE

- application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
- application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
- application/src/main/java/run/halo/app/plugin/SpringPluginManager.java
- application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
/kind bug
/area plugin
/area core
This PR resolves the problem that some plugins could not be used after upgrading dependent plugin.
Fixes https://github.com/halo-dev/halo/issues/5615
1. Install plugin [app-store](https://www.halo.run/store/apps/app-VYJbF)
2. Install plugin [backup](https://www.halo.run/store/apps/app-dHakX) and activate it
3. Disable plugin app-store
4. Check the features of plugin backup
5. Enable plugin app-store
6. Check the features of plugin backup
7. Upgrade plugin app-store with the any versions
8. Check the features of plugin backup
```release-note
修复因升级应用市场插件导致部分插件意外停止的问题
```
> Fix the problem that some plugins could not be used after upgrading dependent plugin

- api/src/main/java/run/halo/app/extension/Unstructured.java
- application/src/test/java/run/halo/app/extension/UnstructuredTest.java
/kind bug
/area core
修复对 Unstructured 的 metadata 进行更改不会被应用的问题
```release-note
修复插件定义的权限没有在插件详情页显示的问题
```
> fix: changes to Unstructured metadata do not take effect

- application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
- application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
- application/src/main/java/run/halo/app/plugin/SpringPlugin.java
- application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
/kind bug
/area core
/area plugin
This PR refactors plugin running state change method to resolve the problem of not being able to initialize preset plugins due to too small gap between installation and enabling.
Fixes https://github.com/halo-dev/halo/issues/5867
```release-note
解决初始化时无法正常启用插件的问题
```
> Fix the problem of not being able to initialize preset plugins

- ui/packages/components/src/components/dialog/Dialog.vue
/kind bug
/area core
/area ui
dialog 组件在标题内容过多的时候，icon 会很小，样式出现错位！
```release-note
修复当 Dialog 标题过长时，提示图标的样式问题。
```
> fix: style issue of dialog component icon

- ui/packages/components/src/components/alert/Alert.vue
/kind feature
/area core
/area ui
alert 组件增加标题插槽，可以更好的自定义标题内容！
```release-note
为 VAlert 组件增加标题插槽
```
> feat: Add title slot to alert component

- ui/console-src/modules/system/roles/RoleDetail.vue
/kind bug
/area core
/area ui
用户角色详情页面，权限设置提示框关闭按钮不能关闭，增加对应关闭事件！
```release-note
用户-角色设置-权限设置提示框关闭按钮
```
> fix: remove close button for reserved alert in role detail page

- application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
- application/src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java
/area core
This PR fixes the problem where extensions were not changed but still updated. What we want is to not update the extension if it has not changed.
Before that, we update the version of extension manually while getting the latest extension, this will lead to change the type of metadata.version from int to long.See the code snippet below:
https://github.com/halo-dev/halo/blob/a629961e8de4c086490e821248b6fa9964caecdd/application/src/main/java/run/halo/app/extension/JSONExtensionConverter.java#L83
Now, we force update the versions using type Long.
```release-note
None
```
> Fix the problem where extensions were not changed but still updated

- api-docs/openapi/v3_0/aggregated.json
- application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
- ui/console-src/modules/contents/attachments/composables/use-attachment.ts
- ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-attachment-api.ts
- ui/src/locales/en.yaml
- ui/src/locales/es.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area core
/area ui
为 `/apis/api.console.halo.run/v1alpha1/attachments` 接口增加了 `accepts` 可选参数，用于根据附件的 `MediaType` 进行筛选。
为附件库增加通过文件的 MediaType 类型进行筛选的筛选项。
同时支持使用了 `CoreSelectorProvider` 组件的文件选择框的筛选。现在只会显示 `accepts` 所支持的文件。
测试 ui 端文件选择框的类型筛选是否正确有效。
测试使用了 `CoreSelectorProvider` 组件的 `accepts` 是否有效。
Fixes #5054
```release-note
附件库支持按文件类型进行过滤
```
> feat: support filtering attachments in the library by file media type

- api-docs/openapi/v3_0/aggregated.json
- application/src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
- application/src/main/resources/extensions/role-template-theme.yaml
- ui/console-src/modules/interface/themes/ThemeDetail.vue
- ui/packages/api-client/src/api/api-console-halo-run-v1alpha1-theme-api.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area core
/area theme
为主题管理增加在线清理缓存功能
Fixes #5440
```release-note
为主题管理增加在线清理缓存功能
```
> feat: add an API to invalidate theme template cache

- ui/packages/editor/src/extensions/table/index.ts
/kind bug
/area editor
目前表格在监听到滚动时，会重新设置 `TextSelection` 用于阴影的显示。
本 PR 将设置 `TextSelection` 更改为重新执行一次 `Transaction` 。这样可以解决在滚动时光标错位的问题。
编写表格时，测试当编写内容出现滚动条时，是否会导致文本错位。
测试滚动表格时，光标位置是否会发生改变。
Fixes #5924 
```release-note
解决默认编辑器中滚动表格时会导致光标变换的问题
```
> fix: cursor misalignment when scrolling through the table

- ui/packages/editor/src/extensions/table/table-cell.ts
- ui/packages/editor/src/extensions/table/table-header.ts
/kind bug
/area editor
默认编辑器中的表格**首行被合并单元格**之后，将会出现当前表在刷新之后宽度被重置为默认。此 PR 改正了计算宽度，使其首次刷新时，也能返回正确的数组。
1. 将表格首行使用合并单元格之后，改变表格宽度。
2. 刷新表格，查看表格宽度是否不再变为默认宽度。
Fixes #5767 
```release-note
解决默认编辑器中的表格首行合并单元格后会出现宽度重置的问题
```
> fix: incorrect column width calculation after merging cells in the table

- application/src/main/java/run/halo/app/security/session/InMemoryReactiveIndexedSessionRepository.java
/area core
当 session id 改变时清除原来的 session id 记录
```release-note
None
```
> refactor: original should be removed when session id changed

- application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
/area core
管理员回复评论或回复后自动通过审核
Fixes #5870
```release-note
管理员回复评论或回复后自动通过审核
```
> refactor: automatically approve comments or replies after admin replied it

- api/src/main/java/run/halo/app/extension/router/SortableRequest.java
/area core
为自定义模型 List API 添加默认排序
Fixes #5647
```release-note
为自定义模型 List API 添加默认排序
```
> refactor: add default sort for extension listing

- application/src/main/java/run/halo/app/notification/DefaultSubscriberEmailResolver.java
- application/src/test/java/run/halo/app/notification/DefaultSubscriberEmailResolverTest.java
/area core
邮件通知功能现在只向经过验证的邮箱地址发送通知匿名用户除外
Fixes #5722
```release-note
邮件通知功能现在只向经过验证的邮箱地址发送通知匿名用户除外
```
> refactor: email notifications are now sent only to verified email addresses

- application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
- application/src/test/java/run/halo/app/config/SecurityConfigTest.java
/area core
This PR ignores `includeSubdomains` for HSTS header. See https://github.com/halo-dev/halo/issues/4943 for more.
Fixes https://github.com/halo-dev/halo/issues/4943
```release-note
修复开启 HSTS 可能会导致未开启 HSTS 的子域名站点无法访问的问题
```
> Ignore includeSubdomains for hsts header

- ui/packages/editor/src/extensions/indent/index.ts
- ui/packages/editor/src/styles/base.scss
/kind bug
/area editor
移除使用 `Backspace` 进行缩进的功能。此功能会导致选中无序列表文本至起始位置时，按 `Backspace` 快捷键会导致无序列表解除当前层级。
测试从后往前选中无序列表文本至文本起始位置，然后按下 `Backspace` 快捷键。此时应当只删除文本而不会调整无序列表层级。
Fixes #5925 
```release-note
修复默认编辑器中列表使用 Backspace 快捷键删除选中文本的错误行为
```
> fix: deleting selected text in a list with the backspace key causes the list to revert

- ui/console-src/modules/interface/themes/components/ThemeListModal.vue
- ui/console-src/modules/interface/themes/components/list-tabs/InstalledThemes.vue
- ui/console-src/modules/interface/themes/layouts/ThemeLayout.vue
/area ui
优化主题管理弹窗的显示逻辑，改为在未打开弹窗组件的时候不渲染组件，减少不必要的请求。
before:
after:
```release-note
优化主题管理弹窗的显示逻辑，减少不必要的请求。
```
> refactor: logic of theme management modal

- ui/console-src/modules/contents/pages/SinglePageEditor.vue
- ui/console-src/modules/contents/pages/SinglePageList.vue
- ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
/area ui
优化页面设置弹窗的显示逻辑，改为在未打开弹窗组件的时候不渲染组件，减少不必要的请求。
```release-note
优化页面设置弹窗的显示逻辑，减少不必要的请求。
```
> refactor: logic of singlePage setting modal

- ui/console-src/modules/contents/posts/components/SnapshotContent.vue
/area ui
/kind bug
修复在文章版本历史内容预览中代码块颜色显示异常的问题。
Fixes https://github.com/halo-dev/halo/issues/5845
```release-note
修复在文章版本历史内容预览中代码块颜色显示异常的问题。
```
> fix: color style issue of code block in post content snapshot page

- ui/console-src/modules/system/roles/RoleDetail.vue
- ui/console-src/modules/system/roles/RoleList.vue
- ui/console-src/modules/system/roles/components/RoleEditingModal.vue
- ui/console-src/modules/system/users/UserList.vue
- ui/console-src/modules/system/users/components/GrantPermissionModal.vue
- ui/src/composables/use-role.ts
/area ui
优化和角色相关的对话框显示逻辑，减少不必要的渲染开销和请求。
```release-note
优化和角色相关的对话框显示逻辑，减少不必要的渲染开销和请求。
```
> refactor: improve code base of role-related

- api-docs/openapi/v3_0/aggregated.json
- api/src/main/java/run/halo/app/core/extension/Plugin.java
- api/src/main/java/run/halo/app/infra/Condition.java
- api/src/main/java/run/halo/app/infra/ConditionList.java
- application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
- application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
- application/src/main/java/run/halo/app/core/extension/service/PluginService.java
- application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
- application/src/main/java/run/halo/app/infra/exception/PluginDependenciesNotEnabledException.java
- application/src/main/java/run/halo/app/infra/exception/PluginDependentsNotDisabledException.java
- application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
- application/src/main/java/run/halo/app/plugin/PluginConst.java
- application/src/main/java/run/halo/app/plugin/SpringPluginManager.java
- application/src/main/resources/config/i18n/messages.properties
- application/src/main/resources/config/i18n/messages_zh.properties
- application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
- application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
- application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
- application/src/test/java/run/halo/app/infra/ConditionListTest.java
- ui/console-src/modules/system/plugins/components/PluginConditionsModal.vue
- ui/console-src/modules/system/plugins/components/PluginListItem.vue
- ui/console-src/modules/system/plugins/composables/use-plugin.ts
- ui/console-src/modules/system/plugins/tabs/Detail.vue
- ui/packages/api-client/src/models/condition.ts
- ui/packages/api-client/src/models/plugin-status.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area core
/area plugin
This PR wholly refactors plugin reconciliation to implement dependency mechanism.
Currently,
- If we disable plugin which has dependents, the plugin must wait for dependents to be disabled.
- If we enable plugin which has dependencies , the plugin must wait for dependencies to be enabled.
- If we upgrade plugin which has dependents, the plugin must request dependents to be unloaded. After the plugin is unloaded, the plugin must cancel unload request for dependents.
Fixes #5872 
```release-note
优化被依赖的插件的升级，启用和禁用
```
> Refactor plugin reconciliation for dependency mechanism

- ui/console-src/modules/system/plugins/PluginList.vue
/area ui
/kind feature
在插件数据管理列表页面路由中记录查询条件，可以保证在刷新页面或者切换路由返回时保留之前的查询状态。
需要测试：
1. 插件管理列表的所有筛选项是否可以正常工作。
```release-note
Console 端的插件管理列表支持在地址栏记录筛选条件。
```
> feat: record the plugin query conditions in the route query parameters

- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/console-src/modules/contents/attachments/components/AttachmentGroupBadge.vue
- ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
- ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
- ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
- ui/console-src/modules/contents/attachments/components/AttachmentPolicyBadge.vue
- ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
- ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
- ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
/area ui
优化附件分组、存储策略选择组件的 UI。
```release-note
优化附件分组、存储策略选择组件的 UI。
```
> refactor: improve ui/ux of attachment group and policy selector

- application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
- application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
- application/src/test/java/run/halo/app/security/authorization/AuthorityUtilsTest.java
/kind bug
/area core
/milestone 2.16.0
PAT could not be created or restored while logging in with remember-me due to lack of RememberMeAuthenticationToken check.
Fixes https://github.com/halo-dev/halo/issues/6000
1. Log in with remember-me
2. Create a PAT or restore a PAT
3. See the result
```release-note
None
```
> Fix the problem the PAT could not be created or restored while logging in with remember-me

- ui/console-src/modules/system/overview/Overview.vue
/area ui
/kind feature
在概览页面复制信息时，为主题和插件添加版本号。
示例：
```
- 外部访问地址: 
- 启动时间: 2024-05-29 15:51
- 版本: 2.16.0-SNAPSHOT
- 构建时间: 2024-05-29 15:51
- Git Commit: 6204472
- Java: OpenJDK Runtime Environment / 17.0.11+0
- 数据库: PostgreSQL / 15.2 (Debian 15.2-1.pgdg110+1)
- 操作系统: Mac OS X / 14.5
- 已激活主题: [Earth 1.8.0](https://github.com/halo-dev/theme-earth.git)
- 已启动插件:
- [静态网页服务 1.0.0-alpha.2](https://github.com/ruibaby/plugin-static-pages)
- [评论组件 2.10.0-SNAPSHOT](https://github.com/halo-dev/plugin-comment-widget)
- [OAuth2 认证 1.1.1](https://github.com/halo-sigs/plugin-oauth2)
- [增强备份（Backup IMproved） 1.0.0-SNAPSHOT](https://www.halo.run/store/apps/app-dHakX)
- [图库管理 1.3.0](https://github.com/halo-sigs/plugin-photos)
- [Markdown / HTML 内容块 …
```
> feat: add version for themes and plugins when copying overview information

- ui/package.json
- ui/pnpm-lock.yaml
/area ui
/kind bug
回退 `@uppy/xhr-upload` 的版本至 3.6.0，因为最新版本的 `@uppy/xhr-upload` 添加了重试机制和修改了错误异常的结构，并且当前重试参数并没有体现在文档和 API 中，所以暂时先回退至 3.6.0 以解决 https://github.com/halo-dev/halo/issues/6014
https://github.com/transloadit/uppy/blame/31cc47f3fb7513c82b887b429aa5f2a36eb4d593/packages/%40uppy/utils/src/fetcher.ts#L26
Fixes https://github.com/halo-dev/halo/issues/6014
需要测试：
1. 附件上传功能
2. 上传已安装的插件或者主题，观察是否有提示升级。
```release-note
None
```
> chore: revert @uppy/xhr-upload version to 3.6.0

- ui/console-src/modules/contents/attachments/components/AttachmentSelectorModal.vue
- ui/console-src/modules/contents/comments/components/CommentListItem.vue
- ui/console-src/modules/interface/themes/components/ThemeListModal.vue
- ui/console-src/modules/system/backup/Backups.vue
- ui/console-src/modules/system/plugins/PluginDetail.vue
- ui/console-src/modules/system/plugins/components/PluginInstallationModal.vue
- ui/console-src/modules/system/users/UserDetail.vue
- ui/packages/shared/src/types/plugin.ts
- ui/src/components/editor/DefaultEditor.vue
- ui/src/composables/use-editor-extension-points.ts
- ui/uc-src/modules/profile/Profile.vue
/area ui
/kind feature
优化 UI 部分的扩展点获取实现，让部分扩展点支持异步获取，之前的实现与文档不符。
比如：
```ts
import { definePlugin } from "@halo-dev/console-shared";
import axios from "axios";
export default definePlugin({
components: {},
routes: [],
extensionPoints: {
"attachment:selector:create": async () => {
const { data } = await axios.get(
"/apis/v1alpha1/fake.halo.run/attachments/selectors"
);
return data;
},
},
});
```
Fixes https://github.com/halo-dev/halo/issues/6008
```release-note
优化 UI 部分的扩展点获取实现，让部分扩展点支持异步获取。
```
> feat: enable asynchronous resolving for UI extension points

- ui/packages/components/src/components/dropdown/Dropdown.vue
/area ui
/kind bug
修复 Dropdown 组件自动销毁的问题，这可能导致部分插件在 Dropdown 中的组件无法正常渲染。
```release-note
None 
```
> fix: dropdown component auto-destruction issue

- application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
- application/src/main/java/run/halo/app/core/extension/service/PluginService.java
- application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
- application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
- application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
/kind bug
/area  core
/area plugin
/milestone 2.16.0
Before the PR, any user can generate bundle files by providing random query param `v` while requesting bundle files.
This PR refactors the whole bundle file generation method.
1. Do nothing if users provide arbitrary bundle file version
2. Better lock for writing bundle files if not exist
1. Request `http://localhost:8090/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.js?v=xyz` 
2. Check if the file `xyz.js` in folder `$TMPDIR/halo-plugin-bundle**`
```release-note
None
```
> Fix the problem that bundle files can be generated arbitrarily

- application/src/main/resources/extensions/system-configurable-configmap.yaml
/kind bug
/area core
补充缺失的系统设置默认值。
```release-note
修复系统设置未保存导致无法正常注册的问题
```
> fix: missing default values for system settings

- application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
/kind failing-test
/area core
I wrongly invoked `Arraylist#add`(probes) method in multi threads. So the unit test was unstable and might encounter the problem as follows:
```java
Expected :1
Actual   :0
<Click to see difference>
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:161)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:632)
at …
```
> Fix concurrent issue during bundle file concurrent generation testing

- ui/packages/components/src/components/tag/Tag.vue
/area ui
Fixes #5877 
```release-note
修复Tag Icon为空时，后台文章的Tag内容不居中
```
> fix: content offset caused by empty slot

- application/src/main/java/run/halo/app/theme/config/ThemeWebFluxConfigurer.java
/kind bug
/area core
When initialized for the first time, the folder `${halo.work-dir}/themes` does not exist, resulting in the `themes` path being ignored when invoking `themeRootResource.createRelative(themeName + "/templates/assets/");`. It works very well after restarting.
This PR fixes the problem by resolving theme resource directly rather than delegating to PathResourceResolver.
Fixes #6048 
```release-note
修复首次初始化后无法正常访问主题资源的问题
```
> Fix the problem that theme assets could not be found after the first initialization

- application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
- application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
/kind regression
/area plugin
This PR reverts changes of generating bundle resource version in <https://github.com/halo-dev/halo/pull/6028>.
Because the changes were adapted realtime change of bundle files for plugin developers in plugin development runtime mode, but I ignored it.
1. Try to start Halo in plugin development mode
2. Change and rebuild ui resources
3. Refresh console and check the result
```release-note
None
```
> Fix the problem that bundle files are not changed in development mode

- ui/src/components/editor/DefaultEditor.vue
/kind bug
/area editor
/area ui
当前为默认编辑器设置焦点的时机放在 `onMounted` 时，但此时默认编辑器可能还未加载成功且标题也为能成功加载，因此无法保证正确设置标题焦点。
当前 PR 将此时机放置在默认编辑器创建完成之后的 `onCreate` ，此时将能够保证焦点设置成功。
测试默认编辑器能否正常设置标题或内容的焦点。
Fixes #6060 
```release-note
解决使用默认编辑器时无法正确设置焦点的问题
```
> fix: default editor focus setting failure

- ui/packages/editor/src/extensions/heading/index.ts
/kind bug
/area editor
当前在编辑器中粘贴内容后，如果不修改任意标题或新增标题，则无法为当前标题自动生成标题 ID，进而导致锚点失效。
本 PR 将在编辑器触发内容更改后，如果是粘贴的内容，则直接触发生成标题 ID。
新建一篇文章并粘贴一段带标题的内容后直接发布。
查看发布后的文章是否可以在主题端使用锚点跳转。
Fixes #6056 
```release-note
解决在默认编辑器中粘贴的内容无法生成标题 ID 的问题
```
> fix: ensure pasted content auto-generates title id

- ui/packages/editor/src/extensions/code-block/code-block.ts
/area editor
将默认编辑器中代码块的缩进由一个制表符(\t)，更改为两个空格` {2}`。
测试使用 `Tab` 即 `Shift + Tab` 缩进时，是否每次缩进两个空格而不是一个制表符。
```release-note
优化默认编辑器代码块缩进为两个空格。
```
> pref: default code block indentation from Tab to 2 Spaces in editor

- ui/console-src/modules/interface/themes/ThemeDetail.vue
- ui/console-src/modules/interface/themes/composables/use-theme.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area ui
为主题增加导入及导出配置的功能。
测试主题导入及导出功能是否正常可用。
测试当前主题下的不同版本导入导出后数据是否正常。
测试在当前主题下使用其他主题导出的配置是否会报错。
Fixes #1073 
```release-note
为单个主题配置增加导入与导出的功能。
```
> feat: add import and export theme configuration

- api-docs/openapi/v3_0/aggregated.json
- api/src/main/java/run/halo/app/core/extension/content/Category.java
- application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
- ui/packages/api-client/src/models/category-spec.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area core
支持在分类上为关联的文章统一设置渲染模板
现在文章的模板生效顺序为：
1. 文章关联的分类上设置的文章模板，如果有多个则选择第一个
2. 文章上设置的自定义模板
3. 文章的默认模板
Fixes #6101
```release-note
支持在分类上为关联的文章统一设置渲染模板
```
> feat: support setting rendering templates for related posts on category

- ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
/area ui
/kind bug
修复首次上传附件时，没有默认选择第一个存储策略的问题。
Fixes https://github.com/halo-dev/halo/issues/6094
```release-note
修复首次上传附件时，没有默认选择第一个存储策略的问题。
```
> fix: not remembering the selected attachment policy in upload modal

- ui/console-src/modules/system/plugins/components/installation-tabs/LocalUpload.vue
- ui/console-src/modules/system/plugins/components/installation-tabs/RemoteDownload.vue
- ui/console-src/modules/system/plugins/composables/use-plugin.ts
/area ui
简化插件启动的接口，改为之前单独提供的修改插件状态的接口，而不是修改 `spec.enabled`。
需要测试：
1. 手动安装插件之后，启动插件。
```release-note
None
```
> refactor: simplify the plugin startup logic

- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/console-src/modules/contents/attachments/components/AttachmentGroupBadge.vue
/area ui
使用新的 [patch](https://github.com/halo-dev/halo/pull/6031) 接口重构附件的移动功能。
1. 测试附件移动至其他分组的功能是否正常。
2. 测试删除附件分组，选择 **删除并将附件移动至未分组** 选项，观察删除分组之后，其中的附件是否已经移动到未分组。
```release-note
None
```
> Refactor attachment moving using the patch api

- gradle.properties
- platform/application/build.gradle
/area core
/kind bug
升级 MariaDB 的原生驱动版本至 [1.2.1](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/releases/tag/1.2.1)，以解决无法正常部署的问题。
Fixes https://github.com/halo-dev/halo/issues/5534
测试方式：
```shell
./gradlew clean build -x check -x test --refresh-dependencies
```
```shell
docker build -t halohub/halo:mariadb-fix .
```
```yaml
services:
halo:
image: halohub/halo:mariadb-fix
restart: on-failure:3
networks:
halo_network:
volumes:
- ./halo2:/root/.halo2
ports:
- "8090:8090"
healthcheck:
test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
interval: 30s
timeout: 5s
retries: 5
start_period: 30s
command:
- --spring.r2dbc.url=r2dbc:pool:mariadb://halodb:3306/halo
- --spring.r2dbc.username=root
- --spring.r2dbc.password=jzm3h9t9jggo6ww
- …
```
> chore: bump mariadb driver to 1.2.1 to fix crash issue

- ui/package.json
- ui/pnpm-lock.yaml
/kind bug
/area ui
修复关于 iconify 图标包的幽灵依赖问题，某些情况下，可能导致无法正常导入模块。
Fixes https://github.com/halo-dev/halo/issues/6102
```release-note
None
```
> fix: resolve phantom dependency issue for iconify

- api/src/main/java/run/halo/app/infra/SystemSetting.java
- application/src/main/java/run/halo/app/notification/DefaultNotificationSender.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
- application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordDelegatingAuthenticationManager.java
- application/src/main/java/run/halo/app/theme/dialect/CommentEnabledVariableProcessor.java
- application/src/main/java/run/halo/app/theme/finders/impl/PostPublicQueryServiceImpl.java
- application/src/main/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImpl.java
- application/src/main/java/run/halo/app/webfilter/AdditionalWebFilterChainProxy.java
- application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
- application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
- application/src/test/java/run/halo/app/theme/dialect/CommentEnabledVariableProcessorTest.java
- application/src/test/java/run/halo/app/theme/finders/impl/PostPublicQueryServiceImplTest.java
- application/src/test/java/run/halo/app/theme/finders/impl/SinglePageConversionServiceImplTest.java
/area core
This PR refactors ExtensionGetter implementation to add a support of enabling extension point(s). Here is an example of data field of `system` config map:
```json
{
"data": {
"extensionPointEnabled": "{  \"search-engine\": [\"search-engine-algolia\"]}"
},
```
> 1. The `search-engine` is a name of extension point definition.
> 2. The `search-engine-algolia` is a name of extension definition.
```release-note
None
```
> Refactor ExtensionGetter for enabling or disabling extensions

- ui/console-src/modules/contents/_components/ContributorList.vue
- ui/packages/components/.storybook/main.ts
- ui/packages/components/src/components/avatar/Avatar.vue
- ui/packages/components/src/components/avatar/AvatarGroup.stories.ts
- ui/packages/components/src/components/avatar/AvatarGroup.vue
- ui/packages/components/src/components/avatar/index.ts
- ui/packages/components/src/components/avatar/interface.ts
- ui/uc-src/modules/contents/posts/components/PostListItem.vue
/area ui
/kind feature
添加 AvatarGroup 组件，用于堆叠多个 Avatar 组件。
Fixes #6079 
```release-note
添加 AvatarGroup 组件，用于堆叠多个头像。
```
> feat: add avatar group component

- ui/console-src/modules/system/users/components/UserCreationModal.vue
- ui/console-src/modules/system/users/components/UserEditingModal.vue
- ui/uc-src/modules/profile/components/ProfileEditingModal.vue
/area ui
移除用户创建/编辑表单的手机号字段，当前手机号在系统中没有任何使用。
```release-note
None
```
> refactor: remove phone field for user form

- ui/console-src/modules/contents/attachments/AttachmentList.vue
/area ui
选择附件时，如果当前没有分组，改为不显示移动按钮。
Fixes #6124 
```release-note
None
```
> refactor: hide move group button when no attachment groups are present

- ui/console-src/modules/system/roles/RoleDetail.vue
- ui/packages/components/src/components/avatar/Avatar.vue
- ui/packages/editor/src/dev/App.vue
- ui/src/composables/use-content-cache.ts
/kind bug
/area ui
解决自动保存失效的问题
测试文章、页面输入内容后，点击其他页面是否能够自动保存。
Fixes #6129 
```release-note
解决文章自动保存失效的问题
```
> fix: autosave content feature not working

- api/src/main/java/run/halo/app/extension/ListOptions.java
- api/src/main/java/run/halo/app/extension/router/selector/LabelSelector.java
- api/src/main/java/run/halo/app/extension/router/selector/SetMatcher.java
- api/src/test/java/run/halo/app/extension/ListOptionsTest.java
- api/src/test/java/run/halo/app/extension/router/selector/LabelSelectorTest.java
/area core
为 ListOptions 增加 Builder 以方便构建 ListOptions 对象,可以通过以下形式创建
```java
var listOptions = ListOptions.builder()
.labelSelector()// 构建 LabelSelector
.eq("key-1", "value-1")
.notEq("key-2", "value-1")
.exists("key-3")
.end()// 结束构建 LabelSelector
.fieldQuery(equal("spec.title", "fake-title"))  // 构建 FieldSelector
.andQuery(equal("spec.slug", "fake-slug"))
.orQuery(equal("spec.slug", "test"))
.build();
```
```release-note
开发者相关：支持通过 Builder 来简化 ListOptions 的构建
```
> refactor: add builder for list options

- api/src/main/java/run/halo/app/extension/ExtensionMatcher.java
- api/src/main/java/run/halo/app/extension/WatcherExtensionMatchers.java
- api/src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
- api/src/main/java/run/halo/app/extension/controller/RequestSynchronizer.java
- api/src/test/java/run/halo/app/extension/controller/RequestSynchronizerTest.java
/area core
为启动时同步添加 ListOptions 选项为后续保持 ExtensionMatcher 的纯粹做准备，后续将移除 ExtensionMatcher 中多余的方法声明，只保留 match 方法,最终的结果希望是
```java
@FunctionalInterface
public interface ExtensionMatcher {
boolean match(Extension extension);
}
```
以前构建 Controller 的写法
```java
public Controller setupWith(ControllerBuilder builder) {
return builder
.extension(new Post())
.onAddMatcher(DefaultExtensionMatcher.builder(client, Post.GVK)
.fieldSelector(FieldSelector.of(
equal(Post.REQUIRE_SYNC_ON_STARTUP_INDEX_NAME, TRUE))
)
.build()
)
.build();
}
```
现在的写法
```java
public Controller setupWith(ControllerBuilder builder) {
var post = new Post();
return builder
.extension(post)
// 当有新数据添加时
.onAddMatcher(extension -> "fake-post".equals(extension.getMetadata().getName()))
// 使用 …
```
> refactor: add list options for sync all synchronizer

- ui/console-src/modules/contents/posts/PostList.vue
- ui/console-src/modules/contents/posts/components/PostBatchSettingModal.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area ui
支持批量为文章设置部分属性。
Fixes https://github.com/halo-dev/halo/issues/4631
```release-note
支持批量为文章设置部分属性。
```
> feat: add batch setting for partial post fields

- api-docs/openapi/v3_0/aggregated.json
- api/src/main/java/run/halo/app/core/extension/content/Category.java
- api/src/main/java/run/halo/app/core/extension/content/Post.java
- api/src/main/java/run/halo/app/extension/index/query/NotEqual.java
- application/src/main/java/run/halo/app/content/AbstractEventReconciler.java
- application/src/main/java/run/halo/app/content/CategoryPostCountUpdater.java
- application/src/main/java/run/halo/app/content/CategoryService.java
- application/src/main/java/run/halo/app/content/PostHideFromListStateUpdater.java
- application/src/main/java/run/halo/app/content/TagPostCountUpdater.java
- application/src/main/java/run/halo/app/content/impl/CategoryServiceImpl.java
- application/src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
- application/src/main/java/run/halo/app/event/post/CategoryHiddenStateChangeEvent.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
- application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
- application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
- ui/console-src/modules/contents/posts/categories/components/CategoryListItem.vue
- ui/packages/api-client/src/models/category-spec.ts
- ui/packages/api-client/src/models/post-status.ts
- ui/packages/api-client/src/models/single-page-status.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area core
允许为分类设置从列表中隐藏则分类及子分类以及关联的文章将不会出现在列表上但可以通过链接访问
Fixes #6093
```release-note
允许为分类设置是否从列表中隐藏
```
> feat: support hide categories and posts from the list

- application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
/kind bug
/area core
/area plugin
The problem was introduced by PR <https://github.com/halo-dev/halo/pull/6141>. That PR wrongly registered `settingFetcher` singleton bean.
```release-note
None
```
> Fix the problem of not being able to autowire settingFetcher bean in plugin

- application/src/main/java/run/halo/app/security/device/DeviceEndpoint.java
/area core
Use top-level interface `org.springframework.session.ReactiveFindByIndexNameSessionRepository` for being compatible with other session repositories.
Fixes https://github.com/halo-dev/halo/issues/6159
```release-note
None
```
> Use top-level interface of session repository

- ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
/area ui
/kind bug
修复在扩展点设置页面切换扩展点定义后，扩展定义的选项被清空的问题。
Fixes #6164 
```release-note
修复在扩展点设置页面切换扩展点定义后，扩展定义的选项被清空的问题。
```
> fix: clear extension definition options after switching extension points

- ui/packages/editor/src/extensions/audio/index.ts
- ui/packages/editor/src/extensions/code-block/code-block.ts
- ui/packages/editor/src/extensions/columns/column.ts
- ui/packages/editor/src/extensions/iframe/index.ts
- ui/packages/editor/src/extensions/image/index.ts
- ui/packages/editor/src/extensions/range-selection/index.ts
- ui/packages/editor/src/extensions/table/index.ts
- ui/packages/editor/src/extensions/table/table-cell.ts
- ui/packages/editor/src/extensions/table/table-header.ts
- ui/packages/editor/src/extensions/table/table-row.ts
- ui/packages/editor/src/extensions/video/index.ts
/area editor
由于 RangeSelection 可能将一些并不想展示为模拟选中效果的节点进行了转换，因此将 RangeSelection 中模拟选中的效果，由默认的自动设置为 true，变为 false。
之后需要由节点自行设置 `fakeSelection: true` 后才会展示为模拟选中的效果，否则保持原本的选择样式。
测试使用 Mod-a 全选后，listItem 等节点是否会展示为模拟选中的效果。
```release-note
None
```
> pref: block-level content actively sets fakeSelection

- ui/packages/components/src/components/avatar/Avatar.vue
/area ui
/kind bug
Fix the vue injection warn in browser console
```release-note
None 
```
> fix: vue injection warn

- application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
/kind bug
/area core
修复查询分类的排序条件拼写错误导致的错误
Fixes #6171
```release-note
修复查询分类的排序条件拼写错误导致的错误
```
> fix: spelling errors in sorting criteria for query categories

- application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
- application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
/kind bug
/area core
Some users encountered 2FA required issue after upgrading Halo 2.16, because they enabled 2FA but didn't configure TOTP before. The issue was introduced by <https://github.com/halo-dev/halo/pull/6005>.
This PR checks if TOTP configured to determine whether 2FA is required.
```release-note
修复在没有配置 TOTP 验证器的情况下仍被要求二步验证的问题
```
> Fix the problem of enabling 2FA unexpectedly

- ui/packages/editor/src/extensions/code-block/CodeBlockViewRenderer.vue
- ui/packages/editor/src/extensions/code-block/code-block.ts
/area editor
为默认编辑器代码块增加折叠功能。
测试折叠功能是否可用。
测试重新打开文章之后代码块是否仍旧处于折叠状态。
Fixes #6166
```release-note
为默认编辑器代码块增加折叠功能
```
> pref: add folding function to code blocks

- ui/packages/editor/src/styles/base.scss
/area ui
/area editor
优化文章编辑器内容区域在低分屏下的表现。
默认：
小屏幕：
Fixes https://github.com/halo-dev/halo/issues/6172
建议测试在各个屏幕下的表现。
```release-note
优化文章编辑器内容区域在低分屏下的表现。
```
> refactor: improve the content area width of the editor for low-resolution screens

- ui/packages/editor/src/extensions/image/BubbleItemImageHref.vue
/area editor
为图片跳转链接增加在新窗口打开的选项。
测试新窗口打开是否正常可用。
Fixes #6109 
```release-note
默认编辑器图片跳转链接支持配置新窗口打开
```
> pref: add the option to open a new window to the picture jump link

- ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
- ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
- ui/console-src/modules/contents/posts/DeletedPostList.vue
- ui/console-src/modules/contents/posts/components/PostBatchSettingModal.vue
- ui/console-src/modules/contents/posts/components/PostSettingModal.vue
- ui/console-src/modules/contents/posts/components/entity-fields/ContributorsField.vue
- ui/env.d.ts
- ui/src/components/user/PostContributorList.vue
- ui/src/formkit/formkit.config.ts
- ui/src/formkit/inputs/user-select.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
- ui/uc-src/modules/contents/posts/components/PostListItem.vue
/area ui
/kind feature
支持手动为文章设置作者。
Fixes https://github.com/halo-dev/halo/issues/5720
需要测试：
1. 打开任意文章的设置，在高级中设置作者并保存，观察是否成功。
2. 选择一批文章，点击批量设置，设置一个作者，观察是否设置成功。
```release-note
支持手动为文章设置作者。
```
> feat: add support for setting an owner for posts

- application/src/main/java/run/halo/app/theme/finders/CategoryFinder.java
- application/src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
- application/src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
- application/src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java
/kind feature
/area core
为分类 Finder 提供获取指定节点的面包屑路径方法
Fixes #3374
```release-note
为分类 Finder 提供获取指定节点的面包屑路径方法
```
> feat: add method to find path of a specified node in a category tree

- ui/packages/ui-plugin-bundler-kit/package.json
/area ui
补充 `@halo-dev/ui-plugin-bunlder-kit` 包的 types 地址定义。
```release-note
None
```
> chore: add types path to ui-plugin-bunlder-kit package.json

- application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
/kind failing-test
/area core
This PR allows retrying to operate on posts when optimistic locking errors occur.
Fixes #6186 
```release-note
None
```
> Fix the unstable integration test of Lucene search engine

- application/src/main/resources/extensions/role-template-authenticated.yaml
/kind bug
/area core
In PR <https://github.com/halo-dev/halo/pull/6130>, I changed the api group of PAT and 2FA endpoints, but I forgot to change the corresponding role templates. So other users except admin will encounter 403 error like <https://github.com/halo-dev/halo/issues/6199>.
Fixes https://github.com/halo-dev/halo/issues/6199
```release-note
None
```
> Rectify role templates about PAT and 2FA endpoints

- ui/console-src/modules/interface/menus/components/MenuList.vue
/area ui
添加对菜单的限制，不能删除已经设置为主菜单的菜单。
Fixes https://github.com/halo-dev/halo/issues/4956
```release-note
None
```
> feat: restrict deletion of the primary menu

- ui/src/formkit/inputs/secret/components/SecretForm.vue
/kind bug
/area ui
修复 Secret Input 保存之后会多出 Secret Form 中数据的问题。
Fixes #6193 
测试方式：
1. 在保存 Secret 的表单选项前，打开一次编辑 Secret 的对话框。
2. 保存数据，检查内容是否多出了其他数据。
```release-note
None
```
> fix: resolve issue with secret input saving additional data

- application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
/area core
/area plugin
修复当启动插件遇到 Error 级别的错误时会导致 API 被挂起无法终止的问题
```
- Throwable
- Error
- Exception
```
see #6192 for more details
Fixes #6192
```release-note
修复当启动插件遇到 Error 级别的错误时会导致 API 被挂起无法终止的问题
```
> fix: causing API to be pending when plugin startup encounters an error

- application/src/main/java/run/halo/app/plugin/DefaultReactiveSettingFetcher.java
- application/src/test/java/run/halo/app/plugin/DefaultSettingFetcherTest.java
/kind bug
/area core
/area plugin
This PR  makes sure the method `cache#put` is called before the event is published to avoid the event listener to fetch the old value from the cache.
The problem was introduced by <https://github.com/halo-dev/halo/pull/6141>.
Fixes #6213 
```release-note
修复在插件配置变更监听器中始终获取到旧数据的问题
```
> Fix the problem of fetching old value from plugin setting fetcher

- build.gradle
- platform/application/build.gradle
/kind cleanup
/area core
This PR upgrades SpringDoc to 2.6.0 and its gradle plugin to 1.9.0.
See https://github.com/springdoc/springdoc-openapi/releases/tag/v2.6.0 and https://github.com/springdoc/springdoc-openapi-gradle-plugin/releases/tag/1.9.0 for more.
```release-note
升级 SpringDoc 至 2.6.0
```
> Upgrade SpringDoc to 2.6.0

- ui/src/styles/tailwind.css
/area ui
当前多选框disabled与非disabled样式上无区别，不好分辨。
Fixes https://github.com/halo-dev/halo/issues/5974
```release-note
增加多选框disabled样式
```
> feat: add disabled state styling to checkboxes

- ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue
- ui/console-src/modules/system/plugins/PluginList.vue
- ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionMultiInstanceView.vue
- ui/console-src/modules/system/plugins/components/extension-points/ExtensionDefinitionSingletonView.vue
- ui/console-src/modules/system/plugins/module.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
完善插件扩展设置页面：
1. 完善 i18n。
2. 将入口移动至插件页面右上角的操作按钮区域。
```release-note
None 
```
> refactor: refine extension settings page

- api/src/main/java/run/halo/app/security/LoginHandlerEnhancer.java
- application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
- application/src/main/java/run/halo/app/security/LoginHandlerEnhancerImpl.java
- application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/totp/TotpAuthenticationFilter.java
/area core
新增 LoginHandlerEnhancer 用于 Halo 扩展登录成功或失败后的处理逻辑如 RememberMe 和设备管理等
```release-note
None
```
> feat: add LoginHandlerEnhancer for enhanced login processing

- api/src/main/java/run/halo/app/search/SearchService.java
- application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
- application/src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
- application/src/main/java/run/halo/app/search/IndexEndpoint.java
- application/src/main/java/run/halo/app/search/SearchServiceImpl.java
- application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
- application/src/test/java/run/halo/app/search/IndexEndpointTest.java
- application/src/test/java/run/halo/app/search/SearchServiceImplTest.java
/kind feature
/area core
/area plugin
This PR creates a SearchService and makes it invokable for plugins.
1. Create a plugin
2. Publish all publication into Maven local repository by executing `./gradlew publishAllPublicationsToMavenLocalRepository`
3. Use `2.17.0-SNAPSHOT` as dependency version and refresh dependencies
4. Try to use the SearchService to search something.
```release-note
为插件提供全文搜索服务
```
> Expose search service for plugin

- application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
- application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
/kind bug
/area core
This PR adds missed type to HaloDocument while converting.
Fixes https://github.com/halo-dev/halo/issues/6235
```release-note
None
```
> Fix the problem of null type of search result

- application/src/main/java/run/halo/app/theme/finders/PluginFinder.java
- application/src/main/java/run/halo/app/theme/finders/impl/PluginFinderImpl.java
- application/src/test/java/run/halo/app/theme/finders/impl/PluginFinderImplTest.java
/kind feature
/area core
/area theme
支持在主题中检查已启动的插件是否符合指定的版本要求,以便可以在某些功能可以正常工作时才渲染
示例
```html
<p th:if="${pluginFinder.available('plugin-search-widget', '>=2.3.0')}>
</p>
```
```release-note
支持在主题中检查已启动的插件是否符合指定的版本要求
```
> feat: enhance PluginFinder to support check plugin availability by version

- ui/src/formkit/theme.ts
- ui/src/styles/tailwind.css
/area ui
/kind bug
修复 FormKit 中当 checkbox 为 disabled 时的样式问题。
before:
after:
```release-note
None
```
> fix: resolve styling issue for checkbox when disabled

- application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
- application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
- application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
- application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java
/area core
This PR provides a configuration property to control whether two-factor authentication is disabled. e.g.:
```yaml
halo:
security:
two-factor-auth:
disabled: true | false # Default is false.
```
Fixes #5640 
1. Enable 2FA and configure TOTP
2. Disable 2FA by configuring property above
3. Restart Halo and try to login
```release-note
支持通过配置的方式全局禁用二步验证
```
> Add support to disable two-factor authentication

- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
- ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
- ui/src/locales/en.yaml
- ui/src/locales/es.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
文章分类和标签 Modal 添加 ”保存并继续添加” 按钮，便于连续添加。
Fixes https://github.com/halo-dev/halo/issues/6127
```release-note
文章分类和标签页添加 "保存并继续添加" 按钮。
```
> feat: tag and category add save and continue button

- api/src/main/java/run/halo/app/extension/router/QueryParamBuildUtil.java
/kind cleanup
/area core
移除 `QueryParamBuildUtil.buildParametersFromType` 方法使用手动构建代替，参考:
https://github.com/halo-dev/halo/blob/f5ebd9fe43403420a4407cac92b944cedd67b4e5/application/src/main/java/run/halo/app/content/PostQuery.java#L135
```release-note
移除 `QueryParamBuildUtil.buildParametersFromType` 方法使用手动构建代替
```
> chore: cleanup buildParametersFromType for QueryParamBuildUtil

- application/build.gradle
/area core
This PR treats `ui/build/dist` as resource dir for application module to adapt building and running using IntelliJ IDEA.
How to use?
1. Build ui project by executing command `./gradlew :ui:build -x :ui:check`.
1. Create a `Run/Debug Configuration` with arguments `--spring.profiles.active=dev --halo.console.proxy.enabled=false --halo.uc.proxy.enabled=false`.
1. Go to `Settings | Build, Execution, Deployment | Build Tools | Gradle` and select `IntelliJ IDEA` for `Build and run using:`
1. Run/Debug the configuration 
```release-note
None
```
> Build and run using IntelliJ IDEA after building ui

- api/src/main/java/run/halo/app/plugin/PluginsRootGetter.java
- application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
- application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
- application/src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
- application/src/main/java/run/halo/app/plugin/PluginProperties.java
- application/src/main/java/run/halo/app/plugin/PluginsRootGetterImpl.java
- application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
- application/src/main/resources/application.yaml
- application/src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java
- application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java
- application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
- application/src/test/java/run/halo/app/plugin/PluginsRootGetterImplTest.java
/kind feature
/area core
/area plugin
This PR supports obtaining plugins root in plugins. Below is an example in plugin:
```java
@Component
class PluginsRootGetterDemo {
private final PluginsRootGetter pluginsRootGetter;
PluginsRootGetterDemo(PluginsRootGetter pluginsRootGetter) {
this.pluginsRootGetter = pluginsRootGetter;
}
}
```
Meanwhile, I remove the `PluginProperties#pluginsRoot` for a clear way to obtain plugins root.
```release-note
支持在插件中获取插件根目录
```
> Support obtaining plugins root in plugins

- api/src/main/java/run/halo/app/plugin/BasePlugin.java
- application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
/area core
为了平滑升级先保留 PluginWrapper 的 Bean
```release-note
None
```
> chore: keep the pluginWrapper bean for compatibility

- application/src/main/java/run/halo/app/infra/exception/Exceptions.java
- application/src/main/resources/config/i18n/messages.properties
- application/src/main/resources/config/i18n/messages_zh.properties
- application/src/test/java/run/halo/app/infra/exception/handlers/I18nExceptionTest.java
- application/src/test/resources/application.yaml
- application/src/test/resources/config/i18n/messages.properties
/area core
This PR makes ConcurrencyFailureException respond http status code 409 instead of 500.
Fixes #6254 
```release-note
None
```
> Respond 409 for operation conflict instead of 500

- .github/workflows/halo.yaml
/kind cleanup
/area core
This PR allows E2E testing to fail due to frequently failing E2E testing.
```release-note
None
```
> Allow E2E testing to fail

- api/src/main/java/run/halo/app/plugin/BasePlugin.java
将 BasePlugin 的 PluginWrapper 构造函数标记为过时并输出警告日志提示
```release-note
在 BasePlugin 的 PluginWrapper 构造函数输出过时警告日志以提醒开发者尽快适配
```
> chore: mark deprecated constructor for base plugin

- ui/console-src/modules/contents/pages/SinglePageEditor.vue
- ui/console-src/modules/contents/posts/PostEditor.vue
- ui/uc-src/modules/contents/posts/PostEditor.vue
/area ui
/kind bug
修复创建文章前批量上传图片可能出现异常的问题。
目前解决方案为：移除上传前创建文章的逻辑，因为在上传前已经确定了文章的 metadata.name。
```release-note
修复创建文章前批量上传图片可能出现异常的问题。
```
> fix: resolve potential exception during bulk image upload in post creation

- api/src/main/java/run/halo/app/plugin/BasePlugin.java
将 BasePlugin 的 PluginWrapper 构造函数标记为过时并输出警告日志提示
```release-note
在 BasePlugin 的 PluginWrapper 构造函数输出过时警告日志以提醒开发者尽快适配
```
> [release-2.17] chore: mark deprecated constructor for base plugin

- ui/packages/editor/src/extensions/text/index.ts
/kind bug
/area editor
在默认编辑器中，选中一个跨多个节点的 text 时，selection 会变为 RangeSelection，此时冒泡菜单将不会出现。
此 RP 将 RangeSelection 添加至 text 的冒泡菜单验证中，使得冒泡菜单可以出现。
测试跨行选中多个无序列表时，是否出现冒泡菜单。
Fixes #6267 
```release-note
修复默认编辑器中跨行选择节点时冒泡菜单无法出现的问题
```
> fix: bubble menu not appearing when crossing lines in editor

- api/src/main/java/run/halo/app/security/AfterSecurityWebFilter.java
- api/src/main/java/run/halo/app/security/BeforeSecurityWebFilter.java
- application/src/main/java/run/halo/app/security/SecurityWebFiltersConfigurer.java
- docs/extension-points/authentication.md
/kind feature
/area core
/area plugin
This PR adds `BeforeSecurityWebFilter` and `AfterSecurityWebFilter` extension points. See https://github.com/halo-sigs/plugin-page-cache/issues/4#issuecomment-2216677891 for more.
Now, we can do something before and after authenticating.
```release-note
添加认证授权的前置和后置处理器扩展点
```
> Add before and after security web filters

- application/src/main/java/run/halo/app/security/device/NewDeviceLoginListener.java
- application/src/main/resources/extensions/notification-templates.yaml
- application/src/test/java/run/halo/app/security/device/DeviceServiceImplTest.java
/area core
Fixes #6256 
```release-note
格式化新设备登录邮件通知内的登录时间为系统时区
```
> Improve timezone information in login notification

- application/src/main/java/run/halo/app/theme/config/ThemeWebFluxConfigurer.java
- application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
/kind bug
/area core
This PR checks readable of theme resources while getting resources to prevent Halo from throwing FileNotFoundException.
Fixes #6338 
1. Try to request <https://www.halo.run/themes/fake-theme/assets/favicons/favicon-32x32.png>
2. See the result
```release-note
修复访问不存在的主题资源时出现服务器异常的问题
```
> Respond 404 for non-exist theme resources instead of 500

- ui/src/components/editor/DefaultEditor.vue
/kind bug
/area editor
使用组合输入时，按下回车键不再执行编辑器获取焦点的事件。
Fixes #6345 
```release-note
解决默认编辑器标题在使用组合输入时，按下回车键会导致其失去焦点的问题。
```
> fix: enter key causing focus loss in default editor title during composition input

- application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
- application/src/test/java/run/halo/app/plugin/HaloPluginManagerTest.java
/kind bug
/area core
/area plugin
This PR checks if the plugin is already unloaded while getting dependents to fix the problem that plugins without jar file may not be deleted or not be enabled or disabled.
Fixes https://github.com/halo-dev/halo/issues/6072
1. Try to move plugins folder to another folder
2. Restart Halo
3. Try to change state of plugins or delete plugins directly
4. See the result
```release-note
修复在没有插件文件的情况下可能无法删除插件的问题
```
> Fix the problem that plugins without jar file may not be deleted

- api/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
- application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
/area core
通过将 ExtensionGetter Bean 共享到给插件的 ApplicationContext，插件能够方便地使用该 Bean 来获取扩展。此更改确保插件具有可靠的扩展访问方式，从而促进系统内更好的模块化和可扩展性。
Fixes #6357 
```release-note
将 ExtensionGetter Bean 共享给插件使用，以便插件可以通过它来获取扩展
```
> feat: share ExtensionGetter Bean with plugins for extension retrieval

- api/src/main/java/run/halo/app/extension/router/QueryParamBuildUtil.java
/area core
在 https://github.com/halo-dev/halo/pull/6244 中移除了过时的 `QueryParamBuildUtil.buildParametersFromType` 方法，但是由于留给插件适配的时间不够，很多官方提供的插件也要和 2.18 一起发版这样会导致使用了此方法的插件无法启动，因此留下方法声明并输出日志等到后续版本在删除，这样可以给出一些时间给用户先升级插件而不是挂掉。
```release-note
None
```
> chore: compatibility for deprecated buildParametersFromType method with deprecation log

- ui/packages/editor/src/extensions/indent/index.ts
/kind feature
/area editor
支持在默认编辑器中使用 Tab 键实现首行缩进的功能。
当光标处于文本首行时，按下 Tab 键会触发首行缩进。
在首行缩进的情况下或者选中一段文本，再次按下 Tab 键会触发整段缩进。
测试文本块及区域标题块首行按下 Tab 键是否可以正常触发首行缩进
Fixes #6316 
```release-note
默认编辑器增加 Tab 快捷键首行缩进功能
```
> feat: add the first line indent to the Tab shortcut key

- ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
/area ui
修改附件选择组件的默认显示数量，以解决因为图片数量过多或者图片过大导致的卡顿问题。
Ref https://github.com/halo-dev/halo/issues/6352
```release-note
修改附件选择组件的默认显示数量，以解决因为图片数量过多或者图片过大导致的卡顿问题。
```
> refactor: change the number of queried attachments in the selector modal

- ui/packages/editor/src/extensions/columns/column.ts
- ui/packages/editor/src/extensions/columns/columns.ts
- ui/packages/editor/src/styles/columns.scss
/area editor
移除编辑器 Column 的默认 padding 样式。
See https://github.com/halo-dev/halo/issues/6377#issue-2428912807
Fixes #6377 
```release-note
移除编辑器分栏卡片的默认 padding 样式。
```
> refactor: remove padding style from editor column block

- ui/packages/editor/src/extensions/indent/index.ts
- ui/packages/editor/src/extensions/paragraph/index.ts
- ui/packages/editor/src/utils/isListActive.ts
/kind bug
/area editor
目前当编辑器中列表内容为空时，需要按退格键多次才能删除掉此列表内容。
本 PR 在执行单行删除逻辑之前，会检查列表是否处于活动状态，如果是则不再执行单行删除的逻辑。列表会执行 ListKeyMap 相关快捷键。
1. 在默认富文本键入一个列表。
2. 使用退格键删除这个列表。
3. 查看是否可以一次就删除。
Fixes #6389 
```release-note
修复默认编辑器中列表项需要按多次退格键才可以删除的问题
```
> fix: list items require multiple backspace presses to delete

- ui/packages/editor/src/extensions/color/index.ts
- ui/packages/editor/src/extensions/font-size/index.ts
- ui/packages/editor/src/extensions/highlight/index.ts
- ui/packages/editor/src/extensions/index.ts
- ui/packages/editor/src/extensions/text-style/index.ts
/kind bug
/area editor
此 PR 解决了使用高亮插件之后按 `up` 或 `down` 按键被阻止的问题。
此问题的来源为 https://github.com/halo-sigs/richtext-editor/pull/56 ，在此前的 PR 中为了解决设置字体大小后再次设置高亮，会导致高亮无法完全笼罩字体的问题。
但经过仔细排查，发现上述问题之前的解决方式有误，正确的原因应该是设置字体大小的 `span` 标签与设置高亮的 `mark` 标签顺序相反导致。如下所示：
正确的情况应该是在 `span` 中包裹 `mark`。此 PR 提升了 `TextStyle` 的优先级，结果如下所示：
测试对文本使用高亮功能之后按 `up` 或 `down` 按键是否生效。
测试对在文本设置大小之后，使用高亮、删除线等样式是否正确。
Fixes #6381 
```release-note
解决默认编辑器中对文本使用高亮会导致按键被阻止的问题
```
> fix: solve the problem that highlighting will prevent the keys

- api/src/main/java/run/halo/app/content/ExcerptGenerator.java
- application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
- application/src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
- application/src/main/resources/extensions/extensionpoint-definitions.yaml
- application/src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
- application/src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
/kind feature
/area core
新增文章摘要生成扩展点用于扩展自动生成摘要的方式
```release-note
新增文章摘要生成扩展点用于扩展自动生成摘要的方式
```
> feat: add extension point for excerpt generation

- ui/package.json
- ui/packages/api-client/package.json
- ui/pnpm-lock.yaml
- ui/src/components/form/AnnotationsForm.vue
/area ui
更新 typescript 依赖版本至 5.5.x，以尝试解决 VSCode Vue 插件频繁崩溃的问题。
```release-note
None
```
> chore: bump typescript version to 5.5.x

- ui/console-src/modules/contents/comments/components/CommentListItem.vue
- ui/console-src/modules/contents/comments/components/ReplyListItem.vue
- ui/docs/extension-points/entity-listitem-operation.md
- ui/packages/shared/src/types/plugin.ts
/area console
/kind feature
评论和回复管理列表项的操作按钮支持被插件扩展。
Fixes #6392 
需要评论和回复的关于列表的已有功能是否正常。
如果需要测试扩展点是否有效，可以使用此插件测试：[plugin-starter-1.0.0-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16482348/plugin-starter-1.0.0-SNAPSHOT.jar.zip)
```
export default definePlugin({
components: {},
routes: [],
extensionPoints: {
"comment:list-item:operation:create": (comment: Ref<ListedComment>) => {
return [
{
priority: 21,
component: markRaw(VDropdownItem),
label: "测试评论菜单",
visible: true,
permissions: [],
action: () => {
console.log(comment)
},
},
];
},
"reply:list-item:operation:create": (reply: Ref<ListedReply>) => {
return [
{
priority: 11,
component: markRaw(VDropdownItem),
label: "测试回复菜单",
visible: true,
permissions: [],
action: () => {
console.log(reply)
},
},
];
},
}, …
```
> feat: make comment and reply list item operations extendable

- api/src/main/java/run/halo/app/search/SearchOption.java
- application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
- application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineIntegrationTest.java
/area core
This PR allows users to filter search result by types, owner names, category names and tag names.
```release-note
完善搜索引擎过滤功能
```
> Support filtering search result by types, ownerNames, categoryNames and tagNames

- ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
- ui/src/components/preview/UrlPreviewModal.vue
/kind bug
/area ui
此 PR 将主题预览及文章预览的 `iframe` 由 srcdoc 改为使用 src 加载。用于解决在主题预览时，如果点击保存设置，会导致主题端页面跳转至首页。
1. 打开主题预览界面。
2. 打开非首页的页面。
3. 点击保存配置。查看此时刷新页面后是否不再回到首页。
同时需要测试 #4047 中的场景是否还会再发生。
Fixes #6371 
```release-note
解决预览主题时保存设置，页面会跳转至首页的问题。
```
> fix: saving settings in theme preview returns to homepage

- ui/packages/editor/src/extensions/paragraph/index.ts
/kind bug
/area editor
修复默认编辑器中，当在列表的下一空白行使用退格键时，会导致无法回退至列表项中的问题。
1. 在编辑器中增加一个列表项。
2. 按两次回车跳出列表编辑器。
3. 按退格键。
查看退格键是否按一次就可以回到列表项，并且再次按时执行列表项的删除。
Fixes #6263
```release-note
解决默认编辑器中在空白行中按退格键无法回退到列表项中的问题
```
> fix: backspace on empty line doesn’t return to previous list item

- ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
/area ui
将主题预览中的保存功能固定在底部，方便当主题设置项过多时进行保存。
为了不影响保存功能，因此此 PR 移除了本来在左下角悬浮的选择主题按钮。选择主题可以直接在右上角进行点击。
Fixes #6448 
```release-note
在主题预览界面中将保存按钮固定在底部
```
> pref: pin save button to the bottom of the page in theme preview

- ui/console-src/modules/contents/posts/categories/CategoryList.vue
- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
/area ui
使用 patch 接口重构分类拖动排序功能。
None
需要测试文章分类的拖动排序功能是否符合预期。
```release-note
使用 patch 接口重构分类拖动排序功能。
```
> refactor: use patch api to refactor category drag-and-drop sorting feature

- application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
- ui/console-src/modules/system/plugins/components/PluginListItem.vue
- ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
- ui/console-src/setup/setupModules.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
- ui/uc-src/setup/setupModules.ts
/area core
支持在插件变动之后（版本更新或者安装启用），提示使用者重载页面。
后端改变了插件 bundle.js 中关于启用插件信息的结构以便在插件升级后检测是否加载。
Fixes #4464
```release-note
支持在插件变动之后（版本更新或者首次启用），提示使用者重载页面。
```
> feat: add prompt for users to reload page after plugin update

- application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
- application/src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
- application/src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClientImpl.java
- application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
/kind cleanup
/area core
移除事务注解避免对索引创建产生影响，原因参考改动中的方法注释
**其中一点特别注意：**
在执行 `client.create(name, data)` 方法后，会尝试进行 `indexer.indexRecord` 操作。但 indexRecord 可能会因唯一索引中存在重复键而导致 indexRecord 失败，索引创建也会随之失败。为确保索引与数据的一致性，此时应回滚由 `client.create(name, data)` 对数据产生的影响，因此除非找到更佳的一致性问题解决方案，否则暂时不能移除此处的手动事务操作。
```java
return client.create(name, version, data)
.map(updated -> converter.convertFrom(type, updated))
.doOnNext(extension -> indexer.indexRecord(convertToRealExtension(extension)))
.as(transactionalOperator::transactional);
```
将变更传递给 extension watcher 是在 `doCreate` 或 `doUpdate` 成功之后才会被处理，因此这里的事务回滚不会对 watcher 造成影响
```release-note
None
```
> chore: remove transactional annotation

- application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java
/kind bug
/area core
修复切换账号登录时设备信息更新不正确的问题
原因：
1. 使用 admin 账号登录，此时会记录 device_id 的 cookie
2. 退出登录，device_id 会保留在 cookie 中并随着新账号带到服务端
3. 服务端根据 device_id 查询当前设备是否有对应的记录，但是没有校验用户名是否与当前登陆的一致然后就去更新登录时间
4. 正确的处理是校验 device_id 是否有与之对应的记录并且用户名相同，如果不相同则认为是新设备重新生成 device_id
**how to test it?**
1. 先清理 cookie 然后使用一个账号登录
2. 退出登陆并切换新账号登录
3. 检查新登录的账号的设备信息是否正确
```release-note
修复切换账号登录时设备信息更新不正确的问题
```
> fix: correct device information update during account switch

- ui/packages/editor/src/extensions/link/index.ts
/area editor
使用白名单校验替换原有的黑名单校验，解决 a 标签潜在的安全问题。
移除自定义的解决方案，使用 Tiptap 所提供的白名单方案。
测试 a 标签的 href 链接是否会受到 xss 的影响。
同时测试 #5479 的情况是否还会发生。即默认富文本编辑器中当链接为纯数字时是否还会报错。
```release-note
使用白名单校验 a 标签的 href 用于解决潜在的安全问题。
```
> pref: use whitelist for allowed href values

- ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
/area ui
优化插件是否需要重载页面的判断条件，否则从低版本升级到 2.19 时，所有插件都会提示需要重载。
因为在 https://github.com/halo-dev/halo/pull/6470 中修改了 bundle.js 的结构，但升级到 2.19 之后可能并不会及时抛弃 bundle.js 的缓存，因为插件本身的 version 并没有改变，bundle.js 的 hash 参数也不会改变。
```release-note
None
```
> refactor: improve conditions for determining if a plugin needs to be reloaded

- ui/console-src/modules/system/backup/components/BackupListItem.vue
- ui/console-src/modules/system/backup/tabs/Restore.vue
/area ui
/kind bug
修复备份相关的 API 接口地址错误的问题，此问题由 https://github.com/halo-dev/halo/pull/6486 引入，后端修改地址之后，前端没有对应修改。
```release-note
None
```
> fix: correct API endpoints related to backup issues

- ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
- ui/console-src/modules/contents/attachments/components/selector-providers/components/AttachmentSelectorListItem.vue
/area ui
/kind feature
为附件选择组件添加更多筛选项支持。
Fixes https://github.com/halo-dev/halo/issues/4605
Fixes https://github.com/halo-dev/halo/issues/6352
需要测试附件选择组件的各项功能是否符合预期。
```release-note
为附件选择组件添加更多筛选项支持。
```
> feat: add filter options for attachment selector component

- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/console-src/modules/contents/attachments/components/AttachmentDetailModal.vue
- ui/console-src/modules/contents/attachments/components/DisplayNameEditForm.vue
- ui/console-src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
/area ui
/kind feature
支持修改附件的显示名称。
Fixes https://github.com/halo-dev/halo/issues/4294
```release-note
支持修改附件的显示名称。
```
> feat: support changing attachment display name

- application/build.gradle
- application/src/main/java/run/halo/app/theme/CompositeTemplateResolver.java
- application/src/main/java/run/halo/app/theme/HaloViewResolver.java
- application/src/main/java/run/halo/app/theme/TemplateEngineManager.java
- application/src/test/java/run/halo/app/theme/CompositeTemplateResolverTest.java
- application/src/test/java/run/halo/app/theme/ThemeIntegrationTest.java
/area core
This PR refactors "Template Not Found Exception" into "NotFoundException" to prevent too many exception stacktraces in logs file.
Fixes #6501 
1. Activate default theme
2. Request <http://localhost:8090/categories>
3. See the result
```release-note
优化当主题模板找不到的异常提示
```
> Respond not found if no theme template found

- build.gradle
/area core
See https://github.com/spring-projects/spring-boot/releases/tag/v3.3.3 for more.
```release-note
升级 Spring Boot 至 3.3.3
```
> Upgrade Spring Boot to 3.3.3

- application/src/main/java/run/halo/app/infra/exception/handlers/ProblemDetailErrorAttributes.java
/kind bug
/area core
After merging https://github.com/halo-dev/halo/pull/6512 and https://github.com/halo-dev/halo/pull/6511, unit tests fail due to the changes of <https://github.com/spring-projects/spring-boot/commit/05b73ceeecd940843a34b9026ce73ba408a7aaa2>.
This PR fixes the problem by letting `run.halo.app.infra.exception.handlers.ProblemDetailErrorAttributes` extend  `org.springframework.boot.web.reactive.error.DefaultErrorAttributes`.
```release-note
None
```
> Fix "Missing exception attribute in ServerWebExchange" error after upgrading Spring Boot 3.3.3

- ui/src/components/alerts/H2WarningAlert.vue
/area ui
/kind bug
修复 H2 数据库提示判断有误的问题。
```release-note
None
```
> fix: wrong condition in h2 warning alert

- application/src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
/kind bug
/area core
This PR corrects list options builder for listing aggregated roles, because I wrongly used the label selector in <https://github.com/halo-dev/halo/pull/6471>.
1. Try to install the plugin <https://www.halo.run/store/apps/app-YXyaD>
2. Enable the plugin and enable setting `匿名评论需要验证码`
3. **Anonymous** request any of posts with comment enabled
4. Check the captcha in comment area
```release-note
修复可能无法正常访问插件提供的接口的问题
```
> Fix the incorrect list options builder while listing aggregated roles

- application/src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
- application/src/test/java/run/halo/app/core/extension/service/DefaultRoleServiceTest.java
/kind bug
/area core
This PR makes the return value of method `DefaultRoleService#getRolesByUsernames` never be `Mono#empty`.
See https://github.com/halo-dev/halo/issues/6528 for more.
Fixes https://github.com/halo-dev/halo/issues/6528 
1. Try to execute command `http -a admin:admin http://127.0.0.1:8090/apis/api.console.halo.run/v1alpha1/users?keyword=xyz`.
2. See the output
```release-note
修复获取用户列表时可能返回空结果的问题
```
> Fix the problem that return empty result while listing users

- ui/src/components/filter/UserFilterDropdown.vue
/area ui
/kind feature
重构用户筛选组件，支持远程搜索，避免在用户量大的时候产生性能问题。
```release-note
重构用户筛选组件，支持远程搜索。
```
> refactor: optimize user filter component to support remote search

- application/src/main/java/run/halo/app/infra/utils/SortUtils.java
- application/src/main/java/run/halo/app/theme/finders/PostFinder.java
- application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
- application/src/test/java/run/halo/app/infra/utils/SortUtilsTest.java
- application/src/test/java/run/halo/app/theme/finders/impl/PostFinderImplIntegrationTest.java
/kind feature
/area core
为 postFinder 添加一个统一参数的 list 方法并支持传递排序参数
Fixes https://github.com/halo-dev/halo/issues/4933
```release-note
为 postFinder 添加一个统一参数的 list 方法并支持传递排序参数
```
> feat: add unified parameter list method for post finder

- ui/src/formkit/inputs/attachment-group-select.ts
- ui/src/formkit/inputs/attachment-policy-select.ts
- ui/src/formkit/inputs/menu-item-select.ts
- ui/src/formkit/inputs/post-select.ts
- ui/src/formkit/inputs/role-select.ts
- ui/src/formkit/inputs/select/SelectMain.vue
- ui/src/formkit/inputs/singlePage-select.ts
- ui/src/formkit/inputs/user-select.ts
/area ui
使用 #6473 中重构的 Formkit Select 组件来实现用户、文章、页面等各种业务搜索组件。 
Fixes https://github.com/halo-dev/halo/issues/4931
测试各类搜索组件是否正常可用。
测试从旧版本升级后，原有数据是否可以正常显示。
```release-note
使用重构的 Formkit Select 组件来实现业务选择器。
```
> pref: implement business selector using new selector component

- ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
- ui/console-src/modules/contents/posts/components/PostSettingModal.vue
- ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
/area ui
简化文章设置表单的部分表单项。
```release-note
简化文章设置表单的部分表单项。
```
> refactor: simplify post settings form fields

- application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
- application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
/kind bug
/area core
This PR refactors LuceneSearchEngine to let IndexWriter and SearcherManager load lazily to prevent LockObtainFailedException from performing a rolling update.
Fixes #6541 
1. Use MySQL or PostgreSQL as database for Halo
2. Start an instance of Halo
3. Try to initialize Halo and search posts
4. Change the `server.port` and start another instance of Halo
5. Check the status of another instance
```release-note
修复滚动更新时无法启动新的 Halo 实例的问题
```
> Fix the problem of LockObtainFailedException while performing a rolling update

- application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
- application/src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java
/kind bug
/area core
修复 postFinder 的 list 排序参数不生效的问题
此问题由于 https://github.com/halo-dev/halo/pull/6531 导致
Fixes #6534
```release-note
None
```
> fix: post list sorting parameter not working

- ui/console-src/modules/system/settings/tabs/Setting.vue
- ui/docs/custom-formkit-input/README.md
- ui/src/formkit/inputs/attachment-group-select.ts
- ui/src/formkit/inputs/attachment-policy-select.ts
- ui/src/formkit/inputs/menu-item-select.ts
- ui/src/formkit/inputs/post-select.ts
- ui/src/formkit/inputs/role-select.ts
- ui/src/formkit/inputs/select/SelectContainer.vue
- ui/src/formkit/inputs/select/SelectMain.vue
- ui/src/formkit/inputs/select/index.ts
- ui/src/formkit/inputs/singlePage-select.ts
- ui/src/formkit/inputs/user-select.ts
/area ui
为 formkit select 增加属性 `autoSelect`。
这个属性仅会作用于单选，且目的是为了初始化数据所用。当 value 或者 placeholder 存在时，此属性无效。
会查找第一个 option 不为 disabled 的数据。
```release-note
None
```
> feat: add default selection option to formkit select component

- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
/kind cleanup
/area core
For backward compatibility, the slug of single page should not be unique.
BTW, the problem was introduced by <https://github.com/halo-dev/halo/pull/6540>.
```release-note
None
```
> Make slug of single page be not unique

- ui/src/components/editor/DefaultEditor.vue
/kind bug
/area editor
为匿名的 `Extension` 添加 name 值，解决由于匿名的 `Extension` name 相同而导致被过滤的问题。
测试默认编辑器附件库是否可以被打开。
```release-note
解决默认编辑器附件库无法被打开的问题
```
> fix: prevent anonymous extensions from being filtered due to duplicate names

- ui/packages/editor/src/components/bubble/BubbleItem.vue
- ui/packages/editor/src/extensions/paragraph/index.ts
- ui/packages/editor/src/utils/isNodeEmpty.ts
- ui/src/components/editor/extensions/audio/AudioView.vue
- ui/src/components/editor/extensions/image/ImageView.vue
- ui/src/components/editor/extensions/video/VideoView.vue
/kind bug
/area editor
/area ui
在上传的文件中执行 `resetUpload` 方法之前，提前验证是否可以进行更新。
测试删除图片或变更图片位置时，默认编辑器是否会进行报错。
```release-note
解决默认编辑器删除图片后报错的问题
```
> fix: resolve error when deleting images in default editor

- api/src/main/java/run/halo/app/extension/index/KeyComparator.java
- api/src/test/java/run/halo/app/extension/index/KeyComparatorTest.java
/area core
重构 KeyComparator 并通过更多的测试用例来确保排序功能的正确性
同时修复了可能存在溢出导致比较结果不正确的问题，目前：
1. 字符串长度比较：在 compareStrings 方法中，字符串的长度比较使用 Integer.compare，这部分代码不会产生整数溢出问题。
2. 数字部分的比较：在 compareNumbers 方法中，数字的比较是基于字符比较的（即逐位比较每个数字字符），没有涉及到将数3. 字字符串转化为 int 或 long 类型的操作，所以不会存在整数溢出问题。
4. 处理小数部分的比较：在 compareDecimalNumbers 方法中，类似地，比较操作也是基于字符的，不涉及到数值转换，因此也不存在整数溢出问题
Fixes #6466
```release-note
修复由于索引比较时可能出现整数溢出导致文章偶尔无法访问的问题
```
> refactor: optimize key comparator for indicates key sort

- application/src/main/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImpl.java
- application/src/main/java/run/halo/app/theme/endpoint/ThumbnailEndpoint.java
- application/src/test/java/run/halo/app/theme/endpoint/ThumbnailEndpointTest.java
/area core
获取缩略图时检查缩略图链接是否可访问否则重定向到原图链接
```release-note
获取缩略图时检查缩略图链接是否可访问否则重定向到原图链接
```
> refactor: redirect to original image if thumbnail is inaccessible

- ui/console-src/views/system/Setup.vue
- ui/console-src/views/system/SetupInitialData.vue
- ui/src/components/alerts/H2WarningAlert.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
将 H2 数据库使用警告放置在数据初始化页面，之前放在初始化表单页面无法正确判断，因为没有登录，无法调用 /actuator/info 接口获取数据库数据。
Fixes https://github.com/halo-dev/halo/issues/6561
需要使用此 PR 测试使用 H2 数据库全新安装，观察是否在数据初始化页面有 H2 数据库的使用提示。
```release-note
None
```
> refactor: add warning alert for H2 database on data initialization page

- ui/packages/editor/src/extensions/clear-format/index.ts
- ui/packages/editor/src/extensions/format-brush/index.ts
/kind bug
/area editor
为默认编辑器格式刷及清除格式扩展增加 name，用于解决其重名而导致被错误过滤的问题
Fixes #6562 
查看默认编辑中格式刷及清除格式功能是否存在且运行正常。
```release-note
解决默认编辑器格式刷及清除格式功能不存在的问题
```
> fix: solving the issue of the default editor format brush being incorectly filtered

- ui/src/formkit/inputs/select/SelectMain.vue
/kind bug
/area ui
当 formkit 选择器初始没有值的情况下，会默认选择第一项，但这同时会导致监听器取消监听，进而无法监听到后续的 value 值变更。
此 PR 将选择值的逻辑与自动选择第一项分开，用于解决此问题。
测试当选择器不存在初始值时，后续通过 v-model 传入的值是否还会使当前选项进行变更。
```release-note
解决 formkit 选择器回显数据异常的问题
```
> fix: formkit selector not listening to data after defaulting to first option

- application/src/main/java/run/halo/app/search/lucene/LuceneSearchEngine.java
- application/src/test/java/run/halo/app/search/lucene/LuceneSearchEngineTest.java
/kind bug
/area core
This PR add keyword synchronized for methods `addOrUpdateDocuments`, `deleteDocuments` and `deleteAll` to ensure the write lock of Lucene is obtained only by one IndexWriter at the same time.
Fixes #6569 
```release-note
修复重启后无法搜索部分文档的问题
```
> Fix the problem that Lucene lock is held by VM

- application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
/area core
当生成缩略图时如果原图尺寸小于请求尺寸则返回原图以保持其质量
Fixes #6579
```release-note
当生成缩略图时如果原图尺寸小于请求尺寸则返回原图以保持其质量
```
> refactor: preserve original image if smaller than requested thumbnail size

- ui/src/components/editor/composables/use-extension.ts
/kind bug
/area ui
在过滤默认编辑器重复扩展时，移除将扩展扁平化的操作。并且若扩展没有 name，则不对其进行过滤，用于解决一些潜在的问题。
测试在默认编辑器中新增 table ，是否会出现报错。
Fixes #6585 
```release-note
解决在默认编辑器中添加表格报错的问题
```
> fix: resolve error when adding tables in default editor

- ui/docs/custom-formkit-input/README.md
/area docs
补充 formkit select 组件中关于 allowCreate 属性的文档
Fixes halo-dev/docs#408 
```release-note
None
```
> docs: add documentation for formkit select allowCreate property

- ui/docs/custom-formkit-input/README.md
- ui/src/formkit/inputs/select/SelectMain.vue
/kind improvment
/area ui
为 Formkit Select 组件增加 `fieldSelectorKey` 字段，用于在使用 `fieldSelector` 字段远程查询时，指定查询所使用的 Key。
例如指定 `fieldSelectorKey` 为 `metadata.name` 则接口调用时的参数为 `fieldSelector: metadata.name=(admin)`。
测试在远程搜索时，`fieldSelector` 的查询 key 是否为设置的内容。
Fixes #6589 
```release-note
为 Formkit Select 组件远程查询增加指定 Key 的字段。
```
> pref: add parameter to formkit select component for remote search by specific field

- ui/src/formkit/inputs/select/SelectMain.vue
- ui/src/formkit/inputs/select/SelectOption.vue
- ui/src/formkit/inputs/select/isFalse.ts
/kind bug
/area ui
解决 formkit select 组件中，option 使用 `attrs: { disabled: true }` 无效的问题。
测试在 formkit select 组件中，option 设置 disabled 属性是否有效。
Fixed #6592 
```release-note
解决 formkit select 组件的 Option 设置 disabled 无效的问题
```
> fix: resolve issue with disabled property in options not working

- application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
/kind bug
/area core
修复 GIF 缩略图生成只会保留第一帧的问题
Fixes #6596
```release-note
修复 GIF 缩略图生成只会保留第一帧的问题
```
> fix: skip thumbnail generation for GIF images

- ui/src/formkit/inputs/select/SelectContainer.vue
- ui/src/formkit/inputs/select/SelectMain.vue
/kind bug
/area ui
重新修改 formkit select 初始化值的监听方式，用于当 value 发生变化时，使选项值可以发生变化。
另外在更新数据时，如果数据发生变化，则发出 `onChange` 事件。
> 需要注意的是，通过 v-modal 传入默认值，再将此值改为 `undefined` 时无法触发 `watch` 及 formkit 的 `input` 事件，原因暂时未知，将此值设置为 `""` 即可正常触发。
由于此 PR 改动了初始化的方式，因此需要全量测试所有使用 `Select` 组件的位置。包括多选与单选，本地源与远程源。确保功能符合预期。
Fixes #6594 
```release-note
解决 Formkit Select 组件在值变更时不会发出事件及修改选项值的问题。
```
> fix: formkit select component not emitting event or updating selection on value change

- application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
- application/src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
/kind bug
/area core
This PR filters blank role name while granting roles for an user to prevent null role in permissions.
Fixes https://github.com/halo-dev/halo/issues/6604
```release-note
修复取消用户角色后无法正常渲染用户列表的问题
```
> Prevent null role while getting permissions

- ui/src/formkit/inputs/select/SelectDropdownContainer.vue
- ui/src/formkit/inputs/select/SelectMain.vue
/kind bug
/area ui
为 formkit select 组件优化逻辑，目前将可以监听到 options 的变化，用于在变化时设置值。用于解决当 options 是异步获取，而 value 是初始设置时，无法显示正常的 label。
测试 options 比设置 value 晚时，数据能否正常显示 label。
```release-note
解决当 formkit select 组件中的 options 延迟设置时无法正常回显的问题。
```
> fix: resolve incorrect display of options in formkit selector with async data

- application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
- application/src/main/java/run/halo/app/core/attachment/reconciler/AttachmentReconciler.java
- application/src/main/java/run/halo/app/core/attachment/reconciler/LocalThumbnailsReconciler.java
- application/src/test/java/run/halo/app/core/attachment/ThumbnailGeneratorTest.java
/area core
优化根据 URI 生成缩略图时的请求头
1. 由于之前 attachment 的 permalink 是 `URI.toString` 会导致根据 permalink 索引查询附件可能由于编码问题无法查询到导致生成缩略图只能根据 URI 生成
2. 可能配置了 nginx 判断请求头不允许脚本请求如导致根据 URI 访问图片无法访问导致无法生成，如
```
if ($http_user agent ~*(python curlljava wget go-http-client httpclient okhttp)){
}
```
Fixes #6627
```release-note
None
```
> refactor: optimize request headers when generating thumbnails from URI

- application/src/main/java/run/halo/app/core/attachment/reconciler/AttachmentReconciler.java
/area core
/area plugin
This PR removes deprecated code that was for backward compatibility and lets reconciler requeue if attachment handler is unavailable.
Fixes https://github.com/halo-dev/halo/issues/4439
```release-note
解决重启后可能无法更新附件链接的问题
```
> Update attachment permalink only when handler is available

- ui/docs/custom-formkit-input/README.md
- ui/src/formkit/formkit.config.ts
- ui/src/formkit/inputs/menu-select.ts
/area ui
/kind feature
为 FormKit 添加菜单选择输入类型
```release-note
为 FormKit 添加菜单选择输入类型
```
> feat: add menu select form item

- application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
- application/src/test/java/run/halo/app/theme/ThemeLocaleContextResolverTest.java
/kind bug
/area theme
If we pass a query `language` while requesting index page, we will get the wrong header `Content-Language`. Please see the result below:
```bash
http https://www.halo.run/\?language\=zh-CN -p h
Content-Language: und
...
```
After fixing, we will get the right header `Content-Language`.
```bash
http http://localhost:8090/\?language\=zh-CN -p h
Content-Language: zh-CN
...
```
```release-note
修复主题端区域和语言解析错误的问题
```
> Fix the problem of resolving locale context by language parameter

- api/src/main/java/run/halo/app/core/extension/attachment/Policy.java
- application/src/main/java/run/halo/app/core/attachment/PolicyConfigChangeDetector.java
- application/src/main/java/run/halo/app/core/attachment/reconciler/PolicyReconciler.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/main/resources/extensions/attachment-local-policy.yaml
- application/src/test/java/run/halo/app/core/attachment/PolicyConfigChangeDetectorTest.java
/area core
当存储策略的配置变更后自动触发关联附件的状态更新
Fixes #6636
```release-note
当存储策略的配置变更后自动触发关联附件的状态（如访问链接等）更新
```
> Trigger attachment status update on storage policy config change

- application/src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
- application/src/main/java/run/halo/app/infra/exception/RequestRestrictedException.java
- application/src/main/resources/config/i18n/messages.properties
- application/src/main/resources/config/i18n/messages_zh.properties
/area core
不允许回复未通过审核的评论
```release-note
禁止非管理员回复未通过审核的评论
```
> refactor: prevent replies to comments that are pending approval

- ui/src/formkit/inputs/select/SelectOption.vue
/area ui
优化了 Formkit 中的 selec 组件，使得其使用快捷键与鼠标选中的预选状态始终只有一个。且在多选状态下按回车时，不再预选跳转至第一个选项。
在多选状态下测试使用键盘进行预选及使用鼠标 hover 进行预选的状态是否符合预期。
Fixes #6600
```release-note
优化 Formkit select 组件在多选状态下的待选中状态。
```
> pref: improve hover and pre-selection state for formkit select

- application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
- application/src/test/java/run/halo/app/theme/ThemeLocaleContextResolverTest.java
/area theme
This PR simplifies ThemeLocaleContextResolver by removing unused attributes. 
In another PR <https://github.com/halo-dev/halo/pull/6647>, fixed locale resolution for query parameter `language`. This PR fixes locale resolution for cookie `language` as well.
Please see the results below:
```bash
http https://www.halo.run/ Cookie:language=zh-CN -p h
Content-Language: und
```
```bash
http http://localhost:8090 Cookie:language=zh-CN -p h
Content-Language: zh-CN
```
```release-note
None
```
> Simplify ThemeLocaleContextResolver

- ui/packages/editor/src/styles/base.scss
/area ui
/kind bug
修复编辑器中有序列表的样式问题。
Fixes #6615 
```release-note
修复编辑器中有序列表的样式问题。
```
> fix: correct ordered list styling issue in editor

- application/src/main/java/run/halo/app/webfilter/LocaleChangeWebFilter.java
- application/src/test/java/run/halo/app/webfilter/LocaleChangeWebFilterTest.java
/area core
This PR adds support changing locale using query `language`. After passing the query, we will automatically respond a cookie `language` back to browser.
Please see the result below:
```bash
http http://localhost:8090/\?language\=zh-CN Accept:text/html -p h
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Language: zh-CN
Content-Type: text/html
Expires: 0
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
content-encoding: gzip
content-length: 4765
set-cookie: language=zh-CN; Path=/; Secure
set-cookie: …
```
> Support changing locale using query language

- application/src/main/java/run/halo/app/theme/message/ThemeMessageResolver.java
- application/src/test/java/run/halo/app/theme/message/ThemeMessageResolutionUtilsTest.java
- application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
- application/src/test/resources/themes/default/i18n/default.properties
- application/src/test/resources/themes/default/i18n/zh.properties
- application/src/test/resources/themes/default/templates/index.html
- application/src/test/resources/themes/default/templates/index.properties
- application/src/test/resources/themes/default/templates/index_zh.properties
/kind feature
/area theme
/sig docs
After this PR, we can define i18n message files next to the template file.
```yaml
i18n:
default.properties
templates:
index.html
index.properties # Higher properties than default.properties
index_zh.properties # Higher properties than index.properties
index_zh_CN.properties # Higher priority than index_zh.properties
```
It's convenient for plugins that define the template files.
See https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#standard-message-resolver for more.
```release-note
支持在主题中通过 Thymeleaf 默认行为实现国际化
```
> Support resolving i18n message with standard way

- application/src/main/java/run/halo/app/notification/DefaultNotificationTemplateRender.java
- application/src/test/java/run/halo/app/notification/DefaultNotificationTemplateRenderTest.java
/area core
修复 external-url 配置带了尾部斜杠导致邮件通知的查看通知链接无法访问的问题
Fixes #6655
```release-note
修复 external-url 配置带了尾部斜杠导致邮件通知的查看通知链接无法访问的问题
```
> refactor: remove trailing slash in site url for notification

- api/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionGetter.java
- api/src/main/java/run/halo/app/theme/dialect/ElementTagPostProcessor.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
- application/src/main/java/run/halo/app/theme/dialect/HaloPostTemplateHandler.java
- application/src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
- application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
- application/src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java
- application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
- application/src/test/java/run/halo/app/theme/dialect/HaloPostTemplateHandlerTest.java
/kind feature
/area plugin
This PR provides an interface ElementTagProcessor to make plugin handle element tag easily. e.g.:
```java
public class ImgTagProcessor implements ElementTagPostProcessor {
@Override
public Mono<Void> process(ITemplateContext context, IProcessableElementTag tag,
IElementTagStructureHandler structureHandler) {
var elementName = tag.getElementDefinition().getElementName();
if (!Objects.equals("img", elementName.getElementName())) {
return Mono.empty();
}
var srcAttr = tag.getAttribute("src");
if (srcAttr == null) {
return Mono.empty();
}
var newSrc = srcAttr.getValue();
// TODO rewrite src
structureHandler.setAttribute("src", newSrc);
return Mono.empty();
}
}
```
After PR merged, plugins https://github.com/webp-sh/halo-plugin-webp-cloud and …
> Provide ElementTagProcessor to handle element tag in plugin

- application/src/main/java/run/halo/app/theme/SiteSettingVariablesAcquirer.java
- application/src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
- application/src/test/java/run/halo/app/theme/SiteSettingVariablesAcquirerTest.java
/kind feature
/area theme
主题支持通过 `${site.version}` 得到 Halo 版本号
Fixes #6676
```release-note
主题支持通过 `${site.version}` 得到 Halo 版本号
```
> feat: add Halo version variable to theme model

- application/src/main/java/run/halo/app/theme/HaloViewResolver.java
- application/src/main/java/run/halo/app/theme/engine/HaloTemplateEngine.java
- application/src/main/resources/application.yaml
/area core
This PR adds chunked transfer support for rendering templates, which means that the max memory used by rendering template will be max chunk size instead of size of rendering result.
Users can define the max chunk size like below:
```yaml
spring:
thymeleaf:
reactive:
maxChunkSize: 8KB # Setting to 0 will disable the chunked response.
```
1. Try to start Halo instance
2. Execute the command like below and see if the response headers contain `transfer-encoding: chunked`:
```bash
http http://localhost:8090/ -p h
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Language: en-CN
Content-Type: text/html
Expires: 0
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Vary: Origin
Vary: …
```
> Add chunked transfer support for rendering templates

- application/src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/HaloPostTemplateHandler.java
- application/src/main/java/run/halo/app/theme/dialect/SecureTemplateContext.java
- application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
- application/src/test/java/run/halo/app/theme/dialect/HaloPostTemplateHandlerTest.java
/area core
/area plugin
This PR disables access to ApplicationContext using ITemplateContext.
```release-note
None
```
> Make ApplicationContext inaccessible in ITemplateContext

- application/src/main/java/run/halo/app/config/WebFluxConfig.java
- application/src/main/java/run/halo/app/infra/SecureRequestMappingHandlerAdapter.java
- application/src/main/java/run/halo/app/infra/SecureServerRequest.java
- application/src/main/java/run/halo/app/infra/SecureServerWebExchange.java
- application/src/main/java/run/halo/app/plugin/AggregatedRouterFunction.java
- application/src/main/java/run/halo/app/plugin/DefaultPluginRouterFunctionRegistry.java
/area core
/area plugin
Plugins can implement their own RouterFunctions and ControllerMappings, but those might expose root ApplicationContext for plugins, which is not expected.
So this PR fixes the insecure access to root ApplicationContext.
```release-note
None
```
> Make ApplicationContext inaccessible in ServerWebExchange

- application/src/main/java/run/halo/app/theme/dialect/EvaluationContextEnhancer.java
- application/src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
- application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
- application/src/test/java/run/halo/app/content/CategoryPostCountUpdaterTest.java
- application/src/test/java/run/halo/app/content/PostIntegrationTests.java
- application/src/test/java/run/halo/app/content/comment/CommentServiceImplIntegrationTest.java
- application/src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
- application/src/test/java/run/halo/app/content/comment/ReplyServiceImplIntegrationTest.java
- application/src/test/java/run/halo/app/core/endpoint/console/EmailVerificationCodeTest.java
- application/src/test/java/run/halo/app/core/endpoint/console/UserEndpointIntegrationTest.java
- application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
- application/src/test/java/run/halo/app/plugin/DefaultSettingFetcherTest.java
- application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
- application/src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
- application/src/test/java/run/halo/app/security/authorization/AuthorizationTest.java
- application/src/test/java/run/halo/app/theme/ThemeIntegrationTest.java
- application/src/test/java/run/halo/app/theme/ViewNameResolverTest.java
- application/src/test/java/run/halo/app/theme/dialect/GeneratorMetaProcessorTest.java
- application/src/test/java/run/halo/app/theme/finders/impl/CommentPublicQueryServiceImplTest.java
- application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
- application/src/test/java/run/halo/app/theme/router/PreviewRouterFunctionTest.java
- build.gradle
/kind cleanup
/area core
This PR upgrades to [Spring Boot 3.4.0-M3](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0-M3).
1. Fix the compilation error of OptimalPropertyAccess because the class has been privated in [this commit](https://github.com/spring-projects/spring-framework/commit/b4315940212b8e955215ffe09bafde228daa6eac).
2. Fix exception `org.mockito.exceptions.misusing.UnnecessaryStubbingException` for some unit tests after upgrading.
3. Replace deprecated annotations `@MockBean` and `@SpyBean` with `@MockitoBean` and `@MockitoSpyBean` respectively.
```release-note
升级 Spring Boot 至 3.4.0-M3
```
> Upgrade to Spring Boot 3.4.0-M3

- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
- ui/console-src/modules/interface/themes/components/preview/ThemePreviewModal.vue
- ui/console-src/modules/system/users/components/UserPasswordChangeModal.vue
- ui/console-src/views/system/Setup.vue
- ui/package.json
- ui/packages/api-client/package.json
- ui/packages/components/package.json
- ui/packages/components/src/components/dialog/Dialog.stories.ts
- ui/packages/components/src/components/dropdown/Draopdown.stories.ts
- ui/packages/components/src/components/dropdown/Dropdown.vue
- ui/packages/components/src/components/dropdown/DropdownItem.vue
- ui/packages/components/tsconfig.app.json
- ui/packages/editor/package.json
- ui/packages/shared/package.json
- ui/pnpm-lock.yaml
- ui/src/components/image/LazyImage.vue
- ui/src/components/video/LazyVideo.vue
- ui/tsconfig.app.json
- ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
- ui/uc-src/modules/profile/components/PasswordChangeModal.vue
- ui/uc-src/modules/profile/components/PersonalAccessTokenCreationModal.vue
/area ui
升级 UI 项目的 Vue 版本至 3.5.x。
```release-note
升级 UI 项目的 Vue 版本至 3.5.x。
```
> chore: bump vue version to 3.5

- application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
- application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
/kind feature
/area core
This PR registers a ServerWebExchangeContextFilter to make ServerWebExchange available under ContextView. The usage example is as follows:
```java
Mono.deferContextual(contextView -> {
var exchange = ServerWebExchangeContextFilter.getExchange(contextView);
assertTrue(exchange.isPresent());
return mono;
})
```
```release-note
None
```
> Support obtaining ServerWebExchange in ContextView

- ui/console-src/modules/contents/comments/CommentList.vue
- ui/console-src/modules/contents/pages/DeletedSinglePageList.vue
- ui/console-src/modules/contents/pages/SinglePageList.vue
- ui/console-src/modules/contents/posts/DeletedPostList.vue
- ui/console-src/modules/contents/posts/PostList.vue
- ui/console-src/modules/contents/posts/categories/CategoryList.vue
- ui/console-src/modules/contents/posts/tags/TagList.vue
- ui/console-src/modules/interface/menus/Menus.vue
- ui/console-src/modules/interface/menus/components/MenuList.vue
- ui/console-src/modules/interface/themes/components/list-tabs/InstalledThemes.vue
- ui/console-src/modules/interface/themes/components/list-tabs/NotInstalledThemes.vue
- ui/console-src/modules/interface/themes/layouts/ThemeLayout.vue
- ui/uc-src/modules/contents/posts/PostList.vue
- ui/uc-src/modules/profile/tabs/PersonalAccessTokens.vue
/area ui
统一空状态界面中操作按钮的风格。
```release-note
统一空状态界面中操作按钮的风格。
```
> refactor: unified empty state UI action button styles

- ui/src/components/editor/utils/upload.ts
- ui/src/composables/use-editor-extension-points.ts
/area ui
取消异步加载默认编辑器，在之前的版本中，由于编辑器体积较大，所以做了异步加载的处理，但近期的版本中，为了让插件可以使用编辑器或者扩展编辑器，已经将编辑器依赖作为全局加载，如果这个时候还是异步加载编辑器组件的话，进入编辑页面的时候出现短暂的灰屏闪烁。
```release-note
优化默认编辑器的加载方式，防止出现灰屏闪烁的问题。
```
> refactor: remove async loading logic for editor

- ui/src/components/editor/extensions/upload/index.ts
- ui/src/components/editor/utils/upload.ts
/area ui
/kind bug
修复在 FireFox 浏览器下的编辑器中无法通过粘贴文件上传的问题。
Fixes #6684 
在 FireFox 浏览器中，复制一张本地的图片，尝试在编辑器中粘贴，观察是否上传成功。
```release-note
修复在 FireFox 浏览器下的编辑器中无法通过粘贴文件上传的问题。
```
> fix: resolve issue with editor not detecting image paste in Firefox

- application/src/main/java/run/halo/app/theme/finders/impl/ThumbnailFinderImpl.java
- application/src/test/java/run/halo/app/theme/finders/impl/ThumbnailFinderImplTest.java
/area core
修复文章封面图链接包含空格时主题端会因为生成缩略图错误而无法访问的问题
这是由于 URI string 中包含空格无法创建 URI 对象,目前将忽略这种非法参数,如果生成失败则直接返回原始 URI string
Fixes #6690
```release-note
修复文章封面图链接包含空格时主题端会因为生成缩略图错误而无法访问的问题
```
> fix: thumbnail generation for URI string containing spaces

- application/src/main/resources/static/styles/main.css
/area core
移除在 Edge 浏览器中，为密码输入框添加显示密码明文按钮。
```release-note
None
```
> feat: remove the button for viewing passwords in the Edge browser

- ui/packages/components/src/components/dialog/Dialog.stories.ts
- ui/packages/components/src/components/dialog/Dialog.vue
- ui/packages/components/src/components/dialog/dialog-manager.ts
- ui/packages/components/src/components/dialog/interface.ts
- ui/packages/components/src/components/modal/Modal.vue
/area ui
/kind feature
Dialog API 支持传入 uniqueId，以限制同一时间仅打开一个。
Fixes https://github.com/halo-dev/halo/issues/6724
```release-note
Dialog API 支持传入 uniqueId，以限制同一时间仅打开一个。
```
> feat: add support for setting uniqueId in Dialog to prevent duplicate creation

- api/src/main/java/run/halo/app/event/user/UserConnectionDisconnectedEvent.java
- application/src/main/java/run/halo/app/core/endpoint/uc/UserConnectionEndpoint.java
- application/src/main/java/run/halo/app/core/user/service/UserConnectionService.java
- application/src/main/java/run/halo/app/core/user/service/impl/UserConnectionServiceImpl.java
- application/src/main/resources/extensions/role-template-authenticated.yaml
/kind feature
/area core
This PR provides an endpoint for disconnecting user connection. After the user connection is disconnected, an event `UserConnectionDisconnectedEvent` will be published for plugins.
Now, OAuth2 plugin can simplify the authentication, binding  and unbinding logic, please see the AuthProvider configuration snippet below:
```diff
spec:
authenticationUrl: /oauth2/authorization/github
- bindingUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/connect/github
+ bindingUrl: /oauth2/authorization/github
- unbindUrl: /apis/api.plugin.halo.run/v1alpha1/plugins/plugin-oauth2/disconnect/github
+ unbindUrl: /apis/uc.api.auth.halo.run/v1alpha1/user-connections/github/disconnect
```
Please note that, OAuth2 plugin can also define binding and unbinding …
> Support unbinding OAuth2User from Halo side

- application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
- application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
- application/src/main/java/run/halo/app/security/DefaultServerAuthenticationEntryPoint.java
- application/src/main/java/run/halo/app/security/ExceptionSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/TotpAuthenticationSuccessHandler.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthenticationEntryPoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
- application/src/test/java/run/halo/app/security/DefaultServerAuthenticationEntryPointTest.java
- application/src/test/java/run/halo/app/security/HaloServerRequestCacheTest.java
/area core
/milestone 2.20.0
This PR supports query `redirect_uri` to control where to redirect after authenticated.
Fixes https://github.com/halo-dev/halo/issues/6720
Every step below needs you logging out.
1. Try to request <http://localhost:8090/console/login?redirect_uri=/xxx
2. Try to request <http://localhost:8090/login?redirect_uri=/xxx
3. Try to request <http://localhost:8090/console/posts
```release-note
None
```
> Support redirecting to page according to query after authenticated

- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
- ui/src/setup/setupApiClient.ts
/area ui
添加登录失效的引导。
```release-note
None 
```
> feat: add login expiration notification

- ui/src/components/editor/DefaultEditor.vue
/area ui
#6748 
Fixes #6748 
使英文标题中字母不被截断 
```release-note
修复文章编辑页面标题输入框中，英文字符可能会被隐藏的问题
```
> fix: prevent hidden English characters in post title input

- api/build.gradle
- application/build.gradle
- build.gradle
/area core
This PR adds [a Gradle plugin ](https://github.com/ben-manes/gradle-versions-plugin)to discover dependency updates.
```bash
❯ ./gradlew dependencyUpdates -Drevision=release
> Task :api:dependencyUpdates
------------------------------------------------------------
:api Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest release version:
- com.github.ben-manes.caffeine:caffeine:3.1.8
- com.github.java-json-tools:json-patch:1.13
- com.j256.two-factor-auth:two-factor-auth:1.3
- io.asyncer:r2dbc-mysql:1.3.0
- io.github.java-diff-utils:java-diff-utils:4.12
- io.github.resilience4j:resilience4j-reactor:2.2.0
- …
```
> Add Gradle plugin to discover dependency updates

- platform/application/build.gradle
/kind cleanup
/area core
This PR upgrades to Guava 33.3.1-jre. See https://github.com/google/guava/releases/tag/v33.3.1 for more.
```release-note
升级依赖 Guava 至 33.3.1-jre
```
> Upgrade to Guava 33.3.1-jre

- application/src/main/resources/extensions/attachment-local-policy.yaml
- ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
- ui/src/constants/finalizers.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area core
为系统默认的存储策略添加保护措施，不允许删除。
```release-note
为系统默认的存储策略添加保护措施，不允许删除。
```
> feat: disallow deletion of system-protected attachment policies

- ui/console-src/modules/system/roles/components/RoleEditingModal.vue
- ui/src/constants/annotations.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
See #6774 
Fixes #6774 
```release-note
移除角色的 **登录之后默认跳转位置** 设置选项。
```
> refactor: remove redirect-on-login setting option from role editing form

- api-docs/openapi/v3_0/aggregated.json
- api-docs/openapi/v3_0/apis_uc.api_v1alpha1.json
- application/src/main/java/run/halo/app/content/PostService.java
- application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
- application/src/main/java/run/halo/app/core/endpoint/uc/UcPostEndpoint.java
- application/src/main/resources/extensions/role-template-uc-content.yaml
- ui/packages/api-client/src/api/post-v1alpha1-uc-api.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
- ui/uc-src/modules/contents/posts/components/PostListItem.vue
/kind feature
/area core
新增 API 用于删除自己的文章
Fixes #5851
```release-note
支持在个人中心的文章管理界面删除用户创建的文章
```
> feat: support deleting posts in user center

- ui/src/formkit/inputs/user-select.ts
/area ui
/milsetone 2.20.x
在 userSelect 查询用户列表时，移除匿名与已删除用户这两个保留用户。
在文章设置，用户列表中不存在匿名与已删除用户即可。
Fixes #6665 
```release-note
在 user select 中不再显示匿名与已删除用户。
```
> pref: remove anonymous and ghost users from the userSelect

- ui/packages/components/src/components/modal/Modal.vue
/area ui
/kind bug
修复 Code 输入框在模态框（VModal）组件中无法正常全屏显示的问题。
Fixes https://github.com/halo-dev/halo/issues/6682
```release-note
修复 Code 输入框在模态框（VModal）组件中无法正常全屏显示的问题。
```
> fix: resolve issue with code input can not displaying fullscreen in modal component

- application/src/main/resources/application.yaml
- application/src/test/java/run/halo/app/XForwardHeaderTest.java
/kind bug
/area core
This PR changes server.forward-header-strategy to native instead of framework due to a bug of Spring Framework 6.20.0-RC.1.
See https://github.com/spring-projects/spring-framework/pull/32097#discussion_r1791264218 for more.
If Halo server is proxied by OpenResty which is using HTTP 2, all header names proxied into Halo server will be lowercase. This behavior makes Halo get a null header(e.g.:: `content-type: application/json`) while invoking `request.getHeaders().getContentType()`.
And I found that `ServerHttpRequest` is mutated by `org.springframework.web.server.adapter.ForwardedHeaderTransformer`, so I try to use native forward-header-strategy to resolve the problem and it works very well. See …
> Fix the problem of not being able to resolve headers correctly

- application/src/main/resources/templates/gateway_modules/form_fragments.html
/area core
优化重置密码表单的错误提示样式。
```release-note
None
```
> refactor: improve error message styling for reset password form

- ui/src/formkit/inputs/code/CodeInput.vue
/area ui
/kind bug
为 Code Input 设置默认高度，修复全屏按钮被遮挡的问题。
Fixes https://github.com/halo-dev/halo/issues/6681
```release-note
为 Code Input 设置默认高度，修复全屏按钮被遮挡的问题。
```
> fix: style issue of the fullscreen button in Code input

- application/src/main/resources/templates/gateway_modules/form_fragments.html
- application/src/main/resources/templates/gateway_modules/form_fragments.properties
- application/src/main/resources/templates/gateway_modules/form_fragments_en.properties
- application/src/main/resources/templates/gateway_modules/form_fragments_es.properties
- application/src/main/resources/templates/gateway_modules/form_fragments_zh_TW.properties
/area core
/kind bug
修复注册时，不能正常显示用户名重复的错误的问题。
```release-note
None
```
> fix: can not display error message for duplicate username during signup

- ui/console-src/modules/system/users/components/UserCreationModal.vue
/area ui
/kind bug
修复创建用户表单的用户名长度校验不生效的问题。
```release-note
修复创建用户表单的用户名长度校验不生效的问题。
```
> fix: username length validation in user creation form is not working

- application/src/main/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpoint.java
/area core
修复当用户通知偏好设置中出现不存在的通知器名称时会导致 NPE 的问题
此问题可能发生在，通知器由插件或者专业版提供并且修改了偏好设置后禁用了插件或切换到开源版导致找不到该通知器的记录
```release-note
None
```
> fix: avoid NPE by skipping nonexistent notifiers in user preferences

- application/src/main/java/run/halo/app/security/authorization/AuthorizationExchangeConfigurers.java
/kind bug
/area core
Currently, logout page is always visible for anyone whether the user is authenticated. This PR restricts the visibility of logout page to authenticated users but anonymous users.
```bash
> http http://localhost:8090/logout
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Expires: 0
Location: /login?authentication_required
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 0
content-length: 0
```
```release-note
修复未登录情况下依然能够访问登出页面的问题
```
> Fix the problem of accessing logout page without authentication

- application/src/main/resources/static/js/main.js
- application/src/main/resources/templates/gateway_modules/common_fragments.html
- application/src/main/resources/templates/gateway_modules/common_fragments.properties
- application/src/main/resources/templates/gateway_modules/common_fragments_en.properties
- application/src/main/resources/templates/gateway_modules/common_fragments_es.properties
- application/src/main/resources/templates/gateway_modules/common_fragments_zh_TW.properties
- application/src/main/resources/templates/gateway_modules/form_fragments.html
- application/src/main/resources/templates/setup.html
/area core
完善部分表单的确定密码校验。
1. 封装单独的校验函数。
2. 完善 i18n。
```release-note
None
```
> feat: improve password confirmation validation for forms

- ui/console-src/modules/system/auth-providers/AuthProviderDetail.vue
- ui/console-src/modules/system/auth-providers/components/AuthProviderListItem.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
完善内置的认证提供商详情页面的 i18n，在 https://github.com/halo-dev/halo/pull/6814 中遗漏了详情页面。
```release-note
None
```
> feat: improve built-in auth providers' i18n in detail page

- application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
- application/src/main/java/run/halo/app/theme/dialect/InjectionExcluderProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
- application/src/test/java/run/halo/app/theme/dialect/InjectionExcluderProcessorTest.java
/area core
模板 head 和 footer 标签注入功能忽略错误页面避免当扩展发生错误时导致错误页面无法显示
Fixes #6500 , #6750
```release-note
代码注入功能忽略对错误页面和登录注册等页面的注入
```
> refactor: head and footer tag injection to skip error pages

- application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
- application/src/test/java/run/halo/app/security/HaloServerRequestCacheTest.java
/kind bug
/area core
This PR supports redirecting to URI with fragment. e.g.: <http://localhost:8090/login?redirect_uri=%2F%23afragment>(redirect_uri is `/#afragment`).
Fixes #6767 
1. Request <http://localhost:8090/login?redirect_uri=%2F%23afragment>
2. Log in
3. See the redirection
```release-note
None
```
> Support redirecting to URI with fragment

- application/src/main/java/run/halo/app/core/endpoint/console/UserEndpoint.java
- application/src/main/java/run/halo/app/infra/ValidationUtils.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
/area core
优化校验提示信息根据用户选择的语言代替 `Locale#getDefault()#getLanguage()`
```release-note
None
```
> refactor: support locale-based validation messages based on users language

- application/src/main/resources/templates/gateway_fragments/password_reset_email_reset.properties
- application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_en.properties
- application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_es.properties
- application/src/main/resources/templates/gateway_fragments/password_reset_email_reset_zh_TW.properties
/area core
优化重置密码页面的密码提示文本，以 https://github.com/halo-dev/halo/blob/aab8806f0d64b4c4cd009ff0a7d9687c9207ab2a/application/src/main/resources/config/i18n/messages_zh.properties#L66 为准。
```release-note
None
```
> refactor: improve password hint text on reset password page

- application/src/main/resources/templates/gateway_fragments/signup.html
/area core
/kind bug
修复不能正常显示邮箱验证提示的问题。
```release-note
None
```
> fix: correct display of email verification message toast

- api/src/main/java/run/halo/app/theme/router/ModelConst.java
- application/src/main/java/run/halo/app/infra/utils/HaloUtils.java
- application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthTwoFactorEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
- application/src/main/java/run/halo/app/theme/HaloViewResolver.java
- application/src/test/java/run/halo/app/infra/utils/HaloUtilsTest.java
- application/src/test/java/run/halo/app/theme/ThemeIntegrationTest.java
/kind bug
/area core
This PR prevents caching from cache plugin for pre-auth pages and logout page.
Fixes #6826 
1. Install `Page Cache Plugin` from <https://www.halo.run/store/apps/app-BaamQ>.
2. Open a private browser window
3. Access login page twice
4. Try to login
5. See the result
```release-note
解决因缓存插件缓存登录页面导致无法登录的问题
```
> Do not cache template result for pre-auth pages

- application/src/main/java/run/halo/app/security/CsrfConfigurer.java
/kind bug
/area core
This PR disables CSRF protection for actuator endpoints because they are not state-changing operations.
Fixes #6827 
Try to restore Halo.
```release-note
修复恢复备份后无法自动重启的问题
```
> Disable CSRF protection for actuator endpoints

- application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
/area core
This PR adds globalInfo data into logout template model.
Fixes https://github.com/halo-dev/halo/issues/6821
```release-note
None
```
> Add globalInfo into logout page

- ui/.vscode/settings.json
- ui/console-src/modules/contents/attachments/AttachmentList.vue
- ui/console-src/modules/contents/comments/components/CommentListItem.vue
- ui/console-src/modules/contents/comments/components/ReplyListItem.vue
- ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
- ui/console-src/modules/system/plugins/components/entity-fields/ReloadField.vue
- ui/console-src/modules/system/users/components/UserCreationModal.vue
- ui/package.json
- ui/pnpm-lock.yaml
- ui/prettier.config.cjs
- ui/src/components/editor/DefaultEditor.vue
- ui/src/formkit/inputs/select/MultipleSelect.vue
- ui/src/formkit/inputs/select/SelectDropdownContainer.vue
- ui/uc-src/modules/profile/tabs/Devices.vue
/area ui
使用 https://github.com/simonhaenisch/prettier-plugin-organize-imports 优化 UI 项目的模块导入，之前我们是通过[配置 VSCode](https://github.com/halo-dev/halo/blob/9468e8741f3ed2d4c225adc8cef6c6145a8b48a9/ui/.vscode/settings.json#L34-L36) 来实现导入优化，但这种方式局限于 VSCode 编辑器，在其他编辑器无法得到统一的支持。
并且我们为 UI 添加了 git pre commit hook，在提交代码前会对已修改的文件执行 prettier，这样能够更好的保证一致性。
```release-note
None
```
> chore: add prettier-plugin-organize-imports plugin to organize imports

- application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
- application/src/test/java/run/halo/app/PathPrefixPredicateTest.java
- application/src/test/java/run/halo/app/infra/properties/HaloPropertiesTest.java
/kind bug
/area core
This PR makes users not be able to configure a invalid external URL like `https:www/halo.run` even if it is an valid URL format.
Fixes #6837 
```release-note
修复可配置无效的外部访问地址的问题
```
> Fix the problem of being able to configure invalid external URL

- application/src/main/resources/static/styles/main.css
- application/src/main/resources/templates/signup.html
/area core
优化登录等页面的 UI，主要优化低分屏下的 UI 表现，防止元素过大。
```release-note
优化登录等页面的 UI，优化低分屏下的 UI 表现，防止元素过大。
```
> refactor: improve login page ui

- application/src/main/java/run/halo/app/security/authentication/rememberme/TokenBasedRememberMeServices.java
- application/src/main/java/run/halo/app/security/authentication/rememberme/WebSessionRememberMeRequestCache.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
- application/src/main/resources/templates/gateway_fragments/login.html
/kind bug
/area core
This PR preserves `remember-me` option after authentication failure.
Fixes https://github.com/halo-dev/halo/issues/6835
1. Go to login page
2. Input invalid username or password and select `remember-me` option
3. Click `Login` button
4. See the result
```release-note
修复登录失败后记住我选项被重置的问题
```
> Preserve remember-me option after authentication failure

- api/build.gradle
- application/src/main/java/run/halo/app/core/attachment/ThumbnailGenerator.java
- platform/application/build.gradle
/area core
修复竖向图片生成缩略图后会丢失方向信息展示为横向图片的问题
Fixes #6802
```release-note
修复竖向图片生成缩略图后会丢失方向信息展示为横向图片的问题
```
> fix: vertical images are rotated to horizontal when generating thumbnails

- application/src/main/java/run/halo/app/plugin/PluginServiceImpl.java
/area core
忽略预设插件安装时的错误避免无法初始化
可能因为没有预先 download 预设插件到项目目录而发生 IO 异常影响初始化流程
```release-note
None
```
> chore: ignore preset plugin installation errors to avoid initialization failure

- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
/kind bug
/area core
This PR fills operation ID while building setup route to prevent errors when generating OpenAPI docs.
```java
2024-10-13T22:09:46.997+08:00 ERROR 68966 --- [     parallel-4] a.w.r.e.AbstractErrorWebExceptionHandler : [88654f05-3]  500 Server Error for HTTP GET "/v3/api-docs/apis_aggregated.api_v1alpha1"
java.lang.IllegalStateException: You should either fill, the Operation or at least the bean class and the bean method
at org.springdoc.core.fn.builders.operation.Builder.build(Builder.java:467) ~[springdoc-openapi-starter-common-2.6.0.jar:2.6.0]
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
```
```release-note
None
```
> Fill operation ID while building setup route

- ui/src/components/alerts/H2WarningAlert.vue
/area ui
before:
after:
```release-note
None
```
> refactor: remove underline in h2 warning alert

- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
/area core
/kind bug
修复初始化登录之后，没有正确重定向到 /console 的问题。
Fixes #6850 
```release-note
None
```
> fix: not redirect to /console after setup

- application/src/main/resources/extensions/system-configurable-configmap.yaml
/area core
/kind bug
修复首次初始化之后，个人中心使用的附件存储策略没有默认值的问题。
Fixes #6834 
```release-note
None
```
> fix: set default value for attachment storage policy in user center

- api-docs/openapi/v3_0/aggregated.json
- api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
- api-docs/openapi/v3_0/apis_extension.api_v1alpha1.json
- api/src/main/java/run/halo/app/core/extension/AuthProvider.java
- api/src/main/java/run/halo/app/extension/Unstructured.java
- api/src/main/java/run/halo/app/infra/SystemSetting.java
- application/src/main/java/run/halo/app/security/AuthProviderService.java
- application/src/main/java/run/halo/app/security/AuthProviderServiceImpl.java
- application/src/main/java/run/halo/app/security/ListedAuthProvider.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
- application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
- ui/console-src/modules/system/auth-providers/AuthProviders.vue
- ui/console-src/modules/system/auth-providers/components/AuthProvidersSection.vue
- ui/console-src/modules/system/auth-providers/module.ts
- ui/console-src/modules/system/users/UserList.vue
- ui/packages/api-client/src/models/auth-provider-spec.ts
- ui/packages/api-client/src/models/listed-auth-provider.ts
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area core
重构认证方式列表的排序
```release-note
重构认证方式列表的排序（此为破坏性更新，需要重新启用以前的 OAuth 认证）
```
> refactor: auth provider sorting logic for better maintainability and clarity

- api/src/main/java/run/halo/app/infra/SystemSetting.java
- application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
/kind bug
/area core
恢复 https://github.com/halo-dev/halo/pull/6846 中删除的 SystemSetting.AuthProvider#enabled 字段避免插件应用到了它可能会发生错误，将其标记为过时
```release-note
None
```
> fix: retain legacy enabled field for auth provider setting

- application/src/main/java/run/halo/app/security/AuthProviderServiceImpl.java
- application/src/main/resources/extensions/system-configurable-configmap.yaml
- application/src/test/java/run/halo/app/security/AuthProviderServiceImplTest.java
/kind bug
/area core
修复初始化 Halo 之后无法进入登录页面的问题
此问题原因是更改了 AuthProvider 的逻辑，当系统启动之后缺少默认的登录方式导致登录页面无法正确渲染
此 PR 将确保默认的登录方式始终存在来解决此问题
重新初始化 Halo 之后能正确渲染登录页面并登录即为符合预期
```release-note
修复初始化 Halo 之后无法进入登录页面的问题
```
> fix: preventing access to login page after Halo setup

- application/src/main/resources/extensions/role-template-authenticated.yaml
/kind bug
/area core
This PR corrects typo of `apisGroups` to `apiGroups` to fix the problem of not being able to disconnect OAuth2 user.
0. Install OAuth2 plugin
1. Log in as a normal user
2. Bind a OAuth2 user
3. Try to unbind it
```release-note
修复无法正常解绑 OAuth2 用户
```
> Fix the problem of not being able to disconnect OAuth2 user

- application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java
- application/src/main/java/run/halo/app/security/authorization/AuthorityUtils.java
- application/src/test/java/run/halo/app/security/authorization/AuthorityUtilsTest.java
/kind bug
/area core
This PR refactors check of whether the current user is a real user to fix the problem of not being able to create PAT for OAuth2 user.
```release-note
修复通过 OAuth2 登录之后无法正常创建和恢复个人令牌的问题
```
> Fix the problem of not being able to create PAT for OAuth2 user

- application/src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/GlobalHeadInjectionProcessor.java
- application/src/main/java/run/halo/app/theme/dialect/HaloPostTemplateHandler.java
- application/src/main/java/run/halo/app/theme/dialect/SecureTemplateContextWrapper.java
- application/src/main/java/run/halo/app/theme/dialect/SecureTemplateWebContext.java
- application/src/main/java/run/halo/app/theme/dialect/TemplateFooterElementTagProcessor.java
- application/src/test/java/run/halo/app/theme/dialect/HaloPostTemplateHandlerTest.java
/kind bug
/area core
修复由 #6680 导致的插件模板处理扩展中无法获取到请求上下文的问题
#6680 修复了插件可以在模板处理扩展中通过请求上下文获取到 Halo 的 ApplicationContext 的问题
但这也引入了新的问题就是导致模板处理扩展无法获取到请求上下文，此 PR 通过判断传递给插件的 ITemplateContext 是否为 IWebContext，如果是则包装为 SecureTemplateWebContext 传递给插件，以解决此问题
Fixes #6875
```release-note
修复插件模板处理扩展中无法获取到请求上下文的问题
```
> fix: missing ServerWebExchange in plugin template processor extension

- application/build.gradle
/area core
Bump app store plugin to 1.6.0
```release-note
None
```
> chore: bump app store plugin version

- application/src/main/java/run/halo/app/theme/service/ThemeServiceImpl.java
/kind bug
/area core
修复从旧版本升级到 2.20 会因为默认主题目录已经存在而无法初始化的问题
Fixes #6887
```release-note
修复从旧版本升级到 2.20 会因为默认主题目录已经存在而无法初始化的问题
```
> fix: prevent initialization failure when theme directory already exists

- application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
/kind bug
/area core
This PR appends query `method=local` after redirection location in authentication failure handler to redirect to login page with local method.
Fixes https://github.com/halo-dev/halo/issues/6894
```release-note
修复非默认登录方式登录失败之后跳转至默认登录方式的问题
```
> Fix the problem of not redirecting to corresponding login page after authentication failure

- api/src/main/java/run/halo/app/core/user/service/SignUpData.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
/area core
This PR refactors sign up data binding using internal `bind` method in `ServerRequest` instead of binding my hand. It's more convenient and simpler.
```release-note
None
```
> Bind sign up data instead of building by hand

- application/src/main/resources/schema-mariadb.sql
- application/src/main/resources/schema-mysql.sql
/area core
将 MySQL 的表创建脚本 name 列字符集改为 utf8mb4_bin 以使其对大小写敏感
Fixes https://github.com/halo-dev/halo/issues/4372
**how to test it?**
使用 docker 运行 MySQL
```shell
docker run --name mysql-test -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=halo -p 3306:3306 --rm -d mysql:latest
```
然后执行表创建脚本并手动执行以下两条 SQL 能成功插入
```sql
insert into extensions(name,data,version) values('a', 'a', 0)
insert into extensions(name,data,version) values('A', 'A', 0)
```
```release-note
修改 MySQL 表创建脚本 name 列的字符集使其大小写敏感以解决可能会遇到切换数据库时因为数据冲突而无法导入备份的问题（这只对此版本及之后的新用户有效）
```
> fix: modify name column charset to make it case-sensitive for MySQL

- ui/console-src/modules/contents/pages/SinglePageEditor.vue
- ui/console-src/modules/contents/posts/PostEditor.vue
/area ui
/kind bug
修复通过登录跳转到文章编辑页面时，发布文章会跳转到个人中心的问题。
Fixes #6901 
测试步骤：
1. 新建文章，编写内容，但是不发布
2. 在新的浏览器选项卡中退出登录
3. 回到文章编辑页面，跳转到登录页面重新登录之后，发布文章
4. 观察是否会返回到 Console 的文章管理页面。
```release-note
修复通过登录跳转到文章编辑页面时，发布文章会跳转到个人中心的问题。
```
> fix: can not return to post list after publishing when re-logged in

- application/src/main/resources/static/styles/main.css
/area core
/kind bug
修复在低版本 Safari 浏览器中，注册表单中的按钮高度溢出的问题。
Fixes #6910 
```release-note
修复在低版本 Safari 浏览器中，注册表单中的按钮高度溢出的问题。
```
> fix: resolve button height overflow in signup form on older Safari

- application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
/area core
This PR excludes console and uc assets in security configuration to make them access by anonymous users.
Fixes https://github.com/halo-dev/halo/issues/6908
```bash
http http://localhost:8090/uc/assets/index-E-uvwInx.css -ph
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Encoding: gzip
Content-Length: 26213
Content-Type: text/css
Vary: Accept-Encoding
```
```release-note
None
```
> Exclude console and uc assets in security configuration

- ui/console-src/composables/use-slugify.ts
- ui/console-src/modules/contents/pages/components/SinglePageSettingModal.vue
- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
- ui/console-src/modules/contents/posts/components/PostSettingModal.vue
- ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
- ui/uc-src/modules/contents/posts/components/PostSettingForm.vue
/area ui
/kind bug
修复文章自动生成别名不按照别名生成策略生成的问题。
Fixes #6913 
需要测试：
1. 分类、标签创建和更新时的别名生成
2. 文章新建时，别名是否按照生成策略生成。
```release-note
修复文章自动生成别名不按照别名生成策略生成的问题。
```
> fix: post slug generation not following selected strategy

- application/src/main/java/run/halo/app/infra/properties/ConsoleProperties.java
- application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
/area core
This PR adds the annotations `@NestedConfigurationProperties` to let Spring Configuration Processor generate fully metadata.
We can execute command `./gradlew :application:compileJava` to generate `application/build/classes/java/main/META-INF/spring-configuration-metadata.json`. If you are using IDEA Ultimate, configuration hints related to Halo will be available.
```release-note
None
```
> Support nested configuration properties

- .github/actions/docker-buildx-push/action.yaml
- .github/workflows/halo.yaml
/area core
This PR adds Fit2Cloud Docker Registry into build stage in Halo workflow.
Before it works, we need to configure Action secrets `F2C_REGISTRY_USER` and `F2C_REGISTRY_TOKEN` in current repository.
```release-note
None
```
> Support pushing Docker image into Fit2Cloud Docker Registry

- application/src/main/java/run/halo/app/infra/webfilter/LocaleChangeWebFilter.java
/kind bug
/area core
修复登录时切换了其他语言但是登录成功后始终显示中文的问题
此问题为 https://github.com/halo-dev/halo/pull/6891 导致
```release-note
修复登录时切换了其他语言但是登录成功后始终显示中文的问题
```
> fix: remove httpOnly from language cookie to allow JS to access current language

- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
/kind bug
/area core
修复使用 `singlePageFinder.list()` 时会提示缺少 spec.deleted 索引的问题
Fixes #6919
```release-note
修复使用 `singlePageFinder.list()` 时会提示缺少 spec.deleted 索引的问题
```
> fix: missing deleted index in list method of single page finder

- application/src/main/java/run/halo/app/security/preauth/PreAuthEmailPasswordResetEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthLoginEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthTwoFactorEndpoint.java
- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
/kind bug
/area core
修复登录页面路由会被自定义页面覆盖导致无法登录的问题
Fixes #6893
```release-note
修复登录页面路由会被自定义页面路由覆盖导致无法登录的问题
```
> fix: prioritize login page route to prevent single page override

- api/src/main/java/run/halo/app/core/user/service/UserPostCreatingHandler.java
- api/src/main/java/run/halo/app/core/user/service/UserPreCreatingHandler.java
- application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
- application/src/test/java/run/halo/app/core/user/service/impl/UserServiceImplTest.java
/kind feature
/area core
This PR adds support for hooking user creating. Plugin developers can define extension points of `UserPreCreatingHandler` and `UserPostCreatingHandler` to do something else.
```release-note
支持在插件中定义用户创建的前置和后置处理器
```
> Support hooking user creation

- ui/src/components/icon/AttachmentFileTypeIcon.vue
在附件，列表模式中，为 jpeg 后缀文件添加图标。
Fixes #
```release-note
为 jpeg 后缀文件添加图标
```
> feat: add supports for displaying jpeg icon in attachments list

- application/src/main/java/run/halo/app/security/CorsConfigurer.java
- application/src/main/java/run/halo/app/security/CsrfConfigurer.java
- application/src/main/java/run/halo/app/security/ExceptionSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/LogoutSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/SecurityWebFiltersConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/login/LoginSecurityConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/oauth2/OAuth2SecurityConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/rememberme/RememberMeConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/twofactor/TwoFactorAuthSecurityConfigurer.java
/area core
This PR rearranges order of security configurers. Especially, SecurityWebFiltersConfigurer has lower priority to configure than other security configurers.
So we can catch internal authentication in plugins.
```release-note
None
```
> Rearrange order of security configurers

- ui/src/formkit/inputs/secret/SecretSelect.vue
- ui/src/formkit/inputs/secret/components/SecretCreationModal.vue
/area ui
/kind bug
修复使用 Secret 输入框创建 Secret 时，stringData 的 key 可能为 undefined 的问题。
See https://github.com/halo-sigs/plugin-alist/issues/23#issuecomment-2443499980 for more
```release-note
修复使用 Secret 输入框创建 Secret 时，stringData 的 key 可能为 undefined 的问题。
```
> fix: prevent undefined key name when creating Secret

- ui/console-src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
- ui/console-src/modules/contents/attachments/components/AttachmentGroupList.vue
- ui/console-src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
- ui/console-src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
- ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
在创建附件分组或者存储策略时，支持检查是否有已存在的名称。
Fixes #6946
```release-note
在创建附件分组或者存储策略时，支持检查是否有已存在的名称。
```
> feat: add name existence check before creating attachment group and storage policy

- api/src/main/java/run/halo/app/extension/MetadataUtil.java
- application/src/main/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpoint.java
- application/src/main/resources/extensions/notification.yaml
- application/src/test/java/run/halo/app/notification/endpoint/UserNotificationPreferencesEndpointTest.java
/area core
隐藏关键通知项设置以避免用户意外禁用而无法收到通知
Fixes #6967
```release-note
隐藏关键通知项设置以避免用户意外禁用而无法收到通知
```
> refactor: hide essential notifications to prevent accidental disabling

- application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java
- application/src/main/java/run/halo/app/security/CorsConfigurer.java
/area core
This PR adds CorsOptions into SecurityProperties to let users customize their own CORS configuration. e.g.:
```yaml
halo:
security:
cors-options:
disabled: false
configs:
- pathPattern: /apis/first.api.halo.run/v1alpha1/**
config:
allowedOrigins: [ "*" ]
allowedHeaders: [ "*" ]
allowedMethods: [ "*" ]
exposedHeaders: [ "*" ]
allowCredentials: true
maxAge: 30m
- pathPattern: /apis/second.api.halo.run/v1alpha1/**
config:
allowedOrigins: [ "www.halo.run", "www.lxware.cn" ]
allowedHeaders: [ "Content-Type", "Authorization" ]
allowedMethods: [ "GET, POST, PUT, DELETE" ]
allowedCredentials: false
maxAge: 1h
```
```release-note
支持自定义跨域配置
```
> Support customizing CORS configuration

- application/src/main/java/run/halo/app/core/reconciler/TagReconciler.java
- application/src/main/java/run/halo/app/theme/finders/vo/TagVo.java
/area core
修复新创建的标签在主题端展示关联文章数量为 null 的问题
Fixes #7042
```release-note
修复新创建的标签在主题端展示关联文章数量为 null 的问题
```
> fix: new tags showing null post count on theme

- application/src/main/java/run/halo/app/theme/TemplateEngineManager.java
/kind bug
/area core
This PR removes template engine instead of clearing cache of template engine after upgrading theme to resolve incomplete cache clear.
Fixes https://github.com/halo-dev/halo/issues/7056
1. Try to install the theme `theme-earth 1.12.0`
2. Request index page and you will see the `上一页` which should be `下一页`
3. Try to upgrade to the theme `theme-earth 1.12.1`
4. Request index page and you should see the `下一页` directly. 
```release-note
修复升级主题后语言包未更新的问题
```
> Remove template engine after upgrading theme

- build.gradle
This PR upgrades to [Spring Boot 3.4.0](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.0).
/kind cleanup
/area core
```release-note
升级依赖至 Spring Boot 3.4.0
```
> Upgrade to Spring Boot 3.4.0

- application/src/main/java/run/halo/app/core/attachment/extension/LocalThumbnail.java
- application/src/main/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImpl.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/test/java/run/halo/app/core/attachment/impl/LocalThumbnailServiceImplTest.java
/area core
对本地缩略图的原图链接和尺寸增加唯一性检查避免重复
```release-note
对本地缩略图的原图链接和尺寸增加唯一性检查避免重复
```
> refactor: add uniqueness check for local thumbnail original links and dimensions to avoid duplication

- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
完善角色模板的 i18n。
```release-note
完善角色模板的 i18n。
```
> feat: improve role template i18n

- ui/src/components/form/AnnotationsForm.vue
/kind bug
/area ui
修复文章元数据表单在 Chrome 下的异常样式。
原因：https://developer.chrome.com/blog/styling-details#demo
```release-note
修复文章元数据表单在 Chrome 下的异常样式。
```
> fix: post annotations form layout issues in Chrome browser

- ui/console-src/modules/system/backup/tabs/Restore.vue
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
为通过备份文件恢复的界面添加空状态提示。
```release-note
为通过备份文件恢复的界面添加空状态提示。
```
> feat: add empty state for restore by backups

- application/src/main/java/run/halo/app/core/attachment/ThumbnailMigration.java
- application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/test/java/run/halo/app/core/attachment/impl/ThumbnailServiceImplTest.java
/area core
修复可能为因为并发调用缩略图生成导致多次创建缩略图的问题
此 PR 为 #7031 的补充，并且会清理以前重复生成的缩略图记录和文件
```release-note
修复可能为因为并发调用缩略图生成导致多次重复缩略图记录的问题
```
> fix: resolve concurrency issue causing duplicate thumbnail generation

- application/src/main/java/run/halo/app/content/HtmlThumbnailSrcsetInjector.java
- application/src/main/java/run/halo/app/core/attachment/ThumbnailService.java
- application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
- application/src/main/java/run/halo/app/core/endpoint/theme/ThumbnailEndpoint.java
- application/src/main/java/run/halo/app/theme/finders/impl/ThumbnailFinderImpl.java
- application/src/test/java/run/halo/app/core/endpoint/theme/ThumbnailEndpointTest.java
- application/src/test/java/run/halo/app/theme/finders/impl/ThumbnailFinderImplTest.java
/area core
限制缩略图生成仅针对附件库中的图片，防止任意 URI 的生成行为带来的潜在攻击风险
先 merge #7077 后才能合并此 PR
```release-note
限制缩略图生成仅针对附件库中的图片，防止任意 URI 的生成行为带来的潜在攻击风险
```
> fix: restrict thumbnail generation to images in the attachment library

- ui/package.json
/area ui
为 UI 项目添加 packageManager 字段，以支持 [corepack](https://nodejs.org/api/corepack.html)。
Fixes https://github.com/halo-dev/halo/issues/6635
```release-note
为 UI 项目添加 packageManager 字段，以支持 [corepack](https://nodejs.org/api/corepack.html)。
```
> chore: add packageManager for corepack

- application/src/main/java/run/halo/app/security/authorization/RequestInfoFactory.java
/area core
统一使用同一个 RequestPath 来解析请求信息
```release-note
None
```
> chore: standardize request parsing to use a single path handler

- application/src/main/java/run/halo/app/core/endpoint/console/SystemConfigEndpoint.java
- application/src/main/java/run/halo/app/core/reconciler/SystemSettingReconciler.java
- application/src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
- application/src/test/java/run/halo/app/core/reconciler/SystemSettingReconcilerTest.java
- application/src/test/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcherTest.java
/area core
为系统配置获取增加缓存以提高路由和主题模板渲染的速度
1. 系统能正确初始化
2. 测试修改系统配置后 http://localhost:8090/actuator/globalinfo 和主题端 `${site}` 是否都是新的
3. 更改了文章路由规则后能正确调整到新的规则
```release-note
为系统配置的获取增加缓存以提高路由和主题模板渲染的速度
```
> perf: add caching for system configuration fetcher to enhance performance

- application/src/main/java/run/halo/app/plugin/extensionpoint/AbstractDefinitionGetter.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionDefinitionGetter.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionDefinitionGetterImpl.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionPointDefinitionGetter.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/ExtensionPointDefinitionGetterImpl.java
- application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
/area core
为扩展获取增加缓存以提高网站整体性能
在此之前，每个请求都要经过很多过滤器，而一些过滤器会获取扩展因此导致频繁查询扩展和扩展点定义拖慢了速度
**测试情况**
初始化一个全新环境，安装并启用以下插件和主题
- 已激活主题: [Earth 1.11.0](https://github.com/halo-dev/theme-earth)
- 已启动插件:
- [SEO 工具集 1.0.1](https://github.com/f2ccloud/plugin-seo-tools)
- [OAuth2 认证 1.5.0](https://github.com/halo-sigs/plugin-oauth2)
- [Trailing Slash 1.0.0](https://github.com/halo-sigs/plugin-trailing-slash)
- [评论组件 2.5.1](https://github.com/halo-dev/plugin-comment-widget)
- [KaTeX 2.1.0](https://github.com/halo-sigs/plugin-katex)
- [应用市场 1.9.0](https://www.halo.run/store/apps/app-VYJbF)
通过 Apache Benchmark (ab) 进行 1w 次请求并发 100 个，测试访问首页，得到以下测试结果：
核心指标对比
|指标|改进前|改进后|提升情况|
|---|---|---|---|
|**总耗时 (Time taken)**|27.030 秒|25.718 秒|减少约 **4.9%**|
|**每秒请求数 (RPS)**|369.96 …
> perf: add caching for extension getter to enhance performance

- ui/package.json
- ui/pnpm-lock.yaml
- ui/src/vite/config-builder.ts
/area ui
/kind cleanup
移除 UI 项目内置的 Vue Devtools，后续建议使用浏览器插件代替：https://chromewebstore.google.com/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd
```release-note
None
```
> chore: remove vue devtools

- application/src/main/java/run/halo/app/core/reconciler/PluginReconciler.java
- application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
- application/src/main/java/run/halo/app/plugin/OptionalDependentResolver.java
- application/src/main/java/run/halo/app/plugin/PluginApplicationContext.java
- application/src/main/java/run/halo/app/plugin/PluginService.java
- application/src/main/java/run/halo/app/plugin/PluginServiceImpl.java
- application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
- application/src/test/java/run/halo/app/core/reconciler/PluginReconcilerTest.java
- application/src/test/java/run/halo/app/plugin/OptionalDependentResolverTest.java
- application/src/test/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetterTest.java
/kind bug
/area core
修复可选插件依赖功能无法正常工作的问题
使用以下两个插件测试可选依赖：
[测试插件集合.zip](https://github.com/user-attachments/files/17989250/default.zip)
使用以下测试用例进行测试：
测试用例1：plugin-feed 插件提供 RSS 扩展功能
- **前置条件：**  
安装并启用 `plugin-feed` 插件。
- **操作步骤：**  
访问 `http://localhost:8090/feed/rss.xml`。
- **期望结果：**  
返回 `plugin-feed` 提供的 RSS 内容。
---
测试用例 2: plugin-moments 扩展了 plugin-feed 的 RSS 功能（依赖于 plugin-feed）
- **前置条件：**  
安装并启用 `plugin-feed` 和 `plugin-moments` 插件。
- **操作步骤：**  
访问 `http://localhost:8090/feed/moments/rss.xml`。
- **期望结果：**  
返回 `plugin-moments` 提供的 RSS 内容。
---
测试用例 3: plugin-feed 启用时安装 plugin-moments
- **前置条件：**  
启用 `plugin-feed` 插件。
- **操作步骤：**
1. 安装 `plugin-moments` 插件。
2. 访问 `http://localhost:8090/feed/moments/rss.xml`。
- **期望结果：**  
`plugin-moments` 提供的 RSS 路由可访问，并返回正确内容。
--- …
> fix: optional plugin dependencies not working correctly

- api/src/main/java/run/halo/app/infra/SystemInfo.java
- api/src/main/java/run/halo/app/infra/SystemInfoGetter.java
- application/src/main/java/run/halo/app/infra/SystemInfoGetterImpl.java
- application/src/main/java/run/halo/app/plugin/SharedApplicationContextFactory.java
/area core
为插件提供 SystemInfoGetter 用于获取站点基本信息
站点标题描述和系统版本这些信息对于插件来说是很有必要的避免插件要直接查询 system ConfigMap 来获取，如 RSS 和 通知器扩展等插件都会需要用到
```json
{
"title" : "guqing's blog",
"subtitle" : "副标题",
"logo" : "/upload/myavatar.png",
"favicon" : "/upload/myavatar.png",
"url" : "http://localhost:8090",
"version" : {
"majorVersion" : 2,
"minorVersion" : 20,
"normalVersion" : "2.20.10",
"preRelease" : true,
"publicApiStable" : true,
"patchVersion" : 10,
"preReleaseVersion" : "SNAPSHOT",
"buildMetadata" : "",
"stable" : false
},
"seo" : {
"blockSpiders" : false,
"keywords" : "keyword1,keyword2",
"description" : "站点描述"
},
"locale" : "zh_CN_#Hans",
"timeZone" : "Asia/Shanghai",
"activatedThemeName" : "theme-earth"
}
```
```release-note
开发者相关：为插件提供 SystemInfoGetter 用于获取站点基本信息 …
```
> feat: add system info getter for plugin

- api/build.gradle
- buildSrc/src/main/groovy/halo.publish.gradle
- platform/application/build.gradle
- platform/plugin/build.gradle
/kind bug
/area core
When I tried to publish Maven publications into OSSHR <https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/>, I couldn't close and release the opening staging repository because our Maven publications didn't meet the requirements of OSSHR, for example, `Sign Files with GPG/PGP` and `Project Name, Description and URL`.
This PR tries to fix those problem and all checks will pass. You can check it from <https://central.sonatype.com/artifact/run.halo.app/api/overview>.
> https://central.sonatype.org/publish/requirements/
```release-note
None
```
> Fix failing checks of staging repository when releasing to Maven

- ui/src/setup/setupApiClient.ts
/area ui
Optimize axios interceptor text/html content type detection
```release-note
None
```
> refactor: optimize axios interceptor text/html content type detection

- ui/console-src/modules/interface/themes/ThemeSetting.vue
- ui/console-src/modules/system/plugins/components/tabs/Setting.vue
/kind bug
/area ui
Prevent data clearing on FormKit component unmount
Fixes #7121 
```release-note
修复 FormKit 组件卸载时，对应数据值也被清除的问题
```
> fix: prevent data clearing on FormKit component unmount

- api/src/main/java/run/halo/app/infra/utils/FileTypeDetectUtils.java
- application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
- application/src/main/resources/config/i18n/messages.properties
- application/src/main/resources/config/i18n/messages_zh.properties
- application/src/test/java/run/halo/app/infra/utils/FileTypeDetectUtilsTest.java
/kind bug
/area core
修复文件类型限制能通过混合文件类型绕过检测的问题
参考：https://github.com/halo-dev/halo/security/advisories/GHSA-99mc-ch53-pqh9
```release-note
修复文件类型限制能通过混合文件类型绕过检测的问题
```
> fix: XSS vulnerability due to polyglot file type upload

- application/src/main/java/run/halo/app/core/reconciler/ThemeReconciler.java
- application/src/test/java/run/halo/app/core/reconciler/ThemeReconcilerTest.java
/area core
卸载主题之后清理模板缓存
此问题是 https://github.com/halo-dev/halo/pull/2970 的遗留问题
```release-note
None
```
> refactor: clear the template cache after uninstalling the theme

- ui/uc-src/modules/contents/posts/components/PostCreationModal.vue
- ui/uc-src/modules/contents/posts/components/PostListItem.vue
- ui/uc-src/modules/contents/posts/composables/use-post-publish-mutate.ts
/area ui
为 UC 端发布文章的操作添加重试机制，防止出现因为锁导致的保存失败问题。
Fixes #7139
```release-note
为 UC 端发布文章的操作添加重试机制，防止出现因为锁导致的保存失败问题。
```
> feat: add retry mechanism for publishing posts on the UC end

- application/src/main/java/run/halo/app/theme/service/ThemeServiceImpl.java
- application/src/test/java/run/halo/app/theme/service/ThemeServiceImplTest.java
/kind bug
/area core
修复主题中声明的通知模板无法被创建的问题
Fixes #7195
```release-note
修复主题中声明的通知模板无法被创建的问题
```
> fix: failure to create notification templates in themes

- api/src/main/java/run/halo/app/core/extension/content/Constant.java
- application/src/main/java/run/halo/app/core/reconciler/PostReconciler.java
- application/src/main/java/run/halo/app/core/reconciler/SinglePageReconciler.java
/area core
自动生成摘要仅对内容变更时生效
see https://github.com/halo-dev/halo/issues/7193#issuecomment-2581699190 for more details
避免对资源造成浪费如 AI 摘要生成
Fixes #7193
```release-note
自动生成摘要仅对内容发生变更时生效
```
> refactor: generate summaries only for content changes

- build.gradle
/kind cleanup
/area core
This PR upgrades to Spring Boot [3.4.2](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.2).
Supersedes of <https://github.com/halo-dev/halo/pull/7208>.
```release-note
升级依赖 Spring Boot 至 3.4.2
```
> Upgrade to Spring Boot 3.4.2

- ui/console-src/modules/system/plugins/PluginExtensionPointSettings.vue
/area ui
/kind bug
See https://github.com/halo-dev/halo/issues/7214
Fixes https://github.com/halo-dev/halo/issues/7214
```release-note
修复插件扩展配置列表底部可能被遮挡的问题。
```
> fix: prevent extension-point list from being obscured at bottom

- gradle.properties
/kind bug
/area core
This PR upgrades to R2dbc MySQL [1.4.0](https://github.com/asyncer-io/r2dbc-mysql/releases/tag/r2dbc-mysql-1.4.0) and tries to fix <https://github.com/halo-dev/halo/issues/6854>.
Fixes https://github.com/halo-dev/halo/issues/6854
```release-note
升级依赖 R2DBC MySQL 至 1.4.0
```
> Upgrade to R2DBC MySQL 1.4.0

- application/src/main/java/run/halo/app/core/attachment/impl/ThumbnailServiceImpl.java
- application/src/test/java/run/halo/app/core/attachment/impl/ThumbnailServiceImplTest.java
将 cache 移动到 doFinally 之后以确保并发控制有效，在这之前可能无法完全有效的控制并发
```release-note
None
```
> fix: move cache after doFinally to ensure effective concurrency control

- Dockerfile
- api/src/main/java/run/halo/app/extension/controller/DefaultController.java
- api/src/test/java/run/halo/app/extension/controller/DefaultControllerTest.java
- application/src/main/resources/application.yaml
/area core
This PR enables Virtual Thread for instances running on JVM 21. This won't affect instances running on JVM 17.
References:
- https://spring.io/blog/2023/10/31/what-new-is-coming-in-reactor-core-3-6-0
- https://spring.io/blog/2022/10/11/embracing-virtual-threads
- https://docs.spring.io/spring-boot/3.4/reference/features/task-execution-and-scheduling.html
```release-note
None
```
> Enable Virtual Thread when running on JVM 21

- application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
- application/src/main/java/run/halo/app/plugin/SpringPlugin.java
- application/src/main/java/run/halo/app/plugin/loader/DevPluginLoader.java
- application/src/main/java/run/halo/app/plugin/loader/HaloPluginClassLoader.java
/area core
修改插件类加载顺序遵循双亲委派机制，以避免插件需要手动排除冲突类的问题
此 PR 的动力是：
1. 插件排除依赖复杂而麻烦
2. 尝试多次无法很好的通过工具实现这一点
3. 对于一些依赖如 kotlin 何 spring security oauth 等同一 JVM 只能加载一次（即不能再次从插件加载）且插件可能无法排除依赖或排除依赖后功能不正确如遇到链接错误等
4. 签名文件冲突等问题
resources 下的资源文件加载顺序还是插件优先，避免与 halo 同名文件不加载的问题
进过测试，插件依赖功能以及其他插件的功能不受影响，建议 Reviewer 再测试一遍
```release-note
调整插件类的加载顺序使其遵循双亲委派机制，替代原先的 Plugin -> Dependent Plugin -> Halo 加载顺序
```
> refactor: modify plugin class loading order to follow parent delegation mechanism

- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
- ui/uc-src/modules/profile/tabs/Devices.vue
/kind feature
/area ui
Fixes #7267 
```release-note
支持批量撤销其他设备的登录状态
```
> feat: add support for one-click revocation of login status of other devices

- application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
/kind bug
/area core
将获取文件名的代码由 `Part.name()` 改为 `FilePart.filename()`。`Part.name()` 在没有覆写 form 时可能无法正确获取到文件的客户端路径。
1. 在文章设置 - 附件存储策略 中，设置一个其他的附件存储策略。
2. 测试在富文本编辑器中上传文件是否报错文件类型与后缀不匹配的问题。
Fixes #7274 
```release-note
解决在默认编辑器中上传文件失败的问题
```
> fix: resolve file extension validation failure issue in editor uploads

- application/src/main/java/run/halo/app/content/PageContentThumbnailHandler.java
- application/src/main/resources/extensions/extension-definitions.yaml
/kind improvment
/area core
为自定义页面的图片增加缩略图支持
Fixes #7232
```release-note
为自定义页面的图片增加缩略图支持
```
> feat: add image thumbnail support for single pages

- ui/src/components/editor/extensions/audio/AudioView.vue
- ui/src/components/editor/extensions/image/ImageView.vue
- ui/src/components/editor/extensions/video/VideoView.vue
/kind bug
/area editor
解决默认编辑器中，粘贴后的图片，按下回车可能会导致重复触发上传的问题。
1. 在默认编辑器中粘贴一个图片。
2. 在图片前进行回车换行。
3. 查看图片是否被重复上传。
Fixes #7206 
```release-note
解决默认编辑器中附件会重复上传的问题
```
> fix: resolve issue of duplicate image uploads in default editor

- api-docs/openapi/v3_0/aggregated.json
- api-docs/openapi/v3_0/apis_console.api_v1alpha1.json
- api/src/main/java/run/halo/app/core/user/service/UserService.java
- api/src/main/java/run/halo/app/security/device/DeviceService.java
- application/src/main/java/run/halo/app/core/endpoint/console/ConsoleUserEndpoint.java
- application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
- application/src/main/java/run/halo/app/infra/SchemeInitializer.java
- application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordHandler.java
- application/src/main/java/run/halo/app/security/device/DeviceServiceImpl.java
- application/src/main/resources/templates/gateway_fragments/login.html
- application/src/main/resources/templates/gateway_fragments/login.properties
- application/src/main/resources/templates/gateway_fragments/login_en.properties
- application/src/main/resources/templates/gateway_fragments/login_es.properties
- application/src/main/resources/templates/gateway_fragments/login_zh_TW.properties
- ui/console-src/modules/system/users/UserDetail.vue
- ui/console-src/modules/system/users/UserList.vue
- ui/console-src/modules/system/users/components/UserListItem.vue
- ui/console-src/modules/system/users/composables/use-user.ts
- ui/packages/api-client/src/api/user-v1alpha1-console-api.ts
- ui/src/locales/_missing_translations_es.yaml
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/kind feature
/area ui
Add support for disabling/enabling user accounts
Fixes https://github.com/halo-dev/halo/issues/7250
```release-note
支持在管理控制台禁用指定用户
```
> feat: add support for disabling/enabling user accounts

- application/src/main/java/run/halo/app/theme/engine/HaloTemplateEngine.java
- application/src/main/resources/application-dev.yaml
- application/src/main/resources/application.yaml
/kind bug
/area core
This PR turns off the logging of TemplateEngine to prevent too many annoying and useless logs.
Please note that the TemplateExceptions won't be eat up because we have a global error handler to log them.
Fixes https://github.com/halo-dev/halo/issues/4468
Steps to verify:
- Start Halo instance
- Execute command `ab -c 100 -n 10000 -H 'Accept: text/html' -H 'Cache-Control: no-cache' http://localhost:8090/` and then press `Ctrl + C` to stop the ab process.
- See the logs of Halo instance.
```release-note
解决日志中出现大量 InterruptedException 异常的问题
```
> Turn off logging of TemplateEngine

- application/src/main/java/run/halo/app/core/reconciler/PluginReconciler.java
- application/src/main/java/run/halo/app/plugin/SpringPlugin.java
当插件启动失败时增加异常堆栈日志输出，否则在插件开发时难以知道具体插件为什么启动失败
```release-note
None
```
> chore: add exception information to log output when the plugin fails to start

- application/src/main/java/run/halo/app/extension/DelegateExtensionClient.java
/kind bug
/area core
This PR adds timeout for blocking Extension client to prevent system from blocking without any error.
Recently, we have received several issues about getting stuck in creating menu items. Please refer to the key threaddump detail:
```release-note
None
```
> Add timeout for blocking Extension client

- api/src/main/java/run/halo/app/extension/controller/DefaultController.java
/kind bug
/area core
This PR adjusts the order of checking instance of ExecutorService and AutoCloseable interfaces. Because the ExecutorService extends AutoCloseable in Java 21. As a result, unit tests against the method won't be passed in Java 21.
```release-note
None
```
> Fix the problem of unit test failure under Java 21

- application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
- application/src/main/java/run/halo/app/infra/utils/FileNameUtils.java
- application/src/main/resources/extensions/attachment-local-policy.yaml
- application/src/test/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandlerTest.java
/kind feature
/area core
This PR allows users to upload local attachment always with a random filename to simply prevent resource leak.
Please see the configuration and the uploaded result below:
```json
{
"spec": {
"displayName": "halo.run-ykfswxmokpjopvkqwybghazloxeovgae.cer",
"policyName": "attachment-policy-XVdDK",
"ownerName": "admin",
"mediaType": "application/pkix-cert",
"size": 1803
},
"status": {
"permalink": "/upload/random/halo.run-ykfswxmokpjopvkqwybghazloxeovgae.cer"
},
"apiVersion": "storage.halo.run/v1alpha1",
"kind": "Attachment",
"metadata": {
"finalizers": [
"attachment-manager"
],
"name": "44b4c8de-0d3b-4bbb-acc2-4af50175a2b5",
"annotations": {
"storage.halo.run/local-relative-path": "upload/random/halo.run-ykfswxmokpjopvkqwybghazloxeovgae.cer", …
```
> Support randomizing local attachment filename

- application/src/main/java/run/halo/app/core/reconciler/PostReconciler.java
- application/src/test/java/run/halo/app/core/reconciler/PostReconcilerTest.java
/kind bug
/area core
This PR fixes the NPE while post content is null. See https://github.com/halo-dev/halo/issues/7320 for more.
Fixes https://github.com/halo-dev/halo/issues/7320
```release-note
修复通过接口创建文章可能导致无法发布和删除的问题
```
> Fix the NPE while post content is null

- api/src/main/java/run/halo/app/core/user/service/UserService.java
- application/src/main/java/run/halo/app/core/user/service/impl/UserServiceImpl.java
- application/src/main/java/run/halo/app/infra/exception/EmailAlreadyTakenException.java
- application/src/main/java/run/halo/app/security/preauth/PreAuthSignUpEndpoint.java
- application/src/main/resources/config/i18n/messages.properties
- application/src/main/resources/config/i18n/messages_zh.properties
- application/src/test/java/run/halo/app/core/user/service/impl/UserServiceImplTest.java
/kind bug
/area core
This PR fixes the repeat registration with the email already verified.
Fixes https://github.com/halo-dev/halo/issues/7308
```release-note
修复注册时未验证邮箱是否已被占用的问题
```
> Fix the repeat registration with the email already verified

- ui/packages/editor/src/components/EditorBubbleMenu.vue
- ui/packages/editor/src/components/EditorHeader.vue
- ui/packages/editor/src/components/bubble/BubbleItem.vue
- ui/packages/editor/src/extensions/commands-menu/CommandsView.vue
- ui/packages/editor/src/extensions/link/LinkBubbleButton.vue
- ui/packages/editor/src/styles/base.scss
/kind bug
/area editor
/area ui
Replace `drop-shadow-*` with `shadow-*` to resolve editor styling issues in Safari brower.
before:
after:
None
```release-note
修复编辑器在 Safari 浏览器中关于浮动工具栏和命令列表的样式问题。
```
> fix: resolve editor styling issues in Safari browser

- application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
- application/src/main/java/run/halo/app/theme/config/ThemeConfiguration.java
- application/src/main/java/run/halo/app/theme/dialect/HaloSpringSecurityDialect.java
- application/src/test/java/run/halo/app/theme/dialect/HaloSpringSecurityDialectTest.java
/area core
/area theme
This PR adds support for sec:authorize attribute of Thymeleaf which is not supported yet. See https://github.com/halo-dev/halo/issues/7316 for more.
Fixes https://github.com/halo-dev/halo/issues/7316
```release-note
完善主题模板判断用户角色等功能
```
> Add support for sec:authorize attribute of Thymeleaf

- api/src/main/java/run/halo/app/security/PersonalAccessToken.java
- application/src/main/java/run/halo/app/core/user/service/PatService.java
- application/src/main/java/run/halo/app/core/user/service/impl/PatServiceImpl.java
- application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationConverter.java
- application/src/main/java/run/halo/app/security/authentication/pat/UserScopedPatHandlerImpl.java
/area core
This PR refactors UserScopedPatHandlerImpl with PAT service to make PAT operations flexible.
```release-note
None
```
> Extract PAT operation with service

- .github/workflows/packages-preview-release.yaml
/kind cleanup
Restrict packages-preview-release job to current repo only
```release-note
None
```
> chore: restrict packages-preview-release job to current repo only

- application/src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
/kind bug
修复 postFinder.list() 传参 categoryName 查询不到子类文章
Fixes #7296 
```release-note
修复 postFinder.list() 的 categoryName 参数无效的问题
```
> fix: resolve issue with categoryName parameter not working in postFinder.list()

- application/src/main/java/run/halo/app/content/PostService.java
- application/src/main/java/run/halo/app/content/impl/PostServiceImpl.java
- application/src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
- application/src/main/java/run/halo/app/core/reconciler/CategoryReconciler.java
- application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
- application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
- application/src/main/resources/extensions/system-setting.yaml
- application/src/test/java/run/halo/app/content/permalinks/PostPermalinkPolicyTest.java
/kind feature
文章访问路径支持设置 `/categories/{categorySlug}/{postSlug}` 的形式
Fixes #7330
```release-note
文章访问路径支持设置 `/categories/{categorySlug}/{postSlug}` 的形式
```
> feat: support route pattern /categories/{categorySlug}/{postSlug} for post access

- application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
- application/src/main/java/run/halo/app/security/HaloRedirectAuthenticationSuccessHandler.java
- application/src/main/java/run/halo/app/security/HaloServerRequestCache.java
- application/src/main/java/run/halo/app/security/authorization/AuthorizationExchangeConfigurers.java
- application/src/main/java/run/halo/app/security/switchuser/SwitchUserConfigurer.java
- application/src/test/java/run/halo/app/security/switchuser/SwitchUserConfigurerTest.java
/kind feature
/area core
This PR adds support for impersonating other users for super admin.
1. Login as super admin
2. Request `POST /login/impersonate?username=xxx` and the current user should be xxx
3. Request `POST /logout/impersonate` and the current user should be super admin
```release-note
None
```
> Support impersonating other users for super admin

- application/src/main/java/run/halo/app/security/CsrfConfigurer.java
- application/src/main/java/run/halo/app/security/authentication/pat/PatAuthenticationConverter.java
- application/src/test/java/run/halo/app/security/CsrfSecurityTest.java
/area core
This PR disables CSRF check for PAT authentication because the authentication won't pass any cookies to server.
```release-note
None
```
> Disable CSRF check for PAT authentication

- ui/console-src/modules/contents/posts/DeletedPostList.vue
- ui/console-src/modules/contents/posts/PostList.vue
- ui/console-src/modules/contents/posts/components/PostBatchSettingModal.vue
/area ui
Use `Promise.all` to execute part of the batch operation logic of the post in chunks to optimize the execution performance.
Fixes #
```release-note
优化文章部分批量操作的执行性能
```
> refactor: add chunked execution mechanism for post batch operations

- api/src/main/java/run/halo/app/extension/Unstructured.java
/kind bug
/area core
修复 Unstructured Metadata 的 equals hashcode  排除 version，这可能是之前误操作提交的
https://github.com/halo-dev/halo/blob/ed50a0224d726b420df70a198111f75e8b0d97a3/api/src/main/java/run/halo/app/extension/Unstructured.java#L75
```release-note
None
```
> fix: equals and hash code for unstructured metadata

- build.gradle
/area core
This PR bumps Spring Boot to [3.4.5](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.5).
Fixes #7374 
```release-note
升级依赖 Spring Boot 至 3.4.5，同时解决可能无法登录的问题
```
> Upgrade to Spring Boot 3.4.5

- api/build.gradle
- application/build.gradle
- platform/application/build.gradle
/area core
This PR adds therapi-runtime-javadoc dependency and annotationProcessor for api and application projects. After doing that, SpringDoc will introspect Javadoc annotations and comments. See https://springdoc.org/#javadoc-support for more.
For support in plugin, just add an annotationProcessor like below:
```gradle
dependencies {
implementation platform('run.halo.tools.platform:plugin:2.20.8-SNAPSHOT')
compileOnly 'run.halo.app:api'
annotationProcessor 'com.github.therapi:therapi-runtime-javadoc-scribe:0.13.0'
}
```
```release-note
None
```
> Support resolving javadoc for SpringDoc

- api/build.gradle
- application/src/main/java/run/halo/app/infra/config/WebServerSecurityConfig.java
- application/src/test/java/run/halo/app/config/SecurityConfigTest.java
- platform/application/build.gradle
/kind bug
/area core
This PR makes Argon2 password encoder as default to remove password limit of 72.
Please note that there is no compatibility issue for old passwords.
Fixes #7405 
1. Try to login as admin
2. Create a password having the length of 73 or more for a new user
3. See the result
```release-note
修复无法设置长度超过72个字符的密码的问题
```
> Use Argon2 password encoder as default to remove password limit

- application/src/main/java/run/halo/app/security/jackson2/HaloSecurityJackson2Module.java
- application/src/main/java/run/halo/app/security/jackson2/SwitchUserGrantedAuthorityMixIn.java
- application/src/test/java/run/halo/app/security/jackson2/HaloSecurityJacksonModuleTest.java
/kind bug
/area core
This PR adds SwitchUserGrantedAuthorityMixin into HaloSecurityJackson2Module to fix the deserialization error.
See https://github.com/halo-dev/halo/issues/7406 for more.
Fixes https://github.com/halo-dev/halo/issues/7406
```release-note
修复个人中心处可能出现登录设备查询异常的问题
```
> Fix SwitchUserGrantedAuthority deserialization error

- application/src/main/java/run/halo/app/Application.java
/area core
This PR change the enable method of configuration properties from `EnableConfigurationProperties` to `ConfigurationPropertiesScan`. This way can decouple the add of configuration properties.
See https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.enabling-annotated-types for more.
```release-note
None
```
> Enable configuration properties by scanning

- application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
- application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
/kind bug
/area core
1. This PR removes duplicate invocations while resolving handler functions of theme.
2. Throw NotFoundException while post was not found.
Fixes https://github.com/halo-dev/halo/issues/7409
```release-note
修复访问不存在的分类或者文章页面时始终抛出异常的问题
```
> Fix potential twice theme route handler invocations

- ui/packages/editor/docs/extension.md
- ui/packages/editor/src/components/EditorBubbleMenu.vue
- ui/packages/editor/src/components/EditorHeader.vue
- ui/packages/editor/src/components/index.ts
- ui/packages/editor/src/components/toolbar/ToolbarItem.vue
- ui/packages/editor/src/extensions/audio/index.ts
- ui/packages/editor/src/extensions/commands-menu/CommandsView.vue
- ui/packages/editor/src/extensions/commands-menu/commands.ts
- ui/packages/editor/src/extensions/draggable/index.ts
- ui/packages/editor/src/extensions/iframe/index.ts
- ui/packages/editor/src/extensions/image/index.ts
- ui/packages/editor/src/extensions/paragraph/index.ts
- ui/packages/editor/src/extensions/table/index.ts
- ui/packages/editor/src/extensions/text/index.ts
- ui/packages/editor/src/extensions/video/index.ts
- ui/packages/editor/src/index.ts
- ui/packages/editor/src/types/index.ts
/area plugin
/area editor
Previously, editor extension related types were not exported because the type names conflicted with some UI component names, making it impossible to import extension types in plugins. This PR modifies the type names and exports them in index.ts.
```release-note
导出与编辑器扩展相关的类型定义
```
> refactor: improve type definitions for editor extension

- application/src/main/java/run/halo/app/theme/router/ThemeCompositeRouterFunction.java
- application/src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
- application/src/test/java/run/halo/app/theme/router/factories/PostRouteFactoryTest.java
/kind bug
/area core
This PR removes wrong cache of pattern matchers. The method `matcher#find` should not be only invoked multiple times.
First invocation of `matcher#find` will return `true`, but `false` for second invocation.
Fixes https://github.com/halo-dev/halo/issues/7426
```release-note
修复文章详情页访问规则为/?p={slug}时无法访问的问题
```
> Remove wrong cache of pattern matchers

- ui/packages/api-client/package.json
- ui/packages/components/package.json
- ui/packages/editor/package.json
- ui/packages/shared/package.json
- ui/packages/ui-plugin-bundler-kit/package.json
/area ui
From 2.20.0 to 2.20.21, the UI packages have undergone some changes, it's time to release a new version.
```release-note
None
```
> chore: bump ui packages version

- .github/actions/setup-env/action.yaml
- api/build.gradle
- application/build.gradle
/area core
This PR sets Java 21 as minimal version. After doing that, Halo can only run on Java 21 or newer version.
Fortunately, all plugins and themes won't be affected by the restriction.
> https://docs.gradle.org/current/userguide/toolchains.html#sec:release-flag-toolchain
Fixes https://github.com/halo-dev/halo/issues/6867
```release-note
[Action Required] 更新最低运行环境为 Java 21
```
> Set Java 21 as minimal version

- application/src/test/java/run/halo/app/content/ContentRequestTest.java
- gradle.properties
/kind cleanup
/area core
If we introduce a dependency depending on `org.json:json`, some unit tests won't pass. Please see the error log below:
```java
org.json.JSONException: Unterminated string at 225 [character 0 line 10]
at app//org.json.JSONTokener.syntaxError(JSONTokener.java:503)
at app//org.json.JSONTokener.nextString(JSONTokener.java:302)
at app//org.json.JSONTokener.nextSimpleValue(JSONTokener.java:430)
at app//org.json.JSONTokener.nextValue(JSONTokener.java:421)
at app//org.json.JSONObject.<init>(JSONObject.java:242)
at app//org.json.JSONTokener.nextValue(JSONTokener.java:409)
at app//org.json.JSONObject.<init>(JSONObject.java:242)
at app//org.json.JSONObject.<init>(JSONObject.java:430)
at app//org.skyscreamer.jsonassert.JSONParser.parseJSON(JSONParser.java:43) …
```
> Upgrade JSONAssert to 2.0-rc1

- application/src/main/java/run/halo/app/infra/webfilter/LocaleChangeWebFilter.java
- application/src/main/java/run/halo/app/theme/ThemeLocaleContextResolver.java
- application/src/test/java/run/halo/app/theme/ThemeLocaleContextResolverTest.java
- application/src/test/java/run/halo/app/webfilter/LocaleChangeWebFilterTest.java
/kind bug
/area core
This PR check if the locale is undetermined during resolving locale. Or it will cause the error below if locale is `und`:
```java
2025-05-21T17:28:45.953+08:00 ERROR 58760 --- [undedElastic-14] o.s.w.s.adapter.HttpWebHandlerAdapter    : [c1824fa5-1] 500 Server Error for HTTP GET "/"
org.thymeleaf.exceptions.TemplateOutputException: An error happened during template rendering
at org.thymeleaf.engine.OutputTemplateHandler.handleText(OutputTemplateHandler.java:75) ~[thymeleaf-3.1.3.RELEASE.jar:3.1.3.RELEASE]
at org.thymeleaf.engine.AbstractTemplateHandler.handleText(AbstractTemplateHandler.java:221) ~[thymeleaf-3.1.3.RELEASE.jar:3.1.3.RELEASE]
at org.thymeleaf.engine.ProcessorTemplateHandler.handleText(ProcessorTemplateHandler.java:587) …
```
> Fix the problem of undetermined locale

- api/build.gradle
- application/build.gradle
- application/src/main/resources/application.yaml
- gradle/libs.versions.toml
/area core
This PR bumps Spring Boot to [3.5.0](https://github.com/spring-projects/spring-boot/releases/tag/v3.5.0).
```release-note
升级依赖 Spring Boot 至 3.5.0
```
> Bump Spring Boot to 3.5.0

- build.gradle
/area core
This PR bumps Spring Boot to [3.4.6](https://github.com/spring-projects/spring-boot/releases/tag/v3.4.6).
```release-note
升级依赖 Spring Boot 至 3.4.6
```
> Bump Spring Boot to 3.4.6

- api/build.gradle
- application/build.gradle
- settings.gradle
/kind cleanup
/area core
This PR fixes fixes deprecation warnings complained from Gradle. Please see the Gradle logs below:
```bash
[Incubating] Problems report is available at: file:///home/runner/work/halo/halo/build/reports/problems/problems-report.html
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.14/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
```
```bash
❯ ./gradlew --warning-mode all
Settings file '/home/johnniang/workspaces/halo-dev/halo/settings.gradle': line 3
Properties …
```
> Fix deprecation warnings from Gradle

- application/src/main/java/run/halo/app/infra/ExternalUrlChangedEvent.java
- application/src/main/java/run/halo/app/infra/SystemConfigFirstExternalUrlSupplier.java
- application/src/main/java/run/halo/app/security/preauth/SystemSetupEndpoint.java
- application/src/main/resources/templates/setup.html
- application/src/main/resources/templates/setup.properties
- application/src/main/resources/templates/setup_en.properties
- application/src/main/resources/templates/setup_es.properties
- application/src/main/resources/templates/setup_zh_TW.properties
/area core
This PR allows users to set external URL at setup page without performing a restart.
Fixes https://github.com/halo-dev/halo/issues/7479
1. Try to start Halo instance with a fresh environment.
2. Request index page and you will be redirected to setup page.
3. Check if the external URL is equal to the base URL in your browser.
4. Try to change external URL and finish the setup process.
5. Login to console and check the external URL in overview page.
```release-note
支持在初始化页面设置外部访问地址
```
> Add support for setting external URL at setup page

- ui/console-src/modules/system/plugins/components/PluginListItem.vue
- ui/console-src/modules/system/plugins/components/tabs/Detail.vue
- ui/src/locales/_missing_translations_es.yaml
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
As per the title, the time shown in the plugin list is the installation time of the plugin. For usage purposes, this time seems to have no meaning or reference value.
Fixes #7493 
```release-note
移除插件列表的时间字段，并在插件详情中显示安装时间。
```
> refactor: remove time field from plugin list

- ui/console-src/modules/contents/pages/components/SinglePageListItem.vue
- ui/console-src/modules/contents/posts/components/PostListItem.vue
- ui/console-src/modules/contents/posts/components/entity-fields/CoverField.vue
- ui/src/utils/thumbnail.ts
/kind feature
/area ui
Fixes #7437 
```release-note
文章管理列表支持显示封面图
```
> feat: add cover for post list

- ui/packages/components/src/components/dialog/Dialog.vue
/area ui
before:
after:
```release-note
None
```
> refactor: improve dialog styles in mobile devices

- ui/package.json
- ui/pnpm-lock.yaml
- ui/src/vite/library-external.ts
/area ui
Optimize the file suffixes of global dependencies by using content hashes instead of random strings. This ensures that when dependencies do not change, the output filenames remain the same after building, resulting in better cache utilization.
```release-note
优化 Console 的全局依赖文件名，以获得更好的缓存利用率。
```
> refactor: optimize global libs filenames for better cache hit rates

- ui/src/utils/thumbnail.ts
/area ui
/kind bug
Encode post cover image URLs to prevent loading issue
```release-note
None
```
> fix: encode post cover image URLs to prevent loading issue

- ui/packages/components/src/components/modal/Modal.vue
/area ui
/kind bug
Fix text overflow issue in modal component.
before:
after:
```release-note
修复模态框标题文字溢出的问题。
```
> fix: prevent title text overflow in modal component

- api/build.gradle
- application/src/main/java/run/halo/app/extension/store/ExtensionStore.java
/kind cleanup
/area core
This PR removes unused JPA dependency to reduce application size about 14.6% off.
```bash
❯ ll application/build/libs
total 123M
-rw-r--r--. 1 johnniang johnniang 123M Jun 13 15:37 halo-2.21.0-SNAPSHOT.jar
-rw-r--r--. 1 johnniang johnniang   64 Jun 13 15:37 halo-2.21.0-SNAPSHOT.jar.sha256
```
```bash
❯ ll application/build/libs
total 105M
-rw-r--r--. 1 johnniang johnniang 105M Jun 13 15:36 halo-2.21.0-SNAPSHOT.jar
-rw-r--r--. 1 johnniang johnniang   64 Jun 13 15:36 halo-2.21.0-SNAPSHOT.jar.sha256
```
```release-note
移除无用的依赖，软件包的体积减少近 15%
```
> Reduce application size by removing unused JPA dependency

- ui/console-src/modules/dashboard/widgets/presets/core/stack/components/WidgetEditableItem.vue
/area ui
/kind bug
Fix the issue where widgets in Stack Widgets cannot display the settings button
Fixes #7562 
```release-note
修复堆叠部件中的部件可能无法显示设置按钮的问题。
```
> fix: display settings button in Stack widgets

- application/src/main/java/run/halo/app/infra/config/WebFluxConfig.java
- application/src/test/java/run/halo/app/config/WebFluxConfigTest.java
/area core
/milstone 2.21.x
This PR uses UrlHandlerFilter to rewrite URL with trailing slash.
Fixes https://github.com/halo-dev/halo/issues/5420
1. Start Halo instance
2. Request to `/archives` and `/archives/` and see the result
```release-note
支持自动重写尾部包含斜杠的 URL
```
> Add support for rewriting URL with trailing slash

- ui/packages/ui-plugin-bundler-kit/package.json
/area ui
Bump @halo-dev/ui-plugin-bundler-kit version to 2.21.1
```release-note
None
```
> chore: bump @halo-dev/ui-plugin-bundler-kit version

- ui/package.json
- ui/packages/ui-plugin-bundler-kit/package.json
- ui/packages/ui-plugin-bundler-kit/src/vite.ts
- ui/pnpm-lock.yaml
/area ui
Bump vite version to [7.0.0](https://github.com/vitejs/rolldown-vite/blob/v7.0.0/packages/vite/CHANGELOG.md#700-2025-06-24)
```release-note
None
```
> chore: bump vite version to 7

- ui/console-src/modules/contents/attachments/components/AttachmentUploadModal.vue
- ui/package.json
- ui/pnpm-lock.yaml
/kind bug
/area ui
Bump rolldown-vite to 7.0.3 to fix a styling issue causing the attachment upload component to not load styles properly.
Ref https://github.com/halo-sigs/plugin-moments/issues/150#issuecomment-3016260268
Need to test whether the attachment upload component works properly in both development and production environments, specifically in the console and UC.
```release-note
修复个人中心上传组件无法正常加载样式的问题。
```
> fix: bump rolldown vite version to fix css chunk issue

- ui/packages/editor/src/extensions/indent/index.ts
- ui/packages/editor/src/extensions/paragraph/index.ts
/area editor
Fixes #7492
优化默认编辑器中缩进的逻辑。现在使用 Tab 对文本进行缩进之后，再按 Backspace 会优先回退缩进。
并且原有的文本会直接删除其上一个节点，现在只有块级节点会被直接删除。
before:
after:
测试使用 Backspace 是否符合正常逻辑。
```release-note
优化默认编辑器缩进逻辑
```
> refactor: optimize indentation behavior

- ui/packages/ui-plugin-bundler-kit/src/vite.ts
/area ui
/area plugin
Modify the vite configuration in ui-plugin-bunlder-kit to avoid passing the entire process.env to the build process.
```release-note
None
```
> refactor: pass NODE_ENV for vite config in ui plugin bunlder kit

- ui/packages/editor/src/components/EditorHeader.vue
- ui/packages/editor/src/components/toolbar/ToolbarItem.vue
/area ui
/area editor
Change the editor's toolbox button to expand on click, rather than on hover, to maintain consistency with other toolbar buttons.
```release-note
将编辑器的工具箱按钮改为点击展开
```
> refactor: make toolbox button expandable on click in editor

- ui/src/components/codemirror/Codemirror.vue
- ui/src/formkit/inputs/code/CodeInput.vue
/area ui
/kind bug
Prevent code input content from being obscured in fullscreen mode
Fixes https://github.com/halo-dev/halo/issues/7574
```release-note
修复代码输入框在全屏时，底部内容被遮挡的问题。
```
> fix: prevent code input content from being obscured in fullscreen mode

- README.md
添加 ClawCloud Run 部署按钮，为 Halo 用户提供：
1. **零配置快速体验** - 无需服务器/域名，60秒内启动可用的 Halo 实例
2. **免费体验环境** - 每月免费提供 $5 的账户额度，用户可以持续稳定部署 Halo 博客在 ClawCloud Run 上
3. **原生集成体验** - 自动配置数据库和存储，开箱即用
4. **低门槛验证** - 降低新用户体验成本，促进项目采用率
None
按钮已添加在部署章节，位于 Gitpod 部署选项之后
```release-note
None
```
> Add ClawCloud one-click deployment button to README

- ui/console-src/modules/contents/posts/categories/components/CategoryEditingModal.vue
- ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue
- ui/src/formkit/inputs/category-select/CategorySelect.vue
- ui/src/formkit/inputs/tag-select/TagSelect.vue
- ui/src/locales/_missing_translations_es.yaml
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
This PR adds frontend support for checking if an slug already exists when creating post categories and tags.
Fixes https://github.com/halo-dev/halo/issues/3172
```release-note
创建文章分类和标签时支持检查别名是否已存在
```
> feat: add slug existence check when creating categories and tags

- ui/package.json
- ui/pnpm-lock.yaml
/kind bug
/area ui
Downgrede rolldown-vite to fix chunk issue
Fixes #7649 
```release-note
修复 2.21.4 无法进入 Console 的问题
```
> chore: downgrade rolldown-vite to fix chunk issue

- ui/eslint.config.ts
/kind bug
/area ui
This PR ignores build directory while linting ui project to prevent eslint from linting js files in build/test-results directory.
```release-note
None
```
> Ingore build directory while linting ui project

- application/src/main/java/run/halo/app/content/comment/AbstractCommentService.java
/area code
Comments are allowed to contain `s` tags and `code` tags with class attributes for the following reasons:
1. `s`: The comment component uses tiptap editor's [strikethrough extension](https://tiptap.dev/docs/editor/extensions/marks/strike#:~:text=while%20you%20type.-,Restrictions,-The%20extension%20will) which enforces the use of `s` tags for strikethrough text and cannot be changed.
2. `code[class]`: Used for code highlighting (class="language-*")
```release-note
None
```
> Allow <s> tag and class attribute on <code> in comments

- ui/src/components/editor/composables/use-attachment.ts
- ui/src/components/editor/extensions/audio/AudioView.vue
- ui/src/components/editor/extensions/image/ImageView.vue
- ui/src/components/editor/extensions/upload/index.ts
- ui/src/components/editor/extensions/video/VideoView.vue
- ui/src/components/editor/utils/upload.ts
- ui/src/locales/_missing_translations_es.yaml
- ui/src/locales/en.yaml
- ui/src/locales/zh-CN.yaml
- ui/src/locales/zh-TW.yaml
/area ui
/area editor
/kind feature
Support transfer external assets in the editor to the attachment library. Currently, it supports individual images, videos, and audio files.
in progress:
Fixes https://github.com/halo-dev/halo/issues/2335
```release-note
支持转存编辑器中的外部资源到附件库
```
> Add external asset transfer for editor attachments

- ui/console-src/modules/contents/pages/components/entity-fields/TitleField.vue
- ui/console-src/modules/contents/posts/components/entity-fields/TitleField.vue
- ui/console-src/modules/dashboard/widgets/presets/posts/components/PostListItem.vue
/area ui
/kind bug
Fix pending comments calculation in post list item
```release-note
None
```
> Fix pending comments calculation in post list item

- ui/package.json
- ui/pnpm-lock.yaml
/area ui
Bump rolldown-vite to [7.1.4](https://github.com/vitejs/rolldown-vite/releases/tag/v7.1.4)
```release-note
None
```
> Bump rolldown-vite to 7.1.4

- application/src/main/java/run/halo/app/plugin/DefaultPluginApplicationContextFactory.java
- application/src/test/java/run/halo/app/plugin/DefaultPluginApplicationContextFactoryTest.java
/kind bug
/area plugin
This PR fixes the problem that loading resources from class path during static initialization doesn't work.
```release-note
修复部分场景下无法正常启动插件的问题
```
> Set context ClassLoader to plugin ClassLoader for correct class loading operations

- ui/src/formkit/inputs/select/SelectMain.vue
/kind bug
/area ui
目前  Select 组件使用远程接口请求数据时，如果存在分页的数据则分页请求可以超过分页数量。
此 PR 限制了分页请求的次数。
```release-note
解决使用 Select 组件远程请求数据时的分页问题
```
> fix: resolve the pagination issue of the select formkit  component using remote data

- ui/console-src/modules/contents/pages/SinglePageEditor.vue
- ui/console-src/modules/contents/posts/PostEditor.vue
/area ui
Optimize the navigation logic after publishing an post.
If there’s a previous page, use router.back() so that the query parameters from the previous page are preserved.
Fixes https://github.com/halo-dev/halo/issues/7609
```release-note
发布文章后支持回到上一页并保留查询状态。
```
> Improve navigation logic after publishing content

- ui/package.json
- ui/pnpm-lock.yaml
- ui/src/vite/config-builder.ts
/area ui
/kind cleanup
This PR removes the vite-pwa plugin since we’re not using it at the moment and there are no plans to support PWA for now.
```release-note
None
```
> Remove vite-plugin-pwa from dev dependencies

- ui/console-src/modules/contents/pages/components/entity-fields/TitleField.vue
- ui/console-src/modules/contents/posts/components/entity-fields/TitleField.vue
- ui/console-src/modules/contents/posts/tags/components/TagListItem.vue
- ui/console-src/modules/dashboard/widgets/presets/posts/components/PostListItem.vue
- ui/uc-src/modules/contents/posts/components/PostListItem.vue
/area ui
/milestone 2.22.x
Replaces 'hidden' and 'inline-block' classes with 'opacity-0' and 'group-hover:opacity-100' for external link icons in multiple components. This change enables smoother transitions and better control over the visibility of external link icons on hover.
```release-note
None
```
> Update external link visibility to use opacity transition

- application/src/main/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandler.java
- application/src/test/java/run/halo/app/core/attachment/endpoint/LocalAttachmentUploadHandlerTest.java
/kind bug
/area core
/milestone 2.22.x
This PR fixes invalid characters in permalink URI construction.
```java
java.lang.IllegalArgumentException: Invalid character ' ' for PATH in "/upload/2021/04/Web 14ecd358cce14f9f9ca0fa7a1716b5d8.pdf"
at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:422) ~[spring-web-6.2.11.jar:6.2.11]
at org.springframework.web.util.HierarchicalUriComponents$FullPathComponent.verify(HierarchicalUriComponents.java:922) ~[spring-web-6.2.11.jar:6.2.11]
at org.springframework.web.util.HierarchicalUriComponents.verify(HierarchicalUriComponents.java:386) ~[spring-web-6.2.11.jar:6.2.11]
at org.springframework.web.util.HierarchicalUriComponents.<init>(HierarchicalUriComponents.java:146) …
```
> Handle invalid characters in permalink URI construction
