halo-dev/halo

src/main/java/cc/ryanc/halo/web/controller/admin/AdminController.java
src/main/java/cc/ryanc/halo/web/controller/admin/AttachmentController.java
src/main/java/cc/ryanc/halo/web/controller/admin/CommentController.java
src/main/java/cc/ryanc/halo/web/controller/admin/PageController.java
src/main/java/cc/ryanc/halo/web/controller/admin/PostController.java
src/main/java/cc/ryanc/halo/web/controller/front/ArchivesController.java
src/main/java/cc/ryanc/halo/web/controller/front/CategoriesController.java
src/main/java/cc/ryanc/halo/web/controller/front/CommentsController.java
src/main/java/cc/ryanc/halo/web/controller/front/IndexController.java
src/main/java/cc/ryanc/halo/web/controller/front/OthersController.java
src/main/java/cc/ryanc/halo/web/controller/front/PagesController.java
src/main/java/cc/ryanc/halo/web/controller/front/TagsController.java

具体表现为: 新建文章时, "永久链接"以.html或者.htm结尾, 可以保存, 查看时ControllerNPE

修复保存带html后缀路径的问题

---

src/main/java/cc/ryanc/halo/model/domain/Options.java

修复字段长度设置错误问题导致使用mysql数据库初始化报错的问题

修复字段长度设置错误问题导致使用mysql数据库初始化报错的问题

---

pom.xml

修复了在Ubuntu18.04 openjdk-11中启动失败问题

添加jaxb-api依赖

---

src/main/java/run/halo/app/handler/file/UpYunFileHandler.java

key包含了又拍云文件的目录，重复设置导致删除时出现报错。
阿里云、七牛云部分代码似乎存在相同问题，但是我没有账号，没有做测试。

Fix UpYun oss

---

src/main/java/run/halo/app/model/params/PostParam.java

解决缺省文章路径未进行URL转义的问题。
这个问题的本质是我们可以设置文章页的路径，且如果不设置系统默认将文章标题设置为路径。
如果文章标题包含如‘/’字符如aaa/bbb，则用户访问文章路径就会出错, 系统将会访问aaa子路径下的bbb页面，从而报错404 not found。
只需要在保存路径时对title先进行url转义在设置到url即可解决。本此修改至少可解决包含以下几种字符的转义问题：
1.+   
2. 空格  
3. / 
4. ? 
5. %
6. #
7. &   
8. =
#350

在dev分支上解决缺省文章路径未进行URL转义的问题

---

src/main/java/run/halo/app/utils/MarkdownUtils.java

增加toc支持的标题层级,目前不支持h4级标题以上(包括)-dev

---

build.gradle
src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java

让模板支持以下写法：
```
<!DOCTYPE html>
<html>
<head>
<title>Base Layout</title>
<@layout.block name="head">
<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
</@layout.block>
</head>
<body>
<@layout.block name="header">
<h1>Base Layout</h1>
</@layout.block>
<div class="base">
<@layout.block name="contents">
<h2>Contents will be here</h2>
</@layout.block>
</div>
<@layout.block name="footer">
<div>Footer base</div>
</@layout.block>
</body>
</html>
```
```
<@layout.extends name="layouts/base.ftl">
<@layout.put block="head">
<script src="//ajax.googleapis.com/ajax/libs/mootools/1.4.5/mootools-yui-compressed.js"></script>
</@layout.put>
<@layout.put block="header" type="prepend">
<h2>Index Page</h2>
</@layout.put>
<@layout.put block="contents">
<p>blah.. …
```

feat: support freemarker template Inheritance #534

---

src/main/java/run/halo/app/config/WebMvcAutoConfiguration.java
src/main/java/run/halo/app/listener/freemarker/FreemarkerConfigAwareListener.java

修改：
1. 修改主题资源文件的根目录，原来为 `/**`，变更为 `/themes/**`。
新增：
1. 新增一个变量代表原来的 `static`，兼容原来的主题，后续可能的话，可以去掉原来的 `static` 变量。

feat: change themes assets base path

---

src/main/resources/application-dev.yaml
src/main/resources/application-user.yaml
src/main/resources/application.yaml

修改一些 application.yaml 的内容。
主要将中文注释改为了英文，因为最近发现，用户下载配置文件的时候，中文注释可能会乱码。
`halo-common` 以及 oss 上的配置文件均已修改：https://github.com/halo-dev/halo-common/blob/master/application-template.yaml
文档也已修改：https://halo.run/guide/install/install-with-linux.html#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

style: collate configuration files.

---

src/main/java/run/halo/app/service/impl/AttachmentServiceImpl.java

需要注意的是，此方法仅仅修改了后台附件列表所展示的路径类型，以及上传文件返回的路径类型（主要体现在编辑器），并未实现修改已有文章内图片的路径类型，且并不建议去实现。
示例：
- 相对路径：`/upload/2020/2/image-6ab5b2de1e714506996f2789c6bf95fa.png`。
- 绝对路径：`http://localhost:8090/upload/2020/2/image-6ab5b2de1e714506996f2789c6bf95fa.png`

feat: support set attachment path type.

---

src/main/java/run/halo/app/exception/ThemeNotSupportException.java
src/main/java/run/halo/app/handler/theme/config/support/ThemeProperty.java
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
src/main/java/run/halo/app/utils/HaloUtils.java
src/main/java/run/halo/app/utils/VersionUtil.java
src/test/java/run/halo/app/utils/HaloUtilsTest.java
src/test/java/run/halo/app/utils/VersionUtilTest.java

一共四种情况需要判断。
1. 安装本地主题的时候。
2. 使用本地主题更新的时候。
3. 在线拉取 Github 仓库的主题的时候。
4. 在线更新的时候，如果不支持当前 Halo 版本，会自动回滚到更新前的状态。
另外还有一项修复：
在 https://github.com/halo-dev/halo/pull/538 中修改了主题资源的根路径，但是没有修改后台主题缩略图的路径设置，此提交修复了。

feat: support theme require halo version.

---

src/main/java/run/halo/app/listener/comment/CommentEventListener.java

style: modify email copy.

---

src/main/java/run/halo/app/model/annotation/DisableOnCondition.java
src/main/java/run/halo/app/model/dto/CategoryDTO.java
src/main/java/run/halo/app/model/dto/TagDTO.java
src/main/java/run/halo/app/model/entity/Category.java
src/main/java/run/halo/app/model/entity/Tag.java
src/main/java/run/halo/app/model/params/CategoryParam.java
src/main/java/run/halo/app/model/params/PostParam.java
src/main/java/run/halo/app/model/params/SheetParam.java
src/main/java/run/halo/app/model/params/TagParam.java
src/main/java/run/halo/app/model/support/HaloConst.java

主要为了适配某些主题，如 https://github.com/halo-dev/halo-theme-siren 。这个主题的每个分类或标签页面是有封面图的。

Support set thumbnail to category and tag.

---

src/main/java/run/halo/app/controller/admin/api/SheetController.java
src/main/java/run/halo/app/controller/content/model/PostModel.java
src/main/java/run/halo/app/controller/content/model/SheetModel.java
src/main/java/run/halo/app/model/dto/post/BasePostMinimalDTO.java
src/main/java/run/halo/app/model/entity/BasePost.java
src/main/java/run/halo/app/model/enums/PostEditorType.java
src/main/java/run/halo/app/model/params/PostParam.java
src/main/java/run/halo/app/model/params/SheetParam.java
src/main/java/run/halo/app/model/properties/OtherProperties.java
src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

简述流程：
1. 添加 editorType 字段，默认为 Markdown(0)。
2. 在保存的时候，当 editorType 为 `MARKDOWN` 时，使用 MarkdownUtils 渲染 `originalContent` 的内容到 `formatContent`。当 editorType 为 `RICHTEXT` 时，直接保存 `originalContent` 字段的内容到 `formatContent`。也就是接口还是只传入 `originalContent`，只是额外增加了个 `editorType`。

Add editorType for post.

---

src/main/java/run/halo/app/controller/content/model/CategoryModel.java
src/main/java/run/halo/app/controller/content/model/JournalModel.java
src/main/java/run/halo/app/controller/content/model/PhotoModel.java
src/main/java/run/halo/app/controller/content/model/PostModel.java
src/main/java/run/halo/app/controller/content/model/TagModel.java
src/main/java/run/halo/app/core/freemarker/tag/JournalTagDirective.java
src/main/java/run/halo/app/core/freemarker/tag/PhotoTagDirective.java
src/main/java/run/halo/app/core/freemarker/tag/PostTagDirective.java
src/main/java/run/halo/app/core/freemarker/tag/TagTagDirective.java
src/main/java/run/halo/app/model/support/Pagination.java
src/main/java/run/halo/app/model/support/RainbowPage.java

前台分页的最终形态，将彩虹分页和上下页整合到了一起。
目前可以这样做：
```
<@postTag method="pagination" page="${posts.number}" total="${posts.totalPages}" display="3" isArchives="false">
<#if pagination.hasPrev>
<a class="extend prev" rel="prev" href="${pagination.prePageFullPath!}">
<i class="fa fa-angle-left" aria-label="Previous page"></i>
</a>
</#if>
<#list pagination.rainbowPages as number>
<#if number.isCurrent>
<span class="page-number current">${number.page!}</span>
<#else>
<a class="page-number" href="${number.fullPath!}">${number.page!}</a>
</#if>
</#list>
<#if pagination.hasNext>
<a class="extend next" rel="next" href="${pagination.nextPageFullPath!}">
<i class="fa fa-angle-right" aria-label="Next page"></i>
</a>
</#if>
</@postTag>
```
一个好处：主题开发者完全不用自己拼接分页链接。

Refactor freemarker pagination tag.

---

src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

文章路径类型为 `年月型` 和 `年月日型`。
如果月和日为个数，在前面加个 0。
如：/2020/03/07。
主要考虑到从其他平台迁移过来的用户，基本都为这种类型。防止造成死链。

Refactor post month path type.

---

src/main/java/run/halo/app/handler/file/LocalFileHandler.java
src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/model/dto/StatisticWithUserDTO.java
src/main/java/run/halo/app/model/entity/Attachment.java
src/main/java/run/halo/app/model/entity/BaseComment.java
src/main/java/run/halo/app/model/entity/BaseEntity.java
src/main/java/run/halo/app/model/entity/BaseMeta.java
src/main/java/run/halo/app/model/entity/BasePost.java
src/main/java/run/halo/app/model/entity/Category.java
src/main/java/run/halo/app/model/entity/CommentBlackList.java
src/main/java/run/halo/app/model/entity/Journal.java
src/main/java/run/halo/app/model/entity/Link.java
src/main/java/run/halo/app/model/entity/Log.java
src/main/java/run/halo/app/model/entity/Menu.java
src/main/java/run/halo/app/model/entity/Option.java
src/main/java/run/halo/app/model/entity/Photo.java
src/main/java/run/halo/app/model/entity/PostCategory.java
src/main/java/run/halo/app/model/entity/PostTag.java
src/main/java/run/halo/app/model/entity/Tag.java
src/main/java/run/halo/app/model/entity/ThemeSetting.java
src/main/java/run/halo/app/model/entity/User.java
src/main/java/run/halo/app/model/params/BaseMetaParam.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
src/main/resources/migration/V3__migrate_1.3.0-beta.1_to_1.3.0-beta.2.sql

1. 将所有实体属性的 columnDefinition 替换为 hibernate 的参数或者注解形式。理论上这样做可以兼容更多的数据库。
2. 删除 deleted 字段。
3. 允许在保存数据的时候传入 id，为以后数据的导入导出功能做准备。
另外有个问题：
有些表的字段默认设置为空串是否有必要。目前带来了两点问题：
1. 后台的有些组件会因为字段为空串而抛异常。
2. 主题开发过程中需要多加一个判断，如：
```
<#if post.thumbnail?? && post.thumbnail!=''>
// do something
</#if>
```
如果字段允许为空，那么：
```
<#if post.thumbnail??>
// do something
</#if>
```

Refactor hibernate column build.

---

src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java

针对 issue #763
1. 修改后文章保存草稿时进行预览不会统计访问量
2. 第二点存疑，如果第二点不统计，第一点也不会出问题。
3. 修改后，当草稿发布时，即是实际点击发布的时间

feat&bug: fix issue 763

---

src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

halo版本：1.3.0
linux版本：centos 7.2
操作说明：在进行项目备份时，出现以下错误。
改动说明：在创建 ".zip" 文件时，先判断其父目录是否存在，不存在则创建。
Caused by: java.nio.file.NoSuchFileException: /tmp/halo-backup/halo-backup-2020-09-07-10-22-58--1183201606.zip
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_131]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_131]
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_131]
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_131]
at java.nio.file.Files.newByteChannel(Files.java:361) ~[na:1.8.0_131]
at java.nio.file.Files.createFile(Files.java:632) ~[na:1.8.0_131]
at run.halo.app.service.impl.BackupServiceImpl.backupWorkDirectory(BackupServiceImpl.java: …

增加网站备份，临时文件不存在时创建

---

src/main/java/run/halo/app/Application.java
src/main/java/run/halo/app/model/enums/TimeUnit.java
src/main/java/run/halo/app/model/properties/PostProperties.java
src/main/java/run/halo/app/task/RecycledPostCleaningTask.java

- 可设置是否自动清理回收站文章，以及文章保留时长
- 定时任务每小时检查一次配置，然后清理已过期文章

feat: support automatic cleaning recycled posts. #1031

---

build.gradle

This is required for the JUnit tests to run.
Source: https://docs.gradle.org/current/userguide/java_testing.html#using_junit5
Issue: https://github.com/halo-dev/halo/issues/1127

Add useJunitPlatform() to build.gradle

---

src/main/java/run/halo/app/controller/content/ContentContentController.java
src/main/java/run/halo/app/model/enums/PostPermalinkType.java
src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

feat: #1103

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/java/run/halo/app/controller/core/CommonController.java
src/main/java/run/halo/app/core/ControllerExceptionHandler.java
src/main/java/run/halo/app/core/ControllerLogAop.java
src/main/java/run/halo/app/filter/LogFilter.java
src/main/java/run/halo/app/handler/file/AliOssFileHandler.java
src/main/java/run/halo/app/handler/file/BaiduBosFileHandler.java
src/main/java/run/halo/app/handler/file/FileHandler.java
src/main/java/run/halo/app/handler/file/FileHandlers.java
src/main/java/run/halo/app/handler/file/HuaweiObsFileHandler.java
src/main/java/run/halo/app/handler/file/LocalFileHandler.java
src/main/java/run/halo/app/handler/file/MinioFileHandler.java
src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
src/main/java/run/halo/app/handler/file/SmmsFileHandler.java
src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java
src/main/java/run/halo/app/handler/file/UpOssFileHandler.java
src/main/java/run/halo/app/utils/ImageUtils.java
src/main/resources/application.yaml

Make more friendly error track

---

src/main/java/run/halo/app/task/RecycledPostCleaningTask.java

Close #1200 
这个issue应该是定时任务cron表达式错误导致的，
目前看halo最低支持小时为单位清理文章，这里设置cron表达式每小时一次。

fix bug for issue#1200

---

src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/java/run/halo/app/controller/admin/api/BackupController.java
src/main/java/run/halo/app/model/params/PostMarkdownParam.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/model/vo/PostMarkdownVO.java
src/main/java/run/halo/app/service/BackupService.java
src/main/java/run/halo/app/service/PostService.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/test/java/run/halo/app/service/impl/PostServiceImplTest.java

已经提交 Issue #1198，
添加了一键以Markdown格式导出Halo所有的文章(打包ZIP)的API：
- /api/admin/backups/markdown-export [GET] 获取文件列表
- /api/admin/backups/markdown-export [POST] 导出为ZIP
- /api/admin/backups/markdown-export [DELETE] 删除文件
- /api/admin/backups/markdown-export/{filename=} [GET] 下载
前端页面后续再修改Halo-admin项目

add API for markdown-export

---

src/test/java/run/halo/app/conf/AntPathMatcherTest.java

**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the execution of the remaining ones.
**Solution:**
By using the JUnit5 grouped assertions feature, all assertions are executed and all failures will be reported together. In this refactoring, no original assertion was changed.
**Result:**
_Before:_
```
assertFalse(pathMatcher.match("/admin/?*/**", "/admin"));
assertFalse(pathMatcher.match("/admin/?*/**", "/admin/"));
assertTrue(pathMatcher.match("/admin/?*/**", "/admin/index.html"));
assertTrue(pathMatcher.match("/admin/?*/**", "/admin/index.html/more"));
```
_After:_
```
assertAll(
() -> assertFalse(pathMatcher.match("/admin/?*/**", "/admin")),
() -> assertFalse(pathMatcher.match("/admin/?*/**", "/admin/")),
() -> …
```

Grouping assertions

---

src/main/java/run/halo/app/config/SwaggerConfiguration.java
src/main/java/run/halo/app/utils/SwaggerUtils.java

Fix Page response model inconsistent in swagger ui

---

src/main/java/run/halo/app/config/SwaggerConfiguration.java
src/main/java/run/halo/app/controller/admin/api/BackupController.java
src/main/java/run/halo/app/security/filter/AbstractAuthenticationFilter.java
src/main/java/run/halo/app/security/service/impl/OneTimeTokenServiceImpl.java
src/main/java/run/halo/app/service/BackupService.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

Provide backup dto fetch api

---

build.gradle
src/main/java/run/halo/app/config/HaloMvcConfiguration.java
src/main/java/run/halo/app/core/freemarker/inheritance/ThemeExtendsDirective.java
src/test/java/run/halo/app/freemarker/FreeMarkerTest.java

1. 在需要组件化的 ftl 模板中，按照如下方式创建块。
```html
<!DOCTYPE html>
<html>
<head>
<@layout.block name="title">
<title>标题</title>
</@layout.block>
</head>
<body>
<@layout.block name="header">
<h1>页头</h1>
</@layout.block>
<div class="content <@layout.block name='class'></@layout.block>">
<@layout.block name="content">
</@layout.block>
</div>
<@layout.block name="footer">
<div>页脚</div>
</@layout.block>
</body>
</html>
```
自定义插槽标签为 `<@layout.block>` ，其属性 name 的值为块名称
2. 在需要渲染和调用模板的地方，使用如下方式传入块内容。
```html
<@layout.extends name="layout.ftl">
<@layout.put block="title" type="replace">
<title>自定义标题 - 替换模板内容</title>
</@layout.put>
<@layout.put block="header">
<h2>第二级页头 - 默认放置在模板内容之后</h2>
</@layout.put>
<@layout.put block="class">sheet test-sheet</@layout.put>
<@layout.put block="contents">
<p>这是自定义页面内容</p> …
```

feat: 扩展 freemarker 实现 block

---

src/main/java/run/halo/app/config/SwaggerConfiguration.java
src/main/java/run/halo/app/config/properties/HaloProperties.java
src/main/java/run/halo/app/listener/StartedListener.java
src/main/resources/application-dev.yaml

```
2021-03-27 13:01:07.550  INFO 73866 --- [  restartedMain] run.halo.app.listener.StartedListener    : Halo started at         http://localhost:8090
2021-03-27 13:01:07.550  INFO 73866 --- [  restartedMain] run.halo.app.listener.StartedListener    : Halo admin started at   http://localhost:8090/admin
2021-03-27 13:01:07.551 DEBUG 73866 --- [  restartedMain] run.halo.app.listener.StartedListener    : Halo api documentation was enabled at  http://localhost:8090/swagger-ui.html
```

feat: enable swagger configuration in development.

---

src/main/java/run/halo/app/controller/content/api/OptionController.java
src/main/java/run/halo/app/model/support/BaseResponse.java
src/main/java/run/halo/app/model/support/HaloConst.java
src/main/java/run/halo/app/service/OptionService.java
src/main/java/run/halo/app/service/impl/OptionFilter.java
src/main/java/run/halo/app/service/impl/OptionServiceImpl.java
src/test/java/run/halo/app/service/impl/OptionFilterTest.java

Add OptionFilter for bulk option api

---

src/main/java/run/halo/app/service/CategoryService.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java

fix: #1386

---

src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/main/java/run/halo/app/utils/MarkdownUtils.java
src/test/java/run/halo/app/service/impl/PostServiceImplTest.java

hexo支持多级分类目录，如下，代表文章分类为 大数据、HBASE、运维，其中 HBASE 是 大数据 的子分类
```
categories: 
- [大数据,HBASE]
- [运维]
```
目前会把 “大数据,HBASE”识别为一个分类，此pull请求对该问题进行修复

修复导入markdown时多级分类无法正确识别的问题

---

build.gradle
src/main/java/run/halo/app/utils/FootnoteNodeRendererInterceptor.java
src/main/java/run/halo/app/utils/MarkdownUtils.java
src/test/java/run/halo/app/utils/FootnoteNodeRendererInterceptorTest.java
src/test/java/run/halo/app/utils/MarkdownUtilsTest.java

Creates footnote references in the document. Footnotes are placed at the bottom of the rendered document with links from footnote references to footnote.
> https://www.markdownguide.org/extended-syntax/#footnotes

feat: MarkDown supports footnote rendering

---

.github/commands.json
.github/commands.yml
.github/subscribers.json
.github/workflows/needs-more-info-closer.yml
.github/workflows/on-comment.yml
.github/workflows/on-label.yml

通过评论和添加标签来管理issues
还需要手动添加一下几个label来更好的管理issues:
- *dev-question: 表明是开发问题，需要到论坛寻求帮助，打上此标签的issue会被自动关闭
- *not-reproducible: 表明无法通过issue的描述的步骤重现问题，打上此标签的issue会被自动关闭
- *out-of-scope：表明这个问题，我们不打算在可预见的未来解决它，打上此标签的issue会被自动关闭
- *as-designed： 设计如此不是缺陷，打上此标签的issue会被自动关闭
- *duplicate： 表明是重复问题，会被自动关闭
- *off-topic: 表明该问题与本项目毫无关联，会自动关闭
- *question: 表明是需要到社区提问的问题，会自动关闭
- confirmed：表明问题已得到halo成员确认，需要进行修复或者开发
- confirmationPending： 表明问题在确认中
- needs more info：表明问题缺少必要的描述信息，难以理解
- needs version info： 缺少版本信息
- lgtm： 表明该问题或pr已经审核通过等待合并或进一步处理
提供以下指令来来协助管理issue:
- /*question: 添加*question标签并自动关闭issue
- /duplicate: 添加*duplicate标签并自动关闭
- /confirmationPending: 为issue分配confirmation-pending标签表示等待确认
- /confirm: 为issue分配confirmed标签,表示问题已经得到确认
- /needsMoreInfo：分配needs more info标签
- /gifPlease: 需要提供屏幕录制来帮助成员理解问题
- …

feat: add issues triage action config

---

src/main/java/run/halo/app/config/HaloMvcConfiguration.java
src/main/resources/application.yaml

fix: #1417

---

CHANGELOG.md
src/main/java/run/halo/app/controller/content/api/PostController.java

fix: the keyword and categoryId parameters of the post list api are required #1432

---

src/main/java/run/halo/app/handler/file/MinioFileHandler.java
src/main/java/run/halo/app/model/properties/MinioProperties.java

fix: 解决minIO无法上传到https的问题 #1455
fix: minIO的Region修改为非必要配置项

fix: 解决minIO无法上传到https的问题

---

src/main/java/run/halo/app/handler/file/FileHandler.java

I have tried to fix bug #1473, please review.

fixed the problem of without dimension information when uploading an ICO picture #1473

---

src/main/java/run/halo/app/core/CommonResultControllerAdvice.java
src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
src/main/java/run/halo/app/theme/GitThemeUpdater.java
src/main/java/run/halo/app/utils/footnotes/Footnote.java
src/main/java/run/halo/app/utils/footnotes/FootnoteBlock.java
src/main/java/run/halo/app/utils/footnotes/FootnoteExtension.java
src/main/java/run/halo/app/utils/footnotes/internal/FootnoteBlockParser.java
src/main/java/run/halo/app/utils/footnotes/internal/FootnoteLinkRefProcessor.java
src/main/java/run/halo/app/utils/footnotes/internal/FootnoteNodeFormatter.java
src/main/java/run/halo/app/utils/footnotes/internal/FootnoteNodeRenderer.java
src/main/java/run/halo/app/utils/footnotes/internal/FootnoteRepository.java

- Fix incorrectly open non-git folder
- Fix start panic when no themes found
- Fix build error complained by latest IDEA
Fix #1460 
/kind bug

Fix incorrectly non-git folder opening and fix start panic when no themes found

---

.github/workflows/halo.yml
build.gradle
gradle.properties

- Set the final version with tag name when releasing, and 
- Change default version of halo to `1.4.13-SNAPSHOT`.
It's more convenient to release a new version of halo. We just need to change the snapshot version in the master branch or other release branches.
/kind enhancement

Set the final version with tag name when releasing

---

src/main/java/run/halo/app/controller/content/api/PostController.java
src/main/java/run/halo/app/model/params/PostQuery.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

文章分页列表支持多文章状态查询
[文章管理方式重构](https://github.com/halo-dev/halo-admin/issues/371) 需要文章列表多状态查询支持
check 这个 PR 到本地运行，使用接口调用工具测试以下接口
```
GET http://localhost:8090/api/admin/posts?page=0&size=10&status=PUBLISHED
```
可以传递多个`status`参数例如
```
GET http://localhost:8090/api/admin/posts?page=0&size=10&status=PUBLISHED&status=DRAFT
```
然后查看接口返回结果是否只包含这写状态的文章

Support querying multi post statuses

---

.github/workflows/halo.yml

Cherry pick of #1509 on release-1.4.
#1509: Simplify Java setup in GitHub workflow
```release-note
```

Automated cherry pick of #1509: Simplify Java setup in GitHub workflow

---

.github/workflows/halo.yml
build.gradle
gradle.properties

Cherry pick of #1511 on release-1.4.
#1511: Set the final version with tag name when releasing
```release-note
```

Automated cherry pick of #1511: Set the final version with tag name when releasing

---

src/main/java/run/halo/app/controller/admin/api/PhotoController.java
src/main/java/run/halo/app/model/dto/PhotoDTO.java
src/main/java/run/halo/app/model/entity/Photo.java
src/main/java/run/halo/app/repository/PhotoRepository.java
src/main/java/run/halo/app/service/PhotoService.java
src/main/java/run/halo/app/service/impl/PhotoServiceImpl.java

增加图库点赞功能
#1433 
1. 将图片添加到图库，期望：该图片的点赞数为0
2. 获取图库中的图片查看该图片的点赞信息是否正常返回，期望：该图片的点赞数为 0
3. 调用此 PR 新增的点赞接口，对图片点赞，期望：该图片的点赞数为 1

Support photo likes

---

src/main/java/run/halo/app/listener/StartedListener.java
src/main/java/run/halo/app/model/support/HaloConst.java

修复 Halo 启动时拷贝默认主题没有使用themeId作为主题文件夹名称的问题
See [#1548](https://github.com/halo-dev/halo/issues/1548)
合并时需要 cherry-pick 到 release-1.4
启动时拷贝默认主题应使用themeId以避免主题在线更新后文件夹名称不一致导致部分文件无法获取
删除`halo work dir`下的默认主题`anatole`,然后启动`halo`查看默认主题文件夹名称是否为`caicai_anatole`
点击在线更新或上传该主题的更新包查看主题文件夹名称是否一致，同为`caicai_anatole`

Fixed the problem that copying the default theme at halo startup did not use themeId as the theme folder name

---

src/main/java/run/halo/app/model/dto/TagDTO.java
src/main/java/run/halo/app/model/entity/Tag.java
src/main/java/run/halo/app/model/params/TagParam.java
src/main/java/run/halo/app/model/support/HaloConst.java

标签支持设置颜色，颜色字段为非必填 默认值为 `#cfd3d7`, 为了返回值客户端统一默认颜色所以`TagDTO`的color字段默认值也为`#cfd3d7`
#1559

Tag support color options

---

.github/workflows/halo.yml

Remove prefix v of tag name when releasing a new version.
We don't need the prefix `v` of the version of halo. This may influence version comparing, making theme installation not working.

Remove prefix v of tag name when releasing a new version

---

.github/workflows/halo.yml

Cherry pick of #1571 on release-1.4.
#1571: Remove prefix v of tag name when releasing a new version
```release-note
```

Automated cherry pick of #1571: Remove prefix v of tag name when releasing a new version

---

src/main/java/run/halo/app/controller/admin/api/ThemeController.java
src/main/java/run/halo/app/service/ThemeService.java
src/main/java/run/halo/app/service/ThemeSettingService.java
src/main/java/run/halo/app/service/impl/ThemeServiceImpl.java
src/main/java/run/halo/app/service/impl/ThemeSettingServiceImpl.java

- 支持分组获取主题设置表单配置项和值
- 支持根据主题id查询主题所有分组名称
合并后 SDK需要在`admin-api`的`ThemeClient`中添加这三个接口对应的方法
如果设置项过多，可能会导致渲染卡顿，因为目前是将所有设置项表单都渲染出来。如果能通过分组名按需调用设置项， 则可以有效改善此问题
相关Issue [主题设置项列表根据 group 获取](https://github.com/halo-dev/halo-admin/issues/227)
安装一个halo并测试三个接口的功能是否符合期望值，以默认主题`caicai_anatole` 为例调用三接口期望值如下:
1. `/api/admin/themes/caicai_anatole/configurations/groups/sns`
```json
{
"status": 200,
"message": "OK",
"devMessage": null,
"data": [
{
"name": "rss",
"label": "RSS",
"type": "RADIO",
"dataType": "BOOL",
"defaultValue": true,
"placeholder": "",
"description": "",
"options": [
{
"label": "开启",
"value": true
},
{
"label": "关闭",
"value": false
}
]
},
{
"name": "twitter",
"label": "Twitter",
"type": "TEXT",
"dataType": "STRING",
"defaultValue": null,
"placeholder": "只需填入 Twitter 用户名即可", …
```

Add some apis for group obtain theme configurations and setting items

---

build.gradle

对齐 gradle 中 log4j 的依赖版本 到 2.15.0 以解决 log4j 0-day 安全漏洞
参考 [gradle文档](https://docs.gradle.org/7.0/userguide/dependency_version_alignment.html)
最终对其后的依赖效果如下：
```shell
$ ./gradlew dependencies | grep log4j                                                                        
+--- org.apache.logging.log4j:log4j-core:2.15.0
|    +--- org.apache.logging.log4j:log4j-api:2.15.0 (c)
|    \--- org.apache.logging.log4j:log4j-api:2.15.0
|         +--- org.apache.logging.log4j:log4j-core:2.15.0 (c)
+--- org.apache.logging.log4j:log4j-api:2.15.0 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.14.1 -> 2.15.0 (*)
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.15.0 (*)
|    \--- …
```

Fix security warning of log4j 0-day

---

build.gradle

Cherry pick of #1588 on release-1.4.
#1588: fix: security warning of log4j 0-day
```release-note
```

Automated cherry pick of #1588: fix: security warning of log4j 0-day

---

build.gradle

由于升级springboot 2.5.7的需要，原先的配置无法适应该升级会导致build失败，因此重构配置。

Refactor gradle config of log4j version

---

build.gradle

升级log4j依赖至2.17.0
在非默认配置下（例如：$${ctx:loginId}）攻击者可以手动创建包含递归查找的恶意输入数据，导致StackOverflowError。
2.17.0 删除了 JNDI 对 LDPA 协议的支持。
- [CVE-2021-45105](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105) 风险等级：高 Fixed in Log4j 2.17.0 (Java 8)
- [CVE-2021-45046](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046) 风险等级：严重 Fixed in Log4j 2.16.0 (Java 8)
所有log4j依赖均已替换
```bash
PS E:\Halo Dev\halo> .\gradlew.bat dependencies | findstr log4j
|    |    |    +--- org.apache.logging.log4j:log4j-to-slf4j:2.14.1 -> 2.17.0
|    |    |    |    \--- org.apache.logging.log4j:log4j-api:2.17.0          
|    +--- org.apache.logging.log4j:log4j-core:2.8.2 -> 2.17.0               
|    |    \--- org.apache.logging.log4j:log4j-api:2.17.0                    
|    \--- …
```

fix: Log4j Security Vulnerabilities

---

build.gradle

Cherry pick of #1604 on release-1.4.
#1604: fix: Log4j Security Vulnerabilities
```release-note
```

Automated cherry pick of #1604: fix: Log4j Security Vulnerabilities

---

build.gradle

Cherry pick of #1615 on release-1.4.
#1615: chore: upgrade log4j dependencies
```release-note
```

Automated cherry pick of #1615: chore: upgrade log4j dependencies

---

src/main/java/run/halo/app/repository/ThemeRepositoryImpl.java
src/test/java/run/halo/app/repository/ThemeRepositoryImplTest.java

Currently, when we get a theme property, the activated field is always false. This PR tries to fix this problem while fetching theme property from disk.
Fix #1629 .
```bash
╭─johnniang at x1c in / 22-01-15 - 18:11:12
╰─○ curl 'http://localhost:8090/api/admin/themes/caicai_anatole' \
-H 'Connection: keep-alive' \
-H 'Admin-Authorization: f2b1955c18f34************86edd270c' \
-H 'Accept: application/json, text/plain, */*' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.62' \
-H 'sec-ch-ua: " Not;A Brand";v="99", "Microsoft Edge";v="97", "Chromium";v="97"' \
-H 'sec-ch-ua-platform: "Windows"' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'Sec-Fetch-Mode: cors' \
-H …
```

Fix the problem where the activated field was not set correctly for a theme property

---

src/main/java/run/halo/app/controller/content/api/ThemeController.java

Add api to fetch theme info and settings according to the themeId
Close #1659
1. 拉取该PR运行
2. 登陆后台设置api key为：12345678
3. 测试接口
获取主题信息：
```text
➤ curl -g -i -X GET http://127.0.0.1:8090/api/content/themes/caicai_anatole -H "API-Authorization: 12345678" -H "Content-Type: application/json"
Date: Fri, 18 Feb 2022 05:08:17 GMT
Access-Control-Allow-Headers: Content-Type,ADMIN-Authorization,API-Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Credentials: true
Access-Control-Max-Age: 3600
Content-Type: application/json
Vary: Accept-Encoding, User-Agent
Transfer-Encoding: chunked
{"status":200,"message":"OK","devMessage":null,"data":{"id":"caicai_anatole","name":"Anatole","website":"https://github.com/halo-dev/halo-theme-anatole","branch …
```

Add APIs to fetch theme info and settings according to the theme id

---

src/main/java/run/halo/app/controller/admin/api/AdminController.java
src/main/java/run/halo/app/model/params/ResetPasswordParam.java
src/main/java/run/halo/app/model/params/ResetPasswordSendCodeParam.java
src/main/java/run/halo/app/service/AdminService.java
src/main/java/run/halo/app/service/impl/AdminServiceImpl.java
src/test/java/run/halo/app/controller/AdminControllerTest.java

perf: add password reset field verification

---

src/main/java/run/halo/app/controller/admin/api/PostController.java
src/main/java/run/halo/app/controller/admin/api/SheetController.java
src/main/java/run/halo/app/controller/content/model/SheetModel.java
src/main/java/run/halo/app/model/params/BasePostParam.java
src/main/java/run/halo/app/model/params/PostContentParam.java
src/main/java/run/halo/app/model/params/PostParam.java
src/main/java/run/halo/app/model/params/SheetParam.java
src/main/java/run/halo/app/service/base/BasePostService.java
src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
src/main/java/run/halo/app/utils/PatchUtils.java
src/test/java/run/halo/app/model/params/PostParamTest.java

Content add front-end rendering options

---

build.gradle

Revert dependency of minio-java to 7.1.4

---

src/main/java/run/halo/app/controller/content/api/PostController.java
src/main/java/run/halo/app/controller/content/api/SheetController.java

fix: Post and sheet content is empty in the Content API

---

src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java

保存或更新文章快照时对于加密状态的文章也应该提升版本号，否则会导致私密文章快照增量不正确
目前私密状态文章处于一个特殊的模糊态，对于私密文章只能每保存一次就提升版本号（生成新快照）否则会导致在刚升级到1.5.0.alpha-1时无法保存私密文章只有发布一次才能保存的问题，后续建议将私密状态单独使用一个字段处理比如 `is_public(true/false)` 表示公开或私有

Fix the leak of version number inference when create or update content patch

---

src/main/java/run/halo/app/cache/AbstractStringCacheStore.java
src/test/java/run/halo/app/cache/LevelCacheStoreTest.java

对`jsonToCacheWrapper(String json)`方法捕获的异常放宽为`Exception`,也就是一旦转换出错就不放入缓存，否则出现未处理异常时会导致功能无法使用
Fix #1681, #1683
但没有完全解决 #1683 问题，所以不应该关联关闭它

Fix the problem jsonToCacheWrapper crashes when cache value is not JSON format

---

gradle/wrapper/gradle-wrapper.properties

Reference: https://docs.gradle.org/7.4/release-notes.html

chore: Upgrade gradle 7.0 to 7.4

---

src/main/java/run/halo/app/service/ContentPatchLogService.java
src/main/java/run/halo/app/service/impl/BackupServiceImpl.java
src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java
src/main/java/run/halo/app/service/impl/ContentServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/main/java/run/halo/app/utils/VersionUtil.java
src/test/java/run/halo/app/utils/VersionUtilTest.java

拆分了内容表后同步修改博客json备份和markdown备份
导入数据只支持导入与系统版本号具有相同主&次版本号的json数据，有几点考虑：
1. 如果支持导入任意版本的备份，后续升级都需要做兼容还需要考虑跨版本升级，而功能不常用却投入巨大
> 要兼容跨版本升级和任意版本导入就要根据不同版本创建导入json的后置处理器，然后根据系统版本和备份版本选择执行哪些后置处理器和决策后置处理器的执行顺序，随着版本号增加，后置处理器会变多且随系统启动时一直被注册在系统中但该功能却只会在整个系统生命周期开始时被执行一次，投入与使用频率严重不成比例
2. 用户可以选择先使用与导出备份相同的版本相同的 halo 大版本jar包升级系统导入json后在升级新版本jar包，这种情况只存在夸服务器迁移并升级
3. 改动表结构才需要考虑兼容导入备份的逻辑，而改动表结构只会存在主(major)版本或次(minor)版本,因此退而求其次，允许在相同的主次版本之间随意导入json备份，减少了不必要的投入

Add post backup for contents and content_patch_logs

---

build.gradle

As mentioned in title.
Too many logging outputs will disturb us to see which test case failed. You can see https://github.com/halo-dev/halo/runs/5401606115?check_suite_focus=true#step:4:4633.

Disable standard streams of test logging

---

src/main/java/run/halo/app/service/assembler/BasePostAssembler.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/main/java/run/halo/app/service/impl/SheetServiceImpl.java

修复文章内容删除后给前端返回被删除数据时，调用过生成摘要方法的时候getById报内容找不到异常的问题
Fix #1713

Fix the exception of content not found when empty sheet deleted

---

src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/main/java/run/halo/app/service/impl/SheetServiceImpl.java

修复没有事物的方法调用时报事物不可见的错误问题，特别是批量删除文章时
Fix #1714

Fix the problem of no EntityManager with actual transaction available for current thread then remove method called

---

src/main/java/run/halo/app/controller/admin/api/JournalCommentController.java
src/main/java/run/halo/app/controller/admin/api/PostCommentController.java
src/main/java/run/halo/app/controller/admin/api/SheetCommentController.java
src/main/java/run/halo/app/controller/content/api/JournalController.java
src/main/java/run/halo/app/controller/content/api/PostController.java
src/main/java/run/halo/app/controller/content/api/SheetController.java
src/main/java/run/halo/app/core/freemarker/tag/CommentTagDirective.java
src/main/java/run/halo/app/service/JournalCommentService.java
src/main/java/run/halo/app/service/PostCommentService.java
src/main/java/run/halo/app/service/SheetCommentService.java
src/main/java/run/halo/app/service/assembler/comment/BaseCommentAssembler.java
src/main/java/run/halo/app/service/assembler/comment/JournalCommentAssembler.java
src/main/java/run/halo/app/service/assembler/comment/PostCommentAssembler.java
src/main/java/run/halo/app/service/assembler/comment/SheetCommentAssembler.java
src/main/java/run/halo/app/service/base/BaseCommentService.java
src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/JournalCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/PostCommentServiceImpl.java
src/main/java/run/halo/app/service/impl/SheetCommentServiceImpl.java
src/test/java/run/halo/app/service/impl/PostCommentServiceImplTest.java

将评论拼装数据的方法从原先的service中移动到特定的assembler中
为 issue #1721 做准备，将在下一个PR修复该 issue

Use the comment assembler to replace the original comment converter

---

src/main/java/run/halo/app/controller/content/api/JournalController.java
src/main/java/run/halo/app/controller/content/api/PostController.java
src/main/java/run/halo/app/controller/content/api/SheetController.java
src/main/java/run/halo/app/core/freemarker/tag/CommentTagDirective.java
src/main/java/run/halo/app/service/assembler/comment/BaseCommentAssembler.java
src/main/java/run/halo/app/service/assembler/comment/JournalCommentRenderAssembler.java
src/main/java/run/halo/app/service/assembler/comment/PostCommentRenderAssembler.java
src/main/java/run/halo/app/service/assembler/comment/SheetCommentRenderAssembler.java
src/main/java/run/halo/app/service/base/BaseCommentService.java
src/main/java/run/halo/app/service/impl/BaseCommentServiceImpl.java
src/test/java/run/halo/app/it/PostCommentApiTest.java

针对前台主题渲染或api提供评论数据组装器并对敏感字段脱敏
Fix #1721

feat: Add comment assembler for theme render

---

src/main/java/run/halo/app/model/params/JournalParam.java
src/main/java/run/halo/app/service/impl/JournalServiceImpl.java

日志支持接收前端渲染结果
- 保存和更新接口增加了`keepRaw`字段默认值为false表示后端使用`sourceContent`渲染`content`
- 如果传递`keepRaw=true`则表示使用前端渲染的内容不再使用`sourceContent`渲染
需要同步修改`SDK`
Fix #1738

Journal supports receiving front-end rendering results

---

src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
src/test/java/run/halo/app/listener/PostRefreshStatusListenerTest.java

修复由于`根据分类id查询文章时`方法内没有查询该分类的子分类下的文章导致状态没有更新问题
场景如下：
1、创建一个分类A,进行加密
2、创建一个分类B,挂在分类A下
3、发布一个新的文章: 文章1, 挂在分类B下
> 此时 文章1 的状态为“私密”
4、将分类A的密码删除
> 此时 文章1 的状态仍然为“私密”, 期望为草稿状态(取消私密状态)
修复 #1779 但没有完全修复，该问题的第`6、重选 文章1 的分类, 重新进行发布,文章1 的状态仍然为“私密”`的问题无法在1.5.x解决，需要将`status`字段的职能拆分才可以。
> 文章的分类变更时没法去更新文章状态，因为：
> 1. 现有文章：post-1 所属加密分类则状态为私密
> 2. 用户修改文章为非私密分类并发布文章
> 3. 由于 status 混在一个字段，从原 私密 -> 非私密状态文章就会转草稿
> 4. 也就是出现了发布文章但文章状态为草稿的情况。
所以该问题无法在现有表结构基础上解决，且1.5.x不再进行大的改动，结合以上矛盾点该 Issue 将被挂起到 2.0 milestone 彻底解决。
1. 创建分类 `分类1`及子分类`分类1-1`
2. 创建文章 `test1`
3. 将 `test1`所属`分类1-1`
4. 为`分类1`设置一个密码
5. 期望`test1`为加密状态
6. 取消 `分类1` 的密码
7. 期望`test1`为草稿状态

Fix the problem of post list is incomplete due to no recursive query categories

---

src/main/java/run/halo/app/controller/content/ContentContentController.java

修复文章和分类的url带有中文时加密功能从密码页重定向到详情url由于乱码跳转不过去的问题
Fix #1784
发布一篇机密文章或分类然后访问它输入密码后期望能正确跳转到文章或分类详情
/kind bug

Fix the redirected URL will be garbled when include Chinese

---

src/main/java/run/halo/app/cache/AbstractStringCacheStore.java

去掉`jsonToCacheWrapper`的参数断言
部分用户使用 leveldb 升级到1.5.0时不知道什么原因.leveldb的持久化文件 会出现一些空记录行导致恢复缓存为CacheWrapper到内存时被卡在断言处影响文章发布。

refactor: remove parameter assertion

---

src/main/java/run/halo/app/event/category/CategoryUpdatedEvent.java
src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/test/java/run/halo/app/listener/PostRefreshStatusListenerTest.java

更改分类更新后的文章状态过渡行为，由于情况复杂该PR并没有提供单元测试，目前只是在相对合理的情况下解决它有些场景不完善，等待2.0重新设计加密功能。
要考虑以下情况：
- 分类被更新： 判断密码，If 从空到非空（转私密），Else 从非空到空（公开）
- 分类被删除：判断被删除分类的密码，1.非空，检查所属该分类及其子分类的文章综合文章私密性来决定最终是私密还是公开，2.空则不用管
针对父分类的私密性对当前分类的影响分析：
- 父分类有密码：
- 当前有密码：私密状态，密码变更 非空 -> 空，为私密
​  - 当前分类没密码：私密状态，密码状态变更也为私密
- 父分类没有密码：
- 当前有密码：私密状态，如果当前变更为 密码 从非空 -> 空，则转为公开 
- 当前没密码：公开状态，如果密码从 空->非空 则为私密，否则为公开
之前更新了分类会将所属分类的文章转草稿不合理，现更改它的行为
Fix #1779

refactor: transition behavior of post state after category updated

---

build.gradle
settings.gradle

升级springboot到2.5.11以解决 [CVE-2022-22950: Spring Expression DoS Vulnerability](https://tanzu.vmware.com/security/cve-2022-22950)
引入了 https://plugins.gradle.org/m2/ 仓库地址，因为升级springboot到2.5.11使用原有aliyun gradle plugin 仓库会报错，该仓库不存在2.5.11
> Could not find spring-boot-buildpack-platform-2.5.11.jar (org.springframework.boot:spring-boot-buildpack-platform:2.5.11).
Searched in the following locations:
https://maven.aliyun.com/repository/gradle-plugin/org/springframework/boot/spring-boot-buildpack-platform/2.5.11/spring-boot-buildpack-platform-2.5.11.jar
到 https://developer.aliyun.com/mvn/search 确认也确实没有
修复 https://spring.io/blog/2022/03/28/cve-report-published-for-spring-framework
/area core

chore: Upgrade springboot to 2.5.11

---

src/main/java/run/halo/app/model/entity/BasePost.java

当保存或更新文章之前清空 posts entity的originalContent和formatContent字段，由于这两个字段已经过时，不需要在保存值。
当用户使用该PR所在版本，如果编辑过以前发布的文章或重新发布文章就会逐渐清空posts表的内容字段，从而提升文章列表的查询速度。
> 1.5.0 新增了contents 表用来保存文章内容替代 posts 表的 format_content 和 original_content 字段，为了过渡到1.5.0，posts 表中还保留了文章内容，所以从此版本开始已经不在需要它。
/area core 
/kind cleanup

refactor: clear the deprecated attributes value of post content when prePersist and preUpdate

---

src/main/java/run/halo/app/controller/content/auth/ContentAuthenticationManager.java
src/test/java/run/halo/app/cache/LevelCacheStoreTest.java
src/test/java/run/halo/app/service/impl/CategoryIntegrationTest.java

修复删除分类时的NPE问题，导致原因是1.5.1事件发布时加了参数，测试类没有覆盖到。
Fix #1805
/area core
/kind bug

Fix the NPE when deleting category

---

.github/ISSUE_TEMPLATE/bug_report.en.yml
.github/ISSUE_TEMPLATE/bug_report.zh.yml

Issues 模板添加获取日志方式的链接。
see https://github.com/ruibaby/halo/issues/new?assignees=&labels=bug&template=bug_report.zh.yml
see https://github.com/ruibaby/halo/issues/new?assignees=&labels=bug&template=bug_report.en.yml

chore: issue template add hints on how to get logs

---

src/main/java/run/halo/app/core/freemarker/tag/PostTagDirective.java

根据分类 id 和 slug 查询文章的自定义标签处过滤掉加密分类
根据分类 id 和 slug 查询文章列表的自定义标签不应该显示加密的文章
Fix #1807
/kind bug
/area core

Fix the problem of encrypted category displayed in query posts according to category

---

src/main/java/run/halo/app/handler/file/FilePathDescriptor.java
src/test/java/run/halo/app/handler/file/FilePathDescriptorTest.java

as the title described.
Fix #1800
/kind bug
/area core

Fix the problem of duplicate path separator in windows system

---

src/main/java/run/halo/app/event/category/CategoryUpdatedEvent.java
src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
src/main/java/run/halo/app/service/CategoryService.java
src/main/java/run/halo/app/service/impl/CategoryServiceImpl.java

删除分类后同步刷新关联文章的加密状态
解决加密分类被删除后文章私密状态没有被恢复问题
/area core

fix: update the posts encryption status synchronously after deleting the category

---

src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/test/java/run/halo/app/utils/MarkdownUtilsTest.java

将 markdown 导出时的 frontMatter 由原先的 ` | ` 号更改为 yaml 语法的 `- `。
用于解决导入时无法处理多个分类/标签的问题。
旧类型：
```
categories:  默认分类 | 多分类
tags:  默认标签 | 多标签
```
新类型
```
categories: 
- 默认分类
- 多分类
tags: 
- 默认标签
- 多标签
```
> 无法处理层级分类的问题，考虑到与其他博客系统的兼容性问题，层级分类将会平摊为线性分类。
- https://gohugo.io/content-management/front-matter/
- https://jekyllrb.com/docs/front-matter/
- https://hexo.io/docs/front-matter.html
Fix #1773

refactor: modify the frontMatter export format to yaml syntax

---

build.gradle

升级 springboot 到 2.5.12
> https://docs.spring.io/spring-boot/docs/2.5.12/reference/html/
/kind dependencies

chore: upgrade spring boot to 2.5.12

---

src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java

修复重新设置回收站中的文章，文章会被从回收站还原的问题
/kind bug

fix: post modified in the recycle will be restored

---

src/main/java/run/halo/app/service/impl/ContentPatchLogServiceImpl.java

允许文章内容 v1 版本的补丁记录的status为回收站时当作草稿状态处理
由于V6__migrate_create_contents_table.sql 脚本中对`content_patch_logs`表的status是使用的文章的状态，当用户存在回收站状态的文章然后升级到1.5.0时 v1版本的 patch log 的状态就是 回收站，而原先代码的 patch 逻辑只是根据draft状态和1版本号去查询内容的 patch log 记录，用户此时恢复回收站文章就会导致文章无法保存。因此本次修改会将v1版patch log的状态为回收站时当作草稿状态处理，即：
1. 有文章 post-1 其内容的 v1 patch log状态值为 3（回收站），此时编辑文章后 ctrl + s
期望：patch log版本号不增加依旧只有v1版，内容被替换
2. 然后 发布 post-1
期望：patch log版本号不增加，内容被替换且status变为 0（发布状态）
> 当时脚本中的 status 不能写死为 1 的原因是，没有发布过的文章 patch log 只能为草稿状态，所以 status 迁移时沿用的是 post的状态
/kind bug
/area core

fix: the content cannot be saved problem when the patch status of V1 version of post content is recycle status

---

src/main/java/run/halo/app/model/projection/CategoryIdPostStatusProjection.java
src/main/java/run/halo/app/repository/PostCategoryRepository.java
src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java

修复根据分类统计文章数量的方法没有排除回收站文章的问题
/kind bug

fix: posts in the recycle are not excluded when calculating posts under category

---

src/main/java/run/halo/app/repository/PostTagRepository.java

修复根据标签统计文章数量时没有过滤掉回收站中的文章问题
/kind bug

fix: posts in the recycle are not excluded when calculating posts under tag

---

src/main/java/run/halo/app/listener/post/PostRefreshStatusListener.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

修复加密文章从回收站恢复后的状态不是加密的问题
/kind bug

fix: the encrypted post is in an incorrect state after being recovered from the recycle

---

OWNERS

添加 OWNERS 文件以确保 prow 可以使用 approve

feat: add OWNERS file for prow

---

src/main/java/run/halo/app/config/WebSecurityConfig.java
src/main/java/run/halo/app/identity/authentication/Context.java
src/main/java/run/halo/app/identity/authentication/DefaultOAuth2TokenContext.java
src/main/java/run/halo/app/identity/authentication/JwtGenerator.java
src/main/java/run/halo/app/identity/authentication/OAuth2TokenContext.java
src/main/java/run/halo/app/identity/authentication/OAuth2TokenGenerator.java
src/main/java/run/halo/app/identity/authentication/OAuth2TokenType.java
src/main/java/run/halo/app/identity/authentication/ProviderContext.java
src/main/java/run/halo/app/identity/authentication/ProviderSettings.java
src/main/java/run/halo/app/infra/config/AbstractSettings.java
src/main/java/run/halo/app/infra/config/ConfigurationSettingNames.java
src/test/java/run/halo/app/authentication/JwtClaimsSetTest.java
src/test/java/run/halo/app/authentication/JwtGeneratorTest.java
src/test/java/run/halo/app/authentication/ProviderSettingsTest.java

- 添加 JwtGenerator
- 为生成 Jwt 提供 OAuth2TokenContext
- 为 OAuth2TokenContext 提供默认实现 DefaultOAuth2TokenContext
- 为 Jwt 生成提供 issuer 等元数据 provider 上下文参数 `ProviderContext`、`ProviderSettings`
- 添加单元测试来为上述功能提供逻辑验证
1. 为后续生成 Jwt bearer token 做准备
2. 可以通过实现该 PR 中的`OAuth2TokenGenerator` 来实现其他的 token 生成器比如： api token 的生成器
3. 通过使用 OAuth2TokenType 可以描述不同的 token，使用方式：  `OAuth2TokenType ACCESS_TOKEN = new OAuth2TokenType("access_token");` 
4. 通过此 PR 中的 AbstractSettings 和 ConfigurationSettingNames 为 token 生成提供一些定制化的数据比如 token 的生存时间、是否启用 refresh token、issuer 等
参考Spring Security类:
- org.springframework.security.oauth2.core.OAuth2Token
- org.springframework.security.oauth2.core.OAuth2AccessToken
- org.springframework.security.oauth2.jwt.Jwt
- org.springframework.security.oauth2.jwt.JwtEncoder
jdk17 Record …

feat: Add JwtGenerator for authentication

---

src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
src/main/java/run/halo/app/identity/authentication/JwtGenerator.java
src/main/java/run/halo/app/identity/authentication/OAuth2TokenContext.java
src/main/java/run/halo/app/identity/authentication/ProviderSettings.java
src/main/java/run/halo/app/infra/config/AbstractSettings.java
src/main/java/run/halo/app/infra/config/ConfigurationSettingNames.java
src/test/java/run/halo/app/authentication/JwtGeneratorTest.java
src/test/java/run/halo/app/authentication/ProviderSettingsTest.java

支持通过配置来定制 token 和 refresh token 的生存时间
参考文档：https://datatracker.ietf.org/doc/html/rfc6749#section-4.2.2
为了确保安全，生成 jwt access token 会伴随有过期时间，过期后在通过携带 refresh token 到接口换取新的 access token，那么access token和 refresh token的生存时间就需要允许通过配置来个性化修改，通常 access token的生存时间要比 refresh token短。
1. 拉取本 PR后运行
```shell
curl -X POST http://localhost:8090/api/v1/oauth2/login -H "Content-Type: application/x-www-form-urlencoded" -d 'username=user&password=123456'
```
2. 会收到类似如下结果
```json
{
"access_token": "eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwibmJmIjoxNjUwMjY2MTI3LCJzY29wZSI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjgwOTAiLCJleHAiOjE2NTAyNjY0MjcsImlhdCI6MTY1MDI2NjEyNywianRpIjoiMjg2Yjc4ODU1MDcxNGQ3M2I1NjgzMjFjYjQ3OWM2NTMifQ.K_5d66DshBClReSKpdMoxQmg_4gMYL0Te8_s2fS5Jbwmur9Lvck2ORzyVDfyi3fTicCLVWeOzJmSBMOTIEA …
```

feat: Allow configuration for token and refresh token time-to-live

---

src/main/java/run/halo/app/config/WebSecurityConfig.java
src/main/java/run/halo/app/identity/authentication/InMemoryOAuth2AuthorizationService.java
src/main/java/run/halo/app/identity/authentication/JwtDaoAuthenticationProvider.java
src/main/java/run/halo/app/identity/authentication/OAuth2Authorization.java
src/main/java/run/halo/app/identity/authentication/OAuth2AuthorizationService.java
src/test/java/run/halo/app/authentication/InMemoryOAuth2AuthorizationServiceTest.java

添加 OAuth2AuthorizationService 的内存级实现 InMemoryOAuth2AuthorizationService，在没有持久化功能之前可用于 开发或测试使用
是 `认证请求 -> 验证密钥 -> 颁发 token -> 持久化 token` 中的一环
它是一个 stacked pull request, 合并该 PR 前先合并它的祖先 #1853
/kind feature
/area core
/milestone 2.0

feat: Add InMemoryOAuth2AuthorizationService for development or testing

---

src/main/java/run/halo/app/controller/admin/api/MailController.java
src/main/java/run/halo/app/core/ControllerExceptionHandler.java
src/main/java/run/halo/app/mail/AbstractMailService.java

Fix #1858
**What this PR does?**
1. 在发送测试邮件之前进行相关检测，并对返回的报错信息进行处理

Handle exception while sending test email

---

src/main/java/run/halo/app/config/WebSecurityConfig.java
src/main/java/run/halo/app/identity/authentication/JwtUsernamePasswordAuthenticationFilter.java
src/main/java/run/halo/app/identity/authentication/OAuth2AuthorizationGrantAuthenticationToken.java
src/main/java/run/halo/app/identity/authentication/OAuth2PasswordAuthenticationConverter.java
src/main/java/run/halo/app/identity/authentication/OAuth2PasswordAuthenticationProvider.java
src/main/java/run/halo/app/identity/authentication/OAuth2PasswordAuthenticationToken.java
src/main/java/run/halo/app/identity/authentication/OAuth2TokenContext.java
src/main/java/run/halo/app/identity/authentication/OAuth2TokenEndpointFilter.java
src/test/java/run/halo/app/authentication/JwtUsernamePasswordAuthenticationFilterTests.java

- 添加 OAuth2PasswordAuthenticationToken 用于处理 Password Authorization Grant Type，避免和 UsernamePasswordAuthenticationToken冲突
- 添加 OAuth2PasswordAuthenticationProvider 作为 Password Authorization Grant Type 的 Provider
- 添加 OAuth2PasswordAuthenticationConverter 用于转换请求参数为 OAuth2PasswordAuthenticationToken 对象
通过上述改变即可将 JwtUsernamePasswordAuthenticationFilter 删除统一使用 OAuth2TokenEndpointFilter 处理 Password Authorization Grant Type，即 OAuth2TokenEndpointFilter 可以处理 Refresh Token Authorization Grant Type 和 Password Authorization Grant Type，减少重复代码如 authenticationSuccessHandler，authenticationFailureHandler 等，使逻辑更加内聚
它是一个 stacked pull request, 合并该 PR 前先合并它的祖先 #1856
/kind feature
/area core
/milestone 2.0

refactor: use OAuth2Password grant instead of JwtUsernamePassword authentication

---

src/main/java/run/halo/app/mail/AbstractMailService.java
src/main/java/run/halo/app/model/properties/EmailProperties.java

Fix #1848
**What this PR does?**
- 为office365,icloud等增添starttls支持
**本地测试**
- office365和outlook成功，iCloud等暂未测试
- 切换回其他邮箱后不影响正常的使用

feat: SMTP support configuration starttls

---

src/main/java/run/halo/app/config/WebSecurityConfig.java

通过`providerSettings#getTokenEndpoint()`创建 OAuth2TokenEndpointFilter 作为其 tokenEndpointMatcher,默认值为`/api/v1/oauth2/token`也就是 password 认证模式和 refresh token 的 uri
统一配置，可以在创建 providerSettings 时定制认证 endpoint
针对已经颁发的 token 提供验证功能，client request 携带 token 后验证是否正确，如果不正确则不允许访问内部资源

chore: use providerSettings to create OAuth2TokenEndpointFilter

---

src/main/java/run/halo/app/controller/admin/api/PostController.java

修复 Admin API 中 post-controller 永久删除 Post 操作名称拼写错误。
https://api.halo.run/admin-api.html#operation/deletePermanentlyUsingDELETE_6

fix typo: swagger api operation title typo

---

src/main/java/run/halo/app/identity/authentication/verifier/AbstractOAuth2TokenAuthenticationToken.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthentication.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationToken.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTest.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenAuthenticationTokenTest.java

为验证 token 做准备：
- 添加 BearerTokenAuthenticationToken
- 添加 BearerTokenAuthentication，一旦创建该对象表示成功验证 BearerTokenAuthenticationToken
- 为其添加测试类
https://tools.ietf.org/html/rfc6750#section-1.2
https://tools.ietf.org/search/rfc7662#section-2.2
在现有的颁发 JWT Token 的基础上，使用 Bearer Token协议
> Bearer Token
A security token with the property that any party in possession of
the token (a "bearer") can use the token in any way that any other
party in possession of it can.  Using a bearer token does not
require a bearer to prove possession of cryptographic key material
(proof-of-possession).
>
>   All other terms are as defined in "The OAuth 2.0 Authorization
>   Framework" [[RFC6749](https://datatracker.ietf.org/doc/html/rfc6749)].
即 client 在 Header 上通过如下格式传递凭证进行身份鉴定:
> Authorization: Bearer some-token …

feat: Add bearer token and bearer authentication

---

src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenError.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenErrorCodes.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenErrors.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorTest.java
src/test/java/run/halo/app/authentication/verifyer/BearerTokenErrorsTest.java

为解析 Bearer token 添加 错误处理
参见 RFC：https://datatracker.ietf.org/doc/html/rfc6750#section-3.1
> When a request fails, the resource server responds using the
appropriate HTTP status code (typically, 400, 401, 403, or 405)
参见： #1868
添加 bearer token resolver 来解析请求
/kind feature

feat: Add bearer token errors for rfc6750#section-3.1

---

src/main/java/run/halo/app/service/impl/BackupServiceImpl.java

**What this PR does?**
fix #1866 
- When backing up, temporarily stop HikariPool.

temporarily stop database connection while backing up database files

---

src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenResolver.java
src/main/java/run/halo/app/identity/authentication/verifier/DefaultBearerTokenResolver.java
src/test/java/run/halo/app/authentication/verifyer/DefaultBearerTokenResolverTest.java

添加 Bearer token 解析器 用于从 request 中解析 Authorization header 或 access_token 参数
参见 RFC：https://datatracker.ietf.org/doc/html/rfc6750#section-2.1
参见：#1864 的描述
/kind feature
/area core

feat: Add default bearer token resolver for rfc6750#section-2.1-2.3

---

src/main/java/run/halo/app/identity/authentication/verifier/InvalidBearerTokenException.java
src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationConverter.java
src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationProvider.java
src/main/java/run/halo/app/identity/authentication/verifier/JwtAuthenticationToken.java
src/main/java/run/halo/app/identity/authentication/verifier/JwtGrantedAuthoritiesConverter.java
src/test/java/run/halo/app/authentication/verifyer/JwtAuthenticationProviderTest.java
src/test/java/run/halo/app/authentication/verifyer/JwtGrantedAuthoritiesConverterTest.java
src/test/java/run/halo/app/authentication/verifyer/TestJwts.java

新增 JwtAuthenticationToken 和 JwtAuthenticationProvider 用于对 Bearer Token 处理后的 Jwt token value进一步处理，需要对其进行 JwtDecoder 来验证是否合法
参见：#1864
添加 BearerTokenAuthenticationFilter 来解析请求参数后委托给 JwtAuthenticationProvider 进行具体的 tokenValue 验证
/kind feature
/area core
/milestone 2.0

feat: Add jwt token and provider for jwt authentication

---

src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationEntryPoint.java
src/main/java/run/halo/app/identity/authentication/verifier/BearerTokenAuthenticationFilter.java

添加 BearerTokenAuthenticationFilter 来解析请求参数后委托给 JwtAuthenticationProvider 进行具体的 tokenValue 验证
在 WebSecurityConfig 中配置 BearerTokenAuthenticationFilter 完成 请求认证 功能
/kind feature
/milestone 2.0

feat: Add bearer token authentication filter for bearer authentication

---

src/main/java/run/halo/app/config/WebSecurityConfig.java
src/main/java/run/halo/app/identity/HelloController.java
src/main/java/run/halo/app/identity/authentication/verifier/JwtProvidedDecoderAuthenticationManagerResolver.java

添加 bearer token filter 的 security 配置，完成整条 token 验证流程
拦截请求，解析并校验 token, 参见：#1864
1. 拉取本 PR 到本地运行
2. 通过默认提供的用户密码获取 token
```shell
curl -X POST http://localhost:8090/api/v1/oauth2/token -H "Content-Type: application/x-www-form-urlencoded" -d 'username=user&password=123456&grant_type=password'
```
3. 先访问 `curl http://localhost:8090/api/v1/tests` 会得到 `Unauthorized` 的 response，表示请求需要认证
4. 使用 `步骤2` 中`/api/v1/oauth2/token`请求获取到的 `access_token` 替换如下 `Bearer` 后的 `your_access_token`(注意 Bearer 和 your_access_token 之间需要一个空格)
```shell
curl http://localhost:8090/api/v1/tests -H "Authorization: Bearer your_access_token"
```
便可看到如下结果
```
Now you see me.⏎
```
/kind feature
/milestone 2.0
/area core

feat: Add bearer token filter config for authentication

---

src/main/java/run/halo/app/identity/authentication/OAuth2PasswordAuthenticationProvider.java

认证成功创建 token 时添加 Principal 属性到 OAuth2Authorization 对象中通过 authorizationService 持久化
在刷新 token 时便于通过其恢复 principal
1. 拉取本PR到本地启动
2. 通过密码认证获取 refresh_token
```shell
curl -X POST http://localhost:8090/api/v1/oauth2/token -H "Content-Type: application/x-www-form-urlencoded" -d 'username=user&password=123456&grant_type=password'
```
3. 使用获取到的 refresh_token 刷新一个新 token 对象(替换下面的 `your_refresh_token` 为 `步骤2` 获取到的 `refresh_token`值)
```shell
curl -X POST http://localhost:8090/api/v1/oauth2/token -H "Content-Type: application/x-www-form-urlencoded" -d 'refresh_token=your_refresh_token&grant_type=refresh_token'
```
此时会得到一个新的token对象
如果继续使用 `步骤3` 的请求会得到
```
{
"error": "invalid_grant"
}
```
原因是： 一个 refresh_token 只能使用一次，用过以后就不能在使用了，这也是为什么需要 OAuth2AuthorizationService 的原因之一
/kind feature
/milestone 2.0
/cc …

feat: Add Principal attribute to authorizationBuilder when password authenticate successfully

---

src/main/java/run/halo/app/handler/file/LocalFileHandler.java

Pass IOException into exception stack instead of ignoring it.
由于忽略了 IOException，导致无法排查到真实错误原因，例如：
- https://github.com/halo-dev/halo/issues/1912
- https://github.com/halo-dev/halo/issues/1897
/kind bug
/area core

Pass IOException into exception stack instead of ignoring it

---

src/main/java/run/halo/app/service/impl/PostServiceImpl.java
src/main/java/run/halo/app/service/impl/StaticStorageServiceImpl.java

fix #1880 
在刷新时把static目录下用户新增的文件（未通过后台添加的）加入blackPatterns中。使其可以正常访问。

Update the path patterns of static files while refreshing

---

src/main/java/run/halo/app/listener/comment/CommentEventListener.java

Set transaction isolation to read_uncommitted because the comment event handlers are executed asynchronously.
Comment events handlers are executed asynchronously.
And default transaction isolation is read_committed,
so the handlers can not see the comments created by event dispatcher
Fix #1798 
- http://www.h2database.com/html/advanced.html#transaction_isolation
- https://dev.mysql.com/doc/refman/8.0/en/innodb-transaction-isolation-levels.html
- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/event/TransactionalEventListener.html
/kind bug
/area core

Set transaction isolation to read_uncommitted due to @Async

---

src/main/java/run/halo/app/model/entity/BasePost.java
src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
src/test/java/run/halo/app/service/impl/HTMLWordCountTest.java

fix #1759 
-   将中文和其他字符分开统计，中文按照字数计数，其他的语言默认按照标点分割来计数。
- 在**BasePost**类里添加了**charCount**字段，用于记录旧版的字符数。
- 添加了对应的测试代码。

feat: Optimized word count for non-Chinese articles

---

build.gradle

Upgrade Spring Boot from 3.0.0-M1 to 3.0.0-M2.
Spring Boot 3.0.0-M2 has been released for a while, it's time to upgrade it. Please refer to 
- https://github.com/spring-projects/spring-boot/releases/tag/v3.0.0-M2
/area core

Upgrade Spring Boot to 3.0.0-M2

---

CHANGELOG.md
README.md
gradle.properties

1. 更新 1.5.3 的 CHANGELOG.md
2. README.md 移除快速开始的内容，改用链接文档的形式。
3. gradle.properties 的默认版本改为 1.6.0-SNAPSHOT

docs: update README.md and CHANGELOG.md for new version

---

build.gradle
src/main/java/run/halo/app/config/WebSecurityConfig.java
src/main/resources/application-dev.yaml

/kind feature
Add support for API documentation using [springdoc v2](https://springdoc.org/v2/#getting-started).
Because we are using Spring Boot 3, springdoc v2 have to be used for our API documentation.
You could learn more about Jakarta support of Springdoc from https://github.com/springdoc/springdoc-openapi/issues/1284.
After started, you can browse `http://localhost:8090/swagger-ui.html` to acess API documentation.
- Why don't we use SpringFox?
The main reason why we don't use it is lack of maintenance. We are using Spring Boot 3 and minimal JDK is 17, SpringFox is incompatible with them.
Fixes #
```release-note
None
```

Add support for API documentation

---

src/main/java/run/halo/app/model/properties/CommentProperties.java
src/main/resources/templates/common/macro/global_macro.ftl

/kind optimization
更换了评论组件的默认url
Fixes #2097 
```release-note
将评论组件的地址由 jsDelivr 更改为 unpkg.com
```

perf: change the resource address of the default comment component library to unpkg.com

---

src/main/java/run/halo/app/controller/admin/api/LinkController.java
src/main/java/run/halo/app/model/params/LinkParam.java
src/main/java/run/halo/app/repository/LinkRepository.java
src/main/java/run/halo/app/service/impl/LinkServiceImpl.java

/kind feature
提供对友链分组的排序功能；前端还通过拖拽来提供可视化的对友链及友链分组的排序操作。
Fixes #1905
出于不更改数据库表的考虑，对分组的排序没有增设新的字段如`team_priority`，而是沿用过去的link的`priority`字段，每个分组的priority设置为其组内link的最高priority。
前端不提供显式的修改priority的接口，改由前端按排序自动计算所有link的priority，再交由后端统一更新。
---
前端方面进行友链管理界面的重构，沿用了vuedraggable组件来实现拖拽，由于我对前端不是很熟练，前端方面的具体实现和PR交由 @gungnir479 负责。
---
总体效果如下
<video src="https://user-images.githubusercontent.com/65994555/169685416-e4b86306-bd96-4e5a-bbde-d40f6383d9ca.mp4"></video>
```release-note
重构了管理友链的界面，现在可以通过拖拽的形式可视化的管理友链及友链分组的排序
```

Add support for link group and its sort

---

src/main/java/run/halo/app/config/WebServerSecurityConfig.java

/area core
By default, when we are redirected to login page, we will got CSRF token in response body(html) only.
After we enable CSRF token in Set-Cookie header to let front-end obtain the token conveniently. Please see the header below:
```properties
Set-Cookie: XSRF-TOKEN=5ea04bc6-5fb2-4d53-9d50-0e42356962c6; Path=/; HttpOnly
```
Fixes #
/milestone 2.0
```release-note
None
```

Enable CSRF token in Set-Cookie header

---

src/main/java/run/halo/app/config/WebFluxConfig.java
src/main/java/run/halo/app/config/WebServerSecurityConfig.java
src/main/resources/application-dev.yaml
src/main/resources/application.yaml
src/test/java/run/halo/app/config/ServerCodecTest.java
src/test/resources/application.yaml

/area core
By default, ServerCodecConfigurer creates some default codecs, including Jackson2Json encoder and decoder. But the ObjectMappers in both are fresh and not able to serialize and deserialize date-time types in package `java.time`.
But we have imported `spring-boot-starter-json` which is globally configuration for JSON. We could autowire an ObjectMapper to customize ServerCodecConfigurer and configure ObjectMapper uniformly.
**Attention:**
- After we do that, the date format should be followed [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) style.
Fixes #
/milestone 2.0
```release-note
None
```

Overwrite Jackson2Json decoder and encoder

---

src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java

/area core 
/milestone 2.0
由于 com.networknt.schema 做了多语言导致单元测试断言时语言环境不同而无法测试成功
Fixes #
```release-note
None
```

fix: locale for unit test of json extension converter

---

src/main/java/run/halo/app/plugin/PluginApplicationContext.java
src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
src/main/java/run/halo/app/plugin/SharedApplicationContext.java
src/main/java/run/halo/app/plugin/SharedApplicationContextHolder.java
src/test/java/run/halo/app/plugin/SharedApplicationContextHolderTest.java

/kind feature
/area core
/milestone 2.0
新增 SharedApplicationContext 做为所有 PluginApplicationContext 的 parent. 当 Core 需要共享实例给插件使用时会注入到 SharedApplicationCoantext 中，它是一个单类，所有插件都公用它。
该方案直接解决了直接使用 Core 作为 PluginApplicationContext 的 parent 的一些问题：
1. 插件获取 Bean 时会获取到 Core 不想共享给插件使用的 Bean，容易出现一些循环问题例如插件获取 RouterFunction 时获取到了 Core 中存在的导致形成环时路由不匹配时出现 Stack Overflow
2. Core 中事件被触发时广播到 PluginApplicationContext 此时 spring 的默认处理是会调用 parent ApplicationContext 发布事件则会导致事件循环
Fixes #
```release-note
None
```

feat: add shared application context for plugin

---

src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
src/test/java/run/halo/app/extension/ExtensionDeleteHandlerTest.java
src/test/java/run/halo/app/extension/ExtensionListHandlerTest.java
src/test/java/run/halo/app/extension/ExtensionRouterFunctionFactoryTest.java
src/test/java/run/halo/app/extension/ExtensionUpdateHandlerTest.java

/kind feature
/area core
为自定义模型数据提供更新和删除接口。这是对 #2158 的补充。
目前删除接口仅仅只是简单修改了 deletionTimestamp 字段，后续提供了 watch 功能后，再逐一物理删除。
Fixes #
- 启动 Halo 并从日志中获取初始密码
- 获取 Access Token
```bash
curl -X POST --location "http://localhost:8090/api/auth/token" \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-d "{
\"username\": \"admin\",
\"password\": \"paste_your_init_password_here\"
}"
```
- 创建角色
```bash
curl -X POST --location "http://localhost:8090/api/v1alpha1/roles" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer {{access_token}}" \
-d "{
\"rules\": [
{
\"apiGroups\": [
\"*\"
],
\"resources\": [
\"*\"
],
\"resourceNames\": [],
\"nonResourceURLs\": [
\"*\"
],
\"verbs\": [
\"*\"
]
}
],
\"apiVersion\": \"v1alpha1\",
\"kind\": …
```

Add update and delete handlers for Extensions

---

src/main/java/run/halo/app/config/WebServerSecurityConfig.java
src/test/java/run/halo/app/config/CorsTest.java

目前，Halo 中所有的 API 和页面都配置了默认的 CORS 规则，以至于无法使用 XHR 请求。
这个 PR 主要配置了 API 的 CORS 规则，允许跨域访问。
Fixes #
1. 启动 Halo
2. 访问 <https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Flocalhost%3A8090%2Fwebjars%2Fswagger-ui%2Findex.html&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote> ，并打开调试工具
3. 点击 `Send Request` 并查看控制台日志
4. 访问 <https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Flocalhost%3A8090%2Fapi%2Ffake&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote> 并点击 `Send Request`。
效果如下：
```js
/#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Flocalhost%3A8090%2Fwebjars%2Fswagger-ui%2Fin …
```

Configure CORS for API endpoints

---

src/main/java/run/halo/app/config/WebServerSecurityConfig.java
src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
src/main/java/run/halo/app/extension/GroupVersionKind.java
src/main/resources/application-dev.yaml

/area core
/milestone 2.0
为自动生成的自定义模型 API 提供 Swagger 文档描述。请看下图：
参考：
- https://springdoc.org/v2/#spring-webfluxwebmvc-fn-with-functional-endpoints
Fixes #
1. 以 dev profile 启动 Halo
2. 访问 <http://localhost:9090/actuator/swagger-ui>
> :information_source: 由于 application-dev.yaml 中配置了 management 端口，所以这里访问 Swagger 的端口为 9090，而不是默认的 8090。
```release-note
None
```

Refine Swagger document for Extension APIs

---

src/main/java/run/halo/app/handler/file/UpOssFileHandler.java

/area core
problem：
附件存储类型选择又拍云时，上传到又拍云的文件名被重命名为原图片名的MD5值。
resolve：
参考 #1500，通过 FilePathDescriptor 来构建 fullPath，relativePath 等
Fixes #2181
```release-note
重构又拍云附件上传文件命名规则为保持原文件名
```

fix: use the original name when uploading the attachment to upyun oss

---

src/main/java/run/halo/app/extension/DefaultExtensionClient.java
src/main/java/run/halo/app/extension/ExtensionClient.java
src/main/java/run/halo/app/extension/Unstructured.java
src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
src/test/java/run/halo/app/extension/ExtensionCreateHandlerTest.java
src/test/java/run/halo/app/extension/ExtensionDeleteHandlerTest.java
src/test/java/run/halo/app/extension/ExtensionUpdateHandlerTest.java
src/test/java/run/halo/app/extension/UnstructuredTest.java

/area core
/milestone 2.0
Add additional method to fetch Extension by GVK and name. If you are using `ExtensionClient`, now you can fetch an Extension by `GroupVersionKind` and its name instead of its type. Because sometimes we don't know the exact type.
Usage example:
```java
client.fetch(fromAPIVersionAndKind("fake.halo.run/v1alpha1", "Fake"), "fake")
```
Fixes #
```release-note
None
```

Add an additional method to fetch Extension by GVK and name

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
src/main/java/run/halo/app/extension/DefaultExtensionClient.java
src/main/java/run/halo/app/extension/ExtensionClient.java
src/main/java/run/halo/app/extension/Watcher.java
src/main/java/run/halo/app/extension/WatcherPredicates.java
src/main/java/run/halo/app/extension/controller/Controller.java
src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
src/main/java/run/halo/app/extension/controller/ControllerManager.java
src/main/java/run/halo/app/extension/controller/DefaultController.java
src/main/java/run/halo/app/extension/controller/DefaultDelayQueue.java
src/main/java/run/halo/app/extension/controller/ExtensionWatcher.java
src/main/java/run/halo/app/extension/controller/Reconciler.java
src/main/java/run/halo/app/extension/controller/RequestQueue.java
src/main/java/run/halo/app/extension/controller/RequestSynchronizer.java
src/main/java/run/halo/app/extension/store/ExtensionStoreClientJPAImpl.java
src/main/java/run/halo/app/security/SuperAdminInitializer.java
src/main/resources/application-dev.yaml
src/test/java/run/halo/app/PathPrefixPredicateTest.java
src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
src/test/java/run/halo/app/extension/FakeExtension.java
src/test/java/run/halo/app/extension/controller/ControllerBuilderTest.java
src/test/java/run/halo/app/extension/controller/DefaultControllerTest.java
src/test/java/run/halo/app/extension/controller/DefaultDelayQueueTest.java
src/test/java/run/halo/app/extension/controller/DelayedEntryTest.java
src/test/java/run/halo/app/extension/controller/ExtensionWatcherTest.java
src/test/java/run/halo/app/extension/controller/RequestSynchronizerTest.java
src/test/java/run/halo/app/security/SuperAdminInitializerTest.java

/kind feature
/area core
/milestone 2.0
This PR mainly implements Extension reconciliation mechanism. That would make developers be able to monitor changes of Extension they care about and make the status of Extension be consistent eventually.
- Controllers in core
Controllers in core are managed by ControllerManager, including starting and disposing.
- Controllers in plugins
Controllers in plugins are managed by PluginManager.
Examplary of Controller:
```java
@Bean
Controller userController(ExtensionClient client) {
return new ControllerBuilder("user-controller", client)
.reconciler(new UserReconciler(client))
.extension(new User())
.build();
}
```
```java
@Slf4j
public class UserReconciler implements Reconciler {
private final ExtensionClient client;
public …
```

Implement Extension reconciliation mechanism

---

src/main/java/run/halo/app/controller/admin/api/PostController.java
src/main/java/run/halo/app/factory/StringToEnumConverterFactory.java
src/main/java/run/halo/app/model/params/BasePostParam.java
src/main/java/run/halo/app/service/impl/BasePostServiceImpl.java
src/main/java/run/halo/app/service/impl/PostServiceImpl.java

Article update time logic optimization;
Update the Edit_time field in the Posts table only when you change the post title or post content
Fixes #2193 
```release-note
NONE
```

perf: optimize the update logic of post editTime field

---

src/main/java/run/halo/app/utils/FileUtils.java
src/test/java/run/halo/app/utils/FileUtilsTest.java

/kind bug
/area core
Check directory traversal while renaming file.
Fixes #2202 
```release-note
修复静态存储文件重命名时文件名造成的目录逃逸问题
```

Fix directory traversal issue while renaming static file

---

build.gradle
src/test/java/run/halo/app/handler/file/HuaweiObsSdkTest.java

/kind bug
/kind regression
/area core
Revert huaweicloud-sdk-java-obs from 3.21.8.1 to 3.21.4.
Please see the release notes of the sdk from <https://github.com/huaweicloud/huaweicloud-sdk-java-obs/blob/81539706e743b3fceaaa7b3bac99c4ddcda7fdda/README.MD>.
Fixes #1909 
```release-note
修复上传附件到华为云时提示“NoSuchMethodError，okhttp3.RequestBody.create”错误
```

Revert huaweicloud-sdk-java-obs from 3.21.8.1 to 3.21.4

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/reconciler/RoleBindingReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/RoleBindingReconcilerTest.java

/kind feature
/area core
/milestone 2.0
This PR adds a RoleBinding reconciler to reset role names of users if reconciler detects any changes of RoleBindings.
Fixes #
```release-note
None
```

Add rolebinding reconciler to reset role names of users

---

src/main/java/run/halo/app/core/extension/Plugin.java
src/main/java/run/halo/app/core/extension/Setting.java
src/main/java/run/halo/app/infra/SchemeInitializer.java
src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
src/main/java/run/halo/app/plugin/SettingFetcher.java
src/test/java/run/halo/app/core/extension/SettingTest.java
src/test/java/run/halo/app/plugin/SettingFetcherTest.java
src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java

/kind feature
/area core
/milestone 2.0
新增插件设置，允许通过 Setting 自定义模型生成表单并收集其值为 ConfigMap
插件可以通过注入 SettingFetcher 来获取值并使用它,例如：
```java
Sns sns = settingFetcher.getGroupForObject("sns", Sns.class);
```
Fixes #
```release-note
None
```

feat: add plugin setting support

---

src/main/java/run/halo/app/extension/DefaultExtensionClient.java
src/main/java/run/halo/app/extension/ExtensionClient.java
src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
src/main/java/run/halo/app/extension/ListResult.java
src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
src/test/java/run/halo/app/extension/ExtensionListHandlerTest.java

/area core
/milestone 2.0
This PR is refactoring the response structure of Extension list API as follows:
```json
{
"page": 0,
"size": 0,
"total": 1,
"items": [
{
"spec": {
"displayName": "Administrator",
"email": "admin@halo.run",
"password": "{bcrypt}$2a$10$/YveWyuf9vyYrHE3fiToI.bGBy5Hgs1eViRvKzU7Kl982la5NSwWO",
"registeredAt": "2022-06-17T09:35:47.237625514Z",
"twoFactorAuthEnabled": false,
"disabled": false
},
"apiVersion": "v1alpha1",
"kind": "User",
"metadata": {
"name": "admin",
"annotations": {
"user.halo.run/roles": "[\"super-role\"]",
"rbac.authorization.halo.run/role-names": "[\"second-super-role\",\"super-role\"]"
},
"version": 3077,
"creationTimestamp": "2022-06-17T09:35:47.367919552Z"
}
}
],
"first": true,
"last": true,
"hasNext": false, …
```

Refactor the response structure of Extension list API

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/config/WebServerSecurityConfig.java
src/main/java/run/halo/app/extension/controller/ControllerManager.java
src/main/java/run/halo/app/infra/properties/ExtensionProperties.java
src/main/java/run/halo/app/infra/properties/HaloProperties.java
src/main/java/run/halo/app/infra/properties/SecurityProperties.java
src/main/java/run/halo/app/security/SuperAdminInitializer.java
src/test/java/run/halo/app/security/SuperAdminInitializerTest.java
src/test/resources/application.yaml

/kind failing-test
/area core
/milestone 2.0
Before this PR, our unit tests were flaky to run. After my inspection, I found that extension controllers will run asynchronously at every unit test that is annotated `@SpringBootTest` annotation. Please see the log of failing test:
```java
ExtensionConfigurationTest > shouldReturnNotFoundWhenSchemeNotRegistered() FAILED
java.lang.AssertionError at ExtensionConfigurationTest.java:72
```
So this PR makes Halo create super admin initializer and run extension controllers conditionally, especially in tests.
You can configure the following property to disable super admin initialization and extension controllers running:
```yaml
halo:
security:
initializer:
disabled: true
extension:
controller:
disabled: true
```
BTW, we can …

Create super admin initializer and run extension controllers conditionally

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/core/extension/service/UserService.java
src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java

/kind feature
/area core
/milestone 2.0
This PR provides an API to change password of user. If the username is equal to `-`, we will change the password of current login user. Otherwise, we update the password according the request URI.
Here is an example:
- Request
```bash
curl -X 'PUT' \
'http://localhost:8090/apis/api.halo.run/v1alpha1/users/-/password' \
-H 'accept: */*' \
-H 'Content-Type: */*' \
-d '{
"password": "openhalo"
}'
```
- Response
```json
{
"spec": {
"displayName": "Administrator",
"email": "admin@halo.run",
"password": "{bcrypt}$2a$10$/v8/nbxoUFGBDoWfOF2NHOHk.2RS0OFfS5AtN2g/mCGjScX19KvSG",
"registeredAt": "2022-07-15T07:50:25.151513387Z",
"twoFactorAuthEnabled": false,
"disabled": false
},
"apiVersion": "v1alpha1",
"kind": "User",
"metadata": {
"name": "admin", …
```

Add an API to change password of user

---

src/main/java/run/halo/app/extension/DefaultExtensionClient.java
src/main/java/run/halo/app/extension/ExtensionRouterFunctionFactory.java
src/test/java/run/halo/app/config/ExtensionConfigurationTest.java
src/test/java/run/halo/app/extension/DefaultExtensionClientTest.java
src/test/java/run/halo/app/extension/ExtensionDeleteHandlerTest.java

/area core
/milestone 2.0
Do not delete directly when invoking ExtensionClient#delete. We just flag it by setting metadata.deletionTimestamp.
The rest should be done by garbage collector.
```release-note
None
```

Refactor deletion of Extension in Extension client

---

src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java
src/main/java/run/halo/app/infra/properties/HaloProperties.java
src/test/java/run/halo/app/infra/ExtensionResourceInitializerTest.java

/area core
/milestone 2.0
This PR makes required extensions got initialized when system starts up. Of course, we can stop the initialization by setting property `halo.required-extension-disabled=true`.
Secondly, we are using [PathMatchingResourcePatternResolver](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/io/support/PathMatchingResourcePatternResolver.html) support more functional Extension locations, please see the doc for more.
```release-note
None
```

Initialize required extensions when system starts up

---

src/main/java/run/halo/app/extension/router/selector/FieldCriteriaPredicateConverter.java
src/main/java/run/halo/app/extension/router/selector/Operator.java
src/test/java/run/halo/app/extension/router/selector/FieldCriteriaPredicateConverterTest.java
src/test/java/run/halo/app/extension/router/selector/OperatorTest.java

/kind feature
/area core
/milestone 2.0
/release-note-none
- Add `IN` operator for fieldSelector and labelSelector.
- Adapt name field selector with `IN` operator.
```release-note
None
```

Add IN operator for fieldSelector and labelSelector

---

src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java
src/main/java/run/halo/app/handler/file/UpOssFileHandler.java

/kind bug
修复了在云端删除文件后，在Halo同时删除多个附件失败的bug。
Halo数据库里的附件并不会和云端文件实时同步，如果在云端删除文件多个后又在Halo删除，在删除第一个文件后则会抛出异常导致其它文件无法在halo的数据库中正常删除。这个PR通过删除在删除又拍云和七牛云的附件后判断返回状态和抛出异常的代码来解决这个问题。
Fixes #2283
该bug只在七牛云和又拍云存在，其它云储存没有判断返回状态和抛出异常的代码，因此不存在这个问题。
```release-note
NONE
```

fix: fail to delete multiple files if the files are removed from upstream storage

---

src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java

/kind bug
发现在七牛的 [QiniuOssFileHandler:145](https://github.com/halo-dev/halo/blob/f8bd4febb9ee59847e1d199b10f3be7ae1c95320/src/main/java/run/halo/app/handler/file/QiniuOssFileHandler.java#L145-L152) 行中，如果文件不是图片类型的话就跳过了setThumbPath
但是在其他文件存储的handler中（如：本地 [LocalFileHandler:125](https://github.com/halo-dev/halo/blob/f8bd4febb9ee59847e1d199b10f3be7ae1c95320/src/main/java/run/halo/app/handler/file/LocalFileHandler.java#L125), [TencentCosFileHandler:128](https://github.com/halo-dev/halo/blob/f8bd4febb9ee59847e1d199b10f3be7ae1c95320/src/main/java/run/halo/app/handler/file/TencentCosFileHandler.java#L128)）调用了handleImageMetadata default方法，该方法最后判断 thumbPath 为空时会将其设为 filePath
故在七牛云handler使用了handleImageMetadata 方法，使得其他类型文件也可以setThumbPath，并成功上传不会引发错误
Fixes #2320 …

fix: Qiniuoss cannot upload non image attachments

---

src/main/java/run/halo/app/core/extension/MenuItem.java
src/main/java/run/halo/app/core/extension/reconciler/MenuItemReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/MenuItemReconcilerTest.java

/area core
/milestone 2.0
1. Synchronize permalink and display name of category every 1min
2. Synchronize permalink and display name of tag every 1min
3. Synchronize permalink and display name of post every 1min
Please note that we don't handle the synchronization of `Page` because we don't have the extension yet.
See https://github.com/halo-dev/halo/pull/2303 for more.
**How to test?**
1. Create a Category/Tag/Post and check the permalink
2. Create a menu and a menu item
3. Set `spec.categoryRef.name` of menu item with the extension name we just created
5. Update the menu item and check the permalink
6. Update slug name of Category/Tag/Post and check the permalink
7. Wait for 1min and check the permalink of menu item
```release-note
None
```

Refine menu item reconciler to sync permalinks of other refs

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
src/main/java/run/halo/app/infra/ExternalUrlSupplier.java
src/main/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplier.java
src/main/java/run/halo/app/infra/properties/HaloProperties.java
src/main/resources/application.yaml
src/test/java/run/halo/app/PathPrefixPredicateTest.java
src/test/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplierTest.java
src/test/resources/application.yaml

/kind feature
/area core
/milestone 2.0
Many permanent links will be generated in the system, in order to ensure accessiblity, we will allow users to configure external access links instead of internal url.
Before starting the application, we need to modify the following configuration into the configuration file(application.yaml):
```yaml
halo:
external-url: https://halo.run
```
Then, after booting the application, check for permalinks of attachments.
```release-note
支持在配置文件中修改博客访问链接
```

Allow configuration of external access url

---

src/main/java/run/halo/app/content/permalinks/CategoryPermalinkPolicy.java
src/main/java/run/halo/app/content/permalinks/ExtensionLocator.java
src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
src/main/java/run/halo/app/content/permalinks/TagPermalinkPolicy.java
src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
src/main/java/run/halo/app/infra/utils/PathUtils.java
src/main/java/run/halo/app/theme/router/PermalinkIndexDeleteCommand.java
src/main/java/run/halo/app/theme/router/PermalinkIndexer.java
src/main/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/CategoryRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/IndexRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/PostRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/TagRouteStrategy.java
src/main/resources/extensions/system-setting.yaml
src/test/java/run/halo/app/infra/utils/PathUtilsTest.java
src/test/java/run/halo/app/theme/router/PermalinkIndexerTest.java
src/test/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategyTest.java
src/test/java/run/halo/app/theme/router/strategy/CategoryRouteStrategyTest.java
src/test/java/run/halo/app/theme/router/strategy/PostRouteStrategyTest.java
src/test/java/run/halo/app/theme/router/strategy/TagRouteStrategyTest.java

/milestone 2.0
/area core
使用正则细化主题端路由并优化
如何测试：
1. 在 admin 系统设置中修改文章文章详情页访问规则
2. 根据规则访问文章详情页，如规则为：`/{year:\d{4}}/{month:\d{2}}/{slug}` 而存在文章 slug 为 fake-slug 且发布日期为 2022-09-08 则 /2022/09/fake-slug 能访问， /2022/9/fake-slug 则不能访问
使用规则 `/{year:\d{4}}/{month:\d{2}}/{day:\d{2}}/{slug}`时 /2022/09/08/fake-slug 能访问 /2022/09/8/fake-slug ，则不能访问
Fixes #2396
```release-note
None
```

refactor: theme route pattern and permalink indexer

---

src/main/java/run/halo/app/service/impl/PostCategoryServiceImpl.java
src/test/java/run/halo/app/service/impl/PostCategoryServiceImplTest.java

/kind bug
/area core
修改 PostCategoryServiceImpl.getPostBy() ，使其同时返回子分类文章。同时添加相关测试样例。
Fixes #2368 
```release-note
修复在单个分类所属文章页面页面变量中无法获取子分类中文章的问题
```

fix: getPostBy() does not return posts in subcategories

---

src/main/java/run/halo/app/core/extension/Category.java
src/main/java/run/halo/app/core/extension/Post.java
src/main/java/run/halo/app/core/extension/Tag.java
src/main/java/run/halo/app/core/extension/reconciler/CategoryReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
src/main/java/run/halo/app/theme/finders/vo/CategoryVo.java
src/main/java/run/halo/app/theme/finders/vo/TagVo.java
src/test/java/run/halo/app/core/extension/reconciler/CategoryReconcilerTest.java
src/test/java/run/halo/app/core/extension/reconciler/TagReconcilerTest.java
src/test/java/run/halo/app/theme/finders/impl/TagFinderImplTest.java

/kind feature
/milestone 2.0
/area core
统计分类和标签下的文章
Fixes #2401
1. 创建一个多层级的分类及若干文章，查看分类的 status.posts 是否包含当前及其子分类下的文章
2. 创建标签，并将其分配给若干文章，查看标签的 status.posts 是否正确
3. 在主题端查看分类和标签包含的文章数量是否正确，需要注意的是主题端显示的文章数量只包含已发布且 visiable 为 public 且未删除的
```release-note
None
```

feat: count the number of posts under categories and tags

---

docs/developer-guide/custom-endpoint.md
src/main/java/run/halo/app/config/SwaggerConfig.java
src/main/java/run/halo/app/core/extension/endpoint/CommentEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/ContentEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/CustomEndpointsBuilder.java
src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/ReplyEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/SinglePageEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/plugin/PluginRequestMappingHandlerMapping.java
src/main/resources/extensions/role-template-anonymous.yaml
src/main/resources/extensions/role-template-authenticated.yaml
src/main/resources/extensions/role-template-permissions.yaml
src/main/resources/extensions/role-template-user.yaml
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/plugin/PluginRequestMappingHandlerMappingTest.java
src/test/java/run/halo/app/security/authorization/RequestInfoResolverTest.java

/area core
/milestone 2.0
- 修改管理后台使用的自定义 API 的 group 为 `api.console.halo.run`
- 面向三方应用的自定义 API 的 group 为 `api.halo.run`
- 插件的自定义 API 的 group 为 `api.plugin.halo.run`
Fixes #2418
```release-note
None
```

refactor: rename api group for custom api

---

build.gradle
src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/reconciler/SystemSettingReconciler.java
src/main/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcher.java
src/main/java/run/halo/app/infra/SystemSetting.java
src/main/java/run/halo/app/plugin/SettingFetcher.java
src/main/java/run/halo/app/theme/router/PermalinkPatternProvider.java
src/main/resources/extensions/system-configurable-configmap.yaml
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/core/extension/reconciler/SystemSettingReconcilerTest.java
src/test/java/run/halo/app/infra/SystemConfigurableEnvironmentFetcherTest.java
src/test/java/run/halo/app/theme/router/PermalinkPatternProviderTest.java

/area core
/milestone 2.0
将原来系统默认的系统配置 system 改名为 system-default, 并使用名为 system 的 ConfigMap 来存储用户自定义的系统配置。系统最终配置为用户自定义系统配置 Merge Patch 系统默认配置的结果。
see also #2304
Fixes #2304
```release-note
None
```

feat: the ConfigMap named system to store user-defined configurations

---

src/main/java/run/halo/app/content/PostQuery.java
src/main/java/run/halo/app/content/impl/PostServiceImpl.java

/area core
/milestone 2.0
修复文章列表的分类、标签查询参数方法名和取值不一致导致无效问题
Fixes #2439
```release-note
None
```

fix: category and tag query parameters in post query

---

src/main/java/run/halo/app/content/PostQuery.java
src/main/java/run/halo/app/content/PostSorter.java
src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/core/extension/Post.java

/area core
/milestone 2.0
文章列表新增更过的查询条件
- publishPhase 状态
- visible 可见性
- keyword 关键词
新增排序（sort）（可逆序 sortOrder）
- 创建时间（默认创建时间逆序）
- 发布时间
关键词过滤暂不管文章内容，否则需要查询所有文章内容判断是否包含字符串
排序暂无法支持评论数量和阅读量，这两个属性属于文章统计需要 #2430 的支撑
Fixes #2424
```release-note
None
```

feat: add more query predicates for post list

---

src/main/java/run/halo/app/config/WebServerSecurityConfig.java
src/main/java/run/halo/app/infra/AnonymousUserConst.java
src/main/java/run/halo/app/security/authorization/DefaultRuleResolver.java
src/main/java/run/halo/app/security/authorization/RequestInfoAuthorizationManager.java
src/test/java/run/halo/app/security/authentication/jwt/JwtAuthenticationTest.java
src/test/java/run/halo/app/security/authorization/AuthorizationTest.java

/area core
/milestone 2.0
- 未认证用户在系统中被定义为匿名用户(username=anonymousUser)，它在授权系统中具有 principle=anonymousUser 且 role=anonymous，key=[secure randomly generated key]
- 未认证用户和已认证用户都将被赋予一个匿名用户角色
参考：
- [Spring security#ServerHttpSecurity.AnonymousSpec](https://github.com/spring-projects/spring-security/blob/70460ca0092dc597e0753af29d3cc823b6b25c80/config/src/main/java/org/springframework/security/config/web/server/ServerHttpSecurity.java#L4387)
- [Spring security reactive AnonymousAuthenticationWebFilter](https://github.com/spring-projects/spring-security/blob/70460ca0092dc597e0753af29d3cc823b6b25c80/web/src/main/java/org/springframework/security/web/server/authentication/AnonymousAuthenticationWebFilter.java#L46)
Fixes #
```release-note
None
```

feat: any user who accesses the system has the anonymous role

---

src/main/java/run/halo/app/core/extension/Setting.java
src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
src/main/resources/extensions/attachment-local-policy.yaml
src/main/resources/extensions/system-setting.yaml
src/test/java/run/halo/app/core/extension/SettingTest.java
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java

/area core
/milestone 2.0
- 安装主题后通过读取主题 Setting 模型中的默认值初始化一个 ConfigMap
- 修改了 Setting 模型的 spec  结构（多了一层 forms 嵌套），配置示例如下：
```yaml
apiVersion: v1alpha1
kind: Setting
metadata:
name: theme-anatole-setting
spec:
forms:
- group: basic
label: 基本设置
formSchema:
- $formkit: select
name: sidebar_width
label: 侧边栏宽度
options:
"20%": 20%
"30%": 30%
"40%": 40%
"50%": 50%
value: "40%"
```
Fixes #2414
```release-note
None
```

feat: create a configmap based on the setting definition when installing a theme

---

src/main/java/run/halo/app/config/WebFluxConfig.java
src/main/java/run/halo/app/infra/properties/ConsoleProperties.java
src/main/java/run/halo/app/infra/properties/HaloProperties.java
src/main/resources/application.yaml
src/test/java/run/halo/app/config/WebFluxConfigTest.java
src/test/resources/console/index.html

/kind feature
/area core
/milestone 2.0
Support configuring console location to access console. By default, `classpath:/console/` location will be used. If anyone want to debug locally, you can configure the console properties as following:
```yaml
halo:
console:
location: file:/home/xxx/path/to/halo-admin/dist/ # The trailing slash is required or it will be treated with a file instead of a folder.
```
```release-note
None
```

Support configuring console location to access console

---

src/main/java/run/halo/app/theme/ThemeConfiguration.java
src/main/java/run/halo/app/theme/ThemeLinkBuilder.java
src/main/java/run/halo/app/theme/dialect/DefaultLinkExpressionFactory.java
src/main/java/run/halo/app/theme/dialect/LinkExpressionObjectDialect.java
src/test/java/run/halo/app/theme/dialect/LinkExpressionObjectDialectTest.java

/kind feature
/milestone 2.0
/area core
允许主题模板在 HTML 或 JavaScript 片段中使用表达式对象获得链接：
- `${#theme.assets('/js/main.js'))}`
- `${#theme.route('/categories')}`
Fixes #2435
```release-note
None
```

feat: add theme link expression dialect

---

src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
src/test/java/run/halo/app/core/extension/endpoint/ThemeEndpointTest.java

/kind feature
/milestone 2.0
/area core
新增主题设置重载 API，调用此 API 会从主题文件中重新加载 settings.yaml 复盖原有记录，便于主题开发和测试
插件不需要此功能，配置了 `fixedPluginPath` 后每次重启都会加载新的配置项
Fixes #2426
```release-note
None
```

feat: add theme setting reload API

---

.gitignore
src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
src/test/java/run/halo/app/core/extension/endpoint/AttachmentEndpointTest.java

/kind bug
/area core
/milestone 2.0
Encode path of attachment permalink instead of using URI#resolve methods directly.
Fixes https://github.com/halo-dev/halo/issues/2408
Steps to test:
1. Create a file with special name, e.g.: `hello world.txt`
2. Upload the file and see the permalink
```release-note
None
```

Fix the problem of generating permalink due to special filename

---

src/main/java/run/halo/app/config/SwaggerConfig.java
src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
src/main/java/run/halo/app/core/extension/endpoint/CommentEndpoint.java
src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
src/main/java/run/halo/app/theme/dialect/CommentWidget.java
src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
src/main/java/run/halo/app/theme/finders/vo/ReplyVo.java
src/main/resources/extensions/role-template-anonymous.yaml
src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
src/test/java/run/halo/app/theme/endpoint/CommentFinderEndpointTest.java

/kind feature
/milestone 2.0
/area core
- 新增主题端评论列表功能
- 新增 `<halo:comment />` html tag 用于扩展评论组件
- 插件可以实现 `CommentWidget` 扩展点来渲染评论组件 html 块，以替换 `<halo:comment />` 标签
Fixes #2432
```release-note
新增主题端评论列表功能
```

feat: add comment list APIs for theme-side

---

src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
src/main/resources/application-postgresql.yaml
src/main/resources/schema-postgresql.sql

/kind feature
/area core
/milestone 2.0
Add PostgreSQL script to support running Halo with PostgreSQL database. BTW, there was a weird issue (emty posts even if there are some posts created) while listing Post, and I fixed it in this PR.
Partial Fixes https://github.com/halo-dev/halo/issues/2464
Steps to test:
1. Start up PostgreSQL. e.g.:
```yaml
version: '3.1'
services:
db:
image: postgres
restart: always
environment:
POSTGRES_PASSWORD: openpostgresql
ports:
- 5432:5432
adminer:
image: adminer
restart: always
ports:
- 8080:8080
```
```bash
docker-compose -f postgresql.yaml up
```
2. Start Halo with `postgresql` profile. e.g.:
```bash
./gradlew bootRun --args="--spring.profiles.active=postgresql"
```
3. Validate the functionality of Halo
```release-note
None
```

Support running Halo with PostgreSQL

---

src/main/resources/extensions/system-setting.yaml

/area core
/milestone 2.0
完善系统设置表单的资源定义。
- 副标题的验证改为取消必填
- 优化主题路由规则显示名称
- 移除暂未实现的用户注册相关设置
- 代码注入设置的文案
Fixes #
```release-note
完善系统设置表单的资源定义
```

perf: refine the extension definition for system setting

---

src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
src/main/java/run/halo/app/theme/engine/SpringWebFluxTemplateEngine.java
src/main/java/run/halo/app/theme/router/PermalinkIndexer.java
src/main/java/run/halo/app/theme/router/strategy/PermalinkPredicates.java
src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
src/test/java/run/halo/app/theme/router/PermalinkIndexerTest.java
src/test/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategyTest.java

/kind bug
/area core
/milestone 2.0
Support setting special characters on slug name of SinglePage.
Partial Fixes https://github.com/halo-dev/halo/issues/2473
Steps to test:
1. Create single pags with slug name `中文`, `/a/b/c/d` or `a / b`
2. Request it with permalink generated by Halo
```release-note
None
```

Fix the problem of not being able to request SinglePage with slug name containing special characters

---

src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/SortResolver.java
src/main/java/run/halo/app/extension/ListResult.java
src/test/java/run/halo/app/core/extension/endpoint/PluginEndpointTest.java

/kind feature
/area core
/milestone 2.0
Support filtering and sorting plugins. e.g.:
```bash
http://localhost:8090/api/api.console.halo.run/v1alpha1/plugins?keyword=xyz&enabled=true&sort=creationTimestamp,desc
```
Fixes https://github.com/halo-dev/halo/issues/2470
```release-note
None
```

Support filtering and sorting plugins

---

src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java

/kind bug
/area core
/milestone 2.0
Fix the problem of changing password not exist before.
Partial Fixes https://github.com/halo-dev/halo/issues/2427
Steps to test:
1. Create an user and change his/her password
2. Login with the user and the password
```release-note
None
```

Fix the problem of changing password not exist before

---

build.gradle

/area core
/milestone 2.0
将 spring boot 的版本从 3.0.0-M5 降级到 3.0.0-M5 以解决 swragger 无法使用的问题
Fixes #
```release-note
None
```

chore: degrade springboot version from 3.0.0-M5 to 3.0.0-M4

---

README.md

/milestone 2.0
因为目前暂时没有提供 JAR 包，所以移除 README 有关使用 JAR 包运行的文档。
```release-note
None
```

docs: remove readme documentation about running with jar

---

build.gradle

/area core
/milestone 2.0
1. Upgrade Spring Boot to 3.0.0-M5. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes for more.
2. Upgrade SpringDoc to 2.0.0-M6. The version is compatible to Spring Boot 3.0.0-M5. See https://github.com/springdoc/springdoc-openapi/issues/1865 for more.
Please check the API documentation endpoint: <http://localhost:8090/swagger-ui.html>.
```release-note
None
```

Bump version of Spring Boot & SpringDoc

---

src/main/resources/extensions/role-template-anonymous.yaml

/kind bug
/area core
/milestone 2.0
修复主题端内容页访问量统计接口角色规则动词配置错误问题
Fixes #2507
```release-note
None
```

fix: tracker counter api does not need authentication for theme

---

build.gradle
src/main/resources/application-mysql.yaml
src/main/resources/schema-mysql.sql

/kind feature
/area core
/milestone 2.0
Add MySQL script to support running Halo with MySQL database due to https://github.com/jasync-sql/jasync-sql/issues/311 has been resolved.
Fixes https://github.com/halo-dev/halo/issues/2464
Steps to test:
1. Start up MySQL. e.g.:
```yaml
version: '3.1'
services:
db:
image: mysql
command: --default-authentication-plugin=mysql_native_password
restart: always
environment:
MYSQL_ROOT_PASSWORD: openmysql
ports:
- 3306:3306
adminer:
image: adminer
restart: always
ports:
- 8080:8080
```
```bash
docker-compose -f mysql.yaml up
```
2. Start Halo with `mysql` profile. e.g.:
```bash
./gradlew bootRun --args="--spring.profiles.active=mysql"
```
3. Validate the functionality of Halo
```release-note
None
```

Support running Halo with MySQL and MariaDB database

---

src/main/java/run/halo/app/plugin/resources/JsBundleRuleProvider.java

/milestone 2.0
Ref #2519 ，我们已经将 halo-admin 的命名改为了 console，所以相关命名需要同步修改。
Fixes #2519 
/hold 
等待插件的 PR。
测试方式：
1. 使用 plugin-links 插件的 https://github.com/halo-sigs/plugin-links/pull/3 PR 进行测试，需要 Clone 到本地。
2. 使用 `./graldew build` 的命令编译插件，得到 `build/libs/plugin-link-*.jar`。
3. Halo 的插件运行模式改为 deployment 模式。
4. 启动 Halo 之后，安装第二步得到的插件。
5. 检查浏览器控制台是否正常加载了 `/assets/PluginLinks/console/main.js` 和 `/assets/PluginLinks/admin/style.css`
```release-note
None
```

chore: rename the default location of the plugin's bundle resources to `console`

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
src/main/java/run/halo/app/plugin/BasePlugin.java
src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/SpringExtensionFactory.java
src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java

/kind bug
/area core
/milestone 2.0
BasePlugin 持有了一个当前插件的 PluginApplicationContext 当插件停止后重新启用会获取到旧的 PluginApplicationContext，之前之所以这样写的目的只是插件的这个 BasePlugin 不支持依赖注入，目前已经支持所以不在这样解决问题
日志：
```
Caused by: java.lang.IllegalStateException: run.halo.app.plugin.PluginApplicationContext@6baf2671 has been closed already
at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1125) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1158) ~[spring-context-6.0.0-M5.jar:6.0.0-M5]
at run.halo.app.plugin.SpringExtensionFactory.create(SpringExtensionFactory.java:102) ~[classes/:2.0.0-alpha.1]
at …
```

fix: the exception of plugin context has been closed when plugin restart

---

src/main/resources/extensions/role-template-authenticated.yaml
src/main/resources/extensions/role-template-menu.yaml
src/main/resources/extensions/role-template-plugin.yaml

/area core
/milestone 2.0
优化系统角色模板配置
- 认证用户仅具有名为 system-states 的 ConfigMap 查看权限而非所有 ConfigMap查看权限
- 主题和插件的管理权限目前需要单独勾选 ConfigMap 和 Setting 的权限才可以看到表单和值
Fixes #2523
```release-note
None
```

refactor: system role templates

---

src/main/java/run/halo/app/infra/ExtensionResourceInitializer.java

/kind bug
/area core
/milestone 2.0
When we initialize default extensions at Halo startup, updation of one extension is very likely to be failed due to modification conflict. Then, remaining extensions won't be updated anymore.
Therefore, this PR resolve this problem by retrying updation with 3 times with interval 100ms and continue extension updation if modification conflict occurs.
1. Fully initialize system(e.g.: Clear `~/halo-next` before starting Halo)
2. Update Role `authenticated` as you wish via Extension API
3. Restart Halo and check it again
4. Retry multiple times
```release-note
修复系统默认数据无法正常更新的问题
```

Continue extension updation if modification conflict occurs

---

README.md

The README.md is out of date due to [2.0.0-alpha.2](https://github.com/halo-dev/halo/releases/tag/v2.0.0-alpha.2) released.
```release-note
None
```

Update README.md due to 2.0.0-alpha.2 released

---

src/main/java/run/halo/app/core/extension/Counter.java
src/main/java/run/halo/app/core/extension/endpoint/TrackerEndpoint.java
src/main/java/run/halo/app/metrics/CounterMeterHandler.java
src/main/java/run/halo/app/metrics/MeterUtils.java
src/main/java/run/halo/app/security/authorization/RbacRequestEvaluation.java
src/main/resources/extensions/role-template-anonymous.yaml
src/test/java/run/halo/app/metrics/MeterUtilsTest.java

/kind feature
/area core
/milestone 2.0
新增文章和评论等资源的点赞和踩 API
Fixes #2565
1.  创建并发布一篇文章 替换下面的 `your-post-name` 然后执行它
```curl
curl --location --request POST 'http://localhost:8090/apis/api.halo.run/v1alpha1/trackers/upvote' \
--header 'Content-Type: application/json' \
--data-raw '{
"group": "content.halo.run",
"plural": "posts",
"name": your-post-name
}
```
2. 请求成功并得到 response 为点赞数
3. 踩的 API 为 `http://localhost:8090/apis/api.halo.run/v1alpha1/trackers/downvote` 请求体与步骤1相同的测试方法
4. 重启 Halo 后 Counter 数据应该依然存在并且正确
```release-note
新增文章和评论等资源的点赞和踩 API
```

feat: add upvote and downvote tracker

---

src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistryTest.java

/area core
/milestone 2.0
对反向代理规则注册增加重复注册检查
场景：
ReverseProxyRouterFunctionRegistry 中有一个 pluginIdReverseProxyMap 记录了 插件名称和插件的 ReverseProxy 名称对应关系
当重复 fake-plugin -> test-reverse-proxy 时，pluginIdReverseProxyMap 的 value 不会去重，因此需要增加重复注册检查
Fixes #
本 PR 不需要测试，已经对上述场景添加了单元测试
```release-note
None
```

refactor: register method for reverse proxy registry

---

src/main/java/run/halo/app/theme/dialect/DefaultFaviconHeadProcessor.java
src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java

/kind feature
/area core
/milestone 2.0
模板渲染自动填充 Favicon 到 head 标签
Fixes #2581
在 console 系统设置 -> 基础设置 填写 Favicon 后，到主题端能到看它
```release-note
支持设置 Favicon
```

feat: add favicon head processor

---

src/main/java/run/halo/app/core/extension/endpoint/ThemeEndpoint.java
src/main/java/run/halo/app/extension/ListResult.java
src/main/java/run/halo/app/theme/ThemePathPolicy.java
src/main/resources/extensions/role-template-theme.yaml

/kind feature
/milestone 2.0
/area core
新增 API 用于查询未安装的主题
Fixes #2554
1. 安装几个主题
2. 直接解压几个主题到 work dir 的 themes 目录
3. 使用以下 endpoint 查询未安装的主题，期望获得所有未安装主题的 themes.yaml 信息
```
/apis/api.console.halo.run/v1alpha1/themes?uninstalled=true
```
```release-note
支持扫描主题目录下未安装的主题
```

feat: add an API to list uninstalled themes

---

src/main/java/run/halo/app/extension/JSONExtensionConverter.java
src/main/java/run/halo/app/extension/Metadata.java
src/main/java/run/halo/app/extension/MetadataOperator.java
src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
src/main/java/run/halo/app/extension/Unstructured.java
src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java
src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java

/kind feature
/area core
/milestone 2.0
See https://github.com/halo-dev/halo/issues/2309 for more.
Fixes https://github.com/halo-dev/halo/issues/2309
```release-note
新增 generateName 字段用于自动生成自定义模型名称
```

Enable generating metadata name using generateName

---

src/main/java/run/halo/app/extension/JSONExtensionConverter.java
src/main/java/run/halo/app/extension/Metadata.java
src/main/java/run/halo/app/extension/MetadataOperator.java
src/main/java/run/halo/app/infra/utils/YamlUnstructuredLoader.java
src/test/java/run/halo/app/extension/JsonExtensionConverterTest.java

/area core
Remove custom schema validation and make field metadata.name of extension required. So that the API client generated by `openapi-gen` will be more consistent than before.
```release-note
None
```

Make field metadata.name of extension required

---

src/main/java/run/halo/app/theme/finders/SiteStatsFinder.java
src/main/java/run/halo/app/theme/finders/impl/SiteStatsFinderImpl.java
src/main/java/run/halo/app/theme/finders/vo/SiteStatsVo.java

/kind feature
/area core
/milestone 2.0
提供主题端站点统计信息查询器
Fixes #
在任意主题页面使用如下语法
```
<p th:text="${siteStatsFinder.getStats()}"></p>
```
```release-note
提供主题端站点统计信息查询器
```

feat: add site stats finder for theme-side

---

src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
src/main/java/run/halo/app/core/extension/theme/ThemeUtils.java
src/main/java/run/halo/app/infra/utils/FileUtils.java
src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java

/kind feature
/area core
/milestone 2.0
This PR mainly provides an endpoint to upgrade theme.
Please see the request sample as follows:
```bash
curl -X 'POST' \
'http://localhost:8090/apis/api.console.halo.run/v1alpha1/themes/theme-default/upgrade' \
-H 'accept: */*' \
-H 'Content-Type: multipart/form-data' \
-F 'file=@theme-default-main.zip;type=application/x-zip-compressed'
```
We also can refer to API documentation:
Fixes https://github.com/halo-dev/halo/issues/2550
1. Install any theme you want
2. Unzip the theme and change the content of theme installed just now
3. Zip the theme and try to upgrade it by requesting theme upgrade API
```release-note
提供主题更新功能
```

Provide an endpoint to upgrade theme

---

src/main/java/run/halo/app/extension/DefaultSchemeManager.java
src/main/java/run/halo/app/extension/DefaultSchemeWatcherManager.java
src/main/java/run/halo/app/extension/controller/DefaultController.java
src/test/java/run/halo/app/extension/DefaultSchemeManagerTest.java
src/test/java/run/halo/app/extension/DefaultSchemeWatcherManagerTest.java

/kind bug
/area core
/milestone 2.0
Use CopyOnWriteArrayList on SchemeManager to prevent concurrent modification when link plugin is installed.
1. Install link plugin
2. Restart Halo
3. Delete any extensions
4. Check the result
```release-note
修复数据一直处于删除中的错误
```

Use CopyOnWriteArrayList on SchemeManager

---

src/main/java/run/halo/app/handler/file/UpOssFileHandler.java

/kind bug
/area core
/milestone 1.6.x
修复又拍云附件删除成功，但是管理页面的“internal server error” 报警
Fixes https://github.com/halo-dev/halo/issues/2603
```release-note
修复又拍云附件删除成功仍旧提示错误的问题
```

Fix the problem of deleting attachment on USS but failed

---

src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
src/main/java/run/halo/app/plugin/PluginBeforeStopSyncListener.java
src/main/java/run/halo/app/theme/router/PermalinkRefreshHandler.java
src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java

/area core
/milestone 2.0
重构 PluginReconciler，避免因为每一段逻辑的执行时间太长而增加乐观锁错误的发生概率
修复判断逻辑问题导致启动时因为发生乐关锁错误造成没有填充 entry 和 stylesheet 字段的问题
Fixes #2616
```release-note
None
```

refactor: plugin reconciler to fix entry path when optimistic lock occurred

---

build.gradle

/area core
/milestone 2.0
Please refer to <https://github.com/jasync-sql/jasync-sql/releases/tag/2.1.7>.
```release-note
None
```

Bump jasync-r2dbc-mysql to 2.1.7

---

src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistryTest.java

/area core
/milestone 2.0
ReverseProxyRouterFunctionRegistry 的注册方法之前使用了一个 LinkedMultiValueMap<String, String>，相当于是一个 Map<String, List<String>>，当插件启动后扫描到 ReverseProxy 资源保存到数据库会触发 ReverseProxyReconciler 调用`ReverseProxyRouterFunctionRegistry#register`，如果此时插件的 PluginApplicationContext 还没有被创建好，register 时会在中途因为获取不到 PluginApplicationContext 而失败然后 requeue，而 LinkedMultiValueMap 此时已经保存了一条记录 requeue后再执行 LinkedMultiValueMap（即`Map<String, List<String>>`） 这个 value 是一个 List 需要更多的判断来防止重复，需要用一个 Map<String, Set<String>>这样的结构来保证 requeue 时 ReverseProxyRouterFunctionRegistry 中集合结构之前的数据一致性这样更方便，所以将从 spring 的 LinkedMultiValueMap 切换到  guava 提供的 LinkedHashMultimap（它的结构是Map<K, Set<V>）
```release-note
None
```

refactor: use LinkedHashMultimap to replace MultiValueMap

---

src/main/java/run/halo/app/theme/router/RadixRouterTree.java
src/main/java/run/halo/app/theme/router/strategy/ArchivesRouteStrategy.java
src/test/java/run/halo/app/theme/router/RadixRouterTreeTest.java

/area core
/milestone 2.0
permalink 路由匹配时自动忽略末尾分隔符
例如
/archives  匹配到 /archives
/archives/ 匹配到 /archives
```release-note
None
```

refactor: ignore trailing separator for permalink router

---

src/main/java/run/halo/app/theme/finders/PostFinder.java
src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java
src/main/java/run/halo/app/theme/finders/vo/NavigationPostVo.java
src/main/java/run/halo/app/theme/finders/vo/PostCursorVo.java
src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java

/kind feature
/area core
/milestone 2.0
支持通过文章名称获取上一篇和下一篇文章数据
本 PR 通过实现一个固定大小的滑动窗口数据结构来通过传入的文章名称获取上一篇和下一篇文章
例如当具有一系列文章名为 [a, b, c, d, e, f, g]
查询文章名为 d 的文章的上一篇和下一篇则使用一个固定大小为 3 的滑动窗口, 示意图如下
通过窗口右移来调整当窗口圈住所需元素 D 时且 元素 D 的位置不是窗口的最后一个元素时得到一个想要的窗口
此时：
1. 如果 D 位于 window 中的第一个元素则 D 没有上一篇
2. 如果 D 位于 window 中间则 window 的第一个元素为 D 的上一篇，最后一个元素为下一篇
3. 如果 D 位于 window 的最后一个位置，则 D 没有下一篇
Fixes #2635
1. 创建几篇文章然后发布
4. 能通过 `${postFinder.cursor(your-post-name)}` 来获取到带有上一页下一页的文章数据
5. 当文章处于第一条时没有上一页，当文章处于最后一页时没有下一页（可以通过`${postCursor.hasPrevious()}` 和 `${postCursor.hasNext()}` 判断按钮是否展示）
```release-note
支持通过文章名称获取上一篇和下一篇文章数据
```

feat: support obtaining the previous post and next post according to post name

---

src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java

/kind bug
/area core
/milestone 2.0
修复文章和自定义页面的 labels 在文章标记为删除状态时没有更新的问题
A part of  #2647
1. 创建文章
2. 由于没有发布，此时访问文章的 permalink 访问不到
3. 发布文章，可以正常访问
4. 更新文章的 `spec.deleted=true`,在访问文章期望404，并且 `metadata.labels` 中的数据正确
5. 自定义页面亦如是
```release-note
None
```

fix: labels update for post and singlepage

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/content/permalinks/CategoryPermalinkPolicy.java
src/main/java/run/halo/app/content/permalinks/PostPermalinkPolicy.java
src/main/java/run/halo/app/content/permalinks/TagPermalinkPolicy.java
src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
src/test/java/run/halo/app/content/permalinks/CategoryPermalinkPolicyTest.java
src/test/java/run/halo/app/content/permalinks/PostPermalinkPolicyTest.java
src/test/java/run/halo/app/content/permalinks/TagPermalinkPolicyTest.java
src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java
src/test/java/run/halo/app/theme/finders/impl/PostFinderImplTest.java

/area core
/milestone 2.0
如果配置了 halo.externalUrl 则 permalink 生成时会自动加上 external url
Fixes #
1. 配置 `halo.externalUrl` 并启动
2. 创建几篇文章、标签、分类、自定义页面
3. console 端能看到访问路径自动带上了 external url 并且通过访问路径能正确访问到相应资源
```release-note
文章/分类/标签的访问路径自动追加外部访问地址
```

refactor: permalink automatically appends external url if it is configured

---

src/main/java/run/halo/app/core/extension/Theme.java
src/main/java/run/halo/app/theme/router/ViewNameResolver.java
src/main/java/run/halo/app/theme/router/strategy/CategoryRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/PostRouteStrategy.java
src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
src/test/java/run/halo/app/core/extension/ThemeTest.java
src/test/java/run/halo/app/theme/router/ViewNameResolverTest.java
src/test/java/run/halo/app/theme/router/strategy/CategoryRouteStrategyTest.java
src/test/java/run/halo/app/theme/router/strategy/PostRouteStrategyTest.java
src/test/java/run/halo/app/theme/router/strategy/RouterStrategyTestSuite.java

/kind feature
/milestone 2.0
/area core
文章/自定义页面/分类支持通过主题配置多套渲染模板
首先需要在 theme.yaml 中声明模板，以文章为例：
```yaml
apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
name: fake-theme-name
spec:
customTemplates:
post:
- name: 新闻
description: 新闻类型的文章模板
screenshot: foo.png
file: post_news.html
```
当文章页选择模板时便可得到下拉列表以配置使用哪个模板 see https://github.com/halo-dev/halo/issues/2322#issuecomment-1215135195
选择了模板之后将模板名存储到 post 的 spec.template 中，渲染时便会首先使用 spec.template，如果该模板不存在则渲染默认模板
Fixes #2569
1. 创建一篇文章并发布
2. 安装一个主题并查看文章详情，默认渲染主题提供的 post.html 页面
3. 修改此文章的 spec.template 字段为一个新的 html 例如 spec.template=post_docs
4. 查看该文章的详情页会渲染为 post_docs.html
5. 分类、自定义页面亦如是
```release-note
文章/自定义页面/分类支持通过主题配置多套渲染模板
```

feat: support custom rendering templates configure through themes

---

src/main/java/run/halo/app/core/extension/Plugin.java
src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
src/main/java/run/halo/app/infra/utils/PathUtils.java
src/main/java/run/halo/app/plugin/resources/BundleResourceUtils.java
src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactory.java
src/main/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionRegistry.java
src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
src/test/java/run/halo/app/infra/utils/PathUtilsTest.java
src/test/java/run/halo/app/plugin/resources/ReverseProxyRouterFunctionFactoryTest.java

/area core
/milestone 2.0
插件 logo 支持配置外部 URL 或相对于 resources 的路径
Console 端展示插件 logo 时使用的字段需要使用 status.logo 而非 spec.logo
Fixes #2651
1. 插件配置 logo 为外部 url 例如 https://guqing.xyz/avatar
2. 安装此插件后不会注册 ReverseProxy 规则
3. logo 配置为相对于 resources 的路径例如：/logo.png
4. 安装此插件后可以访问到 /plugins/{your-plugin-name}/assets/logo.png
5. 开发模式启动插件后，修改了 plugin.yaml 中的 spec.logo 则也会更新 ReverseProxy 的 rule
```release-note
插件 Logo 支持配置外部 URL 或相对于 resources 的路径
```

feat: create reverse proxy for logo when plugin created

---

src/main/java/run/halo/app/theme/TemplateEngineManager.java
src/main/java/run/halo/app/theme/ThemeLinkBuilder.java
src/test/java/run/halo/app/theme/ThemeLinkBuilderTest.java

/area core
/milestone 2.0
主题预览使用的 ThemeLinkBuilder 需要根据 `halo.externalUrl` 配置来决策是否带预览参数
安装几个主题后预览看链接是否正确
see also https://github.com/halo-dev/halo/blob/69a112a060ef9c8ae33a3ced489b475b22e6a1bb/src/test/java/run/halo/app/theme/ThemeLinkBuilderTest.java#L101-L124
```release-note
None
```

refactor: ThemeLinkBuilder needs to rely on external url

---

src/main/java/run/halo/app/infra/SystemSetting.java
src/main/java/run/halo/app/theme/finders/MenuFinder.java
src/main/java/run/halo/app/theme/finders/impl/MenuFinderImpl.java
src/main/resources/extensions/system-configurable-configmap.yaml
src/test/java/run/halo/app/theme/finders/impl/MenuFinderImplTest.java

/kind feature
/milestone 2.0
/area core
新增主菜单选择配置项
menuFinder 方法从 getDefault 改为 getPrimary 需要主题适配
Fixes #2533
新增几组菜单选择后切换看主题端是否生效
```release-note
Action Required: MenuFinder 的 getDefault 方法已更名为 getPrimary，如果在主题中调用过该方法则需要手动修改。
```

feat: add setup primary menu support

---

src/main/java/run/halo/app/theme/finders/PluginFinder.java
src/main/java/run/halo/app/theme/finders/impl/PluginFinderImpl.java
src/test/java/run/halo/app/theme/finders/impl/PluginFinderImplTest.java

/kind feature
/milestone 2.0
/area core
主题端提供判断插件是否已经启用的方法
Fixes #2677
在主题端使用 `${pluginFinder.available(your-plugin-name)}`  来查看某个插件是否已经启用，如果是则得到 true ，否则 false，如果插件没有安装也得到 false
```release-note
主题端支持获取插件启用状态
```

feat: add plugin finder for theme-side

---

src/main/java/run/halo/app/infra/utils/PathUtils.java
src/main/java/run/halo/app/plugin/YamlPluginFinder.java
src/test/java/run/halo/app/core/extension/SettingTest.java
src/test/java/run/halo/app/plugin/PluginStartedListenerTest.java
src/test/java/run/halo/app/plugin/YamlPluginFinderTest.java
src/test/java/run/halo/app/theme/ThemeContextTest.java
src/test/java/run/halo/app/theme/message/ThemeMessageResolutionUtilsTest.java
src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java

/kind cleanup
Fix failing tests on Windows.
```bash
╰─$ ./gradlew check
> Task :checkstyleTest
Checkstyle rule violations were found. See the report at: file:///C:/Users/johnn/workspaces/halo-dev/halo/build/reports/checkstyle/test.html
Checkstyle files with violations: 8
Checkstyle violations by severity: [warning:20]
> Task :test
2022-11-11T14:19:41.265+08:00 DEBUG 5948 --- [ionShutdownHook] r.halo.app.metrics.CounterMeterHandler   : Persist counter meters to database before destroy...
2022-11-11T14:19:41.277+08:00 DEBUG 5948 --- [ionShutdownHook] r.halo.app.metrics.CounterMeterHandler   : Persist counter meters to database before destroy...
2022-11-11T14:19:41.281+08:00 DEBUG 5948 --- [ionShutdownHook] r.halo.app.metrics.CounterMeterHandler   : Persist counter meters to database before …
```

Fix test issues on Windows

---

src/main/resources/extensions/role-template-post.yaml

/kind bug
/area core
/milestone 2.0
This PR refines the role template of posts to allow post managers to unpublish and recycle a specific post.
Before that, post managers will be forbidden to unpublishing and recycling posts. You can see the screenshot below:
After that, we can unpublish and recycle posts successfully. You can see the screenshot below:
Steps to test manually:
1. Create a `Role` with `Posts Management` permission
2. Create an `User` with the role bound
3. Login with the `User`
4. Create a `Post` and publish it
5. Unpublish the post and Recycle it
```release-note
修复无法“取消发布”和“删除”文章的错误
```

Fix the problem of unpublishing and recycling posts by member of post manager

---

src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/extension/Comparators.java
src/test/java/run/halo/app/extension/ComparatorsTest.java

/kind feature
/area core
/milestone 2.0
Provide sort query param for sorting attachment. By default, we use creationTimestamp(desc) to sort the attachments.
Below is an example to sort with creationTimestamp(desc) and size(asc):
```bash
curl -X 'GET' \
'http://localhost:8090/apis/api.console.halo.run/v1alpha1/attachments?sort=creationTimestamp%2Cdesc&sort=size%2Casc' \
-H 'accept: */*'
```
Fixes https://github.com/halo-dev/halo/issues/2627
```release-note
附件列表支持排序
```

Provide sort query param for sorting attachment

---

src/main/resources/application.yaml

/kind bug
/area core
Before this, `CounterMeterHandler#stop` will encounter an error when Halo is graceful shutdown due to database closed before.
```java
2022-11-16T15:52:17.904+08:00 DEBUG 21324 --- [ionShutdownHook] r.halo.app.metrics.CounterMeterHandler   : Persist counter meters to database before destroy...
2022-11-16T15:52:17.910+08:00 ERROR 21324 --- [ionShutdownHook] r.halo.app.metrics.CounterMeterHandler   : Persist counter meters to database failed.
org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection
at org.springframework.r2dbc.connection.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:88) ~[spring-r2dbc-6.0.0-RC4.jar:6.0.0-RC4]
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
```
Steps …

Prevent H2 from closing on exit to allow destruction

---

src/main/java/run/halo/app/plugin/SharedApplicationContextHolder.java
src/main/java/run/halo/app/theme/SiteSettingVariablesAcquirer.java
src/main/java/run/halo/app/theme/finders/vo/SiteSettingVo.java
src/test/java/run/halo/app/theme/SiteSettingVariablesAcquirerTest.java

/area core
/milestone 2.0
主题和插件支持获取 `halo.external-url` 配置信息
Fixes #2711
1. 在主题中使用`<p th:text="${site.url}"></p>` 可以正确显示
2. 在插件中可以依赖注入 ExternalUrlSupplier
```release-note
主题和插件支持获取外部访问地址配置
```

feat: support obtaining the configuration of halo.external-url for themes and plugins

---

src/main/java/run/halo/app/theme/ReactivePropertyAccessor.java
src/main/java/run/halo/app/theme/ReactiveSpelVariableExpressionEvaluator.java
src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java

/area core
/milestone 2.0
支持在 JavaScript 中对 Flux 或 Mono 的泛型类型属性链式调用
测试参考：
https://github.com/halo-dev/halo/blob/7e9bdec4923348b98df17b7e1071154ecec8ead1/src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java#L131-L147
期望
https://github.com/halo-dev/halo/blob/7e9bdec4923348b98df17b7e1071154ecec8ead1/src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java#L64-L79
```release-note
支持在 JavaScript 中对 Flux 或 Mono 的泛型类型属性链式调用
```

refactor: support chaining calls for flux and mono in javascript inline tag

---

src/main/java/run/halo/app/config/ExtensionConfiguration.java
src/main/java/run/halo/app/extension/controller/ControllerBuilder.java
src/main/java/run/halo/app/extension/controller/DefaultController.java
src/main/java/run/halo/app/extension/gc/GarbageCollectorConfiguration.java
src/main/resources/application-dev.yaml
src/test/java/run/halo/app/extension/controller/DefaultControllerTest.java

/kind feature
/area core
/milestone 2.0
This PR enables adding more workers for controller to speed up reconciliations. Default woker count is 1 for one controller.
**What's next?**
Fixes https://github.com/halo-dev/halo/issues/2708
You can see there are more threads for post controller in the following screenshot:
```release-note
None
```

Enable adding more workers for controller

---

src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java

/kind bug
/kind regression
/area core
/milestone 2.0
When we try to upgrade a theme, error will appear like below:
```java
2022-11-18T15:45:35.130+08:00 ERROR 18136 --- [oundedElastic-1] a.w.r.e.AbstractErrorWebExceptionHandler : [26de12d5-51]  500 Server Error for HTTP POST "/apis/api.console.halo.run/v1alpha1/themes/theme-earth/upgrade"
java.io.IOException: Pipe closed
at java.base/java.io.PipedInputStream.read(PipedInputStream.java:307) ~[na:na]
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
reactor.core.publisher.Mono.flatMap(Mono.java:3080)
run.halo.app.core.extension.theme.ThemeServiceImpl.upgrade(ThemeServiceImpl.java:72)
Error has been observed at the following site(s): …
```

Fix the problem of upgrading theme due to pipe closed

---

build.gradle

/area core
/milestone 2.0.0
springdoc-openapi 2.0.0-RC2 fully supports Spring Boot 3.0.0-RC2 currently, please see https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.0-RC2 for more.
```release-note
升级依赖 SpringDoc OpenAPI 至 2.0.0-RC2
```

Bump up springdoc-openapi

---

src/main/java/run/halo/app/console/ConsoleProxyFilter.java
src/main/java/run/halo/app/console/WebSocketServerWebExchangeMatcher.java
src/test/java/run/halo/app/console/WebSocketServerWebExchangeMatcherTest.java

/kind feature
/area core
Ignore websocket protocol while proxying console. If we don't do this, console dev environment will crash with following error:
```bash
VITE v3.2.4  ready in 1672 ms
➜  Local:   http://localhost:3000/console/                                                                           16:12:21
➜  Network: http://172.23.176.1:3000/console/                                                                        16:12:21
➜  Network: http://172.18.96.1:3000/console/                                                                         16:12:21
➜  Network: http://192.168.31.106:3000/console/                                                                      16:12:21
[vite-plugin-static-copy] Collected 8 items. …
```

Ignore websocket protocol while proxying console

---

src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java

/area core
/milestone 2.0.0-rc.1
插件以开发模式启动时加载插件需判断是否已经加载过
Fixes #2758
1. 配置 `halo.plugin.fixed-plugin-path`
2. 以开发模式启动后重启几次不会出现  #2758 中描述的异常
```release-note
修复插件以开发模式启动时会出现插件已经加载过的异常
```

refactor: check whether plugin has been loaded when startup

---

src/main/java/run/halo/app/core/extension/attachment/Attachment.java
src/main/java/run/halo/app/core/extension/attachment/Policy.java
src/main/java/run/halo/app/core/extension/attachment/PolicyTemplate.java
src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
src/main/resources/extensions/attachment-local-policy.yaml
src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java

/area core
/milestone 2.0.x
This PR replace refs in Attachment extension with simple name.
> **Warning** Please @halo-dev/sig-halo-console be aware of that this PR contains break changes, so that we can not use Attachment feature in the console directly. The console has to adapt the break changes.
```release-note
None
```

Simplify references in Attachment

---

src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java
src/main/java/run/halo/app/theme/dialect/GlobalSeoProcessor.java
src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java

/area core
/milestone 2.0.0-rc.2
适配 SEO 系统设置，此功能之前遗漏
Fixes #2797
1. seo 设置禁用搜索引擎，会在所有页面的 head 添加 `<meta name="robots" content="noindex" />`
2. seo 设置填写`关键词`和`描述`会在所有页面的 head 标签填充 `<meta name="xxx> content="xxx" />` 
```release-note
支持 SEO 全局系统设置
```

feat: theme templates support global seo settings

---

src/main/java/run/halo/app/config/WebFluxConfig.java
src/main/java/run/halo/app/core/extension/attachment/Constant.java
src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
src/main/java/run/halo/app/infra/properties/AttachmentProperties.java
src/main/java/run/halo/app/infra/properties/HaloProperties.java
src/main/resources/application.yaml
src/main/resources/extensions/attachment-local-policy.yaml

/area core
/milestone 2.0.0
This PR provides an ability to migrate attachments from other places, like Halo 1.x or Wordpress.
We could simply configure resource mappings to support attachments migration:
```yaml
halo:
attachment:
resource-mappings:
- pathPattern: /upload/**
locations:
- upload
- migrate-from-1.x
- pathPattern: /wp-content/uploads/**
locations:
- migrate-from-wp
```
Meanwhile, I refactored LocalAttachmentUploadHandler for managing attachments from migration in the future.
Fixes https://github.com/halo-dev/halo/issues/2585
**Steps to test:**
1. Try to configure the resource mappings
2. Put some static resources into the corresponding location
3. Access it from Browser
At last, please make sure the functionalities of attachment are ok as before. …

Allow migrating attachments from other places

---

src/main/resources/schema-mysql.sql

/area core
/milestone 2.0.1
See https://github.com/halo-dev/halo/issues/2832 and https://github.com/halo-dev/halo/issues/2832#issuecomment-1336616901 for more.
For a workaround, please refer to:
- https://github.com/halo-dev/halo/issues/2832#issuecomment-1336610679
But, there are still limitations here:
- For MySQL: ~4GB
- For PosgreSQL: ~1GB
Fixes https://github.com/halo-dev/halo/issues/2832
```release-note
修复因文章过长导致无法保存数据的问题
```

Fix the problem that MySQL complains "Data too long for column 'data' at row 1"

---

README.md

鉴于目前已不在 Release 中提供 Jar 包下载，Releases 下载数量的展示已经没有太大意思，所以去掉了 README 中的 Releases 下载数量徽章。
```release-note
None
```

docs: remove the downloads badge in README

---

src/main/java/run/halo/app/core/extension/Role.java
src/main/java/run/halo/app/security/SuperAdminInitializer.java
src/main/resources/extensions/system-default-role.yaml

/kind bug
/area core
Add forgotten label `rbac.authorization.halo.run/system-reserved` for system-reserved roles. See the screenshot below:
Fixes https://github.com/halo-dev/halo/issues/2844
For @halo-dev/sig-halo-console : We have to determine whether the role is system-reserved by checking if label `rbac.authorization.halo.run/system-reserved` is equal to `true`.
```release-note
修复每个角色都显示系统保留标签的问题
```

Add forgotten label for system-reserved roles

---

.github/workflows/halo.yaml

/area core
Set docker image name to `halo` instead of `halo-dev` when releasing.
Please refer to a real test at <https://github.com/JohnNiang/halo/actions/runs/3636780100/jobs/6137100454>
```release-note
None
```

Set docker image name properly when releasing

---

README.md

更新 Readme 中快速开始的命令，提供初始管理员账号和外部访问链接的环境变量设置。
```release-note
None
```

feat: improve the quick start section of the readme

---

src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/PluginDevelopmentInitializer.java

/area core
在插件开发模式下加载插件失败时不抛出异常改为静默提示
A part of #2901
1. 配置 `halo.plugin.fixed-plugin-path` 为一些不合法的插件项目路径不影响 Halo 正常启动，且有错误提示
2. 配置合法路径，插件能正确启动
```release-note
插件开发模式下无法被加载时改为静默提示不抛出异常
```

Silent prompt when plugins fail to load in development mode

---

src/main/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategy.java
src/test/java/run/halo/app/theme/router/strategy/SinglePageRouteStrategyTest.java

/kind bug
/area core
修复自定义页面没有统计访问量的问题
Fixes #2912
创建自定义页面并到主题端访问，可以看到访问量增加
```release-note
修复自定义页面没有统计访问量的问题
```

fix: single page does not count visits

---

src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/ReverseProxyReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/ReverseProxyReconcilerTest.java

/kind bug
/area core
修复插件 logo 为相对路径时先启用再停后就无法加载 logo  的问题
原因是 reverse proxy reconciler 资源被删除要取消注册路由时没有确切指定名称，logo 这样的 ReverseProxy 是插件安装时初始化的这条初始化的规则要跟随插件的生命周期，只有插件卸载时才会被删除，而在此之前插件被停止时就被误取消注册了
see #2937 for more detail
Fixes #2937
```release-note
修复插件 logo 为相对路径时先启用再停后就无法加载 logo  的问题
```

fix: plugin logo cannot be loaded when it is not enabled

---

Dockerfile

/area core
Force to add environment variables `HALO_WORK_DIR` and `SPRING_CONFIG_LOCATION` into Dockerfile. After that, we can configure `application.yaml` in working directory as we want.
Please note that we can not configure Halo working directory in `/root/.halo2/application.yaml` directly. Use environment variable `HALO_WORK_DIR` instead.
Fixes https://github.com/halo-dev/halo/issues/2812
Steps to test:
1. Prepare custom configuration
```bash
mkdir -p halo2
cat <<EOF > halo2/application.yaml
server:
port: 12345
EOF
```
2. Start up Halo using Docker
```bash
docker run -it --rm -p12345:12345 -v `pwd`/halo2:/root/.halo2  johnniang/halo:configure-halo-in-work-dir
```
3. Request http://localhost:12345
```bash
curl -v localhost:12345
```
```release-note …
```

Support configuring Halo in working directory

---

Dockerfile

/area core
Now, we can pass command-line arguments while using Docker. Please refer to <https://github.com/halo-dev/halo/issues/2902>.
Fixes https://github.com/halo-dev/halo/issues/2902
Steps to test:
1. Run Halo with command-line arguments:
```bash
docker run --rm -it -p6666:6666 johnniang/halo:support-command-line-args --server.port=6666
```
1. Request <http://localhost:6666>
```bash
curl -v http://localhost:6666
```
```release-note
支持命令行参数启动 Halo
```

Support command-line arguments running with Docker

---

src/main/java/run/halo/app/plugin/BasePlugin.java
src/main/java/run/halo/app/plugin/HaloPluginManager.java
src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java

/area core
HaloPluginManager 移除 getRootApplicationContext 方法
Fixes #2943
```release-note
HaloPluginManager 移除 getRootApplicationContext 方法
```

refactor: remove get root application context method from halo plugin manager

---

src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java

/kind bug
Fixes #2951 
```release-note
修复开启评论审核的情况下无法显示评论回复的问题
```

Fixed the problem that comment reply cannot be displayed in the front end

---

src/main/java/run/halo/app/theme/finders/impl/PostFinderImpl.java

优化归档页面数据排序，按月份降序
Fixes #2958 
```release-note
归档数据按月降序
```

feat: archives in descending order by month

---

.github/workflows/halo.yaml

/kind cleanup
/area core
We should build console project on branch `release-2.0` instead of `main` when building Halo on branch release-2.0. 
So that we can test latest Halo 2.0.x using `docker pull ghcr.io/halo-dev/halo-dev:release-2.0`
```release-note
None
```

Update console ref to release-2.0 for current branch

---

OWNERS
src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
src/main/java/run/halo/app/theme/TemplateEngineManager.java
src/main/java/run/halo/app/theme/ThemeResolver.java
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java

通过在模板引擎管理器里添加clearCache方法，在升级主题后进行缓存刷新，让新模板内容生效。
Fixes #2953 
```release-note
NONE
```

fix: not clearing the template engine cache after upgrading the theme

---

src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
src/main/java/run/halo/app/core/extension/theme/SettingUtils.java
src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
src/main/java/run/halo/app/core/extension/theme/ThemeService.java
src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
src/main/resources/extensions/role-template-plugin.yaml
src/main/resources/extensions/role-template-theme.yaml
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
src/test/java/run/halo/app/core/extension/theme/SettingUtilsTest.java
src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java

/kind feature
/area core
为主题和插件提供重置设置项 API
此 PR 会重新读取配置对应的 Setting 资源，从其中读取默认值后更新到现有的 ConfigMap 中替换其 data
see #2789 for more details
Fixes #2789
1. 在主题设置或插件设置配置一些设置项后保存
2. 执行重置配置
3. 配置恢复为了 Setting 中指定的默认值
```release-note
为主题和插件提供重置设置项 API
```

feat: add reset config API for theme and plugin

---

README.md
src/main/java/run/halo/app/infra/DefaultThemeInitializer.java

/kind bug
To fix that default earth theme file not found in system initialization.
Fixes #2910 
```release-note
NONE
```

fix: default theme cannot be initialized in the jar distribution

---

src/main/java/run/halo/app/theme/finders/impl/SinglePageFinderImpl.java
src/test/java/run/halo/app/theme/finders/impl/SinglePageFinderImplTest.java

/kind bug
/area core
修复自定义页面 Finder 中 getByName 方法没有返回访问量的问题
此问题为重构 #2918 时引入。
Fixes #2992
```release-note
None
```

fix: page stats does not subscribe in finder

---

src/main/java/run/halo/app/infra/exception/handlers/GlobalErrorWebExceptionHandler.java

/kind cleanup
/area core
Because these code has already defined in [here](https://github.com/spring-projects/spring-boot/blob/28f9f20d39325985ea79868bbf85a51fffa76c8f/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/error/AbstractErrorWebExceptionHandler.java#L310-L339). Printing error twice in development mode is completely unnecessary.
```release-note
None
```

Clean up unnecessary code in GlobalErrorWebExceptionHandler

---

src/main/java/run/halo/app/extension/controller/DefaultController.java
src/main/java/run/halo/app/theme/finders/CategoryFinder.java
src/main/java/run/halo/app/theme/finders/impl/CategoryFinderImpl.java
src/test/java/run/halo/app/theme/finders/impl/CategoryFinderImplTest.java

What type of PR is this?
/kind feature
What this PR does / why we need it:
添加一个方法可以根据分类树的任意一层级的名称查询子树
Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/issues/2960
Special notes for your reviewer:
None
Does this PR introduce a user-facing change?
```release-note
CategoryFinder 添加根据分类查询子分类树结构的方法
```

Support querying sub-categories of any level

---

src/main/resources/extensions/role-template-attachment.yaml

/kind bug
/area core
- Add missing resources `"policies", "policytemplates", "groups"` in policy rules in attachment role templates.
- Correct `nonResourceURLs` and `verbs`
See https://github.com/halo-dev/halo/issues/3007 for more.
Fixes https://github.com/halo-dev/halo/issues/3007
Steps to test:
1. Start Halo and login with `admin`
2. Create a Role with `Attachment Manage` permission only
3. Create an user and assign the role to the user
4. Set password for the user
5. Log out current user and log in as the user created just now
6. Try to do various operations in attachment tab
- Create and list policy
- Create and list group
- Upload and list attachments
```release-note
修复附件权限定义的错误
```

Fix invalid attachment role templates

---

src/main/java/run/halo/app/core/extension/AnnotationSetting.java
src/main/java/run/halo/app/core/extension/Theme.java
src/main/java/run/halo/app/core/extension/reconciler/AnnotationSettingReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/ThemeReconciler.java
src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
src/main/java/run/halo/app/core/extension/theme/ThemeUtils.java
src/main/java/run/halo/app/infra/SchemeInitializer.java
src/main/resources/extensions/role-template-authenticated.yaml
src/test/java/run/halo/app/core/extension/reconciler/ThemeReconcilerTest.java
src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java

/kind feature
/area core
新增 AnnotationSetting 自定义模型以扩展自定义元数据设置表单
主题安装/更新/重载时都会重新加载与 theme.yaml 同层级的其他 yaml，但只会保存 kind 为 Setting 和 AnnotationSetting的，主题卸载时会删除这些 yaml 资源
Fixes #3005
- 修改影响到了主题安装、更新、重载和删除，需要检查这些功能是否正确加载了 Setting 和 AnnotationSetting
- 插件启动时初始化的 AnnotationSetting 在插件停止时会被删除
- 主题添加了 annotation setting 资源，使用非超级管理员也可以获取
```release-note
新增 AnnotationSetting 以扩展自定义元数据设置表单
```

feat: add annotation setting extension

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/resources/extensions/role-template-authenticated.yaml
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java

/kind feature
/area core
Provide an endpoint to update current user profile instead of whole user data.
```bash
curl -X 'PUT' \
'http://localhost:8090/apis/api.console.halo.run/v1alpha1/users/-' \
-H 'accept: */*' \
-H 'Content-Type: */*' \
-d '{
"spec": {
"displayName": "JohnNiang",
"email": "johnniang@halo.run",
"password": "xxx",
"registeredAt": "2022-12-19T03:46:54.809770900Z",
"twoFactorAuthEnabled": false,
"disabled": false
},
"status": {
"permalink": "http://localhost:8090/authors/admin"
},
"apiVersion": "v1alpha1",
"kind": "User",
"metadata": {
"finalizers": [
"user-protection"
],
"name": "admin",
"annotations": {
"rbac.authorization.halo.run/role-names": "[\"super-role\"]"
},
"version": 3,
"creationTimestamp": "2022-12-19T03:46:54.911951800Z"
}
}'
```
```json
{ …
```

Provide an endpoint to update user profile

---

src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java

/area core
迁移后文章过多，当文章的 Reconciler 还没有执行完时访问 Console 端文章列表会因为 post.status  为 Null 出现 NPE 问题
使用文章的 status 时需要对其进行判空
/cherry-pick release-2.0
Fixes #3066
```release-note
None
```

Avoid NPE problems when querying the list of posts in the console

---

src/main/java/run/halo/app/core/extension/MenuItem.java

/kind feature
为 MenuItem 模型添加 a 标签的 target 属性设置。
Fixes https://github.com/halo-dev/halo/issues/3063
测试方式请看：https://github.com/halo-dev/console/pull/805
```release-note
菜单项支持设置打开方式
```

feat: add target attribute for menu item

---

src/main/java/run/halo/app/theme/dialect/HaloExpressionObjectFactory.java
src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
src/main/java/run/halo/app/theme/dialect/expression/Annotations.java
src/main/java/run/halo/app/theme/finders/vo/CategoryTreeVo.java
src/main/java/run/halo/app/theme/finders/vo/CategoryVo.java
src/main/java/run/halo/app/theme/finders/vo/CommentVo.java
src/main/java/run/halo/app/theme/finders/vo/ExtensionVoOperator.java
src/main/java/run/halo/app/theme/finders/vo/ListedPostVo.java
src/main/java/run/halo/app/theme/finders/vo/ListedSinglePageVo.java
src/main/java/run/halo/app/theme/finders/vo/MenuItemVo.java
src/main/java/run/halo/app/theme/finders/vo/MenuVo.java
src/main/java/run/halo/app/theme/finders/vo/ReplyVo.java
src/main/java/run/halo/app/theme/finders/vo/TagVo.java
src/main/java/run/halo/app/theme/finders/vo/ThemeVo.java
src/main/java/run/halo/app/theme/finders/vo/UserVo.java
src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java

/kind feature
/area core
新增操作 annotations 的表达式对象
在 thymeleaf 模板中使用示例：
```html
<p th:text="${#annotations.get(user, 'background')}"></p>
<p th:text="${#annotations.getOrDefault(user, 'background', 'default-value')}"></p>
<p th:text="${#annotations.contains(user, 'background')}"></p>
```
Fixes #3073
```release-note
新增 Annotations 表达式对象用于在 thymeleaf 中操作自定义模型的 annotations
```

feat: add annotations expression object for thymeleaf

---

src/main/java/run/halo/app/core/extension/content/Post.java
src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/SinglePageReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java
src/test/java/run/halo/app/core/extension/reconciler/SinglePageReconcilerTest.java

文章和自定义页面支持展示最后修改时间
- 文章发布后会同步 post.spec.releasedSnapshot 记录的最后修改时间到 post.status.lastModifyTime，自定义页面亦如是。
- 主题端可以通过 `${item.status.lastModifyTime}` 获取（item表示文章或自定义页面 Vo）。
Fixes #3090 
```release-note
文章和自定义页面支持展示最后修改时间
```

feat: add the lastModifyTime attribute for post and single page

---

src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
src/main/java/run/halo/app/plugin/PluginProperties.java
src/main/resources/application-dev.yaml

/area core
修复引入外部依赖的插件以开发模式启动时会出现 NoClassDefFoundError 的问题
see #3107 for more detail.
Fixes #3107
以插件 development 模式启动以下两个插件观察是否正常启动：
- https://github.com/halo-sigs/plugin-s3
- https://github.com/halo-sigs/plugin-alioss
期望没有 `Caused by: java. lang. NoClassDefFoundEenon` 错误，且插件正确启动。
```release-note
修复引入外部依赖的插件以开发模式启动时会出现 NoClassDefFoundError 的问题
```

refactor: support extending jar directories for plugin class loader

---

src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
src/test/java/run/halo/app/theme/finders/impl/CommentFinderImplTest.java

/area core
主题端显示当前用户创建的未审核通过的评论/回复
在开启了评论审核功能的前提下：
- 如果非匿名用户在主题端创建的评论或回复必须审核通过才能显示。
- 如果用户登录后评论或回复会被立即展示在列表，但仅限创建者可见，审核通过后对所有人可见。
Fixes #2731
```release-note
主题端支持显示当前用户创建的未审核的评论
```

feat: display unapproved comments created by the current user

---

src/main/java/run/halo/app/theme/router/RadixRouterTree.java
src/test/java/run/halo/app/theme/router/RadixRouterTreeTest.java

/kind bug
/area core
Remove URI decode operation while inserting key into RadixRouterTree to avoid repeat decode.
Fixes #3178 
1. Set slug name to `1%1` when creating a post
2. Publish it
3. Browse the post
```release-note
修复因别名包含百分号导致无法正常访问的问题
```

Fix the problem of slug name with percent sign when publishing post

---

build.gradle

/area core
See https://github.com/jasync-sql/jasync-sql/releases/tag/2.1.23 for more.
```release-note
升级依赖 jasync-sql 至 2.1.13
```

Upgrade jasync-sql to 2.1.23

---

src/main/java/run/halo/app/core/extension/Theme.java

/kind bug
/area core
Make requires field of Theme not required.
Fixes https://github.com/halo-dev/halo/issues/3177
1. Clear Halo working directory
2. Start Halo freshly
```release-note
None
```

Fix the problem of not initializing default theme correctly

---

src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/infra/exception/PluginInstallationException.java
src/main/resources/config/i18n/messages.properties
src/main/resources/config/i18n/messages_zh.properties

/kind bug
/area core
修复重复安装插件时 JAR 文件被删除的问题
需要注意的场景：
prod 模式下，假如安装一个 sitemap 插件，版本为 1.0.0 ，而此时 plugins 目录已经存在同名文件 sitemap-1.0.0.jar 文件但 sitemap 的 plugin.yaml 没有被持久化过，则能正常安装，旧的 JAR 文件被覆盖。
see #3159 for more details
Fixes #3159
```release-note
修复重复安装插件时 JAR 文件被删除的问题
```

fix: plugin disappeared after plugin with same name reinstalled

---

src/main/java/run/halo/app/extension/store/ReactiveExtensionStoreClientImpl.java
src/main/java/run/halo/app/infra/exception/DuplicateNameException.java
src/main/resources/config/i18n/messages.properties
src/main/resources/config/i18n/messages_zh.properties

/area core
I create another exception `DuplicateNameException` to map `org.springframework.dao.DuplicateKeyException` when creating extensions.
See https://github.com/halo-dev/halo/issues/3180 for more.
Fixes https://github.com/halo-dev/halo/issues/3180
1. Try to create an user which name has already exist
2. See the error
```release-note
优化名称重复的错误提示
```

Refine exception message of duplicate key

---

src/main/java/run/halo/app/infra/exception/handlers/HaloErrorWebExceptionHandler.java
src/main/java/run/halo/app/theme/HaloViewResolver.java
src/main/java/run/halo/app/theme/ThemeContextBasedVariablesAcquirer.java
src/main/java/run/halo/app/theme/ThemeResolver.java
src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java

/area core
Save ThemeContext into ServerWebExchange to reduce the number of queries to resolve theme from 2(or 3) to 1.
Fixes https://github.com/halo-dev/halo/issues/3162
```release-note
优化查询主题的查询次数
```

Reduce the number of queries to resolve theme

---

src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java

/area core
当开发模式启动时上传 JAR 运行插件会出现插件不存在的异常，但由于 PluginReconciler 中检查状态不一致后 return 在 optional 语句中只是让当前 optional 后面的代码停止执行，还会继续执行 optional 外面的代码导致 status 的异常信息不一致，进而 object equals 始终为 false 而无法让 reconciler 终止运行导致循环。
此 PR 调整了一下代码位置，进入 reconciler 时先进行检查，如果不满足则不执行后面的代码同时将信息写入 plugin.status 让用户知晓。
此问题是修改了 Reconciler 判断逻辑后出现的 https://github.com/halo-dev/halo/pull/3210 ，因此不影响之前的代码只针对当前 2.3.x
1. 模拟一个插件找不到的错误场景例如以生产模式启动插件但配置 fixed-plugin 指定为插件项目目录
2. 启动 Halo 看 Reconciler 是否会一直在控制台输出日志
3. 卸载它能成功
```release-note
None
```

fix: plugin status check to prevent inconsistent status

---

src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java

/area core
/cherry-pick release-2.2
修复插件安装时有几率出现设置没有默认值导致无法保存的问题
see https://github.com/halo-dev/halo/issues/3224#issuecomment-1418825809 for more details
Fixes #3224
1. 安装 https://github.com/halo-sigs/plugin-feed 插件并立即启用（或以开发模式）
2. 到此插件设置**始终**能查询到默认值并且能保存
```release-note
修复插件安装时有几率出现设置没有默认值导致无法保存的问题
```

fix: default value cannot be read when the setting is not created because of asynchrony

---

src/main/resources/extensions/system-default-role.yaml

为系统初始化的角色添加显示名称
Fixes https://github.com/halo-dev/halo/issues/3257
see 
```release-note
为系统初始化的角色添加显示名称
```

perf: refine display name of system default role

---

src/main/java/run/halo/app/content/Contributor.java
src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/resources/extensions/system-default-role.yaml

/kind bug
文章发布用户被删除后，设置这篇文章的发布人为Ghost
Fixes #3265
```release-note
NONE
```

perf: associate ghost user with posts on user deletion.

---

src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
src/main/java/run/halo/app/infra/utils/FileNameUtils.java
src/test/java/run/halo/app/infra/utils/FileNameUtilsTest.java

/area core
Before this PR, halo will throw an FileAlreadyExists exception if users upload file which already exists.
But now, we will rename the attachment automatically on filename conflict. e.g.:
```bash
halo.run -> halo-xyz.run
.run -> xyz.run
halo -> halo-xyz
```
Fixes https://github.com/halo-dev/halo/issues/3218
```release-note
附件已存在时自动重命名
```

Auto rename attachment if it exists

---

src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java

/area core
状态更新时检查是否与之前状态相同，目前先这样解决后续等 status 的 update 出来以后再重构一下 plugin 的 status 结构。
测试：
测试插件在开发模式和生产模式下填写 settingName 后有/无对应 settingName 资源的插件启动情况，看 PluginReconciler 出错时是否很快
步骤：
1. 开发模式下，插件的 plugin.yaml 配置了 settingName 但没有创建名称为 settingName 对应的 Setting 资源看插件启动时控制台是否出现很快的错误日志，期望出现错误的时间间隔会逐渐变长。
2. 与步骤一相同，但 settingName 对应有 Setting 模型的 yaml，期望插件正常启动且能保存配置
3. 生产模式启动插件重复步骤 1 和 2
```release-note
None
```

refactor: status update when setting not found

---

src/main/java/run/halo/app/core/extension/reconciler/TagReconciler.java
src/main/java/run/halo/app/core/extension/reconciler/TagRouteReconciler.java
src/test/java/run/halo/app/core/extension/reconciler/TagReconcilerTest.java

/kind bug
/area core
1. 去掉原 TagReconciler 的 requeue 逻辑，来临时解决大量 tag 时 reconciler 空转导致 cpu 下不来的问题，参考： https://github.com/halo-dev/halo/issues/3311
2. 增加 TagRouteReconciler 在启动时注册路由
Fixes #3321
```release-note
修复 #3316 引入的 tags 标签的路由没有注册的问题
```

fix: route for the tag is not registered when halo starts

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java

/kind bug
为后端用户管理提供更多筛选接口，包括关键词、角色、创建时间排序
Fixes #3290
```release-note
NONE
```

Add custom endpoint for listing user conditionally

---

src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
src/main/java/run/halo/app/infra/exception/PluginAlreadyExistsException.java
src/main/resources/config/i18n/messages.properties
src/main/resources/config/i18n/messages_zh.properties

/area core
This PR refines problem detail of PluginAlreadyExistsException. Please note the new type `https://halo.run/probs/plugin-alreay-exists` and additional property `pluginName` of problem detail.
Meanwhile 
- Before
```json
{
"type": "about:blank",
"title": "Plugin Already Exists Error",
"status": 400,
"detail": "Plugin PluginCommentWidget already exists.",
"instance": "/apis/api.console.halo.run/v1alpha1/plugins/install",
"requestId": "880fe8cd-5",
"timestamp": "2023-02-20T10:17:21.541104Z"
}
```
- After
```json
{
"type": "https://halo.run/probs/plugin-alreay-exists",
"title": "Plugin Already Exists Error",
"status": 400,
"detail": "Plugin PluginCommentWidget already exists.",
"instance": "/apis/api.console.halo.run/v1alpha1/plugins/install",
"pluginName": …
```

Refine problem detail when plugin is already installed

---

src/main/java/run/halo/app/content/Contributor.java
src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/resources/extensions/user.yaml

/kind bug
系统默认初始化一个 ghost 用户，用于表示用户已删除。
Fixes #3317
```release-note
NONE
```

fix: initializes a ghost user by default to replace that the users that has been deleted

---

.github/workflows/halo.yaml

/kind cleanup
This PR aims to resolve GitHub workflow warnings which are deprecated by GitHub Action. See https://github.com/halo-dev/halo/issues/3200 for more.
Please note that workflow will always fail before https://github.com/halo-sigs/actions/pull/15 being merged.
Fixes https://github.com/halo-dev/halo/issues/3200
```release-note
None
```

Bump up checkout and setup-java actions

---

src/main/java/run/halo/app/core/extension/Plugin.java
src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
src/main/java/run/halo/app/infra/Condition.java
src/main/java/run/halo/app/infra/ConditionList.java
src/main/java/run/halo/app/plugin/PluginBeforeStopSyncListener.java
src/main/java/run/halo/app/plugin/PluginConst.java
src/main/java/run/halo/app/plugin/PluginExtensionLoaderUtils.java
src/main/java/run/halo/app/plugin/PluginStartedListener.java
src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java
src/test/java/run/halo/app/plugin/PluginStartedListenerTest.java

/kind feature
/area core
/area plugin
顺便重构了一下插件 Reconciler ，否则经常容易出 bug，刚好一起测试一下免得反复整体测试这一块。
1. 插件 status 里的 message 和 reason 之前是直接放在 status 里的，现在改为一个 ConditionList， 最新的始终在 ConditionList 的第一个，这可以避免插件启动成功时还能在 message 上看到错误信息会很奇怪
2. 插件的 Setting 只会在卸载时删除，停止时不进行删除
3. 插件启动和停止状态的调和能从 CREATED、DISABLED、RESOLVED、STARTED、STOPPED、FAILED 这些状态之间进行循环过渡，如插件当前状态为 CREATED 期望达到 STARTED 则可能会经历 CREATED -> RESOLVED -> STARTED( -> FAILED) 这些过渡, 逻辑更清晰
Console 需要适配：
1. 需要去掉插件启动时才加载 Setting 的判断，让其在插件停用时也能加载
2. 需要修改发生错误时的字段取值，显示 conditons[0] 
Fixes #3352
1. 测试在开发模式和生产模式下插件启用/设置/配置是否正常
2. 测试开发模式下插件启动失败后修复问题重启 halo 后能否正常启用
3. 测试插件卸载后 setting 是否被正确删除
4. 测试插件 logo 相对路径和 url 是否都能正常显示
5. 测试评论插件启动成功后主题端是否能显示评论列表（验证扩展点加载是否正常）
6. 测试插件配置了 settingName 但没有对应的 Setting 时的情况看 Reconciler 重试时间是否增长 …

feat: plugin supports configuration when not started

---

src/main/java/run/halo/app/extension/JSONExtensionConverter.java
src/main/java/run/halo/app/extension/JsonExtension.java
src/main/java/run/halo/app/extension/ReactiveExtensionClientImpl.java
src/test/java/run/halo/app/extension/JsonExtensionTest.java
src/test/java/run/halo/app/extension/ReactiveExtensionClientTest.java

/area core
This PR mainly creates two things:
1. Create JsonExtension to represent any extension and make extension modification more convenient
2. Discard watch when we detect that the extension status is changed only. It's useful to prevent infinite loop of reconciler.
Fixes https://github.com/halo-dev/halo/issues/3273
Try to install test plugin from [plugin-comment-widget.zip](https://github.com/halo-dev/halo/files/10799875/plugin-comment-widget.zip) before checking out this PR. You will get a infinite reconciliation loop.
Then, stop the process and checkout this PR and see the result.
```release-note
None
```

Discard watch when extension status is changed only

---

src/main/java/run/halo/app/content/comment/CommentServiceImpl.java
src/main/java/run/halo/app/content/comment/OwnerInfo.java
src/main/java/run/halo/app/content/comment/ReplyServiceImpl.java
src/main/java/run/halo/app/content/impl/PostServiceImpl.java
src/main/java/run/halo/app/content/impl/SinglePageServiceImpl.java
src/main/java/run/halo/app/core/extension/service/UserService.java
src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java
src/main/java/run/halo/app/theme/finders/impl/ContributorFinderImpl.java
src/test/java/run/halo/app/content/comment/CommentServiceImplTest.java
src/test/java/run/halo/app/theme/finders/impl/CommentFinderImplTest.java

/area core
用户被删除时关联到的用户返回 ghost 用户信息
Fixes #3356
```release-note
用户被删除时关联到的用户返回 ghost 用户信息
```

refactor: APIs returns ghost users when user is deleted

---

src/test/java/run/halo/app/infra/exception/handlers/I18nExceptionTest.java

/area core
修复 i18n 的单元测试，在中文或其他除了英语之外的系统语言的环境下断言无法通过
可以将系统语言设置为其他来测试此 PR 不会出现上述问题即可
```release-note
None
```

fix: i18n unit test

---

src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java
src/main/java/run/halo/app/core/extension/service/RoleService.java
src/main/java/run/halo/app/core/extension/service/UserServiceImpl.java
src/main/resources/extensions/role-template-user.yaml
src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java
src/test/java/run/halo/app/core/extension/service/UserServiceImplTest.java

/kind feature
/area core
获取用户信息的 API 响应体包含关联角色信息
- 新增 API `/apis/api.console.halo.run/v1alpha1/users/{name}`
- 修改了 API 的返回值类型 `/apis/api.console.halo.run/v1alpha1/users/-`
由于 API 响应体结构的改变，需要 Console 适配
Fixes #3342
```release-note
获取用户信息的 API 响应体包含关联角色信息
```

feat: add role information for user-related custom endpoint

---

src/main/java/run/halo/app/theme/router/factories/PostRouteFactory.java
src/test/java/run/halo/app/theme/router/factories/PostRouteFactoryTest.java

/kind bug
/area core
修复文章模板渲染丢失 template_id 参数导致无法代码注入的问题
测试 [plugin-highlightjs](https://github.com/halo-sigs/plugin-highlightjs) 插件功能是否正常，期望在 html head 插入 `/plugins/PluginHighlightJS/assets/static/highlight.min.js`
Fixes #3403
```release-note
None
```

fix: template rendering missing template_id model data

---

src/main/java/run/halo/app/core/extension/endpoint/TrackerEndpoint.java
src/main/java/run/halo/app/metrics/VisitLogWriter.java
src/test/java/run/halo/app/metrics/VisitLogWriterTest.java

/kind cleanup
/area core
移除 VisitLogWriter 的使用，不再记录访问日志，后续由 httptrace 去暴露指标
```release-note
None
```

chore: disable the visit log writer

---

.github/workflows/halo.yaml

/kind cleanup
/area core
For a stable workflow.
```release-note
None
```

Update halo-next-docker-build action to release-2.2

---

build.gradle

/kind feature
/area core
Add downloadPluginPresets task to download plugin presets from GitHub release.
```bash
> Task :downloadPluginPresets
Download https://github.com/halo-sigs/plugin-comment-widget/releases/download/v1.2.0/plugin-comment-widget-1.2.0.jar
Download https://github.com/halo-sigs/plugin-sitemap/releases/download/v1.0.1/plugin-sitemap-1.0.1.jar
Download https://github.com/halo-sigs/plugin-feed/releases/download/v1.1.0-beta.1/plugin-feed-1.1.0-beta.1.jar
Download https://github.com/halo-sigs/plugin-search-widget/releases/download/v1.0.0/plugin-search-widget-1.0.0.jar
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own …
```

Add downloadPluginPresets task

---

.github/workflows/halo.yaml

/kind cleanup
/area core
Correct console ref while building on branch release-2.2. After that, we can build Halo and console on same branch(release-2.2) instead of main branch of console.
```release-note
None
```

Correct console ref while building on branch release-2.2

---

.github/workflows/halo.yaml

/kind cleanup
/area core
Correct console ref while building on branch release-2.1. After that, we can build Halo and console on same branch(release-2.1) instead of main branch of console.
```release-note
None
```

Correct console ref while building on branch release-2.1

---

console/src/modules/contents/pages/components/SinglePageSettingModal.vue
console/src/modules/contents/posts/components/PostSettingModal.vue
console/src/modules/contents/posts/components/__tests__/PostSettingModal.spec.ts

支持强制保存文章和单页面的设置，绕开后端 version 锁的机制，因为目前发现在后端 Reconcile 处理文章较慢时会影响文章的保存。
需要注意的是，这是一个不太合理的处理方式，但目前别无选择。
Fixes https://github.com/halo-dev/halo/issues/3339
测试方式：
1. 同时打开多个同文章的编辑页面的窗口。
2. 编辑任意一个窗口的文章设置。
3. 然后再去其他窗口保存，观察是否有异常。
```release-note
支持强制保存文章和页面的设置，避免因为 Version 锁的机制导致保存失败。
```

perf: add supports for force updating of post and single page settings

---

console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/posts/PostEditor.vue

/kind bug
修复在新建文章时，首次切换编辑器后没有设置内容 rawType 资源为对应编辑器类型的问题。
Fixes #3512 
测试方式：
1. 安装任意一个编辑器插件，比如：https://github.com/halo-sigs/plugin-stackedit
1. 新建文章，选择安装的编辑器。
1. 发布文章。
1. 卸载或者停止编辑器。
1. 重新编辑刚刚创建的文章，如果提示 `未找到符合 markdown 格式的编辑器，请检查是否已安装编辑器插件` 则代表正常。
```release-note
修复在新建文章时，首次切换编辑器后没有设置内容 rawType 资源为对应编辑器类型的问题。
```

fix: the rawType of Content was not updated when switching editors

---

console/src/formkit/inputs/tag-select/TagSelect.vue

/kind bug
/area console
修复 FormKit 的文章标签搜索组件无法使用搜索功能的问题。
Fixed https://github.com/halo-dev/halo/issues/3536
测试方式：
1. 在文章设置中，测试标签选择输入框的搜索功能是否正常即可。
```release-note
修复文章设置中的标签选择组件无法正常搜索的问题。
```

fix: search issue of post tag selection component

---

console/src/components/login/LoginForm.vue
console/src/formkit/formkit.config.ts
console/src/formkit/plugins/password-prevent-autocomplete.ts

/area console
默认禁用 password 输入框的浏览器自动填充，实现方式为默认给 type 为 password 的 input 添加 `autocomplete="new-passwrod"` 属性。如果需要自动填充，手动为组件添加 `autocomplete` 属性即可。
此改动主要是针对非登录表单场景的密码输入框来做优化，在这些场景下，浏览器如果自动填充用户保存的用户名密码，会带来一定的干扰。
Fixes https://github.com/halo-dev/halo/issues/3502
1. 登录 Console，并将用户名和密码保存在浏览器的密码管理器。
2. 然后进入任意使用了密码输入框的页面，检查是否自动填充了密码。推荐使用 https://github.com/halo-sigs/plugin-s3 测试。
```release-note
禁用非登录场景下，密码输入框的浏览器自动填充
```

perf: disable browser's autocomplete feature for password input field

---

console/src/composables/use-content-cache.ts
console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/posts/PostEditor.vue

/kind bug
/area console
修复新建文章或页面保存后，本地内容缓存可能不会及时清空的问题。
Fixes https://github.com/halo-dev/halo/issues/3380
测试方式：
1. 连续创建多篇新的文章，然后反复进入新建页面，观察是否有恢复缓存的提示。
```release-note
修复新建文章或页面保存后，本地内容缓存可能不会及时清空的问题。
```

fix: the issue of local cache not being cleared after saving a new post

---

console/src/components/login/LoginForm.vue
console/src/router/guards/auth-check.ts
console/src/utils/api-client.ts

/kind bug
/area console
修复使用非本地认证登录之后，无法重新登录的问题。此问题来源是三方登录方式登录之后没有在 localStorage 存入 `logged_in` 的 flag。并且在引入匿名用户之后，本身也不再需要这个 flag。
Fixes #3569 
测试方式：
1. 使用 https://github.com/halo-sigs/plugin-oauth2/pull/3 插件配置 OAuth 2 的登录方式。
2. 在个人资料中绑定配置的登录方式。
3. 测试登录之后退出，再进行登录。
```release-note
None
```

fix: unable to login again after using oauth providers login

---

api/src/main/java/run/halo/app/plugin/SettingFetcher.java
application/src/main/java/run/halo/app/plugin/DefaultSettingFetcher.java

/kind bug
/area core
Change type of SettingFetcher from interface into abstract class for backward compatibility. See https://github.com/halo-dev/halo/issues/3592 for more.
Fixes https://github.com/halo-dev/halo/issues/3592
Please use [plugin-search-widget](https://github.com/halo-sigs/plugin-search-widget) to test.
```release-note
None
```

Change type of SettingFetcher from interface into abstract class

---

console/src/layouts/BasicLayout.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/modules/contents/pages/module.ts
console/src/modules/system/actuator/module.ts

/area console
优化移动端底部菜单栏的布局和样式。
before:
after:
Fixes #3575 
```release-note
优化 Console 在移动端下底部菜单栏的布局和样式。
```

perf: improve styles of bottom menu in mobile devices

---

application/src/main/java/run/halo/app/plugin/HaloPluginManager.java

/area core
修复插件启动失败后停止插件时出现的 NPE 问题
见 #3579，先使用 issue 描述步骤复现问题，在切换到此 PR 尝试相同步骤
Fixes #3579
```release-note
修复插件启动失败后停止插件时出现的 NPE 问题
```

fix: NPE when stopping the plugin after the plugin startup fails

---

api/src/main/java/run/halo/app/core/extension/content/Comment.java
application/src/main/java/run/halo/app/core/extension/reconciler/ReplyReconciler.java
application/src/main/java/run/halo/app/event/post/ReplyChangedEvent.java
application/src/main/java/run/halo/app/metrics/ReplyEventReconciler.java

/area core
修复未审核过的回复包含在了评论的回复数量中的问题
此改动需要评论组件修改回复数量取值为 `status.visibleReplyCount`
1. 创建评论，并在评论下回复
2. 评论的所有回复被计数在 `status.replyCount` 中
3. 而 `status.visibleReplyCount` 数量不包含 `spec.hiden=true` 或 `spec.approved = false` 的
Fixes #3165
```release-note
修复未审核过的回复包含在了评论的回复数量中的问题
```

fix: unapproved replies are included in the reply count of comments

---

api/src/main/java/run/halo/app/extension/Secret.java
api/src/test/java/run/halo/app/extension/SecretTest.java
application/src/main/java/run/halo/app/infra/SchemeInitializer.java

/kind feature
/area core
提供 Secret 自定义模型用于存储敏感数据
例如：密码、token 等
参考自： https://kubernetes.io/docs/concepts/configuration/secret
Fixes #3267
```release-note
提供 Secret 自定义模型用于存储敏感数据
```

feat: provide a secret extension to store sensitive data

---

platform/application/build.gradle

/kind cleanup
/area core
See https://github.com/halo-dev/halo/issues/3600 for more.
Fixes https://github.com/halo-dev/halo/issues/3600
We can follow the commands below to test it:
```bash
docker run -d --env MARIADB_USER=halo -p 3306:3306 --env MARIADB_PASSWORD=mariadb --env MARIADB_ROOT_PASSWORD=mariadb -e MARIADB_DATABASE=halo mariadb:latest
make -C console dev
./gradlew bootRun --args="--spring.profiles.active=dev,mariadb"
```
```release-note
升级至 MariaDB R2DBC connector 1.1.4
```

Upgrade to MariaDB R2DBC connector 1.1.4

---

console/package.json
console/pnpm-lock.yaml
console/src/components/editor/DefaultEditor.vue

/kind feature
/area console
升级 `@halo-dev/richtext-editor` 以支持 i18n。 https://github.com/halo-sigs/richtext-editor/pull/6
Ref #3574 
在不同语言的浏览器中测试编辑器的语言是否显示正确即可。
```release-note
None
```

chore: bump @halo-dev/richtext-editor version to support i18n

---

application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
application/src/main/java/run/halo/app/infra/properties/SecurityProperties.java

/kind feature
/area core
This PR provides a configuration item to control referrer-policy header. Default is `strict-origin-when-cross-origin`.
```yaml
halo:
security:
referrer-options:
policy: no-referrer
```
Fixes https://github.com/halo-dev/halo/issues/3064
```release-note
提供配置以控制站点引用策略（Referrer-Policy）
```

Make referrer-policy configurable

---

console/src/modules/system/auth-providers/AuthProviders.vue

/kind bug
/area console
修复认证方式管理页面在加载时不显示加载状态的问题。
```release-note
None
```

fix: the loading status is not displayed when loading auth providers

---

console/src/layouts/BasicLayout.vue

/kind bug
/area console
/milestone 2.4.0
修复跳转页面之后无法固定菜单滚动位置的问题。
Fixes https://github.com/halo-dev/halo/issues/3633
```release-note
None
```

fix: menu scrollbar position cannot be restored after switching routes

---

console/package.json
console/pnpm-lock.yaml
console/src/setup/setupComponents.ts

/area console
重新在全局注册 FloatingDropdown 组件，因为在 https://github.com/halo-dev/halo/pull/3576 中移除之后，会导致插件无法正常加载 FloatingDropdown 组件，从而带来破坏更新。
Fixes #3621 
```release-note
None
```

chore: add FloatingDropdown to solve compatibility issues

---

application/src/main/java/run/halo/app/core/extension/reconciler/AuthProviderReconciler.java

/area core
/milestone 2.4.0
移除 AuthProviderReconciler 中关于 authProvier 数据被删除时禁用它提供的登录方式的逻辑
当第三方登录插件如 plugin-oauth2 被停止时不应该从已启用的登录配置中移除 auth provider name，这会导致插件被停用在启用后需要重新启用登录方式。
之前之所以如此是想着去掉 system configmap 中的配置残余，虽然现在去掉了 Reconciler 但为了确保数据干净或许还得想其他办法来解决它，但目前不是重点也没有一个很好的办法，或许可以在插件中去做，比如当插件被卸载的生命周期方法中去更新 ConfigMap 中关于此项的配置。
```release-note
None
```

refactor: do not disable when auth provider deleted

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

/area console
/milestone 2.4.0
修改 Console 的版本号为 2.4.0。
修改 `@halo-dev/components` 的版本为 1.3.0
```release-note
None
```

chore: bump console version to 2.4.0

---

console/src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue

/kind bug
/area console
修复附件存储策略编辑表单无法正常渲染的问题。此问题原因为 Modal 组件使用了 OverlayScrollbars 库来模拟滚动条，但在初始化的时候由于 Body 没有任何子元素，所以导致异常。
Fixes #3662 
测试是否能够正常打开附件存储策略编辑表单即可。
```release-note
修复 Console 端附件存储策略编辑表单无法正常渲染的问题
```

fix: attachment policy editing modal crashes when opened

---

console/src/components/global-search/GlobalSearchModal.vue

/kind bug
/area console
/cherry-pick release-2.4
修复后台全局搜索中关于 Console 路由的文字没有适配 i18n 的问题。
Fixes #3664 
```release-note
修复后台全局搜索中关于 Console 路由的文字没有适配 i18n 的问题。
```

fix: route title i18n in global search is not compatible

---

console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/pages/components/SinglePageSettingModal.vue
console/src/modules/contents/posts/PostEditor.vue
console/src/modules/contents/posts/components/PostSettingModal.vue

/kind bug
/area console
/cherry-pick release-2.4
修复文章设置中的发布时间无法回显导致重新保存时丢失发布时间的问题。
Fixes #3669 
测试方式：
1. 新建或者修改已有文章的设置。
2. 检查时间输入框的时间是否显示正确。
3. 检查保存之后时间是否显示正确。
```release-note
修复 Console 端文章设置中的发布时间无法回显导致重新保存时丢失发布时间的问题。
```

fix: publish time of the post cannot be displayed back

---

application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java

/kind bug
/area core
Move `defaultHandler#onAuthenticationSuccess` up to response write, or it will be executed always.
Fixes https://github.com/halo-dev/halo/issues/3553
Try to login and see the log detail.
```release-note
修复登录成功或失败后报错的问题
```

Fix the problem of ServerHttpResponse already committed after logging in

---

console/src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
console/src/modules/interface/themes/ThemeSetting.vue
console/src/modules/interface/themes/components/preview/ThemePreviewModal.vue
console/src/modules/system/auth-providers/AuthProviderDetail.vue
console/src/modules/system/plugins/PluginSetting.vue
console/src/modules/system/settings/SystemSetting.vue

/kind bug
/area console
/cherry-pick release-2.4
修复使用了 FormKit Schema 生成的表单中，Radio 输入类型如果值的类型定义为 boolean 类型，但得到的结果为 string 类型的问题。
Fixes #3666 
测试方式：
1. 安装一个主题设置使用了 Radio 输入类型的主题，比如 https://github.com/halo-dev/halo-theme-anatole
2. 测试保存其中包含了 Radio 输入类型的表单。
3. 刷新页面，检查值回显是否正确。
```release-note
修复 Console 端 FormKit Schema 生成的表单中，Radio 输入类型值类型为 boolean 但结果为 string 的问题。
```

fix: radio value type is incorrect in the form defined by formkit schema

---

application/src/main/resources/application.yaml
console/.env.development

/area core
Configure default external-url as slash. So that system will generate relative links for all permalinks.
See https://github.com/halo-dev/halo/issues/3654 for more.
Fixes https://github.com/halo-dev/halo/issues/3654
```release-note
None
```

Configure default external-url as slash

---

console/package.json
console/pnpm-lock.yaml

/area console
/cherry-pick release-2.4
升级 `@halo-dev/richtext-editor` 的版本以解决编辑器翻译不完整的问题。
see https://github.com/halo-sigs/richtext-editor/pull/7
```release-note
升级 `@halo-dev/richtext-editor` 的版本以解决编辑器部分文本翻译不完整的问题。
```

chore: bump @halo-dev/richtext-editor version to resolve i18n issue

---

console/src/composables/use-setting-form.ts

/kind bug
/area console
修复保存系统设置之后，启用主题的设置丢失，恢复为了默认主题。原因是因为在 https://github.com/halo-dev/halo/pull/3606 中使用了新的 useSettingFormConvert 方法，但这个方法未考虑到某些 ConfigMap 的分组并未在表单中定义，也就是数据转换方法是以表单的定义为基准，所以丢失了 `theme.active` 设置。
Fixes #3673 
测试方式：
1. 安装若干主题并启用。
2. 然后去系统设置修改任意数据并保存。
3. 检查主题是否被修改为默认主题。
```release-note
修复保存系统设置之后导致激活主题的设置值丢失，恢复为了默认主题的问题。
```

fix: lost the activated theme settings when saving the system settings

---

application/src/main/java/run/halo/app/core/extension/endpoint/CustomEndpointsBuilder.java
application/src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
application/src/test/java/run/halo/app/plugin/PluginCompositeRouterFunctionTest.java

/kind feature
/area core
/area plugin
Including CustomEndpoint beans while building plugin router functions.
After that, we can define a CustomEndpoint in plugin like this:
```java
@Component
public class ApplicationEndpoint implements CustomEndpoint {
@Override
public RouterFunction<ServerResponse> endpoint() {
return SpringdocRouteBuilder.route()
.GET("/applications", request -> ServerResponse.ok().build(), builder -> {
builder.operationId("ListV1Alpha1Applications");
})
.build();
}
@Override
public GroupVersion groupVersion() {
return CustomEndpoint.super.groupVersion();
}
}
```
Fixes https://github.com/halo-dev/halo/issues/3700
```release-note
None
```

Add support defining custom endpoint in plugin

---

application/src/main/resources/application.yaml
application/src/test/java/run/halo/app/XForwardHeaderTest.java

/kind bug
/area core
Set property `server.forward-header-strategy` to `framework` to enable handling `X-Forwarded*` headers correctly.
By default, Spring won't handle `X-Forwarded*` headers. It doesn't work correctly if Halo is running back reverse proxy server.
Supported headers: <https://github.com/spring-projects/spring-framework/blob/310344cf615339ec330031da127737a41400b6cd/spring-web/src/main/java/org/springframework/web/server/adapter/ForwardedHeaderTransformer.java#L63-L69>.
Fixes https://github.com/halo-dev/halo/issues/3670
```release-note
解决反向代理后无法正确获取当前请求 URI 的问题
```

Set property server.forward-header-strategy to framework by default

---

application/src/main/java/run/halo/app/config/HaloConfiguration.java

/area core
After enabling this mapper feature, we could pass a enum value with any case in request body(JSON format).
See https://github.com/FasterXML/jackson-databind/blob/39fdb63607a0e7a6dbf9d6be84fe7e380e661dcb/src/test/java/com/fasterxml/jackson/databind/deser/enums/EnumDeserializationTest.java#L22 for more.
```release-note
None
```

Enable mapper feature: accept case-insensitive enums

---

console/src/modules/interface/themes/layouts/ThemeLayout.vue
console/src/modules/system/plugins/layouts/PluginLayout.vue

/kind bug
/area console
获取主题配置时，重复添加了上次已经获取到的主题配置，导致重复显示。并同步修改了 plugin 中可能出现问题的位置。
Fixes #3726 
1. 打开 Console 端主题页面
2. 点击右上角预览页面
3. 关闭预览页面，选项卡无重复即为正常。
```release-note
修复 Console 端主题设置中，选项卡会重复显示的问题
```

fix: repeated display of theme tabs.

---

api/src/main/java/run/halo/app/extension/ListResult.java
api/src/main/java/run/halo/app/infra/utils/GenericClassUtils.java
api/src/test/java/run/halo/app/infra/utils/GenericClassUtilsTest.java

/kind bug
/area core
- Use the class loader belonging to the parameter type when creating a generic class.
- Use full qualified class name when generating a generic class.
Before testing, you have to set property `springdoc.cache.disabled` to `true`.
Fixes #3728 
```release-note
None
```

Fix the problem that generateing OpenAPI defined in Plugin may not work

---

api/src/main/java/run/halo/app/core/extension/attachment/Attachment.java
api/src/main/java/run/halo/app/core/extension/attachment/Constant.java
api/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentHandler.java
api/src/main/java/run/halo/app/core/extension/attachment/endpoint/DeleteOption.java
api/src/main/java/run/halo/app/core/extension/attachment/endpoint/SimpleFilePart.java
api/src/main/java/run/halo/app/core/extension/attachment/endpoint/UploadOption.java
api/src/main/java/run/halo/app/core/extension/service/AttachmentService.java
application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
application/src/main/java/run/halo/app/core/extension/attachment/endpoint/LocalAttachmentUploadHandler.java
application/src/main/java/run/halo/app/core/extension/reconciler/attachment/AttachmentReconciler.java
application/src/main/java/run/halo/app/core/extension/service/impl/DefaultAttachmentService.java
application/src/main/java/run/halo/app/plugin/SharedApplicationContextHolder.java
application/src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java

/kind feature
/area core
/area plugin
This PR refactor AttachmentEndpoint by extracting `upload`, `delete`, `getPremalink` and `getSharedURL` logic in the endpoint into AttachmentService. Meanwhile, I expose the service to plugin, so that we can use the service in plugin conveniently.
Please confirm that those changes won't influence existing attachment features.
```release-note
None
```

Expose attachment service to plugin

---

application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
application/src/main/java/run/halo/app/core/extension/service/PluginService.java
application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
application/src/main/resources/extensions/role-template-plugin.yaml
application/src/test/java/run/halo/app/core/extension/service/impl/PluginServiceImplTest.java

/kind feature
/area core
/area plugin
新增 reload 插件的 API
通过以下 API 测试是否可以在不重启 Halo 的情况下使新改动的插件代码生效
```shell
./gradlew clean build && curl -u your-name:your-password -X PUT http://127.0.0.1:8090/apis/api.console.halo.run/v1alpha1/plugins/{plugin-name}/reload
```
Fixes #3748
```release-note
None
```

feat: add an API for reloading plugin

---

application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
application/src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java
application/src/test/java/run/halo/app/core/extension/reconciler/UserReconcilerTest.java

/area core
允许用户修改自己的元数据信息
how to test it
使用 API 修改元数据 `PUT localhost:8090/apis/api.console.halo.run/v1alpha1/users/-`
1. 修改 annotations 中的 `"rbac.authorization.halo.run/role-names": "[\"super-role\",\"fake-role\"]"` 会被复原
2. 修改其他的 annotations 能正确修改，也能增加新的 annotation
Fixes #3544
```release-note
允许用户修改自己的元数据信息
```

refactor: allow users to modify their own annotations in metadata

---

.github/workflows/halo.yaml
api/build.gradle
buildSrc/build.gradle
buildSrc/src/main/groovy/halo.publish.gradle
console/Makefile
platform/application/build.gradle
platform/plugin/build.gradle

/kind feature
/area core
Use Gradle plugin `maven-publish` to publish Halo modules(`platform.application`, `platform.plugin` and `api`) to Maven central repository.
```bash
./gradlew publish
./gradlew -Prelease publish -PossrhUsername=username -PossrhPassword=password
```
Note that currently we only support manually publishing.
Fixes https://github.com/halo-dev/halo/issues/2730
```release-note
None
```

Support publishing to Maven central repository

---

console/src/components/editor/DefaultEditor.vue

/kind bug
/area console
为默认编辑器侦听器增加 `immediate` 属性，使其在创建之后立即执行，生成目录。
Fixes #3769 
打开已经存在并且具有标题的文章/页面，查看大纲是否正常生成。
```release-note
修复文章/页面已有内容重新编辑时，无法立即显示大纲的问题。
```

fix: outline not displayed when first entering the editor.

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/interface/themes/components/ThemeListModal.vue
console/src/modules/interface/themes/components/ThemeUploadModal.vue

/area console
优化安装主题和升级主题的流程，支持在升级或者安装之后自动关闭弹框以及刷新数据。
测试方式：
1. 测试升级或者安装新主题之后是否关闭弹框以及是否有提示即可。
```release-note
优化 Console 端安装和升级主题的流程，支持自动关闭安装弹框和显示反馈提示
```

perf: automatically close the installation modal after installing the theme

---

console/src/modules/interface/themes/components/components/ThemeListItem.vue
console/src/modules/interface/themes/components/preview/ThemePreviewListItem.vue
console/src/modules/interface/themes/composables/use-theme.ts
console/src/modules/interface/themes/layouts/ThemeLayout.vue

/area console
在主题列表激活主题之后，自动刷新页面。
Fixes #3778 
测试方式：
1. 打开主题列表，选择任意主题激活，观察是否刷新页面。
```release-note
优化 Console 端激活主题的流程，支持激活后自动刷新页面
```

perf: reload page after active theme

---

api/src/main/java/run/halo/app/infra/ExternalUrlSupplier.java
application/src/main/java/run/halo/app/actuator/GlobalInfoEndpoint.java
application/src/main/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplier.java
application/src/main/java/run/halo/app/infra/properties/HaloProperties.java
application/src/main/java/run/halo/app/theme/dialect/HaloTrackerProcessor.java
application/src/main/resources/application.yaml
application/src/test/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplierTest.java
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/system/actuator/Actuator.vue
console/src/modules/system/actuator/types/index.ts

/area core
Add property `halo.use-absolute-permalink`(default is `false`) to control permalink generation. Leave `halo.external-url` as `null` by default.
Meanwhile, I enhanced `ExternalUrlSupplier#getURL` to get URL from not only properties but only http request.
```yaml
halo:
use-absolute-permalink: false
```
Or:
```yaml
halo:
external-url: https://halo.run/
use-absolute-permalink: false
```
Or:
```yaml
halo:
external-url: https://halo.run/
use-absolute-permalink: true
```
Fixes https://github.com/halo-dev/halo/issues/3762
```release-note
新增是否生成相对地址的配置
```

Add property halo.use-absolute-permalink to control permalink generation

---

console/src/components/upload/UppyUpload.vue

/kind feature
/area console
为上传组件 Uppy 导入中文繁体的语言包。
Ref https://github.com/halo-dev/halo/pull/3672
```release-note
None
```

feat: import zh_TW locale for uppy component

---

application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
application/src/main/java/run/halo/app/plugin/PluginControllerManager.java

/kind feature
/area core
/area plugin
This PR adds reconciliation mechanism for plugin. After that, we could define a `Reconciler<Request>` like the following when developing plugin:
```java
@Slf4j
@Component
public class ApplicationReconciler implements Reconciler<Reconciler.Request> {
@Override
public Result reconcile(Request request) {
log.info("Application {} changed.", request);
return Result.doNotRetry();
}
@Override
public Controller setupWith(ControllerBuilder builder) {
return builder
.extension(new Application())
.workerCount(1)
.build();
}
}
```
You can reconcile any extensions as needed.
Meanwhile, all plugins will be stopped when Halo is shutting down.
Fixes https://github.com/halo-dev/halo/issues/3783
```release-note
支持在插件中定义 Reconciler
```

Enable defining Reconciler in plugin

---

console/src/components/upload/UppyUpload.vue
console/src/modules/contents/attachments/components/AttachmentUploadModal.vue

/area console
支持在附件上传弹框中点击完成按钮关闭弹框。
测试方式：
1. 测试上传完附件之后，点击完成按钮，观察是否关闭上传弹框即可。
```release-note
优化 Console 端上传附件的弹框，支持点击完成按钮以关闭弹框。
```

perf: close attachment upload modal after click complete button

---

console/src/modules/system/plugins/PluginDetail.vue

/kind bug
/area console
修复插件页面中的角色模板在首次进入页面时，无法加载的问题。
Fixes #3793 
测试方式：
1. 安装一个带有角色模板的插件，比如：https://github.com/halo-sigs/plugin-links
2. 进入插件详情页面，观察角色模板是否显示正确。
```release-note
修复 Console 端插件详情页面中角色模板无法正常加载的问题。
```

fix: role templates in the plugin detail page is not loaded.

---

console/src/modules/system/plugins/components/PluginUploadModal.vue

/kind bug
/area console
修复升级插件之后没有自动刷新页面的问题，一般情况来说，升级插件之后需要重载插件 Console 部分的资源。
测试方式：
1. 以 deployment 模式启动 Halo
2. 测试升级插件之后是否有正常刷新页面
```release-note
修复 Console 端升级插件之后没有自动刷新页面的问题。
```

fix: not reload page after upgrading a plugin

---

console/src/formkit/formkit.config.ts
console/src/formkit/inputs/group.ts
console/src/formkit/inputs/repeater/Repeater.vue
console/src/formkit/theme.ts

/kind feature
/area console
Fixes #3734
为 FormKit 的 group 输入组件重构布局和样式。
before:
after:
可以测试的 FormKit Schema：
```yaml
- $formkit: group
name: author
label: 作者
children:
- $formkit: text
name: name
label: 名称
- $formkit: text
name: email
label: Email
```
```release-note
为 Console 端 FormKit 的 group 输入组件重构布局和样式。
```

feat: improve layout and styles of group formkit input

---

console/package.json
console/src/modules/interface/themes/ThemeDetail.vue
console/src/modules/system/roles/RoleDetail.vue

/area console
调整 ESLint 的执行参数，添加 max-warnings 为 0，意味着在提交或者运行 CI 的时候不再允许包含 warning 级别的检测。
```release-note
None
```

chore: set eslint max-warnings option and remove unused imports

---

console/src/formkit/formkit.config.ts
console/src/formkit/plugins/required-asterisk.ts

/area console
为 FormKit 表单中包含了 required 验证的表单元素的 label 添加指示器（*），优化可访问性。
Fixes #3823 
测试方式：
1. 检查 Console 端的表单中必填项的 label 是否添加了 * 即可。
```release-note
为 FormKit 表单中包含了 required 验证的表单元素的 label 添加指示器（*），优化可访问性。
```

feat: add required indicator for formkit label

---

console/src/modules/contents/attachments/AttachmentList.vue
console/src/modules/contents/attachments/components/AttachmentDetailModal.vue
console/src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue

/area console
为附件库的图片渲染添加硬件加速（GPU）的支持，可以改善在附件库包含大量大图时的操作体验，能够缓解卡顿的问题。不过最终还是需要 https://github.com/halo-dev/halo/issues/2387 的支持。
测试（一共 60 张图片，合计 230m）：
before:
after:
Fixes #3830 
测试方式：
1. 上传若干大图，对比修改前对附件库的操作，以及在文章中选择附件。
```release-note
优化 Console 端附件库的图片渲染性能。
```

perf: enable hardware acceleration for attachment images

---

application/src/main/java/run/halo/app/plugin/YamlPluginFinder.java

/kind bug
/area plugin
/area core
Close file system after reading plugin descriptor.
Fixes https://github.com/halo-dev/halo/issues/3720
1. Build a plugin and install it
2. Update plugin.yaml of the plugin, rebuild and upgrade it
3. Check the change you modified
```release-note
修复无法正常升级插件的问题
```

Fix the problem of upgrading plugins with same version

---

console/src/formkit/theme.ts

/kind bug
/area console
修复文章分类和标签选择组件在 Repeater 组件中，下拉框无法完整显示的问题。
Fixes #3479 
```release-note
修复 Console 端的文章分类和标签选择组件在 Repeater 组件中，下拉框无法完整显示的问题。
```

fix: category select dropdown cannot be fully displayed in repeater component

---

application/build.gradle

/kind cleanup
/area core
Upgrade to plugin-sitemap 1.0.2 and plugin-feed 1.1.1.
```bash
❯ ./gradlew :application:downloadPluginPresets  
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Task :application:downloadPluginPresets
Download https://github.com/halo-sigs/plugin-search-widget/releases/download/v1.0.0/plugin-search-widget-1.0.0.jar
Download https://github.com/halo-sigs/plugin-comment-widget/releases/download/v1.5.0/plugin-comment-widget-1.5.0.jar
Download https://github.com/halo-sigs/plugin-sitemap/releases/download/v1.0.2/plugin-sitemap-1.0.2.jar
Download https://github.com/halo-sigs/plugin-feed/releases/download/v1.1.1/plugin-feed-1.1.1.jar
BUILD SUCCESSFUL in 4s
8 actionable tasks: 1 executed, 7 up-to-date
```
Fixes …

Upgrade plugin presets

---

application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java
application/src/main/java/run/halo/app/event/post/PostVisibleChangedEvent.java
application/src/main/java/run/halo/app/search/post/PostEventReconciler.java
application/src/test/java/run/halo/app/core/extension/reconciler/PostReconcilerTest.java

/kind bug
/area core
This PR adds PostVisibleChangedEvent to synchronizing post indices when post visible is changed, whether from public to private or from private to public.
Fixes https://github.com/halo-dev/halo/issues/3438
1. Install Search plugin
2. Create a post
3. Try to search the post
4. Make post private
5. Try to search the post
6. Make post public
7. Try to search the post
```release-note
修复隐藏的文章已然能够被搜索到问题
```

Fix the problem of being able to search private posts after making post private

---

console/packages/components/src/components/dialog/Dialog.vue

/kind bug
/area console
修复在 Dialog 组件中，如果 onConfirm 方法出现异常，按钮加载状态没有复原的问题。
Fixes https://github.com/halo-dev/halo/issues/3844
```release-note
None
```

fix: loading state is not restored when Dialog's onConfirm method has exception

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json

修改版本号，准备发布 2.5.0-rc.2。
```release-note
None
```

chore: bump up version to 2.5.0-rc.2

---

application/src/main/java/run/halo/app/theme/router/SinglePageRoute.java

/kind bug
/area core
修复页面的链接不能包含特殊字符的问题。
Fixes https://github.com/halo-dev/halo/issues/3808
测试方式：
1. 创建一个页面。
2. 尝试设置别名为中文或者其他字符。
3. 尝试包含多个 `/` 分隔符。
4. 尝试访问页面，检查是否能够正常访问。
```release-note
修复页面链接包含中文等字符后无法访问的问题。
```

fix: permalink of singlePage cannot contain special characters

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java
application/src/main/java/run/halo/app/plugin/PluginUtils.java

/area core
修复插件缺失路径信息升级后无法使用的兼容性问题
1. 生产模式安装插件
2. 更新插件将插件中的 status.loadLocation 和 metadata.annotations["plugin.halo.run/plugin-path"] 删除
3. 查看插件功能是否正常
```release-note
修复插件缺失路径信息升级后无法使用的兼容性问题
```

refactor: compatibility issues with plugins lacking loadLocation after upgrading

---

console/src/modules/system/users/components/UserCreationModal.vue
console/src/modules/system/users/components/UserEditingModal.vue

/kind bug
/area console
修复用户头像不支持相对链接的问题。
Fixes #3879 
测试方式：
1. 创建或者编辑用户资料。
2. 从附件库选择头像，检查是否可以通过表单验证。
```release-note
修复创建用户或者修改用户资料时，头像链接不支持相对链接的问题。
```

fix: user avatar link does not support relative paths

---

application/src/main/java/run/halo/app/infra/SetupStateCache.java
application/src/main/java/run/halo/app/security/InitializeRedirectionWebFilter.java
application/src/test/java/run/halo/app/security/InitializeRedirectionWebFilterTest.java
application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java

/area core
/milestone 2.5.2
添加系统初始化检查，如果未初始化则重定向到控制台。
此检查只针对首页，当用户访问首页时检查到未初始化则跳转到 Console 让用户初始化以优化没有数据时的访问体验。
SetupStateCache 用于缓存系统初始化状态，当数据库状态改变时会更新缓存以优化性能，避免每次访问首页都查询数据。
A part of #3230
```release-note
添加系统初始化检查，如果未初始化则重定向到控制台
```

refactor: add system initialization check and redirect to console if not initialized

---

console/src/views/system/Setup.vue

/kind bug
/area console
修复初始化时，预设插件安装失败的问题，目前的解决方案是重试安装操作。
Fixes #3893 
测试方式：
1. 建议参考 https://docs.halo.run/developer-guide/core/build 构建成 Docker 镜像再测试。
2. 测试初始化完成之后，预设插件是否正确安装以及启动即可。
```release-note
修复在初始化时，预设插件可能初始化失败的问题。
```

fix: failed to initialize the preset plugins

---

console/src/formkit/plugins/required-asterisk.ts

/kind bug
/area console
修复部分 FormKit 的 radio 表单项的 label 设置不正确的问题。目前影响范围：
1. 使用了 type 为 `menuCheckbox`  `menuRadio` 并将 validation 设置为了 `required`。
Fixes #3876 
```release-note
修复部分 FormKit 的 radio 表单项的 label 设置不正确的问题。
```

fix: the label of some radio is displayed incorrectly

---

application/src/main/java/run/halo/app/theme/ReactivePropertyAccessor.java

/kind bug
/area core
When we use curl or ab command to access any pages rendered by thymeleaf at first up, we will get the error described in <https://github.com/halo-dev/halo/issues/3861>.
This PR will resolve the problem by checking null value.
Fixes https://github.com/halo-dev/halo/issues/3861
```release-note
解决访问页面无法渲染的问题
```

Fix the problem of resolving authentication in template when using curl or ab command

---

console/src/setup/setupVueQuery.ts

/area core
/milstone 2.6.x
将 TanStack Query 的 Network Mode 设置为 always，防止在无网络的情况下，开发环境也无法请求数据。
测试方式：断网之后使用开发模式访问 Console，观察请求是否正常发送即可。
```release-note
None
```

refactor: make tanstack query's network mode option to always

---

console/README.md
console/pnpm-lock.yaml

/area console
升级 pnpm 的版本为 pnpm 8，更新 pnpm-lock.yaml 文件。
GitHub Actions 的改动将在 https://github.com/halo-sigs/actions
Fixes #3934 
```release-note
None 
```

chore: bump pnpm version to 8

---

console/src/modules/interface/themes/layouts/ThemeLayout.vue

/kind bug
/area console
Fixes #3933 
1. 创建一个拥有主题查看而没有主题管理权限的角色，并为某个用户分配这个角色。
2. 使用该用户登录 console，点击主题选项卡查看控制台是否报错。
```release-note
修复没有主题管理权限时，进入主题功能页面报错的问题。
```

fix: theme page displays error without management permissions.

---

console/packages/components/src/components/entity/Entity.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/contents/attachments/AttachmentList.vue
console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/posts/PostList.vue
console/src/modules/system/plugins/components/PluginListItem.vue

/area console
1. 移除 Entity 组件最外层容器的手型样式，避免出现可点击性的误导。
2. 为部分数据列表项操作提供更多的访问选项。
1. 文章 / 页面列表添加编辑按钮。
2. 插件列表项添加详情按钮。
3. 附件列表项添加详情按钮。
Fixes #3914 
```release-note
优化 Console 端部分数据列表的可访问性
```

refactor: improve the accessibility of action items in some data list

---

console/src/modules/system/plugins/PluginDetail.vue
console/src/modules/system/plugins/components/PluginListItem.vue
console/src/modules/system/plugins/composables/use-plugin.ts

/area console
重构 Console 端插件异常状态的判断和显示，改动如下：
1. 移除插件名称旁边的启用状态。
2. 切换按钮的状态是期望值，意思就是不与插件实际状态一致。
3. 小红点出现的时机为：插件的实际状态与期望状态不一致以及插件本身出了异常。
4. 插件详情页面支持横幅显示插件异常状态。
Fixes https://github.com/halo-dev/halo/issues/3940
测试方式：
1. 想办法将插件状态变成异常，比如在开发环境将 runtime-mode 改为 deployment。
2. 检查 Console 端插件管理中的 UI 表现是否和上面的描述一致。
```release-note
重构 Console 插件管理的异常状态显示。
```

refactor: abnormal status display of plugin management

---

console/src/modules/system/auth-providers/AuthProviders.vue

/kind bug
添加关键字搜索功能到认证方式列表
Fixes #3948
```release-note
修复 Console 端认证方式列表无法使用搜索的问题。
```

fix: add keyword search functionality to AuthProvider list

---

console/src/formkit/inputs/category-select/CategorySelect.vue
console/src/formkit/inputs/tag-select/TagSelect.vue

改善分类和标签选择性输入框的输入逻辑
Fixes #3959
```release-note
NONE
```

perf: improve the logic of input selection for category and tag

---

console/src/modules/system/users/Login.vue
console/src/router/guards/auth-check.ts

/area console
/kind feature
Console 端的登录页面支持登录之后重定向到某个链接（通过 redirect_uri 参数）。
支持一下链接形式：
1. 相对地址，比如 `/console#/plugins`、`/apps/app-links`
2. 绝对地址，仅限于同源地址，不支持非同源地址的重定向。
Fixes https://github.com/halo-dev/halo/issues/3982
测试方式：
1. 在未登录的情况下访问如 `http://127.0.0.1:8090/console#/theme` 地址，观察登录之后是否会返回到这个页面。
2. 手动在登录页面构造如 `https://127.0.0.1:8090/console#/login?redirect_uri=/` 的地址，观察登录之后是否会跳转。
```release-note
Console 端的登录页面支持登录之后重定向到某个站内链接。
```

feat: login page supports redirect_uri parameter

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/interface/themes/components/ThemeListModal.vue
console/src/modules/interface/themes/components/ThemeUploadModal.vue

/kind feature
/area console
支持在安装已存在主题时提示是否升级主题。
Fixes #3969 
测试方式：
1. 通过本地上传和远程下载的方式重复安装某个主题，观察是否可以正常提示升级以及测试升级是否正常。
```release-note
Console 端支持安装已存在主题时提示升级主题。
```

feat: prompt to upgrade theme when installing existing theme

---

console/package.json
console/packages/api-client/package.json
console/packages/shared/package.json

修改版本号，准备发布 2.6.0-rc.1。
```release-note
None
```

chore: bump up version to 2.6.0-rc.1

---

console/src/router/guards/auth-check.ts
console/src/router/index.ts

/area console
将 Console 的 Router 模式从 Hash History 改为 Web History。可以让路由看起来更加简洁，也方便在后端或者页面上构建路由。
文档：https://router.vuejs.org/zh/guide/essentials/history-mode.html
测试 Console 的各个页面是否正常访问即可。
```release-note
修改 Console 的路由模式为 HTML5 模式。
```

refactor: use createWebHistory instead of createWebHashHistory

---

console/packages/components/src/components/dialog/Dialog.vue

/area console
修复 Console 端 Dialog 对话框组件中的文字内容可能会溢出容器的问题。
before:
after:
Fixes #4006 
```release-note
修复 Console 端 Dialog 对话框组件中的文字内容可能会溢出容器的问题。
```

fix: text content overflowing the container in the dialog component

---

application/src/main/java/run/halo/app/theme/router/SinglePageRoute.java
application/src/test/java/run/halo/app/theme/router/SinglePageRouteTest.java

/kind bug
/area core
This PR refactors request predicate of path when building router functions for single page. I only compare the exact slug name instead of treating it as a URI template.
See <https://github.com/halo-dev/halo/issues/3931> for more.
Fixes <https://github.com/halo-dev/halo/issues/3931>
1. Try to create a single page with slug name like `{}[]{[]}[{}]`.
2. Publish the single page.
3. Try to request the page.
4. See the result.
```release-note
修复页面别名包含特殊字符导致无法访问的问题
```

Fix the problem of crashing requests when slug names of single page contains special chars

---

application/src/main/java/run/halo/app/search/post/LucenePostSearchService.java

/kind bug
/area core
On first start, we will receive an exception about post indices, please see the logs below:
```java
2023-06-01T10:49:57.191+08:00  INFO 7 --- [         task-1] run.halo.app.search.IndicesInitializer   : Initialize post indices...
2023-06-01T10:49:57.352+08:00 ERROR 7 --- [-controller-t-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.apache.lucene.index.IndexNotFoundException: no segments* file found in LockValidatingDirectoryWrapper(MMapDirectory@/root/.halo2/indices/posts lockFactory=org.apache.lucene.store.NativeFSLockFactory@3de15f4f): files: [write.lock]
Caused by: org.apache.lucene.index.IndexNotFoundException: no segments* file found in …
```

Set open mode of indices to CREATE_OR_APPEND

---

application/src/main/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessor.java

/kind bug
/area core
Fix the problem that the meta description with special characters causes the page to display abnormally.
Use htmlEscape in org.springframework.web.util.HtmlUtils to escape the special characters contained in the original description.
see #4000 
Fixes #4000
```release-note
修复 meta description 中含有特殊字符导致页面显示异常的问题
```

Fix the meta description with special characters causing the page to display abnormally

---

application/src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
docs/developer-guide/plugin-configuration-properties.md

/kind feature
/area core
/area plugin
This PR adds property sources into PluginApplicationContext environment to support configuration properties mechanism.
See https://github.com/halo-dev/halo/issues/4015 for more.
Fixes https://github.com/halo-dev/halo/issues/4015
You can verify the mechanism in [plugin-starter](https://github.com/halo-dev/plugin-starter) according to documentation `docs/developer-guide/plugin-configuration-properties.md`.
I've only tested it on macOS, looking forward to feedback on Windows.
```release-note
支持在插件中定义 @ConfigurationProperties 注解
```

Support configuration properties mechanism for plugin in Halo core

---

application/src/main/java/run/halo/app/plugin/resources/BundleResourceUtils.java
application/src/main/java/run/halo/app/theme/ThemeConfiguration.java
application/src/test/java/run/halo/app/plugin/resources/BundleResourceUtilsTest.java
application/src/test/java/run/halo/app/theme/ThemeConfigurationTest.java

/kind bug
/area core
修复主题和插件静态资源的文件遍历漏洞
漏洞描述：
攻击者可以通过`/plugins/{name}/assets/console/{*resource}` 和 `/themes/{themeName}/assets/{*resource}` 的 resource 参数部分添加特殊字符（如 ../ 或 ..\）来绕过应用程序的访问控制，访问他们没有权限访问的文件或目录。
修复方法：
访问文件之前检查文件路径是否在被限制的目录下，如:
resource = /themes/default/templates/../../test
简化路径为 /themes/test
想限制路径在 `/themes/default/templates` 则已经越权拒绝访问
1. 访问例如 `localhost:8090/themes/theme-earth/assets/dist/../../../../../keys/id_rsa` 来检查获取上级目录，上上级目录是否可以访问到，必须只能访问到 themes/assets下的文件即为合理
2. 类似步骤 1 可以尝试`../`， `..\` 来访问 `localhost:8090/plugins/{name}/assets/console/{*resource}`，必须只能访问到插件的 `classpath:console/` 下的文件即为合理
```release-note
修复主题和插件静态资源的路径遍历漏洞
```

fix: file path traversal vulnerability in theme and plugin resource APIs

---

.github/workflows/halo.yaml
README.md
gradle.properties

/kind cleanup
/area core
This PR adapts GitHub workflow for branch `release-2.5` and bumps Halo version to 2.5.3-SNAPSHOT. Or the workflow on branch `release-2.5` will fail.
```release-note
None
```

Adapt workflow for release-2.5 branch

---

application/build.gradle
platform/application/build.gradle

/area core
升级 Google Guava 版本至 32.0.1-jre
Guava [31.1](https://github.com/google/guava/releases/tag/v31.1) 至 [32.0.1](https://github.com/google/guava/releases/tag/v32.0.1) 的变化：
1. 移除了部分 API 的 `@Beta` 注解进入稳定版
2. 关于 `Files.createTempDir` 方法的安全性修复 https://github.com/advisories/GHSA-7g45-4rm6-3mm3 (https://github.com/google/guava/issues/2575)
详情参考：https://github.com/google/guava/releases/tag/v32.0.0
```release-note
升级 Google Guava 版本至 32.0.1-jre
```

chore: bump google guava version to 32.0.1-jre

---

api/build.gradle
application/build.gradle
application/src/main/java/run/halo/app/infra/exception/Exceptions.java
application/src/main/java/run/halo/app/infra/exception/ThemeAlreadyExistsException.java
application/src/main/java/run/halo/app/infra/utils/IpAddressUtils.java
application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
application/src/main/resources/application.yaml
application/src/main/resources/config/i18n/messages.properties
application/src/main/resources/config/i18n/messages_zh.properties
application/src/test/java/run/halo/app/infra/utils/IpAddressUtilsTest.java
console/src/components/login/LoginForm.vue
platform/application/build.gradle

/kind feature
/area core
This PR introduces https://github.com/resilience4j/resilience4j to archive the feature. The login endpoint has limited login failures at a rate of 3 per minute.
See https://github.com/halo-dev/halo/issues/4044 for more.
Fixes https://github.com/halo-dev/halo/issues/4044
1. Start Halo.
2. Try to login with incorrect credential 4 times
3. Check the response.
```release-note
增加登录失败次数限制功能
```

Add rate limiter for login endpoint

---

console/index.html

/area console
去除`index.html`的`lang`属性以避免console端出现翻译提示
Fixes https://github.com/halo-dev/halo/issues/3692
```release-note
避免 Console 端出现翻译提示
```

perf: remove html lang attribute in console

---

console/src/components/login/SocialAuthProviderItem.vue
console/src/components/login/SocialAuthProviders.vue

/area console
在使用某个三方登录的时候，禁用其他三方登录，防止重复点击。
Fixes #4064 
测试方式：
1. 可安装 https://github.com/halo-sigs/plugin-oauth2 进行测试，可以不用配置各个登录方式，只需开启即可。
2. 在登录页面点击某个三方登录方式，观察所有三方登录方式的按钮是否被禁用。
```release-note
优化 Console 端登录页面的三方登录方式按钮，禁用重复点击。
```

perf: disallow repeated clicks when third-party login

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/contents/posts/categories/CategoryList.vue
console/src/modules/contents/posts/categories/components/CategoryEditingModal.vue
console/src/modules/contents/posts/categories/components/CategoryListItem.vue

/area console
/kind feature
支持在创建分类的时候选择上级分类。
Fixes https://github.com/halo-dev/halo/issues/4040
测试方式：
1. 测试新建的时候指定上级分类的功能是否正常。
2. 点击某个分类的操作按钮，选择添加子分类的菜单项，检查在新建分类的表单中上级分类是否选中了此分类。
```release-note
Console 端的文章分类支持在新建时指定上级分类。
```

feat: add support for selecting the parent category when creating a new category

---

application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java

/kind bug
/area core
This is a bug introduced from https://github.com/halo-dev/halo/pull/4062. I have overridden onAuthenticationSuccess to create rate limiter in advance instead of invoking `securityContextRepository#save` before.
See https://github.com/halo-dev/halo/pull/4099#issuecomment-1598074131 for more.
1. Try to log in with incorrect password three times
2. Log in with correct password and check if the response headers contain `Set-Cookie`
```release-note
None
```

Fix the problem of logging in successfully even if request not permitted

---

application/src/main/java/run/halo/app/config/WebFluxConfig.java
application/src/main/java/run/halo/app/console/ConsoleProxyFilter.java
application/src/main/java/run/halo/app/console/WebSocketRequestPredicate.java
application/src/main/java/run/halo/app/console/WebSocketServerWebExchangeMatcher.java
application/src/main/java/run/halo/app/console/WebSocketUtils.java
application/src/test/java/run/halo/app/console/WebSocketUtilsTest.java

/kind bug
/area core
This PR excludes WebSocket request when serving console index and remove request predicate accept in ConsoleProxyFilter.
Fixes https://github.com/halo-dev/halo/issues/4083
1. Start Console with dev environment
2. Start Halo with dev profile
3. Try to browse <http://localhost:8090/console> and check the log
```release-note
修复开发环境下访问 Console 出现错误的问题
```

Exclude WebSocket request when serving console index

---

application/src/main/java/run/halo/app/infra/exception/Exceptions.java
application/src/main/java/run/halo/app/infra/exception/handlers/ProblemDetailErrorAttributes.java
application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
application/src/main/resources/config/i18n/messages.properties
application/src/main/resources/config/i18n/messages_zh.properties
application/src/test/resources/config/i18n/messages.properties

/area core
Define a global map to mapping exception to problem detail type.
```release-note
None
```

Refactor setting of problem detail type

---

console/packages/components/src/components/button/Button.vue

/area console
为默认类型的按钮添加鼠标悬浮的样式。
Fixes #4067 
```release-note
Console 端默认类型的按钮添加鼠标悬浮的样式。
```

feat: add mouse hover style to the default type of button

---

console/src/modules/contents/comments/components/CommentListItem.vue

/area console
Fix style issue of the comment subject ref title.
before:
after:
Fixes #4068 
```release-note
None
```

perf: improve the text length style of the comment subject ref title

---

application/src/main/java/run/halo/app/security/DefaultUserDetailService.java
application/src/test/java/run/halo/app/security/DefaultUserDetailServiceTest.java

/kind bug
/area core
Catch UserNotFoundException instead of ExtensionNotFoundException to map correctly to BadCredentialsException.
Fixes https://github.com/halo-dev/halo/issues/4057
1. Start Halo
2. Login with an username which does not exist
3. Check the response
```release-note
修复登录时出现用户名不存在的问题。
```

Fix the problem that the username does not exist when the username does not exist

---

application/src/main/java/run/halo/app/theme/endpoint/CommentFinderEndpoint.java
application/src/main/resources/application.yaml
application/src/test/java/run/halo/app/theme/endpoint/CommentFinderEndpointTest.java

/kind feature
/area core
Apply rate limiter for replying a comment as well. This feature is supplement of <https://github.com/halo-dev/halo/pull/4084>.
Try to reply any comments 11 times within 1 minute.
```release-note
对评论回复添加频率限制
```

Apply rate limiter for replying a comment

---

application/src/main/java/run/halo/app/infra/utils/IpAddressUtils.java
application/src/test/java/run/halo/app/infra/utils/IpAddressUtilsTest.java

/kind bug
/area core
In some special situations, Halo can not obtain client IP address from request headers and socket address is unresolved, so that `java.lang.NullPointerException: Cannot invoke "java.net.InetAddress.getHostAddress()" because the return value of "java.net.InetSocketAddress.getAddress()" is null` will happen.
This PR will resolve the problem by checking `X-Real-IP` header and checking if remote address is unresolved.
Fixes https://github.com/halo-dev/halo/issues/4134
```release-note
None
```

Check X-Real-IP header when obtaining client IP

---

console/src/components/editor/DefaultEditor.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml

/kind feature
/area console
/area editor
默认编辑器支持直接插入图片、视频、音频，提供除了附件库的媒体插入入口。
通过链接插入图片需要 https://github.com/halo-sigs/richtext-editor/pull/17 的支持。
Fixes https://github.com/halo-dev/halo/issues/3882
Fixes https://github.com/halo-dev/halo/issues/3994
测试编辑器通过链接插入图片、视频、音频的功能是否正常。
```release-note
默认编辑器支持不通过附件库直接插入图片、视频、音频。
```

feat: add support for inserting external media resources to the default editor

---

application/src/main/java/run/halo/app/theme/endpoint/PublicUserEndpoint.java
application/src/main/resources/application.yaml
application/src/test/java/run/halo/app/theme/endpoint/PublicUserEndpointTest.java

/kind feature
/area core
Add rate limiter for signing up. We only allow 3 registrations within 1 hour by default, despite registration failure.
1. Start Halo and console.
2. Try to enable registration for public users.
3. Browse <http://localhost:8090/console/login?type=signup>
4. Input duplicate username for 4 times and see the result.
5. Or input valid username for 4 times and see the result.
```release-note
限制注册接口的请求速率
```

Add rate limiter for signing up

---

console/package.json
console/pnpm-lock.yaml

/area console
升级 `@halo-dev/richtext-editor` 的版本至 0.0.0-alpha.24
https://github.com/halo-sigs/richtext-editor/pull/17
```release-note
None
```

chore: bump @halo-dev/richtext-editor version to alpha 24

---

api/src/main/java/run/halo/app/infra/ExternalUrlSupplier.java
application/src/main/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplier.java
application/src/test/java/run/halo/app/infra/HaloPropertiesExternalUrlSupplierTest.java

/kind feature
/area core
支持通过 ExternalUrlSupplier 获取 externalUrl 配置
Fixes #4149
```release-note
支持通过 ExternalUrlSupplier 获取 externalUrl 配置
```

feat: support obtaining the raw external URL configuration

---

application/src/main/java/run/halo/app/content/AbstractContentService.java
application/src/main/java/run/halo/app/theme/router/PreviewRouterFunction.java

此改动为还原 AbstractContentService 的 getContent 逻辑
当将 AbstractContentService 的 getContent 的查询改为 client.get 时会影响到文章 reconciler 的调用导致出错后一直requeue 所以无法完成文章逻辑处理。
reconciler 这里获取 releaseSnapshot 时可能文章还是草稿，所以会导致调用 getContent 时多一次查询，所以最好是后续判断一下，当然这里已经在 getContent 判断了
Fixes #4154
```release-note
None
```

fix: creating a draft cannot be displayed in the post list

---

console/src/components/filter/FilterDropdown.vue
console/src/components/input/SearchInput.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/contents/attachments/AttachmentList.vue
console/src/modules/contents/comments/CommentList.vue
console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/posts/PostList.vue
console/src/modules/system/plugins/PluginList.vue
console/src/modules/system/users/UserList.vue
console/src/setup/setupComponents.ts

/area console
重构 Console 端数据列表的筛选项 UI，并提供全局的筛选列表组件和搜索输入框组件。
> 在此 PR 同时重构了插件列表和用户列表用于验证，其他页面后续提 PR 修改。
重构之后可以获得：
1. 更好的代码组织。
2. 更好的使用体验。
3. UI 更加容易适配移动端。
Fixes #4181 
需要测试：
1. 测试插件管理和用户管理的数据列表筛选和关键词搜索功能是否正常。
```release-note
重构 Console 端数据列表的筛选项 UI，并提供全局的筛选列表组件和搜索输入框组件。
```

refactor: data list filter components

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/contents/comments/CommentList.vue

/area console
重构评论数据管理的筛选条件逻辑以及 UI。
Ref https://github.com/halo-dev/halo/pull/4182
Ref https://github.com/halo-dev/halo/issues/4181
需要测试：
1. 测试评论的筛选条件包括关键词筛选功能是否正常。
```release-note
重构 Console 端评论数据列表的筛选项 UI 和逻辑。
```

refactor: logic of comment data filtering

---

console/docs/components/README.md
console/src/setup/setupComponents.ts

/area console
/kind feature
全局注册 AnnotationsForm 组件，以暴露给插件使用，让插件可以实现为模型设置 annotations 数据的功能。
Fixes #4183 
```release-note
Console 端全局注册 AnnotationsForm 组件，以暴露给插件使用
```

feat: register the AnnotationsForm component globally

---

console/src/modules/system/plugins/PluginDetail.vue
console/src/modules/system/plugins/tabs/Setting.vue
console/src/modules/system/settings/SystemSettings.vue
console/src/modules/system/settings/tabs/Setting.vue

/area console
/kind bug
修复系统设置面板和插件设置面板无法正常显示的问题，此问题由 https://github.com/halo-dev/halo/pull/4102 中升级了 `@vueuse/router` 导致。
Fixes #4221 
需要测试：
1. 测试系统设置能否正常工作。
2. 测试插件的设置能否正常工作。
```release-note
None
```

fix: system settings and plugin settings panels cannot be displayed

---

console/packages/components/src/components/dropdown/DropdownItem.vue
console/src/components/dropdown-selector/EditorProviderSelector.vue
console/src/constants/annotations.ts
console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/pages/components/SinglePageSettingModal.vue
console/src/modules/contents/pages/composables/use-page-update-mutate.ts
console/src/modules/contents/posts/PostEditor.vue
console/src/modules/contents/posts/components/PostSettingModal.vue
console/src/modules/contents/posts/composables/use-post-update-mutate.ts

/area console
/kind feature
支持在编辑文章时切换编辑器，不再限制仅新建时允许切换。但需要注意的是，目前只支持同类型的编辑器切换（rawType）。
Fixes #4176 
测试方式：
1. 安装多个编辑器插件，可以在 https://github.com/halo-sigs/awesome-halo 中查找。
2. 测试在新建文章时是否能够正常切换编辑器。
3. 测试在修改文章时能够正常切换同类型的编辑器。
```release-note
Console 端编辑文章时允许同类型的编辑器切换。
```

feat: allow switching editors while editing a post

---

console/src/formkit/formkit.config.ts
console/src/formkit/inputs/attachment-group-select.ts
console/src/formkit/inputs/attachment-policy-select.ts

/kind feature
/area console
为 formkit 添加一个 `attachmentPolicySelect` 类型的下拉选择框组件，用来供用户选择附件策略。
同时也添加了一个 `attachmentGroupSelect` 类型的下拉选择框组件，用来供用户选择附件分组。
Fixes #4247 
使用 formkit 组件时将 type 修改为 `attachmentPolicySelect` 或 `attachmentGroupSelect`，查看是否能够展示一个可以选择附件策略或附件分组的组件，
```release-note
None
```

feat: add attachment policy and group selection component to formkit

---

console/src/components/filter/UserFilterDropdown.vue
console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/posts/PostEditor.vue

/area console
/kind feature
在页面数据管理列表页面路由中记录查询条件，包括分页信息、筛选信息等。可以保证在刷新浏览器窗口或者从编辑页面返回时保留之前的查询状态。
需要测试：
1. 页面管理列表的所有筛选项是否可以正常工作。
3. 尝试设置部分筛选，然后选择任意一个页面进行编辑，观察发布之后是否正常返回到管理列表，并正确设置了查询参数。
```release-note
Console 端的页面管理列表支持在地址栏记录筛选条件。
```

feat: record the single page query conditions in the route query parameters

---

console/src/components/signup/SignupForm.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/system/users/components/UserCreationModal.vue
console/src/modules/system/users/components/UserPasswordChangeModal.vue

/area console
/kind feature
在 Console 端关于用户密码输入的部分添加基本的验证，目前的规则是：
1. 必填，且不能全为空格符
2. 长度为 5-100
3. 字符串前后不能有空格
Fixes https://github.com/halo-dev/halo/issues/4203
按照以上规则测试即可。
```release-note
Console 端关于用户密码输入的部分添加基本的验证
```

feat: refine validation for password field

---

console/src/modules/contents/posts/PostList.vue

/kind bug
/area console
修复文章状态筛选在刷新页面之后无法回显的问题。
see https://github.com/halo-dev/halo/pull/4219#issuecomment-1641310000
需要测试：
1. 在文章管理页面选择某个状态筛序项，观察数据是否正常。
2. 刷新页面，观察筛选项是否回显。
```release-note
None
```

fix: post status filter item cannot be displayed when the page is refreshed

---

api/src/main/java/run/halo/app/core/extension/attachment/Group.java
application/src/main/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpoint.java
application/src/test/java/run/halo/app/core/extension/attachment/endpoint/AttachmentEndpointTest.java
console/src/modules/contents/attachments/composables/use-attachment-group.ts

/kind feature
/area core
为附件库增加过滤条件，过滤 labels 中包含 `halo.run/hidden` 的分组及其附件。
Fixes #4251 
保证默认情况下附件能够正常访问即可。
或者为分组增加 `halo.run/hidden` label，之后查看接口中是否不包含具有目标分组及其附件。
```release-note
None
```

feat: allow attachment library to filter certain groups and their attachments

---

console/package.json
console/pnpm-lock.yaml

/area console
/kind bug
升级编辑器以修复图片被自动修改尺寸的问题，see https://github.com/halo-sigs/richtext-editor/pull/22
Fixes https://github.com/halo-dev/halo/issues/4215
测试方法可以参考：https://github.com/halo-sigs/richtext-editor/pull/22
```release-note
修复编辑文章时，原来的图片尺寸被自动修改的问题。
```

chore: bump @halo-dev/richtext-editor to fix image size was abnormally modified

---

application/src/main/java/run/halo/app/plugin/extensionpoint/DefaultExtensionGetter.java
application/src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
application/src/main/resources/extensions/extensionpoint-definitions.yaml
application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java

/area core
优化评论扩展点的使用方式
测试评论插件是否正常可用
```release-note
优化评论扩展点的使用方式
```

refactor: optimize the usage of comment widget extension point

---

console/src/modules/contents/comments/CommentList.vue

/area console
/kind feature
在评论数据管理列表页面路由中记录查询条件，包括分页信息、筛选信息等。可以保证在刷新浏览器窗口或者从其他页面返回的时候不丢失筛选条件。
需要测试：
1. 评论管理列表的所有筛选项是否可以正常工作。
```release-note
Console 端的评论管理列表支持在地址栏记录筛选条件。
```

feat: record the comment query conditions in the route query parameters

---

console/src/components/input/SearchInput.vue

/area console
/kind bug
修复在非安全域名下，SearchInput 组件无法正常渲染的问题，因为使用了 crypto 接口来随机生成表单的 id。但 crypto 在非安全域名下无法被调用，参考：https://developer.mozilla.org/en-US/docs/Web/API/Crypto
Fixes https://github.com/halo-dev/halo/issues/4250
```release-note
None
```

fix: search input component cannot be rendered normally under a non-secure domain name

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/main/java/run/halo/app/plugin/DefaultDevelopmentPluginRepository.java
application/src/test/java/run/halo/app/plugin/DefaultDevelopmentPluginRepositoryTest.java

/kind bug
/area core
修复插件被卸载时 delete 生命周期方法不会被触发的问题
1. 测试开发模式下卸载插件，delete 生命周期方法被触发且不会误删项目目录
2. 测试生产模式下插件卸载，文件正确被删除且触发 delete 生命生命周期方法
Fixes #4238
```release-note
修复插件被卸载时 delete 生命周期方法不会被触发的问题
```

fix: plugin delete lifecycle method will not be triggered when the plugin is uninstalled

---

application/src/main/java/run/halo/app/plugin/ExtensionContextRegistry.java
application/src/main/java/run/halo/app/plugin/PluginApplicationEventBridgeDispatcher.java
application/src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
application/src/main/java/run/halo/app/plugin/PluginCompositeRouterFunction.java
application/src/test/java/run/halo/app/plugin/PluginCompositeRouterFunctionTest.java

/area core
/area plugin
修复由于多线程环境下导致的插件卸载时的路由异常问题
改动描述：
为了确保在多线程环境下访问 ExtensionContextRegistry 类的注册表时的线程安全。通过添加读写锁，可以保证在读取和写入PluginApplicationContext 时只有一个线程可以访问，从而避免了多个线程同时访问注册表时可能出现的竞态条件和数据不一致的问题。同时，更新了 register、remove、getByPluginId、containsContext 和 getPluginApplicationContexts 方法，以在访问注册表时获取和释放适当的锁，从而确保了线程安全。
问题原因：
当插件卸载时，卸载动作在 Reconciler 线程中执行而路由访问是在 reactor 的 NonBlockingThread 线程执行，当 PluginCompositeRouterFunction 的 routerFunctions() 方法从 ExtensionContextRegistry 中获取所有 PluginApplicationContext 并持有还未处理完成时由于 PluginReconciler 中执行了卸载插件逻辑而将某个 PluginApplicationContext 关闭从而让 PluginCompositeRouterFunction 中持有到的对象引用发生变化出现数据不一致问题导致出现 `PluginApplicationContext@14971c8e has been closed already` 异常。
解决方案：
所以此修改让读取和写入PluginApplicationContext 时只有一个线程可以访问来解决此问题
how …

refactor: add read-write lock to ExtensionContextRegistry

---

console/src/modules/contents/attachments/AttachmentList.vue

/area console
/kind feature
在附件数据管理列表页面路由中记录查询条件，包括分页信息、筛选信息等。可以保证在刷新浏览器窗口或者从编辑页面返回时保留之前的查询状态。
需要测试：
1. 附件管理列表的所有筛选项是否可以正常工作。
```release-note
Console 端的附件管理列表支持在地址栏记录筛选条件。
```

feat: record the attachment query conditions in the route query parameters

---

console/src/modules/system/users/components/UserEditingModal.vue

/area console
移除用户编辑表单中用户名的校验规则，在这个表单中，用户名本身就是不能修改的，所以不需要验证。移除之后还能够解决旧版本 Halo 升级之后无法修改资料的问题。（旧版本没有用户名校验）
Fixes #4269 
```release-note
移除 Console 端用户编辑表单中用户名的校验规则，防止旧版本 Halo 升级之后无法修改资料。
```

refactor: remove username input validation rule in user editing form

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java

/area core
/area plugin
修复插件启动成功但更新数据失败而导致插件状态不符合预期的问题
1. 安装一个带 console 页面的插件并停用它
2. 使用 IDEA 在 doStart 方法最后更新数据的地方也就是 https://github.com/halo-dev/halo/blob/834e37cf130f2487fab268c9bc7198555933f0dc/application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java#L447 处打断点，suspend 勾选为 Thread
3. 启用插件,会执行到断点处
4. 使用如下命令更新数据将 status 删除以模拟乐观锁冲突并清除 status 状态排除干扰
```shell
curl -u admin:admin -X PUT http://localhost:8090/apis/plugin.halo.run/v1alpha1/plugins/{name} --data '替换为 plugin 的 json '
```
5. 放行端点
根据上述步骤先在 main 分支浮现然后在切换到此 PR 对比结果，期望插件的状态为启动成功且 status 数据示例如下：
conditions 有两条会因为乐观锁更新失败一次且entry和stylesheet都有值
```json
{
"phase": "STARTED",
"conditions": [
{
"type": "STARTED",
"status": "TRUE",
"lastTransitionTime": …
```

fix: inconsistency status occurred during plugin startup due to optimistic locking conflict

---

application/build.gradle

/kind cleanup
/area core
Bump plugin preset. See https://github.com/halo-sigs/plugin-comment-widget/releases/tag/v1.7.0 for more.
```release-note
None
```

Bump plugin preset

---

api/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticationManager.java
application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordAuthenticator.java
application/src/main/java/run/halo/app/security/authentication/login/UsernamePasswordDelegatingAuthenticationManager.java
application/src/main/resources/extensions/extensionpoint-definitions.yaml

/kind feature
/area core
/area plugin
Plugin developers are able to define own UsernamePasswordAuthenticationManager to take charge of username password authentication. 
1. If the manager fails to handle, the default authentication manager will be used.
2. If the manager returns `Mono.empty()`, the default authentication manager will be used.
For example:
```java
@Component
public class LdapAuthenticationManager
extends UserDetailsRepositoryReactiveAuthenticationManager
implements UsernamePasswordAuthenticationManager {
public LdapAuthenticationManager(ReactiveUserDetailsService userDetailsService) {
super(userDetailsService);
}
@Override
protected Mono<UserDetails> retrieveUser(String username) {
return super.retrieveUser(username);
}
}
```
See …

Support extending username password authentication

---

console/packages/components/src/components/dialog/Dialog.vue
console/packages/components/src/components/dialog/interface.ts
console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/posts/PostEditor.vue
console/src/modules/system/backup/tabs/Restore.vue

/area console
为 Dialog 组件添加 showCancel 属性用于控制是否显示取消按钮，某些场景下 Dialog 只是用于提示切必须点击确定。
此外，还对以下位置做了对应修改：
1. 进入文章编辑时检查编辑器是否存在的弹框，只允许点击确定并返回。
2. 备份恢复完成之后点击确定关闭 Halo。
```release-note
Console 端的 Dialog 组件添加 showCancel 属性用于控制是否显示取消按钮。
```

feat: add showCancel prop for dialog component

---

application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
application/src/main/java/run/halo/app/core/extension/reconciler/UserReconciler.java

/kind bug
/area core
解决 #4253  所导致的用户旧头像被删除的问题。
1. 使用 2.7.x 之前的 Halo 版本，新建用户并设置其头像。
2. 升级 Halo 至 2.8.0-rc.1 
3. 头像还存在即可。
4. 测试头像上传、移除功能是否正常可用。
```release-note
None
```

fix: resolve the issue of missing old avatar

---

console/src/components/common/AppDownloadAlert.vue
console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/interface/themes/components/ThemeUploadModal.vue
console/src/modules/system/plugins/components/PluginUploadModal.vue

/area console
在安装主题和插件的界面中添加下载源的提示。
Fixes https://github.com/halo-dev/halo/issues/4307
```release-note
在安装主题和插件的界面中添加下载源的提示。
```

feat: add download tips in plugin and theme installation modal

---

console/src/modules/system/users/layouts/UserProfileLayout.vue

/area console
/kind bug
修复用户详情页面切换用户之后，数据不更新的问题。操作路径：
1. 进入任意一个用户的资料页面。
2. 点击左下角当前登录用户的个人资料。
Fixes https://github.com/halo-dev/halo/issues/4320
```release-note
修复用户详情页面切换用户之后，数据不更新的问题。
```

fix: user detail page switching does not take effect

---

application/src/main/java/run/halo/app/infra/exception/NotFoundException.java
application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
application/src/main/resources/config/i18n/messages.properties
application/src/main/resources/config/i18n/messages_zh.properties
application/src/test/java/run/halo/app/migration/impl/MigrationServiceImplTest.java

/kind bug
/area core
Currently, we have not process the deletion of backup files when downloading theme. This PR will handle the situation.
Please see the example result:
```bash
curl -s -u admin:admin -H "Accept-Language: zh" http://localhost:8090/apis/api.console.migration.halo.run/v1alpha1/backups/backup-waELO/files/20230725225726-backup-waELO.zip | jq .
{
"type": "about:blank",
"title": "资源不存在",
"status": 404,
"detail": "备份文件不存在或已删除。",
"instance": "http://localhost:8090/apis/api.console.migration.halo.run/v1alpha1/backups/backup-waELO/files/20230725225726-backup-waELO.zip",
"requestId": "8654fdc6-1478",
"timestamp": "2023-07-25T15:26:56.771260Z"
}
```
```bash
curl -s -u admin:admin -H "Accept-Language: en" http://localhost:8090/apis/api.console.migration.halo.run/v1alp …
```

Add error prompt when downloading backup files that do not exist

---

application/src/main/java/run/halo/app/theme/router/SinglePageRoute.java
application/src/test/java/run/halo/app/theme/router/SinglePageRouteTest.java

/kind bug
/area core
- Remove route when single pages become unpublished
- Add some unit tests against the change.
Fixes https://github.com/halo-dev/halo/issues/4309
1. Create a single page with slug name `about.html` and publish it.
2. Create a static file `about.html` into static folder`${halo.work-dir}/static/`.
3. Try to request <http://localhost:8090/about.html> and check the result.
4. Unpublish the single page and then do the step 3 again.
```release-note
修复页面取消发布后访问仍然出现页面未找到错误。
```

Remove route when single pages become unpublished

---

console/src/composables/use-content-cache.ts
console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/posts/PostEditor.vue

/area console
/kind bug
修复新建文章发布或者保存之后，浏览器中的内容缓存没有清空的问题。
Fixes #4310 
需要测试：
1. 新建一篇文章，测试未保存到服务器时，刷新浏览器，观察内容是否还存在。
2. 保存之后，再次新建文章，观察编辑器是否没有内容。
```release-note
修复新建文章发布或者保存之后，浏览器中的内容缓存没有清空的问题。
```

fix: content cache was not cleaned up after the new post was saved

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/system/backup/tabs/List.vue

/area console
移除备份列表空状态的创建备份按钮，防止出现多个创建的按钮。
```release-note
None 
```

refactor: remove the duplicate button to create a backup

---

console/src/modules/contents/attachments/composables/use-attachment.ts

/kind bug
/area console
修复在最后一个附件点击 "下一个" 时, 附件库内容全部消失或得到一个 "空" 附件, 且不能 "往前"
Fixes #4326
1. 上传附件
2. 一直点击 "下一个" 直到最后一张
3. 在最后一张再点击下一个, 观察页面是否出现异常, 正常情况下会停在最后一个附件上且页面不会有刷新
```release-note
修复 Console 端在最后一个附件点击下一项按钮时得到空结果的问题。
```

fix: click "next" on the last attachment will get null

---

console/src/modules/contents/attachments/composables/use-attachment.ts

/kind bug
/area console
在预览附件时点击 "下一个" 或者 "上一个", 如果这时翻页, 预览页面可能不会刷新, 也可能刷新到其他非预料中的页面
Fixes #4330
1. 准备附件测试翻页
2. 在第一页的最后一个附件预览中点击 "next", 观察是否正常
3. 在第二页的第一个附件预览中点击 "pre", 观察是否正常
```release-note
预览附件点击 "下一个" 或者 "上一个" 翻页后, 预览页面不正常刷新
```

fix: page does not refresh or get wrong page when turn page

---

console/src/modules/system/roles/RoleList.vue

/area console
/kind bug
修复创建角色时，如果基于某个角色创建，实际权限可能不会更新的问题。
需要测试：
1. 基于超级管理员创建新角色。
2. 取消勾选一些角色模板。
3. 测试此角色是否存在取消了勾选的角色模板。
```release-note
修复创建角色时，如果基于某个角色创建，实际权限可能不会更新的问题。
```

fix: not reset permission after cloning a role

---

console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json

/kind cleanup
修改 Console 以及其下 packages 的版本号，发布 Halo 2.8
```release-note
None
```

chore: bump console version to prepare release 2.8

---

console/src/modules/system/users/UserList.vue

/kind bug
/area console
在用户列表中，禁止用户选中自己，以解决用户能够进行视觉上自我删除的 bug。
Fixes #4350 
```release-note
在用户列表中禁用选中当前用户
```

fix: resolve the issue of users being able to delete themselves.

---

application/src/main/resources/application-dev.yaml
platform/application/build.gradle

/kind cleanup
This PR upgrades SpringDoc to 2.2.0 for OpenAPI 3.1 support. Please see https://github.com/springdoc/springdoc-openapi/releases/tag/v2.2.0 for more.
- Start Halo by using following command:
```bash
./gradlew bootRun --args="--spring.profiles.active=dev --halo.plugin.runtime-mode=deployment"
```
- Try to request <http://localhost:8090/swagger-ui.html> and check if the OpenAPI version is 3.1
```release-note
升级 SpringDoc 至 2.2.0
```

Upgrade to SpringDoc 2.2.0 for OpenAPI 3.1 support

---

console/src/components/form/AnnotationsForm.vue

/kind bug
/area console
在 AnnotationsForm 新增 customAnnotationsDuplicateKey 校验规则，校验自定义元数据中是否具有重复的 key。
Fixes #4367 
在任意一个使用 AnnotationsForm 的位置，例如`文章设置 - 元数据` 中，新增一个已经存在的 key，查看是否有重复 key 的校验。
```release-note
修复 AnnotationsForm 重复的 key 校验无效的问题。
```

fix: resolve the issue of ineffective duplicate key validation in AnnotationsForm

---

application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
application/src/main/java/run/halo/app/core/extension/theme/ThemeEndpoint.java
application/src/main/java/run/halo/app/core/extension/theme/ThemeService.java
application/src/main/java/run/halo/app/core/extension/theme/ThemeServiceImpl.java
application/src/main/java/run/halo/app/core/extension/theme/ThemeUtils.java
application/src/main/java/run/halo/app/infra/DefaultThemeInitializer.java
application/src/main/java/run/halo/app/infra/utils/DataBufferUtils.java
application/src/main/java/run/halo/app/infra/utils/FileUtils.java
application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
application/src/test/java/run/halo/app/core/extension/theme/ThemeEndpointTest.java
application/src/test/java/run/halo/app/core/extension/theme/ThemeServiceImplTest.java

/kind cleanup
/area core
Before this, If we use a file with length less than 256KB for recovery, the process remains stagnant until we cancel the request.
This PR refactors the transformation between data buffers and input stream and resolve the issue above. We should avoid returning InputStream directly in reactive stream.
- DataBufferUtils before
```java
public static InputStream toInputStream(Flux<DataBuffer> content) throws IOException {
var pos = new PipedOutputStream();
var pis = new PipedInputStream(pos);
write(content, pos)
.doOnComplete(() -> {
try {
pos.close();
} catch (IOException ignored) {
// Ignore the error
}
})
.subscribeOn(Schedulers.boundedElastic())
.subscribe(releaseConsumer(), error -> {
if (error instanceof IOException) {
// Ignore the error
return; …
```

Refactor the transformation between data buffers and input stream

---

api/src/main/java/run/halo/app/infra/BackupRootGetter.java
application/src/main/java/run/halo/app/infra/DefaultBackupRootGetter.java
application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
application/src/main/java/run/halo/app/plugin/SharedApplicationContextHolder.java
application/src/test/java/run/halo/app/infra/DefaultBackupRootGetterTest.java
application/src/test/java/run/halo/app/migration/impl/MigrationServiceImplTest.java

/kind feature
/area core
We already support backup and restore feature in Halo 2.8.0, but we cannot obtain backup files through regular channels in the plugin. For example, we want to upload backup files to OSS in the plugin.
This PR is aimed at solving this problem.
```release-note
支持在插件中获取备份文件根目录。
```

Support getting backup root path in plugin

---

console/src/components/form/AnnotationsForm.vue

由于后端 annotation 的值可以为空，而前端则规定 annotation 值为必填项，因此去除前端必填属性。
Fixes #4279 
```release-note
将元数据值更改为非必填
```

pref: allow annotations value to be empty

---

console/src/components/upload/UppyUpload.vue

/kind bug
/area console
原先使用 uppy 上传文件时抛出异常时，处理了 Halo 系统内部异常，但并未处理外部抛出的异常，例如反向代理等，因而会导致上传文件时卡在 0% 或者 100%。
更改之后当上传抛出异常时，首先会尝试将异常信息转换为 JSON，如果转换失败，则代表为外部异常，此时会抛出异常信息，异常信息格式为 `status: statusText`。
在 Halo 上传接口前增加一层反向代理，并设置最大允许文件值，之后上传超过其值的文件进行尝试，若能够成功抛出异常即可。
Fixes #4359 
```release-note
修复上传文件时由于外部异常而导致进度条不变的问题
```

fix: handle external exceptions when uploading files

---

application/src/main/java/run/halo/app/theme/dialect/CommentElementTagProcessor.java
application/src/main/java/run/halo/app/theme/dialect/CommentEnabledVariableProcessor.java
application/src/main/java/run/halo/app/theme/dialect/HaloProcessorDialect.java
application/src/test/java/run/halo/app/theme/ReactiveFinderExpressionParserTests.java
application/src/test/java/run/halo/app/theme/dialect/CommentElementTagProcessorTest.java
application/src/test/java/run/halo/app/theme/dialect/CommentEnabledVariableProcessorTest.java
application/src/test/java/run/halo/app/theme/dialect/ContentTemplateHeadProcessorIntegrationTest.java
application/src/test/java/run/halo/app/theme/dialect/HaloProcessorDialectTest.java

/kind bug
/area core
修复评论启用状态的主题模板变量名作用域不正确的问题
评论组件标签处理器只会在处理到 `<halo:comment/>` 自定义标签时被执行，而 haloCommentEnabled 状态是评论标签之前使用的那么此时值还没有被评论标签处理器填充所以取不到正确的值，目前的做法是在模板开始解析时填充 haloCommentEnabled 变量到 context，但这样存在的问题时无法判断页面是否使用了评论自定义标签即每个页面都会有这个变量，不过目前没有更好的办法去解决这样的问题。
how to test it？
在模板页面的任意位置使用 `${haloCommentEnabled}` 都能取到正确的值。
Fixes #4378
```release-note
修复评论启用状态的主题模板变量名作用域不正确的问题
```

fix: incorrect scope for haloCommentEnabled template variable

---

console/src/formkit/formkit.config.ts
console/src/formkit/inputs/password/RevealButton.vue
console/src/formkit/inputs/password/index.ts
console/src/styles/index.css

/area console
/kind feature
为 FormKit 的 password 类型输入框添加统一的显示/隐藏明文按钮。
Fixes #4382 
测试密码输入框的显示隐藏明文按钮是否可以正常使用即可。
```release-note
为 FormKit 的 password 类型输入框添加统一的显示/隐藏明文按钮。
```

feat: add reveal button for password input

---

console/src/components/editor/DefaultEditor.vue

A function to debounce editor updates was added to the DefaultEditor.vue component. This change was necessary to prevent excessive event executions. Now, 'update:raw', 'update:content', and 'update' events will be emitted 250ms after the last update, reducing the number of redundant operations and increasing the editor's performance.
目前默认编辑器在文章内容过多时，会出现输入延迟。
Fixes #4389
```release-note
增强默认编辑器在文章内容过大时的性能。
```

perf: increasing the editor performance

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java

/kind bug
/area core
修复从插件管理器中获取已启动插件的记录不正确的问题
由于 PR #4403 优化了 plugin extension 的 status 与内存状态的同步方式，优先级改为以数据库为准但这样状态维护变得复杂，所以此 PR 还是以内存为准但不同的是：
1. 当状态不一致时在 reconciler 中先将数据库的和内存状态都统一为停止状态即调用 haloPluginManager.stopPlugin 然后将停止状态更新到 status 的 phase 上，在继续后续的逻辑
2. 如果在更新 status 失败时加上重试避免因乐观锁而容易导致插件启动或停止成功但 status 更新失败导致的不一致几率问题。
经过上述两点的双重保障，多次测试后暂没有发现状态不一致的场景
1. 多安装几个插件十个以上最好，测试启动后通过 HaloPluginManager 获取已启动插件名称是否与 Console 已启动插件列表一致
```java
haloPluginManager.getStartedPlugins()
```
2. 对于提供了 console 功能的插件不会出现启动成功但 status 的 entry 为空的情况
```release-note
None
```

fix: incorrect started plugin records obtained from plugin manager

---

application/src/main/java/run/halo/app/migration/impl/MigrationServiceImpl.java
application/src/test/java/run/halo/app/migration/impl/MigrationServiceImplTest.java

/kind bug
/area core
Before this, if we deleted a backup without filename, the BackupReconciler would get stuck infinitely. And no further backups would be reconciled.
This PR fixes the problem that it is always in deleting phase after deleting backups.
```release-note
修复因备份数据状态不正常导致无法正常删除备份的问题。
```

Fix the problem that it is always in deleting phase after deleting backups

---

console/src/modules/contents/comments/CommentList.vue

/kind bug
/area console
Console 评论列表中，使用用户名查询时携带 kind
在 Console 端评论列表，选中右上角评论者，进行选择。
Fixes #4465 
```release-note
解决评论列表根据评论者条件筛选时为空的问题
```

fix: the search for comments by username yields empty results

---

console/packages/components/src/components/tabs/Tabbar.vue

/area console
/kind feature
Console 端的 Tabs 组件支持通过鼠标滚动选项卡。
Fixes #4353 
None
```release-note
Console 端的 Tabs 组件支持通过鼠标滚动选项卡。
```

feat: add mouse scrolling handler for tabs component

---

console/docs/extension-points/entity-listitem-operation.md
console/packages/shared/src/index.ts
console/packages/shared/src/states/entity.ts
console/packages/shared/src/types/plugin.ts
console/src/components/entity/EntityDropdownItems.vue
console/src/composables/use-entity-extension-points.ts
console/src/modules/contents/posts/components/PostListItem.vue
console/src/modules/system/plugins/components/PluginListItem.vue

/area console
/kind feature
添加扩展数据列表中操作按钮列表的基础能力，并为文章和插件管理列表的操作按钮列表添加扩展点以测试此扩展能力。
todo:
Ref https://github.com/halo-dev/halo/issues/4177
可以使用以下插件进行测试：
- 源码：[plugin-export-md.zip](https://github.com/halo-dev/halo/files/12436956/plugin-export-md.zip)
- 可安装的 JAR 包：[plugin-export-md-1.0.0-SNAPSHOT.jar.zip](https://github.com/halo-dev/halo/files/12436950/plugin-export-md-1.0.0-SNAPSHOT.jar.zip)
安装之后可以在文章列表的操作按钮列表中新增一个 `导出为 Markdown 文档` 的按钮，点击之后会导出一个 Markdown 文档。
```release-note
Console 端的文章和插件列表的操作按钮列表支持扩展。
```

feat: add extension point for extend data list operation items

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/system/plugins/components/PluginListItem.vue
console/src/modules/system/plugins/composables/use-plugin.ts

/area console
移除启动/停止插件的确认弹框。
Fixes #4471 
测试启动和停止插件是否正常工作即可。
```release-note
移除 Console 端启动/停止插件的确认弹框。
```

refactor: remove the confirmation box of the enable/disable plugin

---

console/src/locales/en.yaml
console/src/locales/zh-CN.yaml
console/src/locales/zh-TW.yaml
console/src/modules/contents/posts/widgets/RecentPublishedWidget.vue

/kind bug
/area console
文章标题过长时，面板“最近文章”会存在日期显示不完整
Fixes https://github.com/halo-dev/halo/issues/4304
目前我的解决方案是将Entity加上一个flex-wrap，这样可以保证日期显示完整，但是这可能导致上下文章的布局结构不统一。不知是否可以采纳。
```release-note
用户在仪表板页面为`最近文章`设置的宽度不够时，可以显示创建日期
```

fix: style issue of post widget when post title is too long

---

application/src/main/java/run/halo/app/core/extension/endpoint/UserEndpoint.java
application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointIntegrationTest.java
application/src/test/java/run/halo/app/core/extension/endpoint/UserEndpointTest.java

/area core
用户列表搜索支持按用户名搜索
Fixes #4256 
```release-note
用户列表搜索支持按用户名搜索
```

pref: user list supports searching by username

---

application/src/main/java/run/halo/app/migration/MigrationEndpoint.java
console/packages/api-client/src/api/api-console-halo-run-v1alpha1-plugin-api.ts
console/packages/api-client/src/api/api-console-halo-run-v1alpha1-theme-api.ts
console/packages/api-client/src/api/api-console-migration-halo-run-v1alpha1-migration-api.ts

/kind feature
/area core
Currently, we only support restoring by uploading backup file. Downloading and uploading larger backup files can be cumbersome for users.
This PR supports restoring with downloadable URL or backup name as well.
```bash
curl -u admin:admin 'http://localhost:8090/apis/api.console.migration.halo.run/v1alpha1/restorations' \
-H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary3Al7pC6AbBNfB1js' \
--data-raw $'------WebKitFormBoundary3Al7pC6AbBNfB1js\r\nContent-Disposition: form-data; name="backupName"\r\n\r\n${BACKUP_NAME}\r\n------WebKitFormBoundary3Al7pC6AbBNfB1js--\r\n'
```
```bash
curl -u admin:admin 'http://localhost:8090/apis/api.console.migration.halo.run/v1alpha1/restorations' \
-H 'Content-Type: multipart/form-data; …
```

Support restoring with downloadable URL or backup name

---

console/src/views/system/SetupInitialData.vue

/area console
/kind bug
修复因为初始化数据异常导致没有记录初始化状态的问题，这个问题可能会导致失败之后无法再让系统正常访问。
```release-note
None
```

fix: setup state is not set due to an exception when initializing the data

---

api/build.gradle
application/src/main/java/run/halo/app/search/post/LucenePostSearchService.java
platform/application/build.gradle

/area core
- Removes dependency `cn.shenyanchao.ik-analyzer:ik-analyzer:9.0.0` due to no significant effect for searching result.
- Customize our own analyzer with StandardTokenizer, HTMLStripCharFilter and LowerCaseFilterFactory.
Please be aware of that the default field to search has become to `content` instead of `title` + `excerpt` + `content`. If someone wants to search title only, use `title: halo` as query string. For more details, please refer to <https://lucene.apache.org/core/9_5_0/queryparser/org/apache/lucene/queryparser/flexible/standard/StandardQueryParser.html>.
Fixes https://github.com/halo-dev/halo/issues/4455
```release-note
优化本地搜索引擎
```

Refine search result by customizing analyzer

---

console/package.json
console/pnpm-lock.yaml
console/src/components/editor/DefaultEditor.vue

/area console
/kind cleanup
升级默认编辑器的版本，包含以下修改：
1. 图片支持修改 alt 属性。 https://github.com/halo-sigs/richtext-editor/pull/32
2. 拖拽修改图片大小的时候保持等比例。 https://github.com/halo-sigs/richtext-editor/pull/33
3. 优化在移动端下，编辑器右侧边栏的样式。 https://github.com/halo-sigs/richtext-editor/pull/35
4. 编辑器标题、段落及代码块增加 Tab 快捷键缩进。 https://github.com/halo-sigs/richtext-editor/pull/34
```release-note
升级默认编辑器的版本，包含以下更改：
1. 图片支持修改 alt 属性。 by @GodlessLiu in <https://github.com/halo-sigs/richtext-editor/pull/32>
2. 拖拽修改图片大小的时候保持等比例。 by @GodlessLiu in <https://github.com/halo-sigs/richtext-editor/pull/33>
3. 优化在移动端下，编辑器右侧边栏的样式。 by @ruibaby in <https://github.com/halo-sigs/richtext-editor/pull/35>
4. 编辑器标题、段落及代码块增加 Tab 快捷键缩进。 by @LIlGG in <https://github.com/halo-sigs/richtext-editor/pull/34>
```

chore: bump @halo-dev/richtext-editor version to alpha.30

---

console/src/composables/use-auto-save-content.ts
console/src/composables/use-content-cache.ts
console/src/composables/use-content-snapshot.ts
console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/posts/PostEditor.vue

本 PR 优化了文章、内容编辑时的本地缓存功能，之前内容对于本地缓存的依赖性非常强，因此导致了部分问题，如 #3820 ，本 PR 计划之后本地缓存将仅用于特殊情况下的内容恢复，因此尝试做了如下修改：
1. 当前正在编辑的文章，会在正常模式（切换路由、刷新页面、失去当前窗口焦点、停止编写一定时间均属于正常模式）下进行自动保存后删除本地缓存。
2. 若本地具有缓存，则会在进入编辑页面时，比对一次 content 的 version，若缓存 version 小于线上 version，则抛弃缓存，若一致，则使用缓存。
但经过测试，本 PR 无法解决如下问题：
1. 同时编辑一篇文章时，内容会被覆盖的问题。
2. 对比版本后会抛弃缓存，而实际上应当将本地缓存加入历史版本中。
1. 新建一篇文章，编写任意内容，返回文章页查看是否已经具有新的文章，且内容已被保存。
2. 修改一篇文章的内容，然后返回文章页，查看是否不是从缓存中加载。
3. 断网模式下修改一篇文章的内容，然后返回文章页，联网后，再次打开此文章，查看是否显示从缓存中加载。
4. 断网模式下修改一篇文章的内容，然后返回文章页。在另一个浏览器或页面修改此文章并保存后，回到断网页面联网后，查看是否更新为最新内容。
Fixes #3820 
Fixes #4223 
```release-note
减少内容编辑对本地缓存依赖，支持内容自动保存至服务端。
```

pref: optimize the caching functionality of content editing

---

console/src/modules/system/plugins/PluginList.vue

/area console
在 https://github.com/halo-dev/halo/pull/4473 中移除了插件管理的分页功能，但可能会造成列表底部看起来不协调，所以恢复总条数的文字显示。
Fixes #4498 
```release-note
None 
```

feat: display total items text for plugins list

---

console/docs/extension-points/entity-listitem-operation.md
console/packages/shared/src/types/plugin.ts
console/src/modules/system/backup/components/BackupListItem.vue

/area console
/kind feature
备份列表的操作列表支持被插件扩展。
```release-note
Console 端的备份列表的操作按钮列表支持扩展。
```

feat: make backup list item operations extendable

---

console/src/composables/use-auto-save-content.ts

/kind bug
/area console
更改自动保存的策略，仅当内容具有缓存时才会执行自动保存。
新建/更新一篇文章之后，点击发布，查看是否还存在“文章已保存但未发布” 的提示
Fixes #4499 
```release-note
修复文章发布后，文章列表显示未发布的问题。
```

fix: resolve the display bug after publishing content

---

console/src/modules/contents/comments/CommentList.vue

/kind bug
/area console
解决评论管理中，根据是否已审核状态的筛选无效的问题
在评论列表上切换审核状态，查看是否有效。
Fixes #4494 
```release-note
修复评论管理中审核状态筛选无效的问题
```

fix: approved filter in comment management is ineffective

---

console/packages/components/src/components/tabs/Tabbar.vue

/kind bug
/area console
修复 Console 端 Tabbar 组件默认类型的样式问题。
before:
after:
```release-note
修复 Console 端 Tabbar 组件默认类型的样式问题。
```

fix: style issue of tabbar component of default type

---

application/src/main/java/run/halo/app/extension/gc/GcReconciler.java
application/src/main/java/run/halo/app/extension/gc/GcSynchronizer.java
application/src/test/java/run/halo/app/extension/gc/GcSynchronizerTest.java

/kind bug
/area core
As I mentioned in <https://github.com/halo-dev/halo/issues/4519>, some extensions which are deletable cannot be recycled by GC. This PR provides an ability to watch scheme changes and recycles deletable extensions.
Fixes https://github.com/halo-dev/halo/issues/4519
```release-note
修复因重启后部分可被回收的资源一直处于删除中的状态
```

Fix the problem that deletable extensions created by plugins cannot be recycled 

---

console/docs/extension-points/entity-listitem-operation.md
console/packages/shared/src/types/plugin.ts
console/src/modules/interface/themes/components/ThemeListItem.vue
console/src/modules/interface/themes/components/operation/UninstallOperationItem.vue

/area console
/kind feature
主题管理列表项的操作按钮支持被插件扩展。
Fixes #4522 
测试已有的操作按钮功能正常即可。
```release-note
Console 主题管理列表项的操作按钮支持被插件扩展。
```

feat: make theme list item operations extendable

---

console/docs/extension-points/entity-listitem-field.md
console/docs/extension-points/entity-listitem-operation.md
console/packages/shared/src/index.ts
console/packages/shared/src/states/operation.ts
console/packages/shared/src/types/plugin.ts
console/src/components/entity-fields/EntityFieldItems.vue
console/src/components/entity/EntityDropdownItems.vue
console/src/composables/use-entity-extension-points.ts
console/src/composables/use-operation-extension-points.ts
console/src/modules/contents/posts/components/PostListItem.vue
console/src/modules/interface/themes/components/ThemeListItem.vue
console/src/modules/system/backup/components/BackupListItem.vue
console/src/modules/system/plugins/components/PluginListItem.vue

/area console
重构数据列表操作项和显示字段扩展点的类型定义和条件判断：
1. `EntityDropdownItem` 改为 `OperationItem` 以适配不同的场景，最开始仅仅是为了提供给 Entity 组件，但后面发现如主题管理列表并没有使用 Entity 组件，所以定义统一改为 Operation 。
2. 修改 `OperationItem` 和 `EntityFieldItem` 的 `visible` 字段为 `hidden`，方便渲染的时候判断，并方便调用方默认不设置值。
```release-note
None
```

refactor: operation and entity field extension points

---

.github/workflows/halo.yaml

/kind cleanup
/area core
Adapt GitHub workflow for branch release-2.9.
```release-note
None
```

[release-2.9] Adapt GitHub workflow for branch release-2.9

---

console/src/modules/system/plugins/composables/use-plugin.ts

/area console
支持在启动插件之后检测插件的启动状态，防止直接刷新之后 bundle.js 的内容没有及时更新。
```release-note
优化 Console 端启动插件的逻辑
```

feat: add supports for check started status after start plugin operation

---

console/src/modules/interface/themes/components/ThemeListItem.vue
console/src/modules/interface/themes/components/list-tabs/InstalledThemes.vue
console/src/modules/interface/themes/components/operation/MoreOperationItem.vue

/area console
/kind bug
修复主题管理列表的更多操作项在某些情况下无法打开的问题。
Fixes https://github.com/halo-dev/halo/issues/4559
测试方式：
1. 安装若干主题，测试每一项主题的更多操作按钮是否可以正常打开。
2. 删除某一个主题，测试每一项主题的更多操作按钮是否可以正常打开。
```release-note
修复 Console 端主题管理列表的更多操作项在某些情况下无法打开的问题。
```

fix: operation items render issue in theme list

---

application/src/main/java/run/halo/app/security/DefaultUserDetailService.java

/kind bug
/area core
This PR fixes the problem of username being case-insensitive and logging in without permissions. Please note that the problem only occurs with MySQL.
Fixes https://github.com/halo-dev/halo/issues/4549
```bash
docker run -it --rm --name halodb -p 3306:3306 -e MYSQL_ROOT_PASSWORD=openmysql -e MYSQL_DATABASE=halo mysql:8
./gradlew bootRun --args="--spring.profiles.active=dev,mysql --halo.plugin.runtime-mode=deployment"
```
```release-note
修复因大小写问题导致登录后无权限的问题
```

Fix the problem of username being case-insensitive and logging in without permissions

---

application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java

/area core
为插件捆绑资源设置 cache-control 以优化静态资源加载
如获取插件 bundle.js 会自动携带参数缓存时间为 7 天，当有插件停止或新增时 v 参数会变化浏览器则使用新的 key 缓存静态资源，旧的 key 将在一天内失效
```
/apis/api.console.halo.run/v1alpha1/plugins/-/bundle.js?v=6c5956f37e7207ab1c0f2f2340f51a101f46b748233992d73729415cd58f3587
```
Fixes #4543
```release-note
为插件捆绑资源设置 cache-control 以优化静态资源加载
```

refactor: set cache-control for bundle resources of plugin

---

console/src/modules/contents/pages/SinglePageEditor.vue
console/src/modules/contents/posts/PostEditor.vue

/area console
当设置模态框打开时，禁用自动保存功能。
1. 新建一篇文章，随意输入内容。
2. 打开保存或发布表单，填写文章标题等内容
3. 切换至其他 tab 页
4. 再切换回来，查看文章标题是否没有被覆盖。
Fixes #4566 
```release-note
当文章或页面设置窗口打开时，禁用自动保存功能。
```

pref: do not auto save when the setting modal is open

---

application/src/main/java/run/halo/app/config/WebServerSecurityConfig.java
application/src/main/java/run/halo/app/security/DefaultServerAuthenticationEntryPoint.java
application/src/test/java/run/halo/app/security/DefaultServerAuthenticationEntryPointTest.java

/area core
See https://github.com/halo-dev/halo/issues/4547 for more.
This PR creates header `WWW-Authenticate` like `FormLogin realm="console"` instead of `Basic realm="realm"` while unauthorized.
Fixes https://github.com/halo-dev/halo/issues/4547
```bash
curl --head 'http://localhost:8090/actuator/info'
HTTP/1.1 401 Unauthorized
transfer-encoding: chunked
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
WWW-Authenticate: FormLogin realm="console"
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 0
Referrer-Policy: no-referrer
```
```release-note
防止浏览器弹出基础认证弹窗
```

Prevent basic authentication from popping up

---

console/src/locales/en.yaml

/area console
/kind bug
修复了主题远程下载标签的英文语言包键，使其可以正确显示标签标题。
```release-note
修复 Console 端主题远程下载标签的英文语言包键名，使其可以正确显示标签标题。
```

fix: i18n key of theme remote download tab label

---

console/src/components/input/SearchInput.vue
console/src/modules/contents/attachments/AttachmentList.vue
console/src/modules/contents/comments/CommentList.vue
console/src/modules/contents/pages/DeletedSinglePageList.vue
console/src/modules/contents/pages/SinglePageList.vue
console/src/modules/contents/posts/DeletedPostList.vue
console/src/modules/contents/posts/PostList.vue
console/src/modules/system/plugins/PluginList.vue
console/src/modules/system/users/UserList.vue

/area console
改进移动设备上数据列表过滤器区域的样式。
before:
after:
Ref https://github.com/halo-dev/halo/issues/2699
```release-note
改进 Console 端在移动设备上数据列表过滤器区域的样式。
```

feat: improve the styles of the data list filter area on the mobile devices

---

application/build.gradle

/area core
/kind cleanup
修改预设插件的下载地址，目前四个预设插件的仓库都已经转移到 halo-dev 组织。
需要测试 `./gradlew downloadPluginPresets` 是否能够正常下载预设插件。 
```release-note
None
```

chore: update download url of presets plugin

---

console/src/modules/interface/menus/Menus.vue
console/src/modules/interface/menus/components/MenuList.vue

/area console
/kind bug
修复菜单管理页面，切换菜单时请求两次菜单项接口的问题。
Fixes https://github.com/halo-dev/halo/issues/4578
测试切换菜单，观察浏览器控制台是否有两次请求即可。
```release-note
修复 Console 的菜单管理页面，切换菜单时请求两次菜单项接口的问题。
```

fix: twice requests in menus page

---

console/src/modules/interface/themes/components/ThemeListModal.vue
console/src/modules/system/plugins/components/PluginInstallationModal.vue

/area console
/kind bug
修复主题管理选项卡和插件安装界面选项卡扩展点没有添加 UI 权限检测的问题。
Fixes #4632 
```release-note
None
```

fix: missing permission check in plugin installation tabs and theme list tabs extension points

---

application/src/main/java/run/halo/app/theme/router/ViewNameResolver.java
application/src/test/java/run/halo/app/theme/router/ViewNameResolverTest.java

/kind bug
/area core
修复文章自定义模板不存在时没有使用默认模板的问题
see #4617 for more details.
Fixes #4617
```release-note
修复文章自定义模板不存在时没有使用默认模板的问题
```

fix: not using the default template when the custom template does not exist

---

application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java

/kind bug
/area core
/area plugin
修复当插件升级后 Logo 改变会无法显示的问题
1. 使用生产模式运行插件
2. 使用 sitemap 插件 1.0.1版本,https://www.halo.run/store/apps/app-QDFMI?tab=releases
3. 升级 sitemap 插件到 1.1.0, https://www.halo.run/store/apps/app-QDFMI?tab=releases
4. 期望 logo 由原先的 halo 图标变为新图标
Fixes #4646
```release-note
修复当插件升级后 Logo 改变会无法显示的问题
```

fix: unable to display if the logo changes after the plugin upgrade

---

console/src/formkit/inputs/category-select/index.ts
console/src/formkit/inputs/tag-select/index.ts

/kind bug
/area console
修复菜单项编辑表单中，切换分类和标签类型可能导致分类或者标签选择框异常的问题。
Fixes #4643 
测试方式：
1. 新建菜单项，先选择分类或者标签，然后选择另外一个类型，观察选择框是否正常。
```release-note
修复 Console 端菜单项编辑表单中可能无法正常切换类型的问题。
```

fix: can not change ref type in menu item modal

---

console/src/formkit/inputs/category-select/CategorySelect.vue

/area console
/kind bug
修复在分类选择组件中，无法通过点击创建分类的问题。
Fixes #4606 
在任意一个分类选择组件输入一个不存在的分类，根据提示点击创建，观察是否创建成功即可。
```release-note
修复 Console 端的分类选择组件中，无法通过点击创建不存在的分类的问题。
```

fix: can not create category by click in category select component

---

api/src/main/java/run/halo/app/plugin/BasePlugin.java
api/src/main/java/run/halo/app/plugin/PluginContext.java
application/src/main/java/run/halo/app/core/extension/reconciler/PluginReconciler.java
application/src/main/java/run/halo/app/plugin/BasePluginFactory.java
application/src/main/java/run/halo/app/plugin/HaloPluginManager.java
application/src/main/java/run/halo/app/plugin/HaloPluginWrapper.java
application/src/main/java/run/halo/app/plugin/PluginApplicationInitializer.java
application/src/main/java/run/halo/app/plugin/PluginAutoConfiguration.java
application/src/main/java/run/halo/app/plugin/SpringExtensionFactory.java
application/src/test/java/run/halo/app/core/extension/reconciler/PluginReconcilerTest.java

/kind feature
/area core
支持在开发模式下通过 JAR 运行插件
*从此版本开始 BasePlugin 的子类建议使用 BasePlugin(PluginContext context) 构造函数，而不要使用之前的 BasePlugin(PluginWrapper wrapper) 构造函数。BasePlugin(PluginWrapper wrapper) 构造函数将计划在后续版本移除* ，当移除构造函数后不再将 PluginWrapper 暴露给插件使用，它只应该在 halo core 使用。
1. 测试开发模式下配置的 `halo.plugin.fixed-plugin-path` 插件是否正确运行
2. 测试开发模式下通过 JAR 包安装插件是否正确运行
3. 测试生产模式下是否能通过项目目录的方式运行插件，期望是生产模式不可以运行开发模式的插件
4. 测试开发模式和生产模式的插件卸载功能是否正确
Fixes #2908
```release-note
支持在开发模式下通过 JAR 运行插件
```

feat: support running plugins from JAR in development mode

---

application/src/main/java/run/halo/app/search/post/LucenePostSearchService.java

/kind bug
/area core
Lucene search engine will stop updating while the content of any post is `null`.
This PR resets the `null` content into empty string and ignore the error while updating Lucene document.
Fixes https://github.com/halo-dev/halo/issues/4623
```release-note
修复因某篇文章的内容为 null 导致无法搜索部分文章的问题
```

Prevent Lucene search engine updates from being interrupted

---

application/src/main/java/run/halo/app/core/extension/service/impl/PluginServiceImpl.java

/kind bug
/area core
修复插件 css bundle 内容被错误拆分导致无法加载的问题
Fixes #4677
```release-note
修复插件 css bundle 内容被错误拆分导致无法加载的问题
```

fix: incorrect truncation of CSS resource reads

---

application/src/main/java/run/halo/app/content/comment/ReplyNotificationSubscriptionHelper.java
application/src/main/java/run/halo/app/notification/EmailNotifier.java
application/src/main/resources/extensions/notification.yaml

/kind bug
/area core
修复当评论或回复者的邮箱为空时通知报错的问题
Fixes #4684
```release-note
修复当评论或回复者的邮箱为空时通知报错的问题
```

fix: compatible email are empty when comment notification triggered

---

console/packages/components/src/components/switch/Switch.vue
console/packages/components/src/components/switch/__tests__/Switch.spec.ts
console/src/modules/system/plugins/components/entity-fields/SwitchField.vue

/area console
/kind feature
VSwitch 组件支持传入 loading 属性以显示加载状态。
此外，此 PR 为插件启动/停止的开关适配了这个特性用于测试。
Fixes #4687 
测试插件启动/停止时是否显示加载状态
```release-note
Console 端的 VSwitch 组件支持传入 loading 属性以显示加载状态。
```

feat: add loading state for switch component

---

application/src/main/java/run/halo/app/notification/EmailNotifier.java
application/src/main/resources/extensions/notification.yaml

/area core
为邮件通知发件设置增加加密方式配置
Fixes #4674
```release-note
为邮件通知发件设置增加加密方式配置
```

feat: add encryption setting for email notifier

---

console/docs/extension-points/entity-listitem-operation.md
console/packages/shared/src/types/plugin.ts
console/src/modules/contents/attachments/AttachmentList.vue
console/src/modules/contents/attachments/components/AttachmentListItem.vue
console/src/modules/contents/attachments/composables/use-attachment.ts

/area console
/kind feature
附件管理列表项的操作按钮支持被插件扩展。
Fixes https://github.com/halo-dev/halo/issues/4667
需要测试附件的关于列表的已有功能是否正常。
如果需要测试扩展点是否有效，可以使用此插件测试：[plugin-s3-1.5.0-SNAPSHOT.jar.zip](https://github.com/halo-dev/halo/files/12839986/plugin-s3-1.5.0-SNAPSHOT.jar.zip)
```diff
export default definePlugin({
components: {},
routes: [],
extensionPoints: {
"plugin:self:tabs:create": (): PluginTab[] => {
return [
{
id: "s3-link",
label: "关联S3文件",
component: markRaw(HomeView),
permissions: [],
},
];
},
+    "attachment:list-item:operation:create": (attachment: Ref<Attachment>) => {
+      return [
+        {
+          priority: 21,
+          component: markRaw(VDropdownDivider),
+        },
+        {
+          priority: 22,
+          component: markRaw(VDropdownItem),
+ …
```

feat: make attachment list item operations extendable

---

console/src/modules/system/users/components/UserAvatar.vue

/area console
当用户未设置头像时，头像显示添加图标，能够更好的提示用户如何设置头像。
Fixes #4693 
1. 测试未设置头像时，是否添加添加图标。
2. 测试设置头像之后，鼠标移动到头像时，是否显示修改图标。
```release-note
优化 Console 端个人资料的头像显示，未设置头像时显示添加图标。
```

feat: display add icon when user avatar is not setting

---

console/packages/components/package.json

/area console
修改 @halo-dev/components 的版本号为 1.9.0，将在 2.10.0 发布之后推送到 npmjs.com
```release-note
None
```

chore: bump @halo-dev/components version to 1.9.0

---

application/build.gradle

/area core
修改应用市场插件的版本为 [1.0.0-beta.2](https://github.com/halo-dev/plugin-app-store/releases/tag/v1.0.0-beta.2)
```release-note
None
```

chore: bump app store plugin version to 1.0.0-beta.2

---

application/src/main/java/run/halo/app/security/authentication/pat/impl/UserScopedPatHandlerImpl.java

/kind bug
/area core
If someone logs in Halo via OAuth2, they will be prohibited from creating PATs. See https://github.com/halo-dev/halo/issues/4697 for more.
This PR also checks for UsernamePasswordAuthenticationToken while checking whether the current session was created by a real user.
Fixes https://github.com/halo-dev/halo/issues/4697
```release-note
None
```

Fix the problem that OAuth2 users cannot create PATs 

---

README.md
console/package.json
console/packages/api-client/package.json
console/packages/components/package.json
console/packages/shared/package.json
gradle.properties

/kind cleanup
Bump all versions.
```release-note
None
```

Prepare for next development 2.11.0

---

console/src/modules/system/plugins/PluginDetail.vue

/kind bug
/area console
修复用户仅拥有插件查看权限时，有setting的插件会导致无法加载插件扩展tab的问题
Fixes #4732
1. 使用如下测试版 s3 插件
[plugin-s3-1.5.0-SNAPSHOT.jar.zip](https://github.com/halo-dev/halo/files/12914987/plugin-s3-1.5.0-SNAPSHOT.jar.zip)
<https://github.com/longjuan/halo-plugin-s3os/tree/aaa>
2. 创建一个用户，仅赋予 S3 Link 权限（依赖于插件查看和附件管理权限）
3. 登录这个新用户，打开 s3 插件详情
4. 观察 关联S3文件 功能是否正常出现
```release-note
修复部分场景下插件详情的扩展 tab 不能正常显示的问题
```

fix: plugin extension tab cannot be displayed when only having plugin view permissions

---

application/src/main/java/run/halo/app/core/extension/endpoint/PluginEndpoint.java
application/src/main/resources/extensions/role-template-plugin.yaml

/area core
/area console
提供允许同步更改插件运行状态的 API
Fixes #4744
```release-note
提供允许同步更改插件运行状态的 API
```

refactor: provide API for change plugin motion status synchronously

---

application/src/main/java/run/halo/app/core/extension/reconciler/PostReconciler.java

/kind bug
/area core
修复筛选未发布文章时结果不正确的问题
Fixes #4730 
```release-note
修复筛选未发布文章时结果不正确的问题
```

fix: incorrect results when filtering unpublished posts

---

console/src/components/form/AnnotationsForm.vue

/kind bug
在获取自定义元数据时，将空白 key 与重复的 key 过滤，用于解决可能出现的额外空白元数据及报错问题。
尝试点击编辑文章 -> 设置，查看是否有额外空白元数据的出现。
由于是概率性问题，因此若本地环境未复现，则需要使用生产环境进行验证。
Fixes #4764 
```release-note
解决文章设置中可能出现空白元数据的问题
```

fix: resolve the issue of occasional blank annotation and error occurrences

---

console/src/modules/system/users/components/UserAvatar.vue

/kind bug
当前用户上传头像时的接口中名字应该是 `-` 而不是具体的 metadata name。
使用无用户管理权限的用户登录，查看是否能上传头像。
Fixes #4776 
```release-note
解决无用户管理权限的用户无法上传头像的问题
```

fix: cannot change the user's own avatar

---

application/src/main/java/run/halo/app/theme/finders/CommentFinder.java
application/src/main/java/run/halo/app/theme/finders/impl/CommentFinderImpl.java

/kind bug
在主题使用如下FinderAPI时
将产生如下错误
因为方法定义为
所以修改方法参数
Fixes #
```release-note
NONE
```

fix: change the ref parameter type in the list method of comment finder api to map

---

console/src/modules/contents/attachments/AttachmentList.vue

/kind bug
console附件页面List Mode和Grid Mode的tooltip写反了：
Fixes #
```release-note
修复附件管理布局切换按钮的提示文字。
```

fix: correct the tooltip of view type in the Attachments page

---

application/src/main/java/run/halo/app/core/extension/service/DefaultRoleService.java

/kind bug
/area core
Fix the problem that we will encounter "insufficient roles" error while creating PAT with hidden roles.
Fixes https://github.com/halo-dev/halo/issues/4783
```release-note
修复因部分角色导致无法正常创建个人令牌的问题
```

Fix the problem of creating PAT with hidden roles

---

console/src/components/editor/DefaultEditor.vue
console/src/composables/use-editor-extension-points.ts

/kind bug
优化了编辑器的性能，并解决了卡死现象。具体措施如下：
1. 编辑器异步加载时，由于其 component 并不会使用响应式，所以也无需进行代理，因此使用 `markRaw` 将其转为普通对象，可以优化 vue 性能。
2. 由于 `DefaultEditor` 有多个根节点导致透传的 attrs 无法设置，因此新增一个 div 节点将其原有节点包裹。参见 https://cn.vuejs.org/guide/components/attrs.html#attribute-inheritance-on-multiple-root-nodes 。
3. 原有编辑器实例在切换路由之后不会释放，此次修改之后，将在 vue 的 `onBeforeUnmount` 时间中手动释放编辑器实例。
1. 新建文章，新建一个表格。
2. 不要保存，点击文章路由跳出编辑器界面，再次点击上一次所编辑器的文章，查看是否会卡死。
Fixes #4798 
```release-note
优化编辑器性能并解决切换页面所造成的卡死现象
```

fix: optimize editor performance and resolve freezing issues

---

application/src/main/java/run/halo/app/core/extension/endpoint/PostEndpoint.java
application/src/test/java/run/halo/app/core/extension/endpoint/PostEndpointTest.java

/area core
修改发布文章的等待时间以防止因数据库执行延迟较高导致的错误提示
最大等待时间为：`100ms * 2 ^ (retryNum - 1)` = `1600ms`
总共需等待时间为：`100ms * (2 ^ retryNum - 1)` = `3100ms`
```release-note
修改发布文章的等待时间以防止因数据库执行延迟较高导致的错误提示
```

chore: update the waiting time for publishing post

---

console/src/setup/setupModules.ts
console/src/utils/load-style.ts

/area console
为插件的 bundle.css 和 bundle.js 重定向请求添加时间戳参数，防止被浏览器、Nginx、CDN 服务缓存，导致插件的资源不能及时更新。
Fixes #4803 
测试方式：
1. 在 Firefox 浏览器测试启动和停止若干插件，观察插件提供的 UI 样式是否正常即可。
```release-note
优化 Console 端插件捆绑资源的请求，防止在操作插件状态之后无法及时更新资源。
```

refactor: add t parameter for plugin bundle resources

---

console/src/components/form/AnnotationsForm.vue

/kind bug
/area console
重构去重元数据的逻辑，解决删除元数据后仍旧提示 key 不能重复的问题。
1. 在文章列表点击设置按钮
2. 添加两个个空的元数据，不保存直接关闭设置框。
3. 再次打开设置框，点击删除空的元数据，查看是否会提示 key 重复。
Fixes #4764 
```release-note
解决删除元数据后仍旧提示 key 不能重复的问题
```

[Release-2.10] fix: resolve errors caused by blank annotations

---

console/src/components/form/AnnotationsForm.vue

/kind bug
/area console
重构去重元数据的逻辑，解决删除元数据后仍旧提示 key 不能重复的问题。
1. 在文章列表点击设置按钮
2. 添加两个个空的元数据，不保存直接关闭设置框。
3. 再次打开设置框，点击删除空的元数据，查看是否会提示 key 重复。
```release-note
解决删除元数据后仍旧提示 key 不能重复的问题
```

fix: resolve the issue of receiving duplicate key error after deleting metadata

---

gradle.properties

/kind cleanup
Upgrade to SnakeYAML 2.2.
This PR fixes CVE-2022-1471(High-severity vulnerabilities).
See https://hub.docker.com/layers/halohub/halo/sha-2ccf811/images/sha256-e11fe7550a6b7eef42166b53373b6fe889538db54921fbd83623558286d9270c?context=explore for more.
```release-note
升级 SnakeYAML 至 2.2
```

Upgrade to SnakeYAML 2.2

---

application/src/main/java/run/halo/app/infra/properties/ThemeProperties.java
application/src/main/java/run/halo/app/theme/ThemeConfiguration.java
application/src/main/java/run/halo/app/theme/dialect/GeneratorMetaProcessor.java
application/src/test/java/run/halo/app/theme/dialect/GeneratorMetaProcessorTest.java
application/src/test/java/run/halo/app/theme/message/ThemeMessageResolverIntegrationTest.java
application/src/test/resources/themes/default/templates/index.html
application/src/test/resources/themes/other/templates/index.html

/kind feature
/area core
Please see https://html.spec.whatwg.org/multipage/semantics.html#meta-generator for more.
This PR add the generator meta into head, so that we can know what sites are using Halo.
```bash
http localhost:8090/ | grep generator
<meta name="generator" content="Halo 2.11.0-SNAPSHOT"/>
```
If someone want to disable the generator meta, they can configure the property `halo.theme.generator-meta-disabled` to `true`.
```release-note
添加 Generator 元数据标识
```

Add generator meta into head

---

api/build.gradle
application/build.gradle

/kind bug
/area core
Currently, some Windows developers using GBK as character encoding are unable to build project, please see https://github.com/halo-dev/halo/issues/4771 for more. 
Because the source code are using UTF-8 character encoding, the `javadoc`, `compileJava`, `compileTestJava` and `delombok` tasks will use the default character encoding GBK to handle the sources, which prevents the `:api:javadoc` task from running properly.
At the same time, we thank to @DaiYuANg for his first proposed solution in https://github.com/halo-dev/halo/pull/4517.
Fixes https://github.com/halo-dev/halo/issues/4771
Validate the result by executing command `./gradlew clean build -x check` on Windows environment.
```release-note
修复在部分 Windows 开发者无法正常构建 Halo 的问题
```

Fix the problem where some Windows developers are unable to build project

---

api/build.gradle
application/build.gradle

/kind cleanup
/area core
Upgrade to Lombok gradle plugin 8.4.
See https://docs.freefair.io/gradle-plugins/8.4/reference/#_installation and https://docs.freefair.io/gradle-plugins/8.4/reference/#_system_requirements for more.
```release-note
升级 Lombok Gradle 插件至 8.4
```

Upgrade to Lombok gradle plugin 8.4

---

console/src/components/preview/UrlPreviewModal.vue

/kind feature
/area console
为文章以及页面预览增加终端切换功能，类似于预览主题的终端切换
Fixes #4789
测试方式：
本地运行halo，预览文章和页面，切换不同终端，各个界面正常显示且功能正常。
```release-note
文章预览支持模拟不同设备尺寸。
```

feat: add devices mock preview for post and single page

---

.github/workflows/halo.yaml

/kind cleanup
/area core
According to <https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow>, we cannot obtain secrets in pull requests. So every checks of PRs will failed due to no secrets provided after <https://github.com/halo-dev/halo/pull/4856>.
So this PR disables code scanning for pull requests except for pushing.
```release-note
None
```

Disable code scanning for pull requests

---

.github/workflows/halo.yaml

Reverts halo-dev/halo#4588
According to https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow, we cannot obtain secrets in pull requests, so that we are not able to push docker image for every pull request.
```release-note
None
```

Revert "ci: push image to GHCR for pull_request event"

---

console/src/vite/config-builder.ts

/kind bug
/area console
修复在 Windows 平台下无法正常启动 Console 服务以及无法正常编译的问题。
Fixes https://github.com/halo-dev/halo/issues/4874
在 Windows 平台下测试 `pnpm dev` 和 `pnpm build`，检查是否能够正常运行。
```release-note
None
```

fix: unable to compile console and uc on Windows platform

---

application/src/main/java/run/halo/app/core/extension/endpoint/SystemInitializationEndpoint.java
application/src/test/java/run/halo/app/core/extension/endpoint/SystemInitializationEndpointTest.java

/area core
Respond HTTP status CREATED for system initialization API instead of string `true`.
Fixes #4885 
```release-note
None
```

Respond HTTP status CREATED for system initialization API
